var data_map_templerun2 = [
{"keyword":"fun","name":"<h1>fun</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's brilliant I <b>loved</b> <u>it</u> <u>its</u> <u>so</u> <u>fun.</u> <br>"
+"&#43; <b>Great</b> <u>endless</u> <u>fun.</u> <br>"
+"&#43; It's <u>fun</u> its <b>a</b> run its temple run two amazing falls and characters and gems and <u>coins</u> <u>fun</u> <b>to</b> <b>collect</b> <b>tell</b> your <b>fri3nds.</b> <br>"
+"&#43; It's <b>super</b> <u>fun.</u> <br>"
+"&#43; It is <b>super</b> <u>fun.</u> <br>"
+"&#43; <b>Great</b> <u>fun</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":6,"sentiment":1.17,"value":2.96},
{"keyword":"graphics","name":"<h1>graphics</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Great</u> <u>Graphics</u> for a game absolutely <b>Free!</b> <br>"
+"&#43; I <b>love</b> the <u>graphics.</u> Beter than TR1. <br>"
+"&#43; <u>Graphics</u> are <b>superb</b> <br>"
+"&#43; <b>Superb</b> <u>graphics.</u> <br>"
+"&#43; <b>Good</b> <u>graphics,</u> unpredictable. <br>"
+"&#43; Just <b>love</b> the <u>graphics</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":7,"sentiment":1.00,"value":2.95},
{"keyword":"game","name":"<h1>game</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This is very <b>lovely</b> and <u>intresting</u> <u>game.</u> <br>"
+"&#43; I <b>loved</b> this <u>game.</u> <br>"
+"&#43; This is the <b>funniest</b> <u>game</u> ever. <br>"
+"&#43; I <b>love</b> this <u>game!</u> <br>"
+"&#43; I <b>love</b> the <u>game!</u> <br>"
+"&#43; Is a <u>game</u> very <b>cool</b> and I loved it. <br>"
+"&#43; This <u>game</u> is <b>so</b> <b>cool</b> and awesome. <br>"
+"&#43; This <u>game</u> is <b>amazing</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I LIKED THIS <u>GAME</u> BECAUSE IT IS A <b>THRILLING</b> <u>GAME</u> SO LIKED THIS <u>GAME</u> VERY MUCH. <br>"
+"- This <u>game</u> is <b>too</b> <b>good</b> <br>"
+"- It's a <b>good</b> <u>game</u> <br>"
+"- It would be much beter if you don't spend real money on this <u>game</u> and my <u>game</u> has <b>been</b> a bjt <b>bugy</b> now and again bjt its quite good thats why I give it 4 stars x <br>"
+"- It is a <b>bad</b> <u>game</u> when we are biting our high score it is telling sory unfortunately Temple run 2 has been stoped did you know? <br>"
+"- I LIKED <u>THIS</u> <u>GAME</u> <u>BECAUSE</u> <u>IT</u> <b>IS</b> A <b>THRILLING</b> <u>GAME</u> SO LIKED <u>THIS</u> <u>GAME</u> VERY MUCH. <br>"
+"- <u>Great</u> <u>game</u> <u>but</u> when <u>I</u> <u>made</u> a <u>purchase</u> <u>they</u> <b>took</b> my <b>money</b> and didn't fulfill my order TWICE. <br>"
+"- <u>Great</u> <u>game</u> <u>but</u> when <u>I</u> <u>made</u> a <u>purchase</u> <u>they</u> took my money and didn't <b>fulfill</b> my <b>order</b> <b>TWICE.</b> <br>"
+"</p>","volumn":156,"sentiment":.92,"value":5.97},
{"keyword":"playing","name":"<h1>playing</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> <u>playing</u> <u>temple</u> run it is really fun <br>"
+"&#43; I really <b>love</b> <u>to</u> <u>play</u> <u>it.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>like</b> <u>playing</u> <u>temple</u> <u>run</u> when i,m bored but l have no weekly challenges and l am not geting coins please solve it out..<br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"challenge","name":"<h1>challenge</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's a <b>great</b> <u>challenge</u> to do and play everyone should play it <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- So much log and no <b>weekly</b> and <u>daily</u> <u>challenge.</u> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"characters","name":"<h1>characters</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's fun its <b>a</b> run its temple run two amazing falls and <u>characters</u> and gems and coins fun <b>to</b> <b>collect</b> <b>tell</b> your <b>fri3nds.</b> <br>"
+"&#43; Both <u>male</u> and <u>female</u> <u>characters</u> should be <b>available</b> <b>from</b> the <b>start.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>new</u> <u>character</u> <b>does</b> <b>not</b> <b>have</b> any <u>new</u> <b>ability</b> and <b>does</b> <b>not</b> ad anything to the game. <br>"
+"- The <u>new</u> <u>character</u> <b>does</b> <b>not</b> have any <u>new</u> ability and <b>does</b> <b>not</b> <b>ad</b> <b>anything</b> <b>to</b> the <b>game.</b> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]