var data_map_totalreviews=562
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_googleplaybooks = [
{"keyword":"this","name":"<h1>this</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>This</u> <u>mater</u> <b>needs</b> <b>to</b> <b>be</b> <b>fixed</b> <b>immediately!</b> <br>"
+"- More unnecessary space taken up when I know Google could <b>make</b> <u>this</u> <u>removable.</u> <br>"
+"- I may try using <u>this</u> if i want to download a book, but I <b>wish</b> <u>this</u> <u>was</u> <u>part</u> <u>of</u> <u>Google</u> <u>Play</u> and not taking up extra memory. <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"could","name":"<h1>could</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>uninstall.</u> <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>get</u> <u>rid</u> <u>of</u> <u>it!</u> <br>"
+"- <u>I</u> really <b>wish</b> <u>I</u> <u>could</u> <u>delete</u> <u>aps</u> that comes with the phone. <br>"
+"- <u>I</u> so <b>wish</b> that <u>I</u> <u>could</u> <u>uninstall</u> the (for <u>me)</u> <u>unused</u> <u>bloatware</u> that Google puts out. <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>have</u> the <u>option</u> too <u>uninstall</u> entirely! <br>"
+"</p>","volumn":6,"sentiment":-.83,"value":.96},
{"keyword":"upload","name":"<h1>upload</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; please please please <b>make</b> <u>the</u> <u>search</u> <u>function</u> <u>work</u> <u>for</u> <u>uploaded</u> <u>books</u> too! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Why it is <b>need</b> <u>to</u> <u>upload</u> the <u>epub</u> <u>file</u> ? <br>"
+"- The <u>upload</u> <u>COULD</u> be a litle <b>faster</b> <b>though.</b> <br>"
+"- The <u>upload</u> <u>COULD</u> be a litle <b>faster</b> <b>though:</b> avg 60 seconds to <u>upload.</u> <br>"
+"- Updated it and <b>then</b> <u>I</u> couldn't <b>see</b> the <u>books</u> <u>I</u> <u>uploaded.</u> <br>"
+"- The <u>upload</u> <u>COULD</u> be a litle <b>faster</b> <b>though:</b> avg 60 seconds to <u>upload.</u> <br>"
+"- And <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>figure</u> <u>out</u> how <u>to</u> <u>upload</u> <u>multiple</u> <u>files</u> simultaneously. <br>"
+"- Also, <u>uploaded</u> <u>books</u> don't remain <u>uploaded</u> and <b>need</b> <b>to</b> <b>be</b> <b>downloaded</b> <b>again</b> <b>at</b> <b>times.</b> <br>"
+"- <u>I</u> only <b>wish</b> that <u>I</u> <u>could</u> <u>write</u> <u>on</u> the <u>picture</u> <u>files.</u> <br>"
+"</p>","volumn":10,"sentiment":-.80,"value":1.50},
{"keyword":"view","name":"<h1>view</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- New features are <b>needed</b> such as being able to write a comment on a highlighted text, <u>change</u> <u>views</u> <u>of</u> the <u>library,</u> <u>including</u> a <u>list</u> <u>view</u> <u>instead</u> <u>of</u> just a grid <u>one.</u> <br>"
+"- After updating i can't <b>see</b> the <u>full</u> <u>view</u> <u>of</u> the <u>single</u> <u>page.</u> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- There's <u>only</u> <u>credit</u> <u>card</u> <u>payment</u> <u>option</u> <u>available.</u> <br>"
+"- Please <b>provide</b> <u>an</u> <u>option</u> <u>to</u> <u>invert</u> <u>volume</u> <u>keys</u> while turning pages ie, the <u>volume</u> up key turns <u>to</u> next page instead of pervious page <br>"
+"- I don't <b>see</b> the <u>option</u> <u>to</u> <u>copy</u> any more when I high light only show the search <u>option</u> and the note ad, what's going on Google, please fix it. <br>"
+"- <b>There</b> <b>should</b> <b>be</b> <u>option</u> that lets you find books by your chosen language. <br>"
+"- On my <b>S3,</b> <b>there</b> <b>is</b> <u>no</u> <u>option</u> <u>in</u> <u>setings</u> <u>for</u> <u>high</u> <u>quality</u> <u>read</u> aloud. <br>"
+"- Please <b>make</b> <u>all</u> <u>nonsense</u> <u>aps</u> <u>optional</u> <br>"
+"- When I turn off my screen while listening <u>to</u> my book,the reading stops, there's <u>no</u> <u>option</u> <u>to</u> <u>keep</u> <u>speech</u> turned on while screen is off. <br>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>SD</u> <u>Card</u> <u>suport.</u> <br>"
+"</p>","volumn":12,"sentiment":-.67,"value":1.82},
{"keyword":"update","name":"<h1>update</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>hope</b> the <u>next</u> <u>update</u> <u>will</u> <u>be</u> <u>awesome!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>It</u> doesn't <b>want</b> <u>to</u> <u>open</u> <u>,</u> <u>its</u> <u>says</u> no <u>connection</u> <u>try</u> again <u>,</u> <u>I</u> <u>have</u> <u>updated</u> <u>several</u> <u>time</u> <u>,</u> <u>please</u> <u>help</u> <u>!</u> <br>"
+"- Can't uninstall ap, only allowed to <b>remove</b> <u>updates</u> <u>which</u> <u>would</u> <u>make</u> <u>it</u> insecure. <br>"
+"- It <b>needs</b> more download speed, It <b>needs</b> an super high speed connection and <u>limited</u> and <u>local</u> <u>connectivity.</u> <br>"
+"- I <b>wish</b> <u>there</u> <u>was</u> <u>a</u> <u>build</u> <u>in</u> <u>dictionary</u> <u>which</u> <u>would</u> <u>help</u> <u>me</u> <u>find</u> <u>out</u> <u>difficult</u> <u>words</u> meaning staying within the <u>ap</u> <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"books","name":"<h1>books</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Sometimes the cover of my <u>books</u> would not pop up, and the app <b>needs</b> <u>to</u> <u>ad</u> <u>a</u> <u>feature</u> <u>that</u> <u>allows</u> <u>user</u> <u>to</u> <u>sort</u> <u>books</u> <u>into</u> <u>folders.</u> <br>"
+"- I <b>wish</b> <u>there</u> <u>were</u> <u>more</u> <u>books</u> in Spanish. <br>"
+"- I <b>wish</b> <u>it</u> <u>was</u> <u>easy</u> <u>to</u> <u>search</u> <u>for</u> <u>books</u> <u>in</u> <u>different</u> <u>languages</u> <br>"
+"- It <b>needs</b> more <u>free</u> <u>traditional</u> <u>books.</u> <br>"
+"- I <b>want</b> <u>to</u> <u>group</u> my <u>books,</u> some <u>sort</u> <u>of.</u> <br>"
+"- <b>Please,</b> someone <u>take</u> <u>the</u> <u>book</u> back and refund my money! <br>"
+"- It <b>needs</b> <u>more</u> completely <u>free</u> <u>books</u> <u>with</u> no <u>payment</u> <u>methods.</u> <br>"
+"- It <b>needs</b> <u>a</u> <u>vertical</u> <u>scrolling</u> <u>option</u> <u>for</u> <u>reading</u> <u>books</u> <br>"
+"</p>","volumn":24,"sentiment":-.58,"value":2.59},
{"keyword":"star","name":"<h1>star</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I loved it first but not it will not let me read anything would <b>give</b> <u>0</u> <u>stars</u> please fix <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I would have <b>given</b> <u>this</u> <u>5</u> <u>stars</u> if I could see the pictures better. <br>"
+"- Only if i could <b>give</b> <u>no</u> <u>star</u> <u>rating.</u> <br>"
+"- <u>Rating</u> <u>one</u> <u>star</u> is only more <b>for</b> <b>it</b> <br>"
+"</p>","volumn":6,"sentiment":-.33,"value":1.46},
{"keyword":"highlight","name":"<h1>highlight</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- No more <u>highlights,</u> <b>please</b> <u>fix!</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"better","name":"<h1>better</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great and simple app but always <b>needs</b> <u>better</u> <u>improving</u> . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Good but <b>needs</b> <u>improvement.</u> <br>"
+"- We <b>need</b> <u>better</u> <u>managing</u> <u>tool.</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"real","name":"<h1>real</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- WE ALL WANT to <b>see</b> the <u>REAL</u> <u>PAGES.</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"see","name":"<h1>see</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>want</b> <u>to</u> <u>see</u> <u>something</u> <u>different.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>There</b> <b>are</b> <u>a</u> <u>couple</u> <u>of</u> <u>things</u> <u>I</u> <u>would</u> <u>like</u> <u>to</u> <u>see</u> <u>aded/changed.</u> <br>"
+"- <b>There</b> <b>are</b> <u>a</u> <u>few</u> <u>things</u> <u>I</u> <u>would</u> <u>like</u> <u>to</u> <u>see</u> <u>aded/changed.</u> <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
{"keyword":"more","name":"<h1>more</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very nice, <b>wish</b> <b>had</b> <u>more</u> <u>colors</u> to choose from when highlighting <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> like <u>it</u> but <u>I</u> <b>wish</b> <u>it</u> <u>had</u> <u>more</u> <u>color</u> <u>options</u> <u>to</u> <u>highlight</u> and <u>it</u> takes awhile <u>to</u> download the books <br>"
+"- It <b>needs</b> <u>More</u> <u>Specifications.</u> <br>"
+"</p>","volumn":8,"sentiment":-.12,"value":1.95},
]