var data_map_totalreviews=1022
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_swiftkey = [
{"keyword":"themes","name":"<h1>themes</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's one of my favorite keyboard but hopefully <b>there</b> <b>will</b> <b>be</b> more <u>theme</u> in the future <br>"
+"&#43; it would be brilliant if you could <b>make</b> <u>the</u> <u>Dark</u> <u>theme</u> with a pitch black background. <br>"
+"&#43; From swype(after their update) to this for now and finding it very good, bought black theme but wud like some <b>more</b> <u>dark</u> <u>themes,</u> touche <br>"
+"&#43; Would love it if you could ad some <b>more</b> <u>material</u> <u>themes.</u> <br>"
+"&#43; <u>Nice</u> <u>themes</u> too but could be a bit <b>more</b> <b>imaginative.</b> <br>"
+"&#43; And please <b>give</b> us <u>some</u> <u>decent</u> <u>light</u> <u>colored</u> <u>themes.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Gets bored due to <b>less</b> <u>free</u> <u>themes.</u> <br>"
+"</p>","volumn":12,"sentiment":.42,"value":2.90},
{"keyword":"change","name":"<h1>change</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>change</u> <u>the</u> <u>design</u> <u>of</u> <u>the</u> <u>slider</u> <u>hamburger</u> <u>icon</u> to match <u>the</u> Material Design looks. <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>change</u> <u>the</u> <u>punctuation</u> <u>key</u> <u>to</u> all <u>the</u> <u>?</u> <u>to</u> be primary. <br>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>change</u> <u>some</u> <u>of</u> the <u>shortcut</u> <u>symbol</u> <u>keys</u> so <u>you</u> don't have to go to the <u>symbol</u> menu. <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"words","name":"<h1>words</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> only <b>want</b> <u>incorect</u> <u>words</u> <u>to</u> <u>be</u> <u>corected.</u> <br>"
+"- <u>I</u> just <b>wish</b> my <u>curse</u> <u>words</u> weren't <u>corected</u> (yes, my <u>filters</u> <u>are</u> <u>disabled)</u> <br>"
+"- updates are just amazing <b>no</b> <u>words</u> for it but one sugestion that if you can whatsap to personalize the <u>words</u> then please ad it <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"had","name":"<h1>had</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Plus I really <b>wish</b> <u>they</u> <u>had</u> the <u>option</u> <u>to</u> <u>show</u> <u>iPhone</u> <u>emojis.</u> <br>"
+"- I love the snow, semi animated theme, so just <b>wish</b> <u>you</u> <u>had</u> <u>way</u> more just like it, therefore I'll be watching for updates. <br>"
+"- I only <b>wish</b> <u>this</u> <u>had</u> <u>been</u> <u>available</u> before I stoped working. <br>"
+"- I <b>wish</b> that <u>i</u> <u>had</u> <u>emogis.</u> <br>"
+"- For languages with accents and diacritics <u>I</u> <b>wish</b> <u>it</u> <u>had</u> <u>a</u> no <u>special</u> <u>characters</u> <u>option</u> <u>for</u> <u>auto-corect</u> <u>-</u> some SMS cariers don't suport the non-standard <u>characters</u> and the recipients get words like c?r?mid? <br>"
+"- I <b>wish</b> <u>it</u> <u>had</u> <u>better/easier</u> <u>s-pen</u> <u>feature</u> <u>suport.</u> <br>"
+"</p>","volumn":7,"sentiment":-.86,"value":1.09},
{"keyword":"old","name":"<h1>old</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>choose</u> the <u>old</u> <u>typewriter</u> <u>sound.</u> <br>"
+"- <u>Wtf</u> <u>2nd</u> <u>last</u> <u>old</u> <u>version</u> was <b>better.</b> <br>"
+"- <b>Please</b> <u>find</u> <u>another</u> <u>way</u> <u>to</u> <u>go</u> <u>to</u> <u>the</u> <u>shortcut</u> <u>besides</u> long <u>pressing</u> <u>the</u> <u>enter</u> <u>buton</u> that's just below <u>the</u> backspace <u>buton.</u> <br>"
+"</p>","volumn":4,"sentiment":-.75,"value":.64},
{"keyword":"could","name":"<h1>could</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <u>do</u> <b>wish</b> that <u>I</u> <u>could</u> manually <u>customize</u> <u>it</u> more so that <u>I</u> don't <u>have</u> the <u>numbers</u> <u>pad</u> when <u>I</u> hit the 123 buton - <u>I</u> would prefer <u>it</u> to be more like an iOS keyboard that way. <br>"
+"- Swype <u>could</u> be a litle better and <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>turn</u> <u>off</u> the <u>stupid</u> <u>autocorect</u> <br>"
+"- <u>I</u> only <b>wish</b> all the <u>custom</u> <u>colors</u> <u>were</u> <u>free.</u> <br>"
+"</p>","volumn":4,"sentiment":-.75,"value":.64},
{"keyword":"there-wa","name":"<h1>there-wa</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I've found ones with great themes, voice, swype, but <b>no</b> <u>way</u> to disable auto corection. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>there</u> <u>was</u> an <u>option</u> to disable emojis because I don't use them and they get annoying. <br>"
+"- I <b>wish</b> <u>there</u> <u>was</u> a <u>way</u> to switch more conveniently between strokes and pinyin input. <br>"
+"- The only con is I <b>wish</b> <u>their</u> <u>was</u> more <u>free</u> <u>themes.</u> <br>"
+"- Now after using it for years <u>I</u> really like it, but <u>I</u> do <b>wish</b> <u>there</u> <u>was</u> <u>a</u> <u>buton</u> <u>you</u> <u>could</u> <u>click</u> <u>on</u> <u>to</u> <u>turn</u> the <u>auto</u> <u>memory</u> <u>on</u> and off because it will automatically change the word <u>you</u> typed if it is <u>a</u> cuss word or <u>certain</u> <u>abrevations,</u> but once <u>you</u> retype the word it will not change it. <br>"
+"- I <b>wish</b> <u>there</u> <u>was</u> a swipe back or <u>use</u> <u>the</u> <u>delete</u> <u>key</u> <u>to</u> quickly <u>undo</u> <u>auto</u> <u>corect.</u> <br>"
+"</p>","volumn":7,"sentiment":-.71,"value":1.23},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; After I learn <b>where</b> <u>the</u> <u>shortcut</u> <u>keys</u> are, I will be able to fly! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- And <b>there</b> <b>is</b> <u>no</u> <u>option</u> <u>to</u> <u>put</u> the <u>arow</u> <u>keys</u> <u>at</u> the <u>top.</u> <br>"
+"- The <b>only</b> <b>thing</b> <b>I</b> <b>wish</b> is the <u>option</u> to change the theme of the Emoji, for example, in my Galaxy S5, SwiftKey uses the stock Samsung Emoji, but <b>I</b> would like to use the Google Emoji or maybe the IOS 7 or Whatsap Emojis. <br>"
+"- PLEASE FOR THE LOVE OF GOD <b>give</b> us <u>the</u> <u>option</u> <u>to</u> <u>turn</u> <u>off</u> <u>auto</u> <u>space</u> <u>after</u> <u>a</u> <u>punctuation.</u> <br>"
+"- <b>There</b> <b>should</b> <b>be</b> a <u>option</u> for using uper case leter continuously <br>"
+"- <u>Numeric,</u> <u>word</u> and <u>symbol</u> <u>keys</u> <u>in</u> <u>one</u> <u>screen,</u> Not <b>need</b> <b>to</b> <b>change</b> every <b>time.</b> <br>"
+"- The beta has been available for well over a year so <u>not</u> releasing it just shows that <b>there</b> <b>is</b> <u>no</u> <u>genuine</u> <u>effort</u> <u>being</u> <u>put</u> <u>into</u> its <u>release.</u> <br>"
+"- <b>Please</b> <u>implement</u> <u>the</u> <u>OPTION</u> <u>to</u> <u>remove</u> <u>the</u> <u>emoticons</u> and all <u>other</u> <u>unwanted</u> <u>bits</u> and <u>bobs.</u> <br>"
+"- STILL <b>no</b> <u>option</u> to turn off auto-space after full stop. <br>"
+"</p>","volumn":20,"sentiment":-.60,"value":2.40},
{"keyword":"Japanese","name":"<h1>Japanese</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>Japanese</u> <u>in</u> the <u>language</u> <u>options</u> <b>though,</b> I have to switch to Samsung keyboard when I need to use it. <br>"
+"- But there's <u>no</u> <u>Japanese</u> <u>input</u> <b>yet.</b> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"prediction","name":"<h1>prediction</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This <u>Chinese</u> <u>input</u> is <b>much</b> <b>better</b> <b>than</b> <b>others.</b> <br>"
+"&#43; If you could <b>make</b> <u>the</u> <u>next</u> <u>word</u> <u>prediction</u> better, I will rate 5 stars?. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Chinese <u>input</u> <u>predictions</u> would be <b>better</b> if it can be filtered by first strokes. <br>"
+"- <u>I</u> <b>wish</b> <u>it</u> <u>could</u> <u>memorise</u> <u>what</u> <u>I</u> <u>was</u> <u>writing</u> <u>before</u> <u>for</u> <u>a</u> <u>better</u> <u>prediction</u> <u>for</u> <u>example</u> <u>:</u> <u>hi</u> <u>John</u> <u>what</u> <u>about</u> those <u>mannequins</u> <u>shall</u> <u>I</u> <u>bring</u> <u>them</u> <u>to</u> <u>section</u> <u>A</u> as we did last time in our beautiful boutique? <br>"
+"- Also <b>more</b> <u>prediction</u> <u>options</u> not only 3. <br>"
+"- <b>Why</b> <b>is</b> <b>there</b> <u>no</u> <u>Chinese</u> <u>input?</u> <br>"
+"- It has slight improvement on swiping input but it's <u>prediction</u> <b>need</b> <b>to</b> <b>be</b> <b>better.</b> <br>"
+"</p>","volumn":8,"sentiment":-.38,"value":1.70},
{"keyword":"emojis","name":"<h1>emojis</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great Ap just <b>want</b> <b>more</b> <u>Emojis!</u> <br>"
+"&#43; And please <b>make</b> <u>emojis</u> like Whatsap. <br>"
+"&#43; It <b>needs</b> <u>new</u> themes and <u>new</u> <u>emoji</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>BTW,</u> <u>Emoji</u> are <b>for</b> <b>chumps</b> <br>"
+"- I <b>wish</b> that the <u>emojis</u> <u>was</u> better as with some of the <u>other</u> keyboard aps out there <u>other</u> than that I like it. <br>"
+"- We <b>need</b> more <u>emojis!</u> <br>"
+"- <u>I</u> Can't <b>See</b> <u>Emoji</u> <u>Icons</u> <u>Please</u> <u>Help</u> <u>Me</u> <br>"
+"- Emoji,portrait <u>layout</u> <b>need</b> <b>to</b> <b>be</b> <b>fixed.</b> <br>"
+"</p>","volumn":9,"sentiment":-.22,"value":1.98},
{"keyword":"more","name":"<h1>more</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; But please, <b>give</b> us <u>more</u> free stunning themes. <br>"
+"&#43; Great ap, but <b>need</b> <u>more</u> <u>improvement</u> <br>"
+"&#43; I love the themes but would love to <b>see</b> <u>more!</u> <br>"
+"&#43; <u>I</u> <b>wish</b> they'd <u>get</u> <u>a</u> <u>few</u> <u>more</u> <u>choices</u> and <u>designs,</u> but <u>I</u> love the ones <u>they</u> have. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- OK thought with today's update it would fix the problems but it still doesn't let me connect to the theme store and I <b>want</b> <u>more</u> <u>themes!</u> <br>"
+"- but I'd <u>like</u> it <u>more</u> if it <b>gives</b> much <u>more</u> <u>themes</u> <u>fancy</u> <u>like.</u> <br>"
+"- <u>I</u> <b>wish</b> <u>it</u> <u>had</u> <u>better</u> <u>themes</u> and <u>more</u> <u>lollipop</u> <u>look.</u> <br>"
+"- <u>I</u> understand <u>it</u> <b>needs</b> <u>a</u> <u>bit</u> <u>more</u> <u>development,</u> <u>in</u> <u>time</u> it'll <u>get</u> there. <br>"
+"- Thai keyboard <b>need</b> <u>more</u> improve. <br>"
+"</p>","volumn":11,"sentiment":.00,"value":2.40},
{"keyword":"something","name":"<h1>something</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"this","name":"<h1>this</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; From <u>5</u> <u>stars</u> <u>to</u> <u>1,</u> I don't wanna swipe or tap <u>from</u> the left, I <u>hate</u> <u>this,</u> <b>please</b> bring back the tap and hold buton, <b>please!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>check</u> <u>this</u> <u>error</u> <u>asap</u> and provide us with the proper leter symbol, otherwise it blemishes the reputation of <u>this</u> great keyboard. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
]