var data_map_totalreviews=531
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_subwaysurf = [
{"keyword":"challenges","name":"<h1>challenges</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Challenge</u> and level is <b>good</b> and this game is perfect. <br>"
+"&#43; The <u>challenges</u> are <b>very</b> <b>interesting.</b> <br>"
+"&#43; And some <b>new</b> <u>challenges.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.33,"value":2.43},
{"keyword":"fun","name":"<h1>fun</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's <u>fun,</u> <b>rewarding,</b> and the environments are colorful and modest. <br>"
+"&#43; Highly adictive and <b>great</b> <u>fun</u> <br>"
+"&#43; Beter graphics=awesome <u>fun.</u> <br>"
+"&#43; It's <b>super</b> <u>fun.</u> <br>"
+"&#43; It is <b>easy</b> <u>fun.</u> <br>"
+"&#43; <u>Fun</u> <b>adictive</b> <u>game</u> I like it <br>"
+"&#43; <b>Why</b> is <u>fun.</u> <br>"
+"&#43; It is so <b>much</b> <u>fun</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":10,"sentiment":1.10,"value":3.40},
{"keyword":"game","name":"<h1>game</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This is very interesting <u>games</u> <b>iloovee</b> <b>it</b> very <b>much.</b> <br>"
+"&#43; It is very <b>nice</b> and <u>interesting</u> <u>game</u> <br>"
+"&#43; It's actually a very <b>good</b> <u>game</u> . <br>"
+"&#43; Challenge and level is good and this <u>game</u> is <b>perfect.</b> <br>"
+"&#43; This <u>game</u> is <b>really</b> <b>good</b> and I love it so much I can't seem to stop playing it <br>"
+"&#43; It is very <b>nice</b> <u>game</u> plus good graphics. <br>"
+"&#43; This is <b>nice</b> <u>game</u> to play we all in family enjoying! <br>"
+"&#43; It's very very interesting <u>game</u> It's <b>best</b> <u>game</u> for timepass and better than temple run. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>like</b> the <u>game</u> but i hate how <b>like</b> every 5 days there's a update <br>"
+"- I <b>love</b> the <u>game</u> but hate that I lost all my stats. <br>"
+"- This <u>game</u> is <b>total</b> <b>off</b> the <b>hook.</b> <br>"
+"- Why does it freeze when I update?the <u>game</u> is <b>very</b> <b>slow</b> <br>"
+"- Why does it freeze when I update?the <u>game</u> is <b>very</b> <b>slow</b> <br>"
+"- I <b>like</b> this <u>game</u> so much the updates are more interesting <br>"
+"- The <u>game</u> is <b>worse</b> after the update it lags very much <br>"
+"- very <b>difficult</b> <u>game</u> for collecting keys <br>"
+"</p>","volumn":99,"sentiment":.82,"value":5.41},
{"keyword":"graphics","name":"<h1>graphics</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Beautiful</u> <u>graphics,</u> <b>I</b> <b>started</b> <b>playing</b> <b>this</b> <b>a</b> while ago and <b>I</b> still love it. <br>"
+"&#43; <b>Good</b> <u>graphics</u> and fun gameplay. <br>"
+"&#43; It's <b>very</b> awesome game and its <u>graphics</u> is <b>very</b> <b>ghaint</b> its really cool game <br>"
+"&#43; <b>Beter</b> graphics=awesome fun. <br>"
+"&#43; <b>Awesome</b> <u>graphics.</u> <br>"
+"&#43; <b>Superb</b> <u>graphics,</u> awesome points. <br>"
+"&#43; It is very <b>high</b> <u>graphics</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Acceleration and <u>graphics</u> <b>re</b> <b>now</b> 0%. <br>"
+"- It is very <b>bad</b> <u>graphics.</u> <br>"
+"</p>","volumn":10,"sentiment":.60,"value":2.90},
{"keyword":"characters","name":"<h1>characters</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Characters</u> are <b>beautiful</b> and the game is very interesting especially when you are bored. <br>"
+"&#43; I <b>love</b> all <u>the</u> <u>characters</u> too. <br>"
+"&#43; The game is awesome and the <u>characters</u> <b>are</b> <b>fit</b> <b>like</b> <b>me</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>characters</u> are <b>so</b> <b>expensive</b> lower the price will u? <br>"
+"- I <b>like</b> the trains travelling in every second and I <b>like</b> the <u>characters.</u> <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"Subway","name":"<h1>Subway</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Subway</u> <u>surfurs</u> is <b>prety</b> <b>good</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Subway</u> <u>surf</u> is <b>so</b> <b>adictive.</b> <br>"
+"- <u>SUBWAY</u> <u>SURFERS</u> <b>IS</b> <b>COOL</b> :'( <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"glitches","name":"<h1>glitches</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <u>glitches</u> real <b>bad!</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"change","name":"<h1>change</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>loved</b> the <u>Halloween</u> <u>theme</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Good but not the <u>one</u> <u>they</u> <b>are</b> <b>advertising</b> <b>here.</b> <br>"
+"- It's <b>good</b> and <u>changes</u> <u>scenery</u> sometimes too would recommend <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
]