var data_map_totalreviews=562
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_googleplaybooks = [
{"keyword":"fonts","name":"<h1>fonts</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>new</u> <u>fonts</u> <b>however</b> is <b>great!</b> <br>"
+"&#43; Masterclass no competitor,it looks always Masterpiece.and going to better and better with every update,new <u>fonts</u> Literata is <b>magnificent.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Font</u> is <b>not</b> <b>clear.</b> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"function","name":"<h1>function</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>My</u> <u>Library</u> <u>function.</u> <br>"
+"&#43; I <b>love</b> the <u>functionality.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>I</b> love the app but it's frustrating that the copy and <u>paste</u> <u>function</u> <b>only</b> <b>works</b> <b>part</b> <b>of</b> the <b>time.even</b> <b>in</b> the <b>same</b> <b>book,</b> <b>same</b> page. <br>"
+"</p>","volumn":4,"sentiment":.25,"value":1.64},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The only other thing I don't like is the <b>white</b> page <u>background</u> <u>option</u> is a litle too yellow for my liking. <br>"
+"- It is very <b>few</b> <u>customization</u> <u>options</u> and features done better by other aps. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"screen","name":"<h1>screen</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Text to speech turns <b>off</b> when <u>screen</u> is <b>off.</b> <br>"
+"- <b>Why</b> is my <u>screen</u> <u>yellow.</u> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"words","name":"<h1>words</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Google Play Books read <b>so</b> clear and <u>words</u> are <b>so</b> <b>understandable.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's slow, <u>words</u> <b>are</b> <b>awkwardly</b> <b>broken</b> up, and it just doesn't lend itself to <b>a</b> great experience. <br>"
+"- <u>Definitions</u> <u>of</u> <u>words</u> are <b>sometimes</b> <b>awful.</b> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>new</u> <u>version</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very useful this <b>updated</b> <u>version</u> <br>"
+"- Hate <b>newest</b> <u>version.</u> <br>"
+"- <u>Latest</u> <u>version</u> doesn't <b>show</b> <b>page</b> <b>corectly</b> <b>on</b> my <b>Energy</b> <b>Sistems</b> <b>Pro+</b> <b>e-Reader.</b> <br>"
+"- <u>Previous</u> <u>versions</u> were <b>better.</b> <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"text","name":"<h1>text</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Other than that, <b>love</b> the <u>text</u> <u>features</u> like inverting color <u>text</u> and sizing. <br>"
+"&#43; Bookmark pages and <u>highlight</u> <b>important</b> <u>text.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Unfortunately, when fliping pages, the <u>text</u> gets displaced and <b>ends</b> up <b>falling</b> <b>out</b> <b>of</b> the <b>screen,</b> rendering this app useless. <br>"
+"- The <u>text</u> <b>apears</b> <b>like</b> <b>a</b> <b>poorly</b> <b>scanned</b> <b>image.</b> <br>"
+"- Why does <u>text</u> <b>become</b> <b>fuzy</b> when zoomed in on my Nexus 6? <br>"
+"- the <u>text</u> <b>is</b> <b>shifted</b> half <b>way</b> <b>off</b> the <b>screen.</b> <br>"
+"- <b>Excellent</b> <u>text</u> to speech features <br>"
+"</p>","volumn":7,"sentiment":-.57,"value":1.37},
{"keyword":"dictionary","name":"<h1>dictionary</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>offline</u> <u>dictionary</u> <u>feature.</u> <br>"
+"&#43; The <u>offline</u> <u>dictionary</u> <b>helps</b> <b>me</b> <b>a</b> <b>lot.</b> <br>"
+"&#43; It is easy use and <b>great</b> <u>offline</u> <u>features</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The constant <u>dictionary</u> <u>popup</u> is <b>extremely</b> <b>annoying,</b> it should be disabled. <br>"
+"- It's slow to load and <u>offline</u> <u>dictionary</u> isn't <b>working</b> <b>for</b> some <b>reason.</b> <br>"
+"- And I <b>hate</b> <u>that</u> <u>stupid</u> <u>dictionary</u> <u>pop-up.</u> <br>"
+"- <u>Offline</u> <u>dictionary</u> <b>does</b> <b>not</b> <b>provide</b> <b>meaning</b> <b>for</b> <b>most</b> <b>of</b> the <b>words</b> and also no <b>further</b> <b>reference</b> <b>for</b> <b>tough</b> <b>words</b> <b>in</b> <u>dictionary</u> <b>meaning</b> <b>itself.</b> <br>"
+"- <u>Offline</u> <u>dictionary</u> doesn't <b>work</b> <b>in</b> <b>offline</b> <b>mode.</b> <br>"
+"- <u>Offline</u> <u>dictionary</u> doesn't <b>work</b> <b>in</b> <b>offline</b> <b>mode,</b> is this GOOGLE we are talking about <b>!</b> <br>"
+"</p>","volumn":10,"sentiment":-.40,"value":1.90},
{"keyword":"read","name":"<h1>read</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> <u>reading</u> and listening to books on here! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I don't <b>like</b> the 'read now ' section.it's better to see your books on tiles.also, can't change pages anymore while reading a rotated small print book set to one page instead of two.must rotate to change pages and rotate back to read.very inconvenient and annoying.please change it back! <br>"
+"- Also <u>collection</u> <u>of</u> <u>free</u> <u>reading</u> <u>material</u> is way <b>too</b> <b>low.</b> <br>"
+"- The <u>read</u> <b>aloud</b> <b>feature</b> relies on <b>a</b> disability seting outside of the app which makes your phone very hard to navigate and announces every action. <br>"
+"</p>","volumn":6,"sentiment":-.33,"value":1.46},
{"keyword":"look","name":"<h1>look</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I still <b>love</b> all other functionality, but the <u>look</u> and feel can definitely be better <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>look</u> and feel is <b>alright</b> but I do wish a list view was there as an option as well. <br>"
+"- The <u>look</u> and feel is <b>alright</b> but I do wish a list view was there as an option as well. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"view","name":"<h1>view</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Carousel</u> <u>view</u> is <b>back!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The look and feel is alright but I do wish a <u>list</u> <u>view</u> was there as an option as <b>well.</b> <br>"
+"- The look and feel is alright but I do wish a <u>list</u> <u>view</u> was there as an option as <b>well.</b> <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
{"keyword":"books","name":"<h1>books</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; If you like reading on your device, you'll <b>love</b> the <u>selection</u> <u>of</u> <u>Google</u> <u>Play</u> <u>Books.</u> <br>"
+"&#43; <u>Google</u> <u>Play</u> <u>Books</u> <b>read</b> so <b>clear</b> and words are so understandable. <br>"
+"&#43; The <u>turn</u> <u>page</u> when <u>your</u> <u>reading</u> <u>gives</u> <u>you</u> the <u>feeling</u> <u>you</u> <u>are</u> <u>reading</u> <b>a</b> <u>physical</u> <u>book,</u> <b>built</b> <b>in</b> dictionary and <b>a</b> <b>lot</b> <b>more</b> <b>feat.</b> <br>"
+"&#43; But the <u>collection</u> <u>of</u> the <u>books</u> are <b>good.</b> <br>"
+"&#43; I <b>love</b> this <u>book.</u> <br>"
+"&#43; So many <b>good</b> <u>free</u> <u>book.</u> <br>"
+"&#43; Ad to this curently <u>two</u> book's and that's just the <b>digital</b> <b>format!</b> <br>"
+"&#43; Play Books is an <b>awesome</b> <u>book</u> <u>store</u> <u>of</u> a wide <u>range</u> <u>of</u> best seller's. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- In a web browser, <u>Google</u> <u>Books</u> <b>is</b> a <b>brilliant</b> <b>source</b> for obscure out-of-copyright texts. <br>"
+"- Comics and <u>books</u> <b>have</b> <b>trouble</b> loading the pages. <br>"
+"- <u>Was</u> <u>WONDERFUL,</u> but since the <u>last</u> <u>update</u> <u>most</u> <u>of</u> my <u>books</u> disapeared and the few that are left <b>have</b> <b>pages</b> that don't turn properly. <br>"
+"- Was WONDERFUL, but <u>since</u> the <u>last</u> <u>update</u> <u>most</u> <u>of</u> my <u>books</u> disapeared and the few that are left <b>have</b> <b>pages</b> that don't turn properly. <br>"
+"- All <u>books</u> are <b>blank.</b> <br>"
+"- Good but only if some <u>books</u> don't <b>cause</b> that <b>much</b> if only <b>they</b> <b>lower</b> the <b>price</b> <br>"
+"- The one and <u>only</u> <u>book</u> that <u>I</u> <u>purchased</u> <u>through</u> <u>GPB</u> <b>is</b> NOT AVAILABLE <b>OFFLINE.</b> <br>"
+"- BONUS - because of DRM, all the <u>books</u> <u>I</u> <u>purchased</u> <u>on</u> the <u>play</u> <u>store</u> <b>are</b> <b>ONLY</b> <b>readable</b> <u>on</u> this ap, which is also prety bogus. <br>"
+"</p>","volumn":29,"sentiment":-.24,"value":3.13},
{"keyword":"page","name":"<h1>page</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Also I love the <u>page</u> <b>turning</b> <b>animation.</b> <br>"
+"&#43; <u>I</u> also <b>love</b> how <u>I</u> <u>can</u> <u>use</u> the <u>volume</u> <u>keys</u> <u>to</u> <u>turn</u> the <u>pages.</u> <br>"
+"&#43; I <b>love</b> the <u>3D</u> <u>page</u> <u>turn</u> <u>animation.</u> <br>"
+"&#43; <u>I</u> also <b>love</b> how <u>I</u> <u>can</u> <u>use</u> the <u>volume</u> <u>keys</u> <u>to</u> <u>turn</u> the <u>pages.</u> <br>"
+"&#43; I <b>love</b> the <u>3D</u> <u>page</u> <u>turn</u> <u>animation.</u> <br>"
+"&#43; <u>I</u> also <b>love</b> how <u>I</u> <u>can</u> <u>use</u> the <u>volume</u> <u>keys</u> <u>to</u> <u>turn</u> the <u>pages.</u> <br>"
+"&#43; I <b>love</b> the <u>3D</u> <u>page</u> <u>turn</u> <u>animation.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's searches don't work, <u>page</u> <b>jumps</b> <b>miss</b> the <b>mark,</b> the size is too small or too big, bookmarks pop on and off as you strugle to navigate through blury text. <br>"
+"- It's searches don't work, <u>page</u> <b>jumps</b> <b>miss</b> the <b>mark,</b> the size is too small or too big, bookmarks pop on and off as you strugle to navigate through blury text. <br>"
+"- Flowing text freezes <u>original</u> <u>pages</u> <b>kicks</b> <b>me</b> <b>to</b> <b>title</b> <b>selection</b> <br>"
+"- Formating is haywire, <u>none</u> <u>of</u> the <u>pages</u> <b>apear</b> <b>corectly!</b> <br>"
+"- <u>New</u> front <u>page</u> <b>is</b> <b>garbage</b> as it's primarily a store front. <br>"
+"- Zooming and <u>page</u> <u>alignment</u> <b>feels</b> warped and <b>unnatural,</b> new main menus are <b>a</b> hassle ading <b>a</b> pre screen instead of straight to library. <br>"
+"- <u>Pages</u> sometimes <b>are</b> <b>blanks</b> and it is needed a restart. <br>"
+"- AN <b>ACTUAL</b> <u>PAGE</u> TURNING BOOK! <br>"
+"</p>","volumn":20,"sentiment":-.15,"value":2.85},
{"keyword":"reader","name":"<h1>reader</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>nice</b> <u>EPUB</u> <u>reader,</u> <b>simple</b> and <b>clean.</b> <br>"
+"&#43; The <u>website</u> <u>upload</u> is <b>simple</b> and easy but the app should have the same possibility. <br>"
+"&#43; It is very <b>good</b> <u>ebook</u> <u>reader.</u> <br>"
+"&#43; I <b>love</b> the <u>upload</u> <u>ability</u> <u>for</u> <u>epubs,</u> pdfs. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Masterclass.Minus point too <u>many</u> <u>errors</u> <u>in</u> <u>uploading</u> <u>third</u> <u>party</u> <u>epub</u> <u>files.other</u> <u>Readers</u> are <b>much</b> <b>better.</b> <br>"
+"- Second, for some books, the <u>chapters</u> <u>in</u> the <u>table</u> <u>of</u> <u>contents</u> are expandable, and <b>collapsed</b> <b>by</b> <b>default.</b> <br>"
+"- <u>Third,</u> for some books, the chapters in the table of contents are expandable, and <b>collapsed</b> <b>by</b> <b>default.</b> <br>"
+"- PDF fonts not adjustable, but still the <b>best</b> <u>reader</u> <u>available</u> I have found for android. <br>"
+"- It's my <b>go-to</b> <u>reader</u> now since it's relatively easy to buy books through Google. <br>"
+"</p>","volumn":10,"sentiment":.00,"value":2.30},
]