var data_map_totalreviews=1041
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_yelp = [
{"keyword":"place","name":"<h1>place</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I'm very big on great customer service so I love to get on here and share my experience, sugest pl check it out and <b>especially</b> if a <u>place</u> is <b>horible.</b> <br>"
+"&#43; It is very good <u>place</u> to eat' <b>thank</b> <b>you</b> <b>Kristina</b> <b>for</b> the <b>excellent</b> <b>service!</b> <br>"
+"&#43; <b>Great</b> <u>place</u> to ride to! <br>"
+"&#43; <u>Place</u> is <b>great</b> and very clean. <br>"
+"&#43; <b>Great</b> <u>place</u> for enjoy time <br>"
+"&#43; <b>Love</b> this <u>place.</u> <br>"
+"&#43; It's <b>great</b> depending where you are and whether other people also <u>rate</u> <u>places.</u> <br>"
+"&#43; <b>Great</b> <u>place</u> for up to date information <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":14,"sentiment":1.21,"value":3.85},
{"keyword":"web-site","name":"<h1>web-site</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; But aside <b>from</b> that, it delivers what the <u>web</u> <u>site</u> does and is <b>easy</b> to move to and <b>fro.</b> <br>"
+"&#43; But aside <b>from</b> that, it delivers what the <u>web</u> <u>site</u> does and is <b>easy</b> to move to and <b>fro.</b> <br>"
+"&#43; But aside from that, it delivers <b>what</b> the <u>web</u> <u>site</u> <b>does</b> and is easy to move to and fro. <br>"
+"&#43; It is very <b>helpful</b> <u>site!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.00,"value":2.39},
{"keyword":"experience","name":"<h1>experience</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>experience!</u> <br>"
+"&#43; We absolutely <b>loved</b> the <u>experience,</u> <u>way</u> <u>more</u> than we expected. <br>"
+"&#43; <b>Lovely</b> <u>experience.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"price","name":"<h1>price</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>price</u> and <b>Great</b> quality <br>"
+"&#43; <b>Great</b> <u>price,</u> great experiance! <br>"
+"&#43; an very <b>knowledgeable.her</b> <u>prices</u> a <u>great.</u> <br>"
+"&#43; <b>Great</b> <u>prices</u> and nice store. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.00,"value":2.39},
{"keyword":"source","name":"<h1>source</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>source</u> <u>of</u> <u>info</u> <br>"
+"&#43; A <b>good</b> <u>reliable</u> <u>source</u> <u>of</u> <u>information.</u> <br>"
+"&#43; It is very <b>convenient</b> and <u>reliable</u> <u>source</u> for just about everthing. <br>"
+"&#43; <b>Good</b> <u>source</u> for finding good cuisine and extras. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.00,"value":2.39},
{"keyword":"staff","name":"<h1>staff</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>staff</u> and teachers are <b>wonderful</b> and they are really dedicated to the children. <br>"
+"&#43; The <u>staff</u> very <u>friendly</u> and they <b>get</b> the <b>job</b> <b>done</b> <b>excellent</b> <b>customer</b> <b>service.</b> <br>"
+"&#43; The <u>staff</u> and doctors are amazing and really <b>care</b> <b>about</b> the animals and their <b>families.</b> <br>"
+"&#43; The <u>staff</u> and doctors are <b>amazing</b> and <b>really</b> care about the animals and their families. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Poor management <b>,</b> also <b>be</b> careful this <u>hotel</u> <u>staff</u> <b>be</b> <b>swiping</b> <b>credit</b> <b>card</b> twice <b>.</b> <br>"
+"</p>","volumn":5,"sentiment":.80,"value":2.41},
{"keyword":"idea","name":"<h1>idea</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>idea,</u> great execution. <br>"
+"&#43; This app is a <b>great</b> <u>idea</u> and extremely easy to use and is very helpful. <br>"
+"&#43; <b>Amazing</b> <u>idea!</u> <br>"
+"&#43; <b>Great</b> <u>idea.</u> <br>"
+"&#43; The <u>widget</u> <u>idea,</u> I think <b>is</b> a <b>good</b> <b>concept,</b> for quick links. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Great</u> <u>idea</u> <b>poorly</b> <b>executed.</b> <br>"
+"</p>","volumn":6,"sentiment":.67,"value":2.46},
{"keyword":"service","name":"<h1>service</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>good</b> <u>service.</u> <br>"
+"&#43; The <u>service</u> <b>was</b> excellent, very <b>friendly</b> <b>employees</b> who really enjoy what they do! <br>"
+"&#43; <b>Great</b> <b>awesome</b> <u>fast</u> <u>service</u> <br>"
+"&#43; <b>Excellent</b> <u>service</u> with an energetic smile. <br>"
+"&#43; Best carpet and <u>upholstery</u> <u>cleaning</u> <u>services</u> <b>I</b> <b>have</b> <b>ever</b> <b>used.</b> <br>"
+"&#43; <b>Excellent</b> <u>service.</u> <br>"
+"&#43; <b>Same</b> <u>great</u> <u>service</u> as always. <br>"
+"&#43; Terible <u>service</u> and <b>terible</b> <u>service</u> <u>recovery</u> from owner. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This <u>service</u> is <b>awful.</b> <br>"
+"- But, the <u>service</u> <u>AMAZING</u> <u>Johnathan</u> <b>made</b> this outgoing an <b>experience.</b> <br>"
+"- Went up on price and the <u>service</u> is <b>not</b> the <b>same.</b> <br>"
+"- <b>Bad</b> <u>service.</u> <br>"
+"- <b>Useful</b> <u>service</u> but weak app. <br>"
+"- While Yelp is a <b>useful</b> <u>service,</u> the Android app offering isn't great. <br>"
+"</p>","volumn":31,"sentiment":.58,"value":4.01},
{"keyword":"restaurants","name":"<h1>restaurants</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's the most <b>efficient</b> and <u>descriptive</u> <u>site</u> I've so far encountered. <br>"
+"&#43; I <b>love</b> the <u>quick</u> <u>findings</u> <u>of</u> <u>restaurants.</u> <br>"
+"&#43; It is the <b>best</b> <u>Indian</u> <u>restaurant</u> in Las Vegas, the food was so good and also the service was awesome <br>"
+"&#43; <u>Great</u> <u>for</u> <u>checking</u> <u>out</u> <u>restaurants</u> <b>need</b> <b>to</b> <b>know</b> if my food and service is good before <b>I</b> go <br>"
+"&#43; <u>Restaurant</u> in Astoria, the menu is <b>exciting,</b> the food comparable. <br>"
+"&#43; I <b>love</b> that <u>restaurants</u> are embracing this! <br>"
+"&#43; <u>I</u> <b>love</b> the <u>descriptions</u> <u>of</u> <u>dishes</u> <u>at</u> <u>restaurants</u> and <u>tips</u> on anything. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Best</u> <u>hot</u> <u>dog</u> <u>Cart</u> <u>at</u> <u>55</u> <u>St</u> <u>E</u> <u>Madison</u> <u>Ave.That</u> <b>is</b> the <b>Wrong</b> <b>Picture.</b> <br>"
+"- <u>Best</u> <u>hot</u> <u>dog</u> <u>Cart</u> <u>at</u> <u>55</u> <u>St</u> <u>E</u> <u>Madison</u> <u>Ave.That</u> <b>is</b> the <b>Wrong</b> <b>Picture.</b> <br>"
+"</p>","volumn":9,"sentiment":.56,"value":2.75},
{"keyword":"resource","name":"<h1>resource</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>resource</u> app. <br>"
+"&#43; <b>Great</b> <u>resource.</u> <br>"
+"&#43; <b>Great</b> <u>resource</u> for almost anything. <br>"
+"&#43; <b>Great</b> <u>resource!</u> <br>"
+"&#43; <b>Great</b> <u>resource</u> for travelers. <br>"
+"&#43; It is easy to use and a <b>great</b> <u>resource</u> when you're out and you want to find some good food nearby <br>"
+"&#43; <b>Great</b> <u>resource.</u> <br>"
+"&#43; what a <b>great</b> <u>resource</u> for local information and reviews. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>Useful</b> <u>Resource.</u> <br>"
+"- <b>Good</b> <u>resource</u> but ratings <u>inaccurate.</u> <br>"
+"</p>","volumn":13,"sentiment":.54,"value":3.10},
{"keyword":"location","name":"<h1>location</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Always</b> <b>tells</b> <b>me</b> <u>location</u> <u>invalid</u> <u>during</u> <u>sign</u> up. <br>"
+"&#43; <b>Good</b> <u>location</u> at whiple road, Union city . <br>"
+"&#43; I <b>love</b> <u>being</u> <u>able</u> <u>to</u> <u>find</u> <u>locations</u> quickly and l <b>love</b> the helpful directions and traffic alerts. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Locations</u> <u>on</u> the <u>map</u> are <b>wrong</b> very <b>often.</b> <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"food","name":"<h1>food</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Yelp is helpful telling you how <b>good</b> quality and <b>good</b> <u>food</u> around you. <br>"
+"&#43; The <u>food</u> is <b>delicious</b> and the strabery mango Margarita excellent. <br>"
+"&#43; The <u>food</u> is <b>very</b> <b>fresh</b> and great quality. <br>"
+"&#43; <u>food</u> is <b>amazing.</b> <br>"
+"&#43; <u>Food</u> was <b>real</b> <b>good,</b> but service stunk <br>"
+"&#43; We <b>love</b> this <u>alternative</u> <u>food</u> <u>source</u> <br>"
+"&#43; <u>food</u> was <b>decent.</b> <br>"
+"&#43; <b>Good</b> <u>food</u> and good service <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Food</u> <u>tastes</u> <u>fresh</u> and <u>the</u> <u>servers</u> are usually very <b>good,</b> <b>HOWEVER,</b> each and every time we go, <u>the</u> older dark haired woman who is often in <u>the</u> front is RUDE, abrasive, and nasty (never to me, <u>I</u> think she knows <u>I</u> would slap her face) OR she's ridiculously, insultingly fake. <br>"
+"- <u>Fast</u> <u>food</u> <u>restaurants</u> shouldn't <b>be</b> <b>displayed</b> <b>with</b> <b>fine</b> <b>dining,</b> its not really <b>a</b> useful comparison <br>"
+"- <u>Food</u> is <b>bad</b> <b>at</b> <b>best</b> and extremely overpriced. <br>"
+"- And then at the end of the review they say the <u>food</u> was <b>incredible</b> and they would be back. <br>"
+"- The <u>food</u> at Bob Evans is <b>expensive</b> and not that great. <br>"
+"</p>","volumn":18,"sentiment":.50,"value":3.39},
{"keyword":"Yelp","name":"<h1>Yelp</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> <b>love</b> <u>using</u> <u>Yelp</u> <u>to</u> <u>find</u> <u>great</u> <u>businesses</u> and <u>also</u> <u>like</u> <u>having</u> the <u>power</u> <u>to</u> <u>rate</u> then <u>myself!</u> <br>"
+"&#43; <u>Yelp</u> is <b>helpful</b> <b>telling</b> <b>you</b> how good quality and good food <b>around</b> <b>you.</b> <br>"
+"&#43; <u>Yelp</u> is <b>best</b> <b>updated</b> and always right about places hours and availability! <br>"
+"&#43; <u>Yelp</u> <b>has</b> <b>lead</b> <b>us</b> <b>to</b> some <b>wonderful</b> <b>times!</b> <br>"
+"&#43; <u>Yelp</u> is the <b>Best!</b> <br>"
+"&#43; <u>Yelp</u> <b>is</b> <b>King!</b> <br>"
+"&#43; <u>Yelp</u> <b>is</b> <b>Crazy</b> to deliver paid contents and always threat to local business owners. <br>"
+"&#43; I travel a great deal, so <u>Yelp</u> is <b>good</b> <b>for</b> <b>finding</b> the <b>types</b> <b>of</b> <b>places</b> <b>that</b> <b>interest</b> <b>me.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The main purpose of <u>Yelp</u> is to discover places near you, but <u>Yelp</u> <b>really</b> <b>lags</b> <b>behind</b> <b>competitors</b> <b>in</b> this <b>area.</b> <br>"
+"- <u>Love</u> <u>yelp</u> because it <b>helps</b> <b>choosing</b> <b>a</b> <b>restaurant,</b> <b>hotel,</b> <b>atraction,</b> <b>service</b> or <b>destination</b> <b>a</b> <b>lot</b> <b>easier.</b> <br>"
+"- <u>Yelp</u> <b>offers</b> <b>a</b> <b>free</b> <b>service</b> <b>to</b> users <b>by</b> <b>charging</b> <b>huge</b> <b>fees</b> <b>to</b> <b>restaurants</b> and <b>businesses</b> <b>in</b> <b>exchange</b> <b>for</b> <b>fairer</b> <b>treatment.</b> <br>"
+"- <u>Yelp</u> <b>is</b> the <b>only</b> <b>app</b> I trust! <br>"
+"- <u>Yelp</u> is <b>very</b> <b>useful</b> <b>in</b> <b>multiple</b> <b>situations.</b> <br>"
+"- <u>Yelp</u> <b>has</b> <b>proven</b> <b>to</b> <b>be</b> <b>prety</b> <b>accurate</b> (at least <b>in</b> my area). <br>"
+"- <u>Yelp</u> <b>is</b> just another loser <b>website.</b> <br>"
+"- <u>Yelp</u> is <b>highly</b> <b>usable.</b> <br>"
+"</p>","volumn":36,"sentiment":.47,"value":4.06},
{"keyword":"helpful","name":"<h1>helpful</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>accurate</b> <u>info.</u> <br>"
+"&#43; <u>I</u> <b>love</b> the <u>ap,</u> <u>always</u> <u>helpful</u> <u>finding</u> <u>what</u> <u>I</u> <u>need,</u> like places to eat, to shop, and to rest in new locations. <br>"
+"&#43; I eat out often and the reviews and direction have been a <b>great</b> <u>help.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I'm always <b>hapy</b> <u>with</u> the reviews and <u>helpful</u> <u>info</u> on YELP! <br>"
+"</p>","volumn":5,"sentiment":.40,"value":2.01},
{"keyword":"comments","name":"<h1>comments</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>comments</u> and photos are <b>very</b> <b>helpful.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"hair","name":"<h1>hair</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Indian</u> <u>human</u> <u>hair</u> <b>goes</b> <b>great</b> <b>with</b> my <u>hair</u> <b>texture</b> <b>they</b> <u>hair</u> <b>is</b> so <b>soft</b> and <b>manageable</b> <b>of</b> <b>it.</b> <br>"
+"&#43; I <b>love</b> my <u>hair</u> and my <u>sisters</u> <u>hair.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Food tastes fresh and the servers are usually very good, HOWEVER, each and every time we go, the older dark <u>haired</u> <u>woman</u> <u>who</u> <u>is</u> often <u>in</u> the <u>front</u> <u>is</u> <b>RUDE,</b> <b>abrasive,</b> and nasty (never to me, I think she knows I would slap her face) OR she's ridiculously, insultingly fake. <br>"
+"</p>","volumn":4,"sentiment":.25,"value":1.64},
{"keyword":"information","name":"<h1>information</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>information</u> when searching for something as important as preschool <br>"
+"&#43; Dependable and <u>information</u> <b>is</b> <b>quality</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- And <b>so</b> my very <u>helpful</u> <u>information</u> <u>about</u> <b>a</b> <u>business</u> is <b>being</b> <b>counted.</b> <br>"
+"</p>","volumn":4,"sentiment":.25,"value":1.64},
{"keyword":"user","name":"<h1>user</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The app is <u>user</u> <b>friendly,</b> and input from customers is usually reliable. <br>"
+"&#43; <b>Great</b> <u>user</u> experience and overall ui performance. <br>"
+"&#43; It has a <b>good</b> <u>user</u> <u>interface.</u> <br>"
+"&#43; It's very <u>user</u> <b>friendly</b> and <u>handy.</u> <br>"
+"&#43; It's <u>user</u> <b>friendly</b> and well designed. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Users</u> <b>would</b> <b>pay</b> <b>for</b> the <b>service,</b> and the company <b>would</b> <b>pay</b> <b>for</b> reviews. <br>"
+"- It is <b>not</b> so <u>user</u> <b>friendly.</b> <br>"
+"- Whoever designed this <u>user</u> <u>flow</u> <b>is</b> a <b>freaking</b> <b>idiot.</b> <br>"
+"</p>","volumn":8,"sentiment":.25,"value":2.33},
{"keyword":"people","name":"<h1>people</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Sharon is the best need <b>more</b> <u>people</u> like her she is friendly and knowledgeable about her job great customer service skills <br>"
+"&#43; It is very cleaned, <u>people</u> are <b>great</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>Dependable</b> <u>People.</u> <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"reviews","name":"<h1>reviews</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's easy to use and very informative but I don't <b>like</b> how some <u>reviews</u> aren't posted. <br>"
+"&#43; The <u>reviews</u> really are <b>very</b> <b>helpful.</b> <br>"
+"&#43; Options are growing and the <u>reviews</u> are <b>right</b> <b>on</b> <br>"
+"&#43; I also <b>love</b> <u>giving</u> <u>reviews!</u> <br>"
+"&#43; The <u>reviews</u> <u>on</u> <u>Yelp</u> are usually <b>more</b> <b>informative.</b> <br>"
+"&#43; <u>Reviews</u> are the <b>best.</b> <br>"
+"&#43; <u>I</u> <b>love</b> the ap, but <b>would</b> <b>love</b> <u>to</u> <u>have</u> the <u>option</u> <u>of</u> <u>sorting</u> every <u>review</u> and <u>picture</u> <u>in</u> <u>date</u> <u>order</u> <br>"
+"&#43; <b>Great</b> <u>reviews!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Helps me find places and some <u>reviews</u> are <b>helpful.</b> <br>"
+"- Discovery is Awful, <u>Reviews</u> are <b>Terific.</b> <br>"
+"- It's easy to use and the <u>reviews</u> for restaurants have been <b>most</b> <b>helpful.</b> <br>"
+"- The <u>reviews</u> <b>are</b> <b>opinions</b> of others which can be misleading, but that's what is so exciting, I can leave my own review. <br>"
+"- <u>Reviews</u> left by others are often <b>very</b> <b>helpful.</b> <br>"
+"- I use it to find what I need in close proximity and the <u>reviews</u> are <b>helpful</b> <b>too.</b> <br>"
+"- <u>Yelp</u> <u>reviews</u> are <b>usually</b> <b>helpful</b> when trying to find new restaurants <br>"
+"- YELP deletes <b>negative</b> <u>reviews</u> <u>of</u> <u>lion</u> poaching sexual pervy business like River Bluff Dental. <br>"
+"</p>","volumn":46,"sentiment":.13,"value":3.96},
{"keyword":"s","name":"<h1>s</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very informative and lets <u>person</u> <u>s</u> <b>interact</b> <b>freely</b> <b>without</b> <b>interuptions</b> <b>.</b> <br>"
+"&#43; Had the best fisherman plater good service and <u>atmosphere.we</u> definately <b>be</b> <b>back.</b> <br>"
+"&#43; <b>Great</b> <u>??</u> and great ice cream to <br>"
+"&#43; If <u>you</u> are the <b>bigest</b> <b>in</b> <u>your</u> <b>field,</b> Yelp is the site for <u>you!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I don't <b>like</b> the <u>new</u> update. <br>"
+"- This <u>ap/website</u> <b>is</b> a <b>weapon</b> for stupid people! <br>"
+"- The food at Bob Evans is expensive and not <u>that</u> <b>great.</b> <br>"
+"</p>","volumn":12,"sentiment":.08,"value":2.57},
{"keyword":"Picture","name":"<h1>Picture</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>submission</u> <u>of</u> <u>multiple</u> <u>pictures</u> can be a litle <b>bit</b> <b>clunky,</b> and there seem to be quite a few outdated restaurants in my area, but the app works well and has never crashed once for me :) update: there is an adorable litle dinosaur Easter eg! <br>"
+"- Best hot dog Cart at 55 St E Madison Ave.That is the <b>Wrong</b> <u>Picture.</u> <br>"
+"- Best hot dog Cart at 55 St E Madison Ave.That is the <b>Wrong</b> <u>Picture.</u> <br>"
+"</p>","volumn":3,"sentiment":-1.33,"value":-.23},
{"keyword":"tool","name":"<h1>tool</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Always a <b>reliable</b> <u>tool.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Always a <b>useful</b> <u>tool.</u> <br>"
+"- It is very <b>helpful</b> <u>tool</u> though some opinions are pety. <br>"
+"- <b>Good</b> <u>tool</u> need refinement. <br>"
+"- A very <b>useful</b> <u>tool</u> when trying to find a bite to eat a yummy establishment. <br>"
+"- I think yelp is a very <b>useful</b> <u>tool</u> although I think some of the non recommended reviews should be recommended sometimes I don't understand how you guys do that but overall I like the ap <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"search","name":"<h1>search</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>hot</u> <u>new</u> <u>businesses</u> <u>search</u> <u>function</u> to find <u>new</u> restaurants. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The recent update <b>allows</b> <u>searches</u> in user review comments, <b>such</b> <b>as</b> <b>keywords</b> <b>like</b> <b>Parking,</b> <b>Cocktails,</b> <b>etc.</b> <br>"
+"- Tends <b>to</b> lag and freeze and its <u>search</u> isn't <b>to</b> <b>convenient</b> <br>"
+"- It is <b>not</b> a <b>great</b> <u>search</u> <u>engine</u> <br>"
+"- <u>Just</u> <u>search</u> near you, <b>enter</b> the <b>name</b> or pick actual filters! <br>"
+"- <u>Searching</u> through people's reviews <b>is</b> <b>something</b> <b>is</b> <b>something</b> I would like to see in future for this app. <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"handicap","name":"<h1>handicap</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Horible</b> <u>handicap</u> accommodations. <br>"
+"- <b>Horible</b> <u>handicap</u> accommodations. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"businesses","name":"<h1>businesses</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>business</u> and food choices. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is <b>not</b> <b>enough</b> <u>businesses.</u> <br>"
+"- Best part is, <u>businesses</u> can't <b>pay</b> their <b>way</b> out of a bad review <b>like</b> <b>on</b> <b>other</b> <b>sites.</b> <br>"
+"- Do <u>businesses</u> <b>actually</b> <b>read</b> <b>reviews</b> <b>on</b> <b>bad</b> <b>service</b> and <b>bad</b> <b>food</b> and <b>dirty</b> <b>establishments</b> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's and <b>easy</b> <u>interface.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>interface</u> isn't <b>as</b> <b>good</b> <b>as</b> <b>Google</b> <b>Maps.</b> <br>"
+"- <b>Terible</b> <u>interface,</u> incomvenient to use <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This <u>aplication</u> is <b>both</b> a great tool for finding the right restaurant, bar, etc. <br>"
+"&#43; This <u>aplication</u> <b>provides</b> a very <b>helpful</b> <b>sevice.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Fantastic and <b>useful</b> <u>aplication.</u> <br>"
+"- The <u>aplication</u> is <b>too</b> <b>bulky,</b> takes <b>too</b> much time to load, and invades user privacy. <br>"
+"- The <u>aplication</u> is too bulky, takes too much time to load, and <b>invades</b> <b>user</b> <b>privacy.</b> <br>"
+"</p>","volumn":5,"sentiment":-.20,"value":1.41},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>mobile</u> <u>version</u> is <b>even</b> <b>better</b> <b>than</b> the <b>laptop</b> <u>version.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- - <u>New</u> <u>version</u> <u>log</u> in nag is <b>incredibly</b> <b>annoying.</b> <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
{"keyword":"access","name":"<h1>access</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is <b>easy</b> <u>access</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is <b>easy</b> <u>access</u> to get valid information to decide what businesses I want to frequent. <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]