var data_map_totalreviews=442
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_espn = [
{"keyword":"UI","name":"<h1>UI</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's a good ap, the <u>UI</u> is <b>better</b> <b>than</b> when <b>it</b> first <b>started.</b> <br>"
+"&#43; <u>New</u> <u>UI</u> is <b>nice.</b> <br>"
+"&#43; It's a good ap, the <u>UI</u> is <b>better</b> <b>than</b> when <b>it</b> first <b>started.</b> <br>"
+"&#43; It's a good ap, the <u>UI</u> is <b>better</b> <b>than</b> when <b>it</b> first <b>started.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Outdated</b> <u>UI,</u> not material design. <br>"
+"- <b>Outdated</b> <u>UI,</u> not material design. <br>"
+"</p>","volumn":6,"sentiment":.33,"value":2.13},
{"keyword":"game","name":"<h1>game</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; When <b>I</b> try to look at scores for NFL <u>games,</u> the top of the screen may say one <b>date,</b> then the first <u>few</u> <u>games</u> <b>will</b> <b>be</b> <b>from</b> <b>a</b> previous <b>date,</b> the <u>next</u> <u>few</u> <u>games</u> <b>will</b> <b>be</b> <b>from</b> <b>a</b> <b>future</b> <b>date,</b> and maybe eventually I'll find <u>games</u> <b>from</b> the <b>date</b> listed at the top of the screen. <br>"
+"&#43; I t shows everything I need score and when the <u>game</u> <b>is</b> <b>played</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Like the yahoo sports layout <b>much</b> <b>better</b> and the fact that they don't have ads, but espn coverage, alerts and <u>game</u> <u>summaries</u> are <b>much</b> <b>better.</b> <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Your <u>version</u> <u>3</u> is <b>by</b> far the <b>best</b> to use. <br>"
+"&#43; I <b>like</b> the <u>older</u> <u>version</u> better. <br>"
+"&#43; I <b>like</b> the <u>older</u> <u>version</u> better. <br>"
+"&#43; I <b>like</b> the <u>older</u> <u>version</u> better. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Old</b> <u>version</u> <u>mention</u> which TV airing each game the New <u>version</u> doesn't <br>"
+"- Old <u>version</u> mention which <b>TV</b> <b>airing</b> each <b>game</b> the <u>New</u> <u>version</u> doesn't <br>"
+"- <b>Earlier</b> <u>versions</u> better. <br>"
+"- The <u>old</u> <u>grey</u> <u>one</u> was <b>better.</b> <br>"
+"</p>","volumn":14,"sentiment":.07,"value":2.71},
{"keyword":"Widget","name":"<h1>Widget</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Widget</u> <b>slow</b> to update. <br>"
+"- Ap <b>is</b> great but the <u>widget</u> <b>is</b> a <b>bugy</b> <b>mess.</b> <br>"
+"- I <b>love</b> the <u>widgets</u> and score updates that can be personalized to your favorite teams. <br>"
+"- <u>Widget</u> is <b>useless</b> <b>now.</b> <br>"
+"- <u>Widget</u> <b>will</b> <b>not</b> <b>function</b> <b>at</b> <b>all</b> and even clicking on icon won't load. <br>"
+"</p>","volumn":5,"sentiment":-1.00,"value":.61},
{"keyword":"score","name":"<h1>score</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is <b>not</b> <b>full</b> <u>score.</u> <br>"
+"- This app <b>is</b> slow and <u>bugy,</u> The <u>Score</u> <b>is</b> a much <b>better</b> <b>alternative.</b> <br>"
+"- This app <b>is</b> slow and <u>bugy,</u> The <u>Score</u> <b>is</b> a much <b>better</b> <b>alternative.</b> <br>"
+"- <b>Excellent</b> <u>score</u> updates. <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"Notifications","name":"<h1>Notifications</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Good ap, but <u>notifications</u> are <b>terible.</b> <br>"
+"- <u>Notifications</u> are <b>useless.</b> <br>"
+"- <u>1</u> <u>star</u> <u>notifications</u> are <b>pointless.</b> <br>"
+"- <u>Notifications</u> are way <b>too</b> <b>disruptive.</b> <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"ESPN","name":"<h1>ESPN</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <b>like</b> all the alerts <u>I</u> get <u>on</u> important sports updates, <u>I</u> just wish they had a better material design, app lags style, lollipop has been out since October of 2014, <u>I</u> <u>would</u> <u>have</u> <u>expected</u> <u>ESPN</u> <u>to</u> <u>be</u> <u>on</u> <u>par,</u> alerts still pop up with no color, <u>I</u> know someone at espn has an android and notices that. <br>"
+"- My deduction says <u>ESPN</u> isn't <b>capable</b> <b>of</b> <b>writing</b> an <b>app</b> <b>for</b> <b>high</b> <b>PPI</b> <b>devices.</b> <br>"
+"- Scores won't load, I'm a <b>huge</b> <u>espn</u> <u>fan</u> but the app sucks, whoever does the app isn't too bright <br>"
+"</p>","volumn":7,"sentiment":-.57,"value":1.37},
{"keyword":"teams","name":"<h1>teams</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Things</u> are <b>a</b> lot faster and <b>provides</b> <b>great</b> <b>content</b> <b>tailored</b> <b>for</b> my <b>sports</b> <b>interests.</b> <br>"
+"&#43; <u>Things</u> are a <b>lot</b> <b>faster</b> and provides great content tailored for my sports interests. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>love</b> the <u>way</u> <u>you</u> <u>can</u> <u>pick</u> <u>your</u> <u>favorite</u> <u>teams,</u> <u>da</u> only <u>thing</u> I dnt like is <u>you</u> can't <u>pick</u> as many <u>teams.</u> <br>"
+"- The <u>ads</u> <u>that</u> now <u>play</u> <u>before</u> every <u>video</u> and cannot <u>be</u> <u>skiped</u> are ridiculously <b>long.</b> <br>"
+"- Don't <b>like</b> the <u>way</u> recaps look on the mobile phone, it's a mobile device showing a full site's page. <br>"
+"- <b>Now</b> <u>many</u> <u>teams</u> <b>are</b> <b>not</b> <b>showing.</b> <br>"
+"</p>","volumn":7,"sentiment":-.29,"value":1.66},
{"keyword":"look","name":"<h1>look</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Looks</u> <b>and</b> <b>works</b> <b>great.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Why <b>does</b> this <u>look</u> like twiter. <br>"
+"- Update: v4.4.2 works with mobile phones better now but still don't <b>like</b> the <u>new</u> <u>look</u> <u>-</u> <u>hate</u> the <u>white</u> <u>background</u> <u>prefer</u> the <u>black</u> <u>background.Old</u> <u>post:</u> <u>Loved</u> <u>it</u> before, now <u>droping</u> <u>5</u> <u>to</u> <u>3</u> <u>stars.</u> <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
{"keyword":"Gamecast","name":"<h1>Gamecast</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Gamecast</u> is <b>pointless</b> <b>now!</b> <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
{"keyword":"design","name":"<h1>design</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Design</u> is <b>excellent,</b> scrolling is lagy. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <b>like</b> all the alerts <u>I</u> get on important sports updates, <u>I</u> just <u>wish</u> <u>they</u> <u>had</u> a better <u>material</u> <u>design,</u> app lags style, lollipop has been out since October of 2014, <u>I</u> would have expected ESPN to be on par, alerts still pop up with no color, <u>I</u> know someone at espn has an android and notices that. <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Update</u> <b>improved</b> <b>performance.</b> <br>"
+"&#43; I <b>love</b> the <u>updats</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>updates</u> can be a <b>litle</b> <b>better.</b> <br>"
+"- <u>Updates</u> are <b>usually</b> <b>prety</b> delayed. <br>"
+"- <u>Updates</u> are also <b>really</b> <b>slow.</b> <br>"
+"- <u>Updates</u> are <b>so</b> <b>slow.</b> <br>"
+"</p>","volumn":9,"sentiment":-.22,"value":1.98},
{"keyword":"feed","name":"<h1>feed</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Love <u>da</u> scores, <b>love</b> <u>da</u> videos, <b>love</b> <u>da</u> <u>news</u> <u>feed.</u> <br>"
+"&#43; Love <u>da</u> scores, <b>love</b> <u>da</u> videos, <b>love</b> <u>da</u> <u>news</u> <u>feed.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>news</u> <u>feed</u> is <b>just</b> <b>not</b> <b>enough</b> and please change da E icon, looks so boring and plain. <br>"
+"- <u>news</u> <u>feed</u> is just not enough and <b>please</b> <b>change</b> <b>da</b> <b>E</b> <b>icon,</b> looks so boring and plain. <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"ads","name":"<h1>ads</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Ads</u> before videos <b>is</b> <b>ANNOYING!</b> <br>"
+"&#43; <b>Malicious</b> <u>ads</u> /pop-ups found, beware! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Terible</b> <u>ads</u> and horible management <u>of</u> <u>info.</u> <br>"
+"- Decent, but too <b>many</b> <u>ads.</u> <br>"
+"</p>","volumn":5,"sentiment":.00,"value":1.61},
{"keyword":"football","name":"<h1>football</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]