var data_map_totalreviews=1022
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_swiftkey = [
{"keyword":"texting","name":"<h1>texting</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is <b>easy</b> <u>texting</u> and fun to use <br>"
+"&#43; <u>I</u> absolutely <b>love</b> all the layouts you can choose from, <u>I</u> also <b>love</b> that <u>it</u> <u>learns</u> how <u>I</u> talk, <u>it</u> <u>makes</u> <u>texting</u> and <u>emailing</u> so much <u>easier.</u> <br>"
+"&#43; <b>Great</b> <u>text</u> prediction and super fast. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"themes","name":"<h1>themes</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Accurate predictions and <b>Awesome</b> <u>themes!</u> <br>"
+"&#43; I'm using it right now and it has a great auto corect and <b>awesome</b> <u>themes</u> and emoticons I highly recommend it! <br>"
+"&#43; SwiftKey is smooth and accurate and has <b>great</b> <u>themes.</u> <br>"
+"&#43; Prediction and <u>themes</u> are <b>good</b> <b>to</b> <b>use.</b> <br>"
+"&#43; The <u>available</u> <u>themes</u> are <b>very</b> <b>nice.</b> <br>"
+"&#43; I am in love this keyboard, it has everything I was looking for and the <u>themes</u> are <b>beautiful.</b> <br>"
+"&#43; The <u>themes</u> are prety <b>cool,</b> <b>even</b> the free ones. <br>"
+"&#43; <b>Nice</b> <u>themes</u> also. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Themes</u> are <b>lame.</b> <br>"
+"- Great predictions which is very helpful for me, I also <b>liked</b> the <u>new</u> <u>theme,</u> but the performance isn't the best out there though. <br>"
+"- As a keyboard, yes it is great, however the <u>themes</u> are <b>boring,</b> <b>without</b> <b>many</b> <b>free</b> <b>choices.</b> <br>"
+"- The <u>themes</u> are <b>ugly</b> <br>"
+"- With text prediction, <b>multiple</b> <u>themes,</u> a customized symbols keyboard and other various improvements this keyboard blows everything else out of the water <br>"
+"- I know it's a freemium app but the <u>free</u> <u>themes</u> are <b>hideous.</b> <br>"
+"- Some <u>themes</u> are <b>fine</b> others, such as carbon, still look weird in the prediction bar. <br>"
+"</p>","volumn":27,"sentiment":.52,"value":3.81},
{"keyword":"language","name":"<h1>language</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Bengali <u>language</u> <u>pack</u> is good but <b>yet</b> <b>needs</b> <b>great</b> <b>improvement</b> <b>as</b> <b>lots</b> <b>of</b> <b>leters</b> <b>not</b> <b>yet</b> <b>covered</b> and <b>come</b> <b>as</b> <b>predictions/</b> <b>sugestions.</b> <br>"
+"&#43; Bengali <u>language</u> <u>pack</u> is <b>good</b> but yet needs great improvement as lots of leters not yet covered and come as predictions/ sugestions. <br>"
+"&#43; I'm also a <b>big</b> <u>fan</u> <u>of</u> all the available <u>language</u> setings, and how I'm able to use a French and English keyboard seting at the same time. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It might be a bit tricky one because unlike English, <u>Thai</u> <u>language</u> <b>has</b> no <b>space</b> <b>between</b> <b>words.</b> <br>"
+"- <u>Multiple</u> <u>languages</u> is <b>also</b> <b>important</b> and it recognises uncommon <u>languages</u> like Dutch and Tagalog. <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"predictions","name":"<h1>predictions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Accurate</b> <u>predictions</u> and Awesome themes! <br>"
+"&#43; It is very <b>impressive</b> <u>prediction</u> and corection capability. <br>"
+"&#43; <u>Intelligent</u> <u>predictive</u> <u>text</u> <b>works</b> <b>well.</b> <br>"
+"&#43; I <b>love</b> the multiple languages and <u>excellent</u> <u>predictions!</u> <br>"
+"&#43; <u>Word</u> <u>prediction</u> is <b>also</b> <b>superb!</b> <br>"
+"&#43; The <u>text</u> <u>prediction</u> is <b>very</b> <b>good.</b> <br>"
+"&#43; <u>Prediction</u> and themes are <b>good</b> <b>to</b> <b>use.</b> <br>"
+"&#43; <b>Great</b> <u>predictions!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Also</b> <u>some</u> <u>of</u> the <u>predictions</u> are <b>ridiculous.</b> <br>"
+"- <b>Previously</b> SwiftKey used <b>to</b> work better with Thai <u>word</u> <u>prediction</u> due <b>to</b> SwiftKey <b>allows</b> <b>both</b> <b>characters</b> <b>to</b> <b>get</b> <b>picked</b> <b>from</b> <b>earlier</b> <b>keyboard</b> <b>layout.</b> <br>"
+"- <u>Predictive</u> <u>text</u> <b>gone</b> <b>to</b> <b>hell.</b> <br>"
+"- The <u>predictive</u> <u>text</u> <b>is</b> the <b>bigest</b> <b>issue</b> for me right now. <br>"
+"- The <u>word</u> <u>prediction</u> are <b>not</b> <b>as</b> <b>good</b> <b>as</b> <b>before</b> <b>AND</b> the <b>vibration</b> on <b>pressing</b> the <b>keys</b> <b>does</b> <b>not</b> <b>work</b> anymore. <br>"
+"- I <b>do</b> <b>not</b> <b>like</b> <u>predictions.</u> <br>"
+"- Personalized <u>text</u> <u>predictions</u> is <b>awesome</b> <b>too.</b> <br>"
+"- <b>Great</b> <u>predictions</u> which is very helpful for me, I also liked the new theme, but the performance isn't the best out there though. <br>"
+"</p>","volumn":99,"sentiment":.07,"value":4.67},
{"keyword":"Swipe","name":"<h1>Swipe</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This keyboard is great with the exception of <b>one</b> major flaw: <u>swiping</u> <b>does</b> <b>not</b> <b>work</b> <b>on</b> <b>lockscreen.</b> <br>"
+"- <u>Swipe</u> <b>has</b> <b>become</b> much less <b>accurate</b> <b>in</b> the <b>last</b> <b>year.</b> <br>"
+"- Performance has been greatly increased, <u>Swipe</u> is <b>accurate,</b> though some terms that are obvious to me aren't to it, but it's learning. <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"emoji","name":"<h1>emoji</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But the <u>emojis</u> are <b>very</b> <b>annoying</b> when typing and I wish there was a way to disable them. <br>"
+"- I like that the keyboard is customizable and the <u>emoji</u> <u>sugestions</u> have <b>been</b> a <b>cute</b> <b>adition</b> to my texts when I wouldn't have thought to ad one. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>latest</u> <u>version</u> is <b>really</b> <b>bugy.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>newer</u> <u>version</u> (date <u>of</u> <u>install:</u> <u>July</u> <u>26,</u> <u>2015)</u> also <b>has</b> <b>better</b> <b>prediction</b> <b>for</b> <b>Croatian</b> <b>language,</b> <b>which</b> <b>I</b> <b>find</b> really <b>useful!</b> <br>"
+"- <u>New</u> <u>version</u> is <b>VERY</b> <b>VERY</b> <b>SLOW</b> ! <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"keys","name":"<h1>keys</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>comfortable</b> and soft <u>touch</u> <u>keys.</u> <br>"
+"&#43; The <u>larger</u> <u>keys</u> are <b>good</b> <b>for</b> my <b>fat</b> <b>thumbs.</b> <br>"
+"&#43; <u>Numeric</u> <u>keys</u> are <b>great.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Still</b> <b>lacks</b> <b>some</b> very <b>useful</b> <u>secondary</u> <u>keys</u> <u>though.</u> <br>"
+"- Word prediction is horible at times on small phones, however I <b>like</b> that I can have <u>arow</u> <u>keys</u> <br>"
+"- <u>keys</u> are <b>too</b> <b>small.</b> <br>"
+"- It is not sure why, but with new update on s5 active my <u>whole</u> <u>phones</u> <b>slowed</b> down <b>tremendously!</b> <br>"
+"- Usually I have tons of troubles when I'm typing with my phone because the <u>keys</u> are <b>really</b> <b>small.</b> <br>"
+"- The one issue I have with the new update is the <b>smaller</b> <u>keys</u> makes texting and typing in general less accurate. <br>"
+"- After the upgrade to marshmallow, in some languages the leters are so small and very hard to read, in others they are even smaller and it seems like the <u>keys</u> are <b>empty.</b> <br>"
+"- <u>Keys</u> cannot <b>be</b> <b>made</b> <b>large</b> enough <b>in</b> <b>landscape</b> <b>pad</b> <b>mode.</b> <br>"
+"</p>","volumn":13,"sentiment":-.46,"value":2.10},
{"keyword":"accuracy","name":"<h1>accuracy</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>horible</b> <u>accuracy.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Also, the <u>accuracy</u> is <b>plain</b> <b>awful.</b> <br>"
+"- <u>Smooth,</u> <u>faster,</u> <u>accuracy</u> is too <b>good</b> <b>even</b> <b>in</b> <b>swipe</b> <b>typing.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"lag","name":"<h1>lag</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>lag</u> is <b>real.</b> <br>"
+"&#43; <b>Serious</b> <u>lag</u> for sure. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>lag</u> is <b>ridiculous.</b> <br>"
+"- Use Google keyboard big and <u>lag</u> <u>only</u> <b>swiftkeyboard</b> smooth and <b>small</b> <br>"
+"- The <u>lag</u> and slow speed was <b>terible</b> the last time <br>"
+"- <b>Slow</b> <u>lag</u> what is going with this keyboard! <br>"
+"- <b>Bad</b> <u>lag.</u> <br>"
+"</p>","volumn":9,"sentiment":-.33,"value":1.86},
{"keyword":"options","name":"<h1>options</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>customization</u> <u>options</u> are <b>great.</b> <br>"
+"&#43; <b>Really</b> <b>like</b> the <b>ap,</b> the <u>different</u> <u>options</u> are <b>great.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I love the keyboard, awesome <u>customisation</u> <u>options,</u> <b>useful</b> layout and the bilingual option is <b>extremely</b> <b>useful.</b> <br>"
+"- I love the keyboard, awesome customisation options, <b>useful</b> layout and the <u>bilingual</u> <u>option</u> is <b>extremely</b> <b>useful.</b> <br>"
+"- It is <b>not</b> <b>enough</b> <u>customisation</u> <u>available.</u> <br>"
+"- <u>Sync</u> <u>option</u> isn't <b>working</b> <b>since</b> the last <b>6</b> days and <b>all</b> my <b>saved</b> <b>words</b> are lost. <br>"
+"- <b>Also</b> the <u>flow</u> <u>option</u> isn't <b>accurate.</b> <br>"
+"</p>","volumn":9,"sentiment":-.33,"value":1.86},
{"keyword":"typing","name":"<h1>typing</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; With the <b>help</b> <b>of</b> <b>Flow,</b> <u>typing</u> has been <b>so</b> <b>easy!</b> <br>"
+"&#43; The <u>typing</u> <u>experience</u> is <b>so</b> <b>great.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But the emojis are very annoying when <u>typing</u> and I <b>wish</b> there was a way to disable them. <br>"
+"- Great layout and has a lot of potential, but the <u>gesture</u> <u>typing</u> is <b>awful,</b> it prefers to enter random leters and nonsense than atempting to form a common word <br>"
+"- Great layout and has a lot of potential, but the <u>gesture</u> <u>typing</u> is <b>awful,</b> it prefers to enter random leters and nonsense than atempting to form a common word <br>"
+"- <u>Gesture</u> <u>typing</u> is <b>very</b> <b>very</b> <b>functional</b> and awesome <br>"
+"</p>","volumn":6,"sentiment":-.33,"value":1.46},
{"keyword":"response","name":"<h1>response</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But when typing continuously, <u>keys</u> <u>responsiveness</u> is <b>not</b> that <b>good.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"lagy","name":"<h1>lagy</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's a <b>litle</b> <u>lagy</u> on my s6 edge, sometimes it can be unresponsive for a few seconds too. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"fonts","name":"<h1>fonts</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Font</u> <b>is</b> <b>kind</b> <b>of</b> <b>old</b> <b>looking.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- With the update to Android M on my Nexus 5 though, the <u>font</u> used for the keyboard and prediction bar is <b>so</b> <b>tiny,</b> it's difficult to read or see at a glance. <br>"
+"- Love this keyboard, just flashed Marshmallow 6.0.0 and the <u>fonts</u> <b>have</b> <b>changed</b> <b>to</b> <b>be</b> <b>too</b> <b>small.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"auto-corect","name":"<h1>auto-corect</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>auto</u> <u>corect,</u> word prediction, emoj/sugestion is <b>wonderful</b> <br>"
+"&#43; <b>Swiftkey</b> <b>gets</b> <b>to</b> <b>know</b> <b>you</b> personally <b>there</b> <u>autocorect</u> and presugestions are amazingly accurate. <br>"
+"&#43; The predictive text and <u>autocorect</u> <b>exceeds</b> all <b>my</b> <b>expectations.</b> <br>"
+"&#43; I'm a fast typer, so the <u>error</u> <u>corection</u> <b>is</b> <b>spot</b> on and easy to use. <br>"
+"&#43; This is helpful and the <u>corections</u> <b>are</b> almost <b>spot</b> on most of the time. <br>"
+"&#43; <u>Auto</u> <u>corect</u> is prety darn <b>good</b> as <b>well</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>auto</u> <u>corect</u> <b>is</b> <b>not</b> <b>working</b> <b>probably,</b> it's puting up leters that I'm <b>not</b> typing, and it's very very slow. <br>"
+"- The <u>auto</u> <u>corection</u> can be <b>annoying</b> <b>sometimes.</b> <br>"
+"- I prefer two finger typing as oposed to swipe, as the <u>corections</u> are <b>so</b> <b>accurate</b> it's unreal. <br>"
+"- The <u>auto</u> <u>corect</u> is the <b>worst.</b> <br>"
+"- Love it, <b>however</b> <b>like</b> all <b>keyboards,</b> <u>auto</u> <u>corect</u> is <b>psychotic.</b> <br>"
+"- <u>Auto</u> <u>space</u> <u>after</u> a <u>punctuation</u> is <b>annoying.</b> <br>"
+"- <b>Sometimes</b> <b>makes</b> <u>auto</u> <u>corect</u> <u>mistakes</u> but <b>i</b> like it overall. <br>"
+"- <b>Where</b> is <u>auto</u> <u>punctuation</u> <u>on</u> <u>space</u> <u>key</u> <u>press?</u> <br>"
+"</p>","volumn":24,"sentiment":-.25,"value":2.93},
{"keyword":"function","name":"<h1>function</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; All in all: <u>Elegant,</u> <b>simple</b> and <u>functional.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- the <u>swipe</u> <u>function</u> is <b>fast</b> and accurate <br>"
+"- <b>Swype</b> <u>function</u> glitchy and inaccurate. <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
{"keyword":"word","name":"<h1>word</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>I</b> think this is so amazing all <b>I</b> do is start typing and the <u>words</u> <b>come</b> up <b>I</b> love love love this ap <br>"
+"&#43; <b>Great</b> <u>word</u> predictor. <br>"
+"&#43; I <b>love</b> the <u>new</u> <u>Romaji</u> <u>input.</u> <br>"
+"&#43; The <u>word</u> <u>sugestions</u> are <b>always</b> <b>accurate.</b> <br>"
+"&#43; <b>Otherwise</b> the <u>English</u> <u>input</u> is <b>excellent.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Just</u> <u>inputs</u> <u>one</u> <u>word</u> <u>and</u> then <b>overwrites</b> <b>with</b> the <b>next</b> <u>word.</u> <br>"
+"- Some <u>words</u> <b>take</b> up to 10-15 secs to be writen, depending <b>on</b> how big your dictionary is, <b>so</b> yeah, the more you use it, the more lagy it gets. <br>"
+"- The <u>intuitive</u> <u>program</u> <u>that</u> <u>guesses</u> your <u>next</u> <u>word</u> is <b>useful</b> <b>too.</b> <br>"
+"- Predicted <u>words</u> are <b>completely</b> <b>wrong</b> . <br>"
+"- It is very <b>intuitive</b> <u>word</u> <u>recommendations,</u> loads of personalization option with free and for purchase skins. <br>"
+"- The <u>swipe</u> <u>input</u> <u>method</u> is <b>super</b> difficult to use compared to AOSP/Google keyboard, so completely useless on handsets. <br>"
+"- Otherwise <u>English</u> <u>input</u> <b>is</b> great, <b>awesome</b> <b>prediction</b> and swipe, no autocorect fails yet! <br>"
+"- <u>Flow</u> <u>input</u> is <b>nice</b> but the predictions are so od that I spend much time corecting them. <br>"
+"</p>","volumn":14,"sentiment":-.21,"value":2.42},
{"keyword":"layout","name":"<h1>layout</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Nice</b> <u>Layout.</u> <br>"
+"&#43; The <u>layout</u> for other languages is actually <b>very</b> <b>easy</b> <b>to</b> <b>use!</b> <br>"
+"&#43; I absolutely <b>love</b> all <u>the</u> <u>layouts</u> you can choose from, I also <b>love</b> that it learns how I talk, it makes texting and emailing so much easier. <br>"
+"&#43; <b>Beautiful</b> <u>layout,</u> arows. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But the <u>layout</u> <u>of</u> <u>emojis</u> is <b>so</b> <b>ugly!</b> <br>"
+"- I love the keyboard, awesome customisation options, <u>useful</u> <u>layout</u> and the bilingual option is <b>extremely</b> <u>useful.</u> <br>"
+"- <u>Layout</u> <u>customisation</u> <b>works</b> <b>flawlessly</b> and it doesn't warp like some keyboards on the market. <br>"
+"- <b>Great</b> <u>layout</u> and has a lot of potential, but the gesture typing is awful, it prefers to enter random leters and nonsense than atempting to form a common word <br>"
+"- It's <b>good</b> but the <u>arabic</u> <u>layout</u> is <b>not</b> <b>good.</b> <br>"
+"- Emoji doesn't show up and <u>layout</u> is <b>lame</b> it covers full screen of my mobile. <br>"
+"</p>","volumn":11,"sentiment":-.18,"value":2.22},
{"keyword":"Swype","name":"<h1>Swype</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>swyping</u> is <b>so</b> <b>accurate.</b> <br>"
+"&#43; <u>Swype</u> is <b>more</b> <b>accurate</b> while <b>swiping.</b> <br>"
+"&#43; <u>Swype</u> is <b>more</b> <b>accurate</b> while <b>swiping.</b> <br>"
+"&#43; I love it and bought it, but I am much more <b>accurate</b> <u>with</u> <u>swype.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Swype</u> <b>has</b> <b>better</b> <b>accuracy</b> than this. <br>"
+"- <u>Swype</u> <b>has</b> <b>better</b> <b>accuracy</b> than this. <br>"
+"- I <b>love</b> using punctuation and <u>playing</u> <u>around</u> <u>with</u> <u>different</u> <u>symbols;</u> I don't like to limit myself?especially when I take editing and proofreading seriously. <br>"
+"- I'd <b>love</b> <u>to</u> <u>swap</u> the <u>common</u> <u>punctuation</u> <u>with</u> <u>|[</u> <u>]</u> and/or <u>{</u> }. <br>"
+"- It is not sure why, <u>but</u> <u>with</u> <u>new</u> <b>update</b> <b>on</b> <b>s5</b> active my whole phones slowed down tremendously! <br>"
+"- Also the <u>swype</u> is <b>not</b> even <b>remotely</b> <b>accurate,</b> and third it does <b>not</b> remember and prompt the corect words that I use. <br>"
+"</p>","volumn":11,"sentiment":-.18,"value":2.22},
]