var data_map_totalreviews=624
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_wechat = [
{"keyword":"experience","name":"<h1>experience</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Amazing</b> <u>experience</u> so far! <br>"
+"&#43; It is very <b>good</b> <u>experience*</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Good interface and <u>experience</u> but some thing <b>is</b> <b>missing</b> <b>like</b> <b>to</b> <b>see</b> <b>offline</b> <b>last</b> <b>seen</b> <b>etc.</b> <br>"
+"</p>","volumn":3,"sentiment":.67,"value":1.77},
{"keyword":"lot","name":"<h1>lot</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>liked</b> the <u>Tuzki</u> <u>Office</u> <u>sticker.</u> <br>"
+"&#43; Essy to use, colorful, and just a <b>whole</b> <u>lot</u> of fun. <br>"
+"&#43; I <b>love</b> the <u>stickers.</u> <br>"
+"&#43; <b>also</b> <b>consumes</b> <u>lots</u> <u>of</u> <u>batery</u> and <u>memory.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- it is quite unconvinient to scroll page by page while I have saved a <u>lot</u> <u>of</u> <u>stickers~</u> <b>T.T</b> <br>"
+"</p>","volumn":5,"sentiment":.60,"value":2.21},
{"keyword":"better","name":"<h1>better</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>nice</b> <u>ap,</u> <u>better</u> than line imo. <br>"
+"&#43; i feel wechat are the <b>best</b> and <u>better</u> <u>aps</u> between another <u>aps</u> . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- its <u>better</u> <u>than</u> <u>before.Samsung</u> <b>can</b> <b>see</b> <b>more</b> <b>aple</b> <u>s</u> <b>emoji.Good!</b> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"video","name":"<h1>video</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>good</b> hd <u>quality</u> <u>video</u> and audio calls <br>"
+"&#43; <u>I</u> <b>like</b> <u>it</u> <u>fast</u> and <u>easy</u> <u>to</u> <u>make</u> <u>a</u> <u>video</u> <u>call</u> <br>"
+"&#43; I <b>love</b> <u>video</u> <u>camera</u> very much <br>"
+"&#43; <u>Call</u> <u>quality</u> <u>is</u> <u>good</u> <u>but</u> <u>once</u> <u>in</u> a <u>while</u> <u>users</u> <u>on</u> the <u>other</u> <u>side</u> can't <b>hear</b> my voice and <b>vice</b> <b>versa,</b> its like its accidentally muted and then we have to call again. <br>"
+"&#43; I <b>love</b> the <u>video</u> <u>quality</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Wechat</u> (before <b>6.0)</b> <u>best</u> <u>feature</u> :Sent <u>video</u> <u>clip</u> <u>30s,</u> now (since <b>6.0)</b> <u>cut</u> <u>video</u> <u>clip</u> <u>to</u> <u>6</u> <u>s,</u> <u>not</u> <u>useful</u> <u>at</u> <u>all</u> <u>,</u> and <u>other</u> <u>who</u> <u>use</u> <u>older</u> <u>ver,</u> can't <b>see</b> your <b>new</b> ver(after <b>6.0)</b> <u>video.</u> <br>"
+"- The <u>call</u> <u>quality</u> was <b>very</b> <b>poor,</b> voice breaking all the time . <br>"
+"</p>","volumn":9,"sentiment":.22,"value":2.42},
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>loved</b> this <u>aplication</u> very <u>useful.</u> <br>"
+"&#43; <b>wonderful</b> <u>aplication.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Everytime I look profile pictures from people nearby, this <u>aplication</u> <b>creates</b> <b>folders</b> <b>in</b> my <b>phone</b> <b>storage,</b> containing photos of people nearby. <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"wechat","name":"<h1>wechat</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Dear</u> <u>admin,</u> <u>I</u> <u>updated</u> my <u>wechat</u> recently and my <u>wechat</u> b'come <u>slow,</u> laging, can't <b>see</b> <b>stickers</b> my friends sent me and even videos or pictures? same to me <u>I</u> can't send out or upload any pictures or videos too! <br>"
+"- The <u>functionality</u> <u>of</u> <u>Wechat</u> is <b>quite</b> <b>terible</b> and there are bugs that was never fixed. <br>"
+"- I <b>like</b> so <u>much</u> <u>wechat</u> <u>but</u> <u>i</u> <b>like</b> old vertn <br>"
+"- <b>I</b> hereby wish that <u>wechat</u> <u>company</u> <b>could</b> <b>look</b> <b>into</b> this <b>mater</b> <b>promptly</b> and make some changes asap! <br>"
+"- I hereby wish that <u>wechat</u> <u>company</u> could look into this mater promptly and <b>make</b> some <b>changes</b> <b>asap!</b> <br>"
+"- I hereby wish that <u>wechat</u> <u>company</u> could look into this mater promptly and <b>make</b> some <b>changes</b> <b>asap!</b> <br>"
+"- <u>Wechat</u> <u>download</u> <b>is</b> <b>geting</b> <b>slower</b> and <b>slower.</b> <br>"
+"</p>","volumn":7,"sentiment":-1.14,"value":.80},
{"keyword":"features","name":"<h1>features</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Really good <u>bout</u> <u>features</u> but should <b>be</b> <b>have</b> <b>facility</b> to forward voice note from chat. <br>"
+"&#43; <b>Great</b> <u>features,</u> very <b>reliable,</b> <u>easy</u> to use. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Too <b>much</b> <u>useless</u> <u>features,</u> <b>requires</b> too <b>much</b> <b>permissions.</b> <br>"
+"- & <u>features</u> <b>are</b> also <b>value</b> less. <br>"
+"- <u>mostly</u> the <u>shake</u> <u>feature</u> doesn't <b>work</b> <b>properly</b> <br>"
+"- Great app to interact with foreigners but I don't <b>like</b> the <u>shake</u> <u>feature</u> because when a female <u>shake</u> her phone one time , she gets Many replies. <br>"
+"- doesn't <b>have</b> <b>the</b> sent or <b>read</b> <u>feature</u> <br>"
+"</p>","volumn":9,"sentiment":-.44,"value":1.75},
{"keyword":"UI","name":"<h1>UI</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; But <u>UI</u> <b>maters</b> a <b>lot</b> <b>to</b> <b>me.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Bad</b> <u>UI.</u> <br>"
+"- <u>ui</u> is <b>not</b> <b>very</b> <b>good</b> and too many use less thing in it? <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>New</u> <u>version</u> is <b>superb</b> <br>"
+"&#43; <u>new</u> <u>version</u> is <b>better</b> <b>than</b> <b>last</b> <b>one</b> <br>"
+"&#43; <u>Old</u> <u>version</u> is <b>good</b> <br>"
+"&#43; the <u>old</u> <u>version</u> is <b>Good.</b> <br>"
+"&#43; I <b>love</b> this <u>new</u> <u>version</u> because they are too many things we can do . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>However</b> the <u>latest</u> <u>version</u> after <u>update</u> <u>look</u> like doesn't work anymore the problem is I can't log in-_- just stuck at main page, I mean at the *earth picture page. <br>"
+"- <b>Latest</b> version(wechat v6.1). <br>"
+"- I <b>like</b> <u>version</u> before this where log in much more simple.this <u>version</u> take a long way to change account <br>"
+"- I know this <u>version</u> is <b>very</b> user <b>friendly</b> <br>"
+"- <u>I</u> <b>like</b> <u>curent</u> <u>version</u> very very <u>much</u> and need more improvements <br>"
+"- <u>Latest</u> <u>version</u> <b>wants</b> <b>access</b> <b>to</b> my <b>phone,</b> and call logs. <br>"
+"- <u>Latest</u> <u>version</u> wants access to my phone, and <b>call</b> <b>logs.</b> <br>"
+"- i <b>hate</b> <u>new</u> <u>version</u> because its auto search at people nearby when i at people nearby and auto refresh when i at moment <br>"
+"</p>","volumn":17,"sentiment":-.12,"value":2.72},
{"keyword":"messageing","name":"<h1>messageing</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Prety <b>nice</b> <u>messageing</u> app with good interactions. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It would be much great if the sender can see if the <u>message</u> <b>is</b> <b>already</b> <b>read</b> by reciever. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
{"keyword":"Social","name":"<h1>Social</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>comfortable</b> <u>social</u> <u>network</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Network</u> <b>automatically</b> <b>shifts</b> <b>to</b> <b>3G</b> <b>frm</b> <b>WiFi</b> when using Shake feature. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
{"keyword":"people","name":"<h1>people</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Fun, and I <b>love</b> <u>meeting</u> <u>people!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>the</b> <u>same</u> <u>repetitive</u> <u>people</u> <b>show</b> up <b>in</b> <b>the</b> <u>people</u> <b>nearby</b> <b>option.</b> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]