var data_map_totalreviews=973
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_spotifymusic = [
{"keyword":"spotify","name":"<h1>spotify</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- If I had to throw out a way that <u>Spotify</u> could <b>improve,</b> I'd say that it would be awesome if they could somehow integrate spotify to my alarm clock so I can have a morning playlist. <br>"
+"- <u>I</u> <b>wish</b> <u>Spotify</u> <u>had</u> the <u>feature</u> <u>that</u> <u>Pandora</u> <u>does</u> <u>to</u> <u>ad</u> <u>variety</u> <u>to</u> my <u>radio</u> <u>station</u> and songs <u>I</u> don't like would stay off my <u>station</u> also only play songs every <u>6</u> hours or so. <br>"
+"- <u>I</u> <b>wish</b> <u>spotify</u> <u>offline</u> <u>was</u> <u>free.</u> <br>"
+"- <b>Really</b> <u>love</u> <u>spotify,</u> just wish <b>there</b> <b>were</b> more payment options. <br>"
+"</p>","volumn":4,"sentiment":-1.00,"value":.39},
{"keyword":"was","name":"<h1>was</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <b>wish</b> the <u>sound</u> <u>playback</u> in the car plugin <u>was</u> better. <br>"
+"- I just <b>wish</b> that <u>there</u> <u>was</u> an <u>option</u> to pay for annual service instead of just monthly. <br>"
+"- I just <b>wish</b> <u>there</u> <u>was</u> an <u>option</u> to save downloaded music to an external SD card. <br>"
+"- Just <b>wish</b> the <u>price</u> <u>was</u> <u>lower</u> <u>for</u> <u>Premium</u> <br>"
+"- Just <b>wish</b> the <u>price</u> <u>was</u> <u>lower</u> <u>for</u> <u>Premium</u> <br>"
+"- <u>I</u> do <b>wish</b> <u>premium</u> <u>membership</u> <u>was</u> <u>a</u> <u>lil</u> <u>cheaper</u> though. <br>"
+"- I <b>wish</b> <u>there</u> wasn't <u>perieam</u> <u>but</u> <u>they</u> <u>got</u> <u>to</u> <u>make</u> <u>money</u> <u>some</u> how <br>"
+"</p>","volumn":7,"sentiment":-1.00,"value":.95},
{"keyword":"some","name":"<h1>some</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The Bluetooth end of this app <b>needs</b> <u>some</u> <u>tlc.</u> <br>"
+"- This app is one of the best aps have seen ever you guys are amazing at what y'all do I have a few complaints and i know it won't mean anything but I can try to persuade you to <b>make</b> <u>some</u> <u>adjustments</u> the skip limit is annoying I don't get it you don't have one on the tablet version and you have shuffle on all the time I wish you let us use the repeat and constant play, and shuffle freely and the mobile data only if no premium is messed up not everyone has unlimited data. <br>"
+"- It <b>need</b> <u>some</u> <u>fix.</u> <br>"
+"- <b>There</b> <b>are</b> <u>some</u> <u>flaws</u> <u>in</u> <u>terms</u> <u>of</u> <u>loading</u> <u>offline/online</u> <u>playlists,</u> but it tends to work after a few tried turning it <u>off</u> and on again? <br>"
+"</p>","volumn":4,"sentiment":-1.00,"value":.39},
{"keyword":"music","name":"<h1>music</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- They need to <b>make</b> <u>the</u> <u>music</u> <u>ti</u> where it doesn't have to have WiFi or data to use it <br>"
+"- I <b>wish</b> the <u>playlists</u> <u>were</u> <u>updated</u> more often <u>with</u> <u>new</u> <u>music</u> <br>"
+"- Just sign up for <u>the</u> premium and it's <u>the</u> best <b>you</b> <b>could</b> ever <u>get</u> <u>all</u> <u>the</u> <u>music</u> <u>I</u> <u>want</u> <u>I</u> <u>have</u> no <u>ads</u> no glitching stalling or hesitation <u>I</u> think this app works amazing <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"5-star","name":"<h1>5-star</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Takes bout two minets or more if you fix this problem then i would <b>give</b> it <u>five</u> <u>stars</u> <u>instead</u> <u>of</u> <u>four.other</u> <u>wis</u> its the coolest music app ever maby you can make some other music player like this BUT PLEASE FIX THIS PROBLEM THANK YOU SO MUCH <br>"
+"- Other than that good app if that was not an issue would <b>give</b> <u>5</u> <u>stars</u> <br>"
+"- I'd <b>give</b> <u>it</u> <u>5</u> <u>stars</u> if <u>I</u> could play the song <u>I</u> <u>choose</u> <u>it</u> goes off of my playlist or the album <u>I</u> <u>choose</u> and <u>I</u> <u>hate</u> that I'm <u>about</u> <u>to</u> <u>uninstall</u> <u>it</u> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"screen","name":"<h1>screen</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Spotify, if you want people to acctualy buy your app you should make it possible for them to buy premium and not <b>give</b> them <u>a</u> <u>loading</u> <u>screen</u> <u>that</u> <u>never</u> <u>ends.</u> <br>"
+"- I like that I instantly got all <u>the</u> albums of my favorite band but very iritated <u>the</u> <u>only</u> <u>option</u> <u>to</u> <u>listen</u> <u>to</u> my <u>playlist</u> is <b>on</b> <b>shuffle</b> <b>mode!</b> <br>"
+"- <u>I</u> do <b>wish</b> the <u>lock</u> <u>screen</u> <u>widget</u> <u>thing</u> <u>could</u> <u>be</u> better <u>designed,</u> but no <u>big</u> <u>deal.</u> <br>"
+"- And lastly <u>playlists</u> <b>need</b> <b>to</b> <b>have</b> a <b>permanent</b> <b>sorting</b> <b>option.</b> <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"they","name":"<h1>they</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The only issue <u>I</u> see <b>is</b> that <b>when</b> <b>there</b> <b>is</b> <u>someone</u> <u>they</u> don't really <u>have</u> <u>much</u> <u>of</u> <u>like</u> The <u>Beatles</u> or <u>Taylor</u> <u>Swift</u> you <u>have</u> no easy option to upload your own music or to buy it <u>like</u> google all access does. <br>"
+"- Awesome just <b>wish</b> <u>it</u> didn't <u>use</u> so <u>much</u> <u>data</u> <br>"
+"- I just <b>wish</b> <u>they</u> <u>put</u> <u>in</u> a <u>sleep</u> <u>timer</u> built into the app. <br>"
+"- PLEASE put the song options buton <b>on</b> the left side <b>of</b> songs so they're <b>not</b> <b>on</b> <b>top</b> <b>of</b> the <b>scroller.</b> <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"Chromecast","name":"<h1>Chromecast</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>it</u> <u>had</u> <u>Chromecast.</u> <br>"
+"- It <b>needs</b> <u>Chromecast</u> <u>suport!</u> <br>"
+"- I <b>wish</b> <u>it</u> <u>had</u> more <u>integration</u> <u>with</u> <u>ford</u> <u>sync.</u> <br>"
+"</p>","volumn":4,"sentiment":-.75,"value":.64},
{"keyword":"songs","name":"<h1>songs</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I really <b>hope</b> that <u>there</u> <u>could</u> <u>be</u> <u>lyrics</u> <u>for</u> the <u>songs.</u> <br>"
+"&#43; <u>I</u> <b>wish</b> that <u>i</u> <u>could</u> <u>play</u> <u>it</u> <u>any</u> <u>where</u> but thats ok <u>its</u> still amazing <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- So if you could ad a are you sure you <b>want</b> <u>to</u> <u>play</u> <u>song</u> popup when you have <u>songs</u> aded in queue. <br>"
+"- I got premium and my downloads are supose to <u>play</u> offline and they don't they <b>need</b> internet to <u>play</u> <u>please</u> <u>fix</u> because i don't wanna be wasting $10 a month <br>"
+"- I like it but I <b>wish</b> <u>you</u> <u>could</u> <u>download</u> <u>songs</u> <u>from</u> <u>this</u> <br>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>select</u> the <u>song</u> <u>for</u> <u>free.</u> <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>play</u> the <u>music</u> that <u>I</u> <u>saved/downloaded</u> <u>offline</u> when <u>I</u> had the trial premium version. <br>"
+"- I love the ap, I just think that on the free version, you should be able to pick what <u>song</u> you <b>wish</b> to listen to. <br>"
+"- And <u>I</u> <b>wish</b> <u>they</u> <u>would</u> <u>ad</u> <u>a</u> don't <u>play</u> this <u>band</u> <u>feature</u> <u>in</u> the <u>radio</u> <u>part.</u> <br>"
+"- I love classic rock but all my favorite <u>Beatles</u> <u>song</u> are not on the list so if <b>you</b> <b>can</b> <u>put</u> <u>some</u> <u>more</u> <u>Beatle</u> <u>song</u> <u>it</u> <u>would</u> <u>be</u> <u>great.P.S.</u> <br>"
+"</p>","volumn":26,"sentiment":-.69,"value":2.57},
{"keyword":"more","name":"<h1>more</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Outstanding but please <b>include</b> <u>more</u> <u>artist</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The only gripe I have is that I'd like to <b>see</b> <u>more</u> <u>Japanese</u> <u>artists</u> (back-on, nami tamaki, stereopony, granrodeo, flow, etc). <br>"
+"- I really like this app but it <b>needs</b> <u>more</u> Taylor Swift every other great artist has all there new song uploaded on to this but no Taylor Swift come what do y'all have against her. <br>"
+"- Like it, but <b>needs</b> more <u>artists.</u> <br>"
+"- <b>Really</b> love spotify, just wish <b>there</b> <b>were</b> <u>more</u> <u>payment</u> <u>options.</u> <br>"
+"- Also, <u>more</u> <u>of</u> <u>a</u> <u>selection</u> <u>of</u> urban/R&B/mainstream <u>pop</u> <b>would</b> <b>be</b> <b>nice.</b> <br>"
+"- Love it, but wish <b>there</b> <b>were</b> <u>more</u> <u>remixes.</u> <br>"
+"- I like the different stations although they do tend to repeat and <b>there</b> aren't <u>enough</u> <u>artist.</u> <br>"
+"- Just <b>wish</b> <u>there</u> <u>were</u> <u>more</u> <u>of</u> my <u>favorite</u> <u>bands.</u> <br>"
+"</p>","volumn":12,"sentiment":-.67,"value":1.82},
{"keyword":"would-be","name":"<h1>would-be</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Spotify <b>is</b> amazing because of their choice of music selection and <b>there</b> <b>is</b> <u>a</u> <u>offline</u> <u>choice.its</u> <u>would</u> <u>be</u> even <u>cooler</u> if the <u>offline</u> was free but still SPOTIFY <b>is</b> amazing! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Also</b> <u>something</u> <u>that</u> <u>would</u> <u>be</u> <u>cool</u> <u>to</u> <u>ad</u> is if you could have access <u>to</u> all your offline music without making one huge playlist full of it. <br>"
+"- I <b>wish</b> <u>it</u> all <u>could</u> <u>be</u> <u>free?</u> <br>"
+"- This isn't exactly spotify's problem but <u>a</u> <u>litle</u> <u>regulation</u> <u>to</u> <u>stop</u> those <u>retarded</u> <u>auto</u> <u>zone</u> <u>ads</u> <b>would</b> <b>be</b> <b>great.</b> <br>"
+"- <u>The</u> <u>only</u> <u>thing</u> <u>i</u> <u>would</u> <u>say</u> <u>to</u> <u>improve</u> <u>is</u> <b>for</b> the <b>mobile</b> <b>aplication</b> <b>you</b> <b>have</b> no <b>hope</b> <b>of</b> <b>being</b> <b>able</b> <u>to</u> <b>see</b> the <b>information</b> <b>of</b> each <b>track</b> easily, or <b>sort</b> <b>them</b> as <b>you</b> can <b>a</b> desktop. <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"no","name":"<h1>no</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Great app just wish the volume wasn't so low literally can't hear any music if there's <u>no</u> <u>headphones</u> <u>pluged</u> <u>into</u> my <u>phone.</u> <br>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>multiple</u> <u>selector</u> <u>for</u> <u>playlist</u> <u>making.</u> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"this","name":"<h1>this</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Can't select <u>a</u> song and play.need to shuffle songs.can't forward songs.charts are very short and can't <b>see</b> all <u>chart.please</u> <u>corect</u> <u>this</u> <br>"
+"- Can't select <u>a</u> song and play.need to shuffle songs.can't forward songs.charts are very short and can't <b>see</b> all <u>chart.please</u> <u>corect</u> <u>this</u> <br>"
+"- I would <b>give</b> <u>this</u> <u>5</u> <u>stars</u> but now it only plays a couple of my playlist songs, then plays continuous sugested songs. <br>"
+"</p>","volumn":8,"sentiment":-.38,"value":1.70},
{"keyword":"could","name":"<h1>could</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I would love it if <u>premium</u> was <b>cheaper</b> <br>"
+"&#43; <u>It</u> is very good music app <u>I</u> just <b>wish</b> <u>I</u> <u>could</u> <u>afford</u> the <u>premium</u> <u>edition.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>listen</u> <u>offline</u> <u>without</u> <u>WiFi</u> <u>for</u> <u>like</u> <u>car</u> <u>journeys</u> <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>use</u> <u>2</u> <u>devices</u> <u>at</u> <u>one</u> <u>time</u> <u>for</u> my <u>spouse.</u> <br>"
+"- I <b>wish</b> <u>we</u> <u>could</u> <u>skip</u> <br>"
+"- I just <b>wish</b> <u>you</u> <u>could</u> <u>use</u> <u>it</u> <u>offline</u> because <u>of</u> my <u>data</u> <u>usage</u> . <br>"
+"</p>","volumn":6,"sentiment":-.33,"value":1.46},
{"keyword":"better","name":"<h1>better</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But if <b>I</b> subscribe the premium it would be more <u>better.</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"change","name":"<h1>change</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>hope</b> <u>to</u> <u>see</u> a <u>change</u> <u>soon!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>to</u> <u>see</u> <u>subscription</u> <u>setings.</u> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]