var data_map_totalreviews=1189
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_imdb = [
{"keyword":"access","name":"<h1>access</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Forum</u> <u>access</u> <b>would</b> <b>be</b> <b>amazing</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"suport","name":"<h1>suport</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's 5/19/15 and still <b>no</b> Chromecast <u>suport!</u> <br>"
+"- Low res trailers and <b>no</b> Chromecast <u>suport.</u> <br>"
+"- It's 6/26/15 and another update and still <b>no</b> Chromecast <u>suport!</u> <br>"
+"- <u>I</u> just <b>wish</b> <u>it</u> <u>had</u> <u>suport</u> <u>to</u> <u>Brazilian</u> <u>showtimes</u> and <u>Episodes</u> <u>reminders</u> <u>for</u> <u>TV</u> <u>shows.</u> <br>"
+"- Also <u>chromecast</u> and <u>Android</u> <u>TV</u> <u>suport</u> <b>would</b> <b>be</b> <b>amazing</b> for trailers. <br>"
+"- Also chromecast and <u>Android</u> <u>TV</u> <u>suport</u> <b>would</b> <b>be</b> <b>amazing</b> for trailers. <br>"
+"- It's 6/26/15 and another update and still <b>no</b> Chromecast <u>suport!</u> <br>"
+"- It <b>needs</b> <u>6.0</u> <u>Suport.</u> <br>"
+"</p>","volumn":8,"sentiment":-1.00,"value":1.08},
{"keyword":"reviews","name":"<h1>reviews</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- And <u>they</u> still haven't <b>given</b> you <u>the</u> <u>ability</u> <u>to</u> <u>leave</u> <u>reviews?</u> <br>"
+"- Have always used this loads, <u>chromecast</u> <u>ability</u> <b>would</b> <b>be</b> <b>great,</b> also there's too many ads. <br>"
+"- Android mobile version still <b>needs</b> <u>spoiler</u> <u>warnings</u> <u>for</u> <u>reviews!</u> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"open-in-ap","name":"<h1>open-in-ap</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>We</b> cannot <u>open</u> <u>New</u> <u>Photos.and</u> also <u>in</u> <u>ap</u> <br>"
+"- <b>We</b> cannot <u>open</u> <u>New</u> <u>Photos.and</u> also <u>in</u> <u>ap</u> <br>"
+"- <b>We</b> cannot <u>open</u> <u>New</u> <u>Photos.and</u> also <u>in</u> <u>ap</u> <br>"
+"- But for me, <u>I</u> <b>see</b> <u>one</u> <u>thing</u> <u>is</u> <u>missing</u> the <u>ap,</u> <u>which</u> <u>is</u> <u>he</u> <u>ability</u> <u>to</u> <u>edit</u> my <u>lists.</u> <br>"
+"- <b>We</b> cannot <u>open</u> <u>New</u> <u>Photos.and</u> also <u>in</u> <u>ap</u> <br>"
+"- <u>I</u> just <u>wish</u> <u>I</u> <u>could</u> <u>see</u> the <u>other</u> <u>lists</u> I've created and <u>I</u> <u>wish</u> <u>I</u> <u>could</u> <u>participate</u> <u>in</u> <u>polls,</u> but those are very minor things. <br>"
+"- <b>Why</b> is <u>the</u> <u>User</u> <u>Reviews</u> <u>section</u> so <u>limited</u> <u>in</u> <u>the</u> <u>IMDB</u> <u>Android</u> <u>ap?</u> <br>"
+"- There's <b>also</b> <u>no</u> <u>way</u> <u>to</u> <u>arange</u> <u>them</u> <u>in</u> <u>a</u> <u>different</u> <u>order</u> (e.g., chronological) <u>like</u> <u>on</u> the <u>IMDB</u> <u>website.</u> <br>"
+"</p>","volumn":9,"sentiment":-.89,"value":1.31},
{"keyword":"could","name":"<h1>could</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I so <b>wish</b> that <u>imdb</u> <u>could</u> <u>be</u> <u>my</u> <u>go</u> <u>to</u> <u>place</u> <u>for</u> <u>trailers,</u> but it's not hapening when it's so low resolution. <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>uninstall.</u> <br>"
+"- I <b>want</b> <u>to</u> <u>be</u> <u>able</u> <u>to</u> <u>cast</u> easily <u>om</u> a tv from this app like I can with YouTube or Netflix . <br>"
+"- This app <b>needs</b> <u>a</u> <u>1080p</u> <u>option</u> <u>for</u> <u>trailers,</u> because there's <u>a</u> lot of phones that have been released recently that have <u>a</u> resolution of <u>1080p</u> or higher. <br>"
+"- I <b>wish</b> <u>it</u> <u>could</u> <u>be</u> <u>removed</u> <u>from</u> my <u>phone</u> <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>uninstall</u> all <u>the</u> <u>updates</u> so <u>I</u> can finally watch an entire trailer without interuptions. <br>"
+"- Why would you <b>need</b> <u>something</u> <u>that</u> <u>just</u> <u>trailer</u> <u>vids</u> <u>wen</u> <u>there</u> <u>youtube</u> <u>go</u> <u>on</u> <br>"
+"- <b>You</b> <b>could</b> just <u>go</u> <u>to</u> <u>the</u> <u>site</u> but I prefer <u>to</u> use this aplication. <br>"
+"</p>","volumn":9,"sentiment":-.89,"value":1.31},
{"keyword":"watchlists","name":"<h1>watchlists</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Can't <b>see</b> my <u>custom</u> <u>watchlists</u> on the app. <br>"
+"- Still <b>no</b> <u>user</u> List, Rating details, My profile options. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"things","name":"<h1>things</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>2</u> <u>things</u> <b>need</b> <b>to</b> <b>be</b> <b>aded</b> <b>for</b> this <b>app</b> <b>to</b> <b>be</b> <b>great.</b> <br>"
+"- I love this app but I feel like <b>there</b> <b>should</b> <b>be</b> a wish list type <u>thing</u> like the movies you plan to watch. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"lists","name":"<h1>lists</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It needs ability to ad to user <b>made</b> <u>lists!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>No</b> <u>lists</u> in the app nor on the mobile site. <br>"
+"- But I <b>want</b> <u>watchED</u> <u>list.</u> <br>"
+"- <b>Where</b> are <u>tv</u> <u>listings?</u> <br>"
+"- The bigest flaw with this app is that <b>you</b> can't <u>access</u> <u>your</u> <u>lists.</u> <br>"
+"- I love the content, but I <b>wish</b> <u>you</u> <u>could</u> <u>scroll</u> <u>through</u> <u>horizontal</u> <u>lists</u> (cast, filmography, etc.). <br>"
+"- <u>I</u> also <b>wish</b> <u>it</u> <u>would</u> <u>list</u> <u>other</u> <u>works</u> <u>from</u> the <u>director/writer/creator</u> <u>on</u> the <u>same</u> <u>page</u> <u>as</u> the <u>show</u> I'm <u>looking</u> <u>at.</u> <br>"
+"- I really <b>want</b> <u>to</u> <u>be</u> <u>able</u> <u>to</u> <u>see</u> the <u>personal</u> <u>lists</u> I have created on the mobile ap, I can <u>see</u> them on the PC but not on my Android app. <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>view</u> my <u>list</u> <u>on</u> <u>mobile</u> <br>"
+"</p>","volumn":14,"sentiment":-.64,"value":2.00},
{"keyword":"overhaul","name":"<h1>overhaul</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The app is great, but <b>it</b> would be better if <b>it</b> <b>had</b> <u>an</u> <u>option</u> <u>for</u> <u>search</u> by genre (or maybe I can't find <b>it)</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>needs</b> <u>an</u> <u>overhaul.</u> <br>"
+"- IMDB for Android <b>needs</b> <u>a</u> <u>fresh</u> <u>overhaul.</u> <br>"
+"- IMDB for Android <b>needs</b> <u>a</u> <u>fresh</u> <u>overhaul.</u> <br>"
+"- It <b>needs</b> <u>an</u> <u>overhaul.</u> <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- And <b>no</b> <u>option</u> to purchase a version without ads. <br>"
+"- I honestly think it <b>needs</b> <u>newer</u> <u>option</u> maybe like <u>newer</u> TV shows it's okay I just excepted better there are a few more issues but other than that I guess its okay And the episodes of switched at birth need to be free and need to ad season 4 episode 11 <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"ads","name":"<h1>ads</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; But please <b>remove</b> <u>the</u> <u>ads!</u> <br>"
+"&#43; You guys make millions with <u>the</u> website so please <b>remove</b> <u>the</u> <u>ads</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>way</u> <u>to</u> <u>access</u> your <u>lists</u> or <u>to</u> <u>ad</u> <u>movies</u> or <u>shows</u> <u>to</u> <u>them</u> at all. <br>"
+"- <u>I</u> don't <b>want</b> <u>to</u> <u>make</u> <u>a</u> <u>list</u> for watched movies <u>cause</u> <u>it</u> doesn't <u>tell</u> <u>you</u> <u>its</u> <u>on</u> the <u>list,</u> all <u>it</u> <u>says</u> <u>is</u> <u>ad</u> <u>to</u> <u>watchlist</u> but <u>a</u> <u>watchED</u> <u>list</u> <u>needs</u> <u>to</u> <u>be</u> <u>created!</u> <br>"
+"- <b>needs</b> Material Design and <u>to</u> <u>be</u> <u>able</u> <u>to</u> <u>ad</u> <u>to</u> <u>lists</u> other than just the watch list. <br>"
+"- But as an Amazon prime member it would be nice if <b>there</b> <b>were</b> <u>some</u> <u>aded</u> <u>perks.</u> <br>"
+"- Have always used this loads, chromecast ability would be great, also there's too <u>many</u> <u>ads.</u> <br>"
+"- Ads <u>ads</u> and <b>more</b> <u>ads.</u> <br>"
+"- (-1 Star) Would like to <b>see</b> an <u>ad</u> <u>free</u> <u>pay</u> <u>version</u> <b>too.</b> <br>"
+"- I really <b>wish</b> <u>i</u> <u>could</u> <u>ad</u> <u>movies</u> <u>to</u> my <u>own</u> <u>list,</u> other than the watchlist! <br>"
+"</p>","volumn":19,"sentiment":-.42,"value":2.52},
{"keyword":"movies","name":"<h1>movies</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It also <b>include</b> bios, trivia about the <u>movies</u> and <u>full</u> <u>cast</u> and <u>crew</u> <u>listings</u> <u>for</u> <u>most</u> <u>of</u> the <u>movies.</u> <br>"
+"&#43; It would be excellent if <b>there</b> <b>was</b> <u>an</u> <u>option</u> <u>to</u> <u>mark</u> the <u>watched</u> <u>movies,</u> like <u>watched</u> list <br>"
+"&#43; You <b>see</b> <u>it</u> <u>has</u> <u>amazing</u> <u>movies</u> but I am not sure how to play them please tell me how <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>You</b> can't <u>watch</u> <u>movies.</u> <br>"
+"- IMDB <b>NEEDS</b> <u>A</u> <u>WATCHED</u> <u>LIST</u> <u>TO</u> <u>TRACK</u> THE MOVIES YOU <u>WATCH.</u> <br>"
+"- I <b>wish</b> <u>we</u> <u>can</u> <u>customize</u> our <u>own</u> <u>lists</u> <u>of</u> <u>movies.</u> <br>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>war</u> and <u>horor</u> <u>movies.</u> <br>"
+"- <u>A</u> <u>list</u> <u>to</u> <u>track</u> the <u>movies</u> you've <u>watched</u> <b>would</b> <b>be</b> <b>awesome.</b> <br>"
+"- The only complain i have is <u>the</u> ads which disturbs at times when <b>you</b> <b>are</b> <u>reading</u> <u>the</u> <u>movie</u> <u>synopsis.</u> <br>"
+"- Just wish <u>I</u> could <b>see</b> how <u>many</u> <u>movies</u> <u>I</u> <u>rated</u> otherwise its <u>awesome</u> <br>"
+"- A)Please can you <b>give</b> us <u>a</u> <u>watchlist</u> <u>which</u> <u>separates</u> <u>both</u> <u>TV</u> <u>shows</u> and <u>movies</u> <u>in</u> <u>2</u> <u>different</u> <u>category.</u> <br>"
+"</p>","volumn":15,"sentiment":-.40,"value":2.31},
{"keyword":"release","name":"<h1>release</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This app needs <u>a</u> <u>1080p</u> option for trailers, because there's <u>a</u> <u>lot</u> <u>of</u> <u>phones</u> <u>that</u> <u>have</u> <u>been</u> <u>released</u> recently <u>that</u> <u>have</u> <u>a</u> <u>resolution</u> <u>of</u> <u>1080p</u> or <u>higher.</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"improvement","name":"<h1>improvement</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This app <b>needs</b> <u>serious</u> <u>improvement,</u> constantly <u>redrawing</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>There</b> <b>is</b> <b>still</b> <u>a</u> <u>room</u> <u>for</u> <u>improvements.</u> <br>"
+"- Photo gallery also <b>needs</b> <u>improvements.</u> <br>"
+"- It freezes sometimes while opening titles, the web version <b>needs</b> <u>a</u> <u>litle</u> <u>improvement.</u> <br>"
+"- Layout <b>needs</b> <u>improvement</u> but all the info you need is there. <br>"
+"</p>","volumn":9,"sentiment":-.33,"value":1.86},
{"keyword":"materi-design","name":"<h1>materi-design</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Still <b>needs</b> <u>proper</u> <u>material</u> <u>redesign.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>need</b> <u>Lollipop</u> <u>Material</u> <u>Design.</u> <br>"
+"- <b>Where</b> is <u>Material</u> <u>Design?</u> <br>"
+"- This app <b>needs</b> <u>Material</u> <u>Design</u> <u>it</u> <u>would</u> <u>be</u> very <u>visually</u> <u>apealing</u> <u>to</u> the <u>eye</u> <u>for</u> <u>IMDb</u> <u>to</u> <u>have</u> <u>a</u> <u>Material</u> <u>Design</u> <u>element</u> <u>to</u> <u>it.</u> <br>"
+"- <b>Why</b> is <u>this</u> <u>not</u> <u>material</u> <u>design?</u> <br>"
+"- <b>Please</b> <u>update</u> <u>it</u> <u>to</u> <u>Material</u> <u>Design</u> <u>Already.</u> <br>"
+"- It <b>needs</b> <u>better</u> (material) <u>interface.</u> <br>"
+"- It <b>need</b> <u>Lollipop</u> <u>Material</u> <u>Design.</u> <br>"
+"</p>","volumn":32,"sentiment":-.19,"value":3.28},
{"keyword":"features","name":"<h1>features</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Good BUT <b>Needs</b> <u>some</u> <u>features.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It doesn't <b>have</b> <u>features</u> like writing review, parents guide, synopsis, . <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]