var data_map_totalreviews=1099
var data_map_fromdate=20140221
var data_map_todate=20151102
var data_map_medscape = [
{"keyword":"content","name":"<h1>content</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very good and <b>authentic</b> <u>content.</u> <br>"
+"&#43; <b>Great</b> <u>content</u> <br>"
+"&#43; <b>Simple</b> but very easily accessible <u>quality</u> <u>of</u> <u>content.</u> <br>"
+"&#43; The <u>content</u> is <b>great.</b> <br>"
+"&#43; <b>Wonderful</b> <u>content.</u> <br>"
+"&#43; <u>Content</u> <b>great,</b> delivery improvement needed. <br>"
+"&#43; <b>Great</b> <u>contents.</u> <br>"
+"&#43; <b>Great</b> <u>content,</u> but not good an <b>experience</b> to use on tablet. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Nice</u> <u>content</u> but it's <b>very</b> <b>boring</b> <b>to</b> <b>expand</b> <b>each</b> and <b>every</b> <b>tab</b> singly. <br>"
+"</p>","volumn":11,"sentiment":.82,"value":3.22},
{"keyword":"information","name":"<h1>information</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Medscape is an <b>excellent</b> <u>source</u> <u>of</u> health <u>information.</u> <br>"
+"&#43; All <u>information</u> is <b>accurate,</b> <b>well</b> organized and easily accessible. <br>"
+"&#43; <u>Information</u> <b>is</b> <b>well</b> <b>organised</b> <br>"
+"&#43; <u>Information</u> <b>is</b> <b>brilliantly</b> <b>organized</b> <br>"
+"&#43; <u>Great</u> <u>work</u> <b>done</b> <b>to</b> <b>compile</b> <b>lots</b> <b>of</b> <b>procedure</b> and <b>diseases.</b> <br>"
+"&#43; <b>A</b> <u>great</u> <u>way</u> <b>to</b> <b>get</b> <b>detailed</b> <b>disease</b> <b>information</b> <b>on</b> the <b>go.</b> <br>"
+"&#43; It is very <b>educative</b> and up to date <u>medical</u> <u>information.</u> <br>"
+"&#43; <b>Extensive</b> and <u>authentic</u> <u>information</u> on the very relevant subjects <u>of</u> <u>Medicine.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>useful</b> <u>source</u> <u>of</u> <u>information.</u> <br>"
+"- It is very <b>concise</b> <u>processed</u> <u>information</u> on your fingertips ! <br>"
+"- So <b>much</b> <u>information.</u> <br>"
+"- <u>Great</u> <u>reference</u> but it <b>frequently</b> <b>fails</b> <b>to</b> <b>open</b> or becomes sudenly unresponsive. <br>"
+"- Although I can move the app to the SDCard, I'm unable to alter the location of the update data/ <b>clinical</b> <u>reference</u> <u>information</u> to another location including the SD card. <br>"
+"</p>","volumn":24,"sentiment":.54,"value":3.72},
{"keyword":"topictures","name":"<h1>topictures</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Updated and <u>topictures</u> <b>are</b> <b>organized</b> <b>as</b> both reference <b>style</b> and <b>a</b> <b>quick</b> <b>glance</b> <b>style.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"access","name":"<h1>access</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is <b>easy</b> <u>access</u> to a lot, <u>of</u> medical info, calculators, and <u>news.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"stuff","name":"<h1>stuff</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Quick ref and <b>good</b> <u>stuff</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"database","name":"<h1>database</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It has a <b>huge</b> <u>database</u> and covers most of the conditions and drugs extensively. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>like</b> the <u>interface,</u> it is simple and intelligible. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"info","name":"<h1>info</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>reliable</b> <u>info</u> <br>"
+"&#43; The <u>info</u> <b>is</b> <b>presented</b> <b>well.</b> <br>"
+"&#43; <b>Good</b> <u>info</u> on most subjects including drugs. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>concise</b> <u>info</u> on all aspects of Medicine <br>"
+"- So <b>much</b> <u>info</u> in a single app that's free and to the point unlike the exorbitantly expensive up to date. <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"user","name":"<h1>user</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Highly <b>informative</b> and very <b>much</b> <u>user</u> <u>friendly.</u> <br>"
+"&#43; It is <b>friendly</b> <u>user.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Most of this app <u>users</u> are <b>android</b> <u>users,</u> yet I don't see much updates and improvements in the functionality of this app compared to what I see on iOS! <br>"
+"</p>","volumn":6,"sentiment":.17,"value":1.96},
{"keyword":"resource","name":"<h1>resource</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>resource.</u> <br>"
+"&#43; <b>Great</b> <u>resource.</u> <br>"
+"&#43; It's a <b>great</b> <u>resource</u> otherwise. <br>"
+"&#43; <u>Resourceful</u> but never <u>always</u> <u>accessible.always</u> <b>needs</b> very <b>good</b> <b>internet</b> to work even after downloading resources for offline use. <br>"
+"&#43; <b>Great</b> <u>resource</u> to have <br>"
+"&#43; <b>Great</b> <u>resource.</u> <br>"
+"&#43; <b>Wonderful</b> <u>Resource</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Excellent</u> <u>resource</u> but using the app on android is <b>such</b> an <b>inferior</b> <b>experience</b> <b>to</b> the <b>ios</b> <b>version</b> it's <b>embarassing.</b> <br>"
+"- <b>Excellent</b> <u>resource</u> for physicians, especially for. <br>"
+"- It's a <b>handy</b> <b>quick</b> <u>reference</u> <u>resource</u> useful for busy practioners <br>"
+"- <b>Excellent</b> <u>resource</u> for healthcare workers at any level. <br>"
+"</p>","volumn":13,"sentiment":.15,"value":2.72},
{"keyword":"reference","name":"<h1>reference</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; My best <b>quick</b> <u>reference.</u> <br>"
+"&#43; <u>Disease</u> <u>references</u> and others are <b>okay</b> though. <br>"
+"&#43; An <b>excellent</b> <u>reference</u> for the medical professional or informed consumer. <br>"
+"&#43; An <b>excellent</b> <u>reference</u> for the medical professional or informed consumer. <br>"
+"&#43; A <b>good</b> <u>source</u> <u>of</u> <u>reference</u> that come in handy in the time <u>of</u> need. <br>"
+"&#43; A <b>perfect</b> <u>pocket</u> <u>reference!</u> <br>"
+"&#43; <b>Great</b> <u>reference.</u> <br>"
+"&#43; <b>Great</b> <u>reference</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Excellent</b> <u>reference</u> for doctors <br>"
+"- <b>Great</b> <u>reference</u> with poor looks <br>"
+"- <b>Reliable</b> <u>reference</u> for med students! <br>"
+"- <b>Good</b> easy <u>reference</u> <u>aplication</u> but missing certain drugs like Nalidixic acid and/or Nitrofurantoin. <br>"
+"- <b>Excellent</b> <u>reference.</u> <br>"
+"- It is very <b>much</b> <b>useful</b> and <u>handy</u> <u>reference</u> when you need it quickly as possible <br>"
+"- <b>Excellent</b> <u>medical</u> <u>reference</u> guide. <br>"
+"- It is very <b>useful</b> <u>clinical</u> <u>reference.</u> <br>"
+"</p>","volumn":29,"sentiment":.14,"value":3.51},
{"keyword":"Font","name":"<h1>Font</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- 2) <u>Font</u> is <b>too</b> <b>small.</b> <br>"
+"- The <u>font</u> <u>size</u> is <b>too</b> <b>small</b> <b>in</b> my <b>tablet.</b> <br>"
+"- <u>Font</u> <u>size</u> <b>small</b> and <b>difficult</b> to read. <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"articles","name":"<h1>articles</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's an incomplete version of the site, so it's hit or miss whether the <u>article</u> <u>I</u> <u>want</u> is <b>available.</b> <br>"
+"- The <u>articles</u> <u>here</u> are <b>too</b> <b>long</b> and unhelpful in case of rapid review there is no summary <b>for</b> each topicture (except <b>for</b> few) <br>"
+"- Also, <u>navigating</u> <u>articles</u> <b>is</b> a <b>huge</b> time <b>waste</b> having to go back and forth between short sections. <br>"
+"- <u>I</u> also <b>enjoy</b> <u>reading</u> the <u>news</u> <u>but</u> <u>it</u> <u>hardly</u> every <u>displays</u> <u>new</u> <u>articles.</u> <br>"
+"- It is very <b>useful</b> <u>articles.</u> <br>"
+"</p>","volumn":5,"sentiment":-1.00,"value":.61},
{"keyword":"function","name":"<h1>function</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>search</u> <u>function</u> in this app <b>is</b> too <b>specific</b> and only searches <b>titles.</b> <br>"
+"- The <u>search</u> <u>functions</u> are kind <b>of</b> <b>strange</b> as <b>of</b> the writing <b>of</b> this review. <br>"
+"- Search <u>function</u> doesn't <b>work</b> <b>80%</b> <b>of</b> the <b>time</b> <br>"
+"- The <u>search</u> <u>function</u> is <b>very</b> <b>poor.</b> <br>"
+"- People sometimes compare this unfavorably to UpToDate or DynaMed, but the purpose and <u>function</u> of Medscape is a <b>entirely</b> <b>different</b> <b>than</b> <b>those.</b> <br>"
+"</p>","volumn":7,"sentiment":-.71,"value":1.23},
{"keyword":"search","name":"<h1>search</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Brand name is not prefered, only Generic names is <b>quick</b> <u>search</u> <u>benefits</u> <br>"
+"- The search function in this app is too <b>specific</b> and only <u>searches</u> <u>titles.</u> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"free","name":"<h1>free</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Dr. Very <b>worthful</b> <b>med</b> <u>free</u> <u>ap</u> <br>"
+"- <b>Good</b> <u>free</u> <u>ap,</u> but not very useful <b>interface,</b> a bit bugy. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's an <b>incomplete</b> <u>version</u> <u>of</u> the <u>site,</u> so it's hit or miss whether the article I want is available. <br>"
+"- <b>Still</b> <b>lacks</b> <u>tablet</u> <u>version</u> <u>though.</u> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"drug","name":"<h1>drug</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <b>new</b> <u>feature_visual</u> <u>drug</u> identification <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- While on call , to get a 1 minute review of disease /drug from medscape is <b>very</b> <b>easy/accurate.</b> <br>"
+"- I've unistalled and re installed again the app ,but <b>still</b> the <u>drug</u> <u>refference</u> doesn't <b>work.</b> <br>"
+"- Also it does not have <u>drug</u> <u>class</u> <b>look</b> up <b>function</b> <b>anymore,</b> which is a useful <b>function</b> when I need to <b>look</b> up an alternative <u>drug,</u> or <b>inspiration.</b> <br>"
+"</p>","volumn":5,"sentiment":-.40,"value":1.21},
{"keyword":"offline","name":"<h1>offline</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>specially</u> <u>offline</u> <u>database</u> <u>download</u> <u>option</u> is <b>very</b> <b>good.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>7/22/14</u> Still very <u>useful</u> and really <b>apreciate</b> this <b>program.</b> <br>"
+"- <u>offline</u> <u>database</u> Not <b>working.</b> <br>"
+"- Even when the app is moved <b>to</b> sd card, the <u>offline</u> <u>files</u> <b>continue</b> <b>to</b> <b>use</b> <b>main</b> <b>storage</b> <br>"
+"</p>","volumn":8,"sentiment":-.25,"value":1.83},
{"keyword":"tool","name":"<h1>tool</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It has become an indispensable tool, especially interaction checker and <b>other</b> <u>tools!</u> <br>"
+"&#43; It has become an <b>indispensable</b> <u>tool,</u> especially interaction checker and other tools! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- a very handy <b>useful</b> <u>tool.</u> <br>"
+"- <b>Indispensable</b> <u>tool</u> for any health care professional. <br>"
+"- It is very <b>useful</b> <u>tool</u> anywhere everywhere. <br>"
+"</p>","volumn":5,"sentiment":-.20,"value":1.41},
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Nice</b> <u>aplication</u> and good arangement <br>"
+"&#43; <b>Nice</b> <u>aplication</u> with illustrations. <br>"
+"&#43; The <u>aplication</u> is very user friendly and <b>gives</b> <b>sufficient</b> <b>for</b> <b>curent</b> <b>clinical</b> <b>practice.</b> <br>"
+"&#43; The <u>aplication</u> is <b>very</b> user <b>friendly</b> and gives sufficient for curent clinical practice. <br>"
+"&#43; <b>Wonderful</b> <u>aplication</u> . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>usefull</b> <u>aplication</u> <br>"
+"- It is very <b>useful</b> <u>aplication</u> in offline status too. <br>"
+"- It is very <b>useful</b> <u>aplication.</u> <br>"
+"- It is very <b>helpful</b> <u>aplication</u> for a doctor in clinic? so one can check drug safety in pregnancy etc.It is very <b>helpful</b> <u>aplication</u> for a doctor in a clinic so one can check drug safety in pregnancy etc <br>"
+"- Hi all its really <b>usefull</b> <u>aplication</u> for medical information <br>"
+"- It has <b>awesome</b> <u>aplication,</u> drugs calculator, charts, references are available in your hand at a time. <br>"
+"</p>","volumn":11,"sentiment":-.09,"value":2.31},
{"keyword":"guide","name":"<h1>guide</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; an excellent reference and <b>quick</b> <u>guide</u> . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- A <b>handy</b> <u>guide</u> for Med students like me, although search engine is a litle bit specific word-wise. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
{"keyword":"interactions","name":"<h1>interactions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Medicines</u> <u>interactions</u> are good, but <b>install</b> <b>more</b> <b>medicines.</b> <br>"
+"&#43; <u>Medicines</u> <u>interactions</u> are <b>good,</b> but install more medicines. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's <b>drug-drug</b> <u>interaction</u> <u>finder</u> is really awesome. <br>"
+"- <u>Interactions</u> <b>are</b> <b>not</b> <b>updated</b> as Found in medscape <b>through</b> <b>web</b> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"refrence","name":"<h1>refrence</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; A <b>good</b> and <u>quick</u> <u>source</u> <u>of</u> <u>refrence</u> <br>"
+"&#43; Totally <b>love</b> <u>it</u> <u>tho</u> some <u>drugs</u> <u>are</u> <u>not</u> <u>included</u> <u>in</u> the <u>refrences</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Excellent</b> <u>quick</u> <u>refrence</u> tool! <br>"
+"- Pill identifier and <u>refrences</u> <b>blew</b> my <b>mind</b> - I wish I had it 15 years earlier <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"Medscape","name":"<h1>Medscape</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Medscape</u> <b>is</b> an <b>excellent</b> <b>source</b> of health information. <br>"
+"&#43; <u>Medscape</u> is <b>informative.</b> <br>"
+"&#43; <u>Medscape</u> is very <b>informative</b> <b>specifically</b> <b>about</b> <b>latest</b> <b>guidelines</b> <br>"
+"&#43; <u>Medscape</u> <b>is</b> ever best handy <b>medical</b> <b>reference,</b> Please keep it. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>MEDSCAPE</u> <b>is</b> your app <b>mediphiles.</b> <br>"
+"- <u>Medscape</u> is <b>very</b> <b>useful</b> <b>for</b> quick reference and <b>reading</b> when i don't have my books with me. <br>"
+"- I <b>like</b> <u>medscape</u> since it was Called e medicine but the app font size is too Small. <br>"
+"- <u>Dear</u> <u>medscape</u> <u>developers</u> <u>thanks</u> for the wonderful app <b>but</b> <b>please</b> provide sd card suport for offline refrence data its of 400mb. <br>"
+"- People sometimes compare this unfavorably to UpToDate or DynaMed, but the <u>purpose</u> and function <u>of</u> <u>Medscape</u> is a <b>entirely</b> <b>different</b> <b>than</b> <b>those.</b> <br>"
+"</p>","volumn":9,"sentiment":.00,"value":2.20},
{"keyword":"UI","name":"<h1>UI</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Older</u> <u>UI</u> was <b>neat</b> and clean. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>UI</u> <b>is</b> <b>not</b> <b>responding</b> <b>properly</b> especially scrolling through articles. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
]