var data_map_swiftkey = [
{"keyword":"flow","name":"<h1>flow</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;The <u>flow</u> <u>beta</u> is <b>fantastic!</b> <br>"
+"&#43;The <u>Flow</u> <u>line</u> <b>looks</b> very <b>nice,</b> <b>almost</b> <b>looks</b> out of place <br>"
+"&#43;The set up, feel, look and <u>overall</u> <u>flow</u> is <b>incredible.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.33,"value":2.43},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;My <u>version</u> <b>has</b> a <b>few</b> <b>misspelled</b> <b>words</b> that <b>it</b> automatically <b>displays</b> <b>in</b> the <b>predictions</b> <b>window.</b> <br>"
+"&#43;With the <b>latest</b> update the voice recognition is the <b>latest</b> <u>version!</u> <br>"
+"&#43;The <u>latest</u> <u>version</u> is <b>awesome.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"mark","name":"<h1>mark</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;My favorite feature is that the <b>period,</b> comma, exclamation <u>mark,</u> and <u>question</u> <u>mark</u> <u>all</u> <b>share</b> the <b>same</b> <b>key</b> (with the <b>period</b> <b>key</b> <b>as</b> primary). <br>"
+"&#43;My favorite feature is that the <b>period,</b> comma, <u>exclamation</u> <u>mark,</u> and question <u>mark</u> all <b>share</b> the <b>same</b> <b>key</b> (with the <b>period</b> <b>key</b> <b>as</b> primary). <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-And hate that the <u>question</u> <u>mark</u> and period <b>are</b> the <b>same</b> <b>key.</b> <br>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"layout","name":"<h1>layout</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;<b>Excellent</b> <u>layout.</u> <br>"
+"&#43;It has a <b>great</b> <u>layout</u> and it has the most intelligent word prediction It can handle up to 3 languages at the same time. <br>"
+"&#43;I <b>love</b> the <u>neon</u> <u>blue</u> <u>layout!</u> <br>"
+"&#43;<b>love</b> the <u>layout.</u> <br>"
+"&#43;The <u>layout</u> is <b>still</b> <b>brilliant</b> though and it's <b>still</b> a far better option than anything else but it's not as good as it was and improvements are needed. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":5,"sentiment":1.00,"value":2.61},
{"keyword":"colors","name":"<h1>colors</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;Plus the endless personalization, themes, and <u>colors</u> <b>put</b> <b>it</b> over the top <b>in</b> my <b>mind.</b> <br>"
+"&#43;It also has <b>cool</b> <u>colors</u> you can choose from. <br>"
+"&#43;Plus the endless personalization, themes, and <u>colors</u> <b>put</b> <b>it</b> over the top <b>in</b> my <b>mind.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"personalization","name":"<h1>personalization</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;The <u>personalization,</u> <b>along</b> <b>with</b> the <b>word</b> predicting is <b>far</b> <b>better</b> than I thought it would be! <br>"
+"&#43;Plus the <u>endless</u> <u>personalization,</u> themes, and colors <b>put</b> <b>it</b> over the top <b>in</b> my <b>mind.</b> <br>"
+"&#43;Plus the <u>endless</u> <u>personalization,</u> themes, and colors <b>put</b> <b>it</b> over the top <b>in</b> my <b>mind.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;The <u>interface</u> and special key layout are the <b>best</b> I've seen. <br>"
+"&#43;very easy to use, and <b>real</b> <u>nice</u> <u>layout.</u> <br>"
+"&#43;Word prediction is accurate and <b>simple</b> and <u>nice</u> <u>interface!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"text","name":"<h1>text</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;I <b>love</b> <u>to</u> <u>text</u> quickly and sometimes I make small errors in keystrokes. <br>"
+"&#43;The <b>predictive</b> <u>text</u> always me to <u>text</u> much faster and more clearly than ever. <br>"
+"&#43;And so far, the <u>voice-to-text</u> <u>feature</u> <b>has</b> <b>been</b> <b>just</b> <b>as</b> <b>great.</b> <br>"
+"&#43;I think the predictive <u>text</u> <u>stuff</u> is <b>just</b> <b>fantastic.</b> <br>"
+"&#43;Especially <b>love</b> that you can keep <u>texting</u> and it separates the words for you. <br>"
+"&#43;Absolutely <b>excellent</b> <u>text</u> prediction and layout. <br>"
+"&#43;<u>Auto</u> <u>text</u> including voice <u>text</u> <b>is</b> <b>working</b> nearly <b>perfect.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-Terrible upgrade, the best thing about this app was the <b>predictive</b> <u>text</u> and now you just have punctuation options after each tines you press space. <br>"
+"</p>","volumn":9,"sentiment":.67,"value":2.86},
{"keyword":"feature","name":"<h1>feature</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;I actually <b>love</b> <u>that</u> <u>feature.</u> <br>"
+"&#43;The <u>features</u> are <b>amazing.</b> <br>"
+"&#43;Removing saved words from the library is an extremely <b>helpful</b> <u>feature</u> that is probably over looked as well. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":5,"sentiment":.60,"value":2.21},
{"keyword":"customization","name":"<h1>customization</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;<u>Customizations</u> are <b>perfect.</b> <br>"
+"&#43;and I <b>like</b> the <u>customization.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-But the <u>lack</u> <u>of</u> <u>customization</u> is really this <b>app</b> <b>back.</b> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"accuracy","name":"<h1>accuracy</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;This app <b>is</b> great works fast and <u>accuracy</u> <b>is</b> great <b>worth</b> <b>buying.</b> <br>"
+"&#43;<u>I</u> <b>love</b> the <u>accuracy</u> <u>of</u> <u>I</u> <b>love</b> the way you can change the themes. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-The <u>accuracy</u> and predictions are <b>awesome;</b> they even come up in other languages. <br>"
+"-Predictions and <u>accuracy</u> are <b>second</b> <b>to</b> <b>none.</b> <br>"
+"</p>","volumn":4,"sentiment":.25,"value":1.64},
{"keyword":"predictions","name":"<h1>predictions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;<u>Predictions</u> are <b>amazing,</b> sometimes <b>writing</b> <b>whole</b> <b>sentence</b> <b>takes</b> just <b>a</b> <b>few</b> <b>clicks!</b> <br>"
+"&#43;A very good keyboard and the <u>prediction</u> is <b>excellent.</b> <br>"
+"&#43;It has a <b>smooth</b> and <u>great</u> <u>interface</u> as well. <br>"
+"&#43;It is incredibly accurate with fixing any mistyped and the <u>predictions</u> are <b>amazing.</b> <br>"
+"&#43;The <u>predictive</u> <u>capabilities</u> are <b>fantastic,</b> <b>layout,</b> <b>options</b> and <b>features</b> <b>brilliant.</b> <br>"
+"&#43;The <u>prediction</u> <u>abilities</u> are pretty <b>amazing</b> as <b>well,</b> it gives you a great insight into words that you use so often! <br>"
+"&#43;<u>Prediction</u> <b>works</b> very <b>well,</b> the smart space is very interesting and useful. <br>"
+"&#43;This keyboard's <u>predictive</u> <u>ability</u> is <b>amazing.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-<u>Predictions</u> are scary <b>accurate</b> and I just I just got a notification telling me that I've saved myself over 10,000 key strokes. <br>"
+"-I <b>hate</b> the fact that you can't turn off <u>predictions,</u> and I also <b>hate</b> that you can't turn off the automatic space after punctuation. <br>"
+"-<b>Otherwise</b> the <u>predictive</u> <u>text</u> <b>is</b> better than the <b>built</b> in <b>one</b> <b>on</b> my <b>Gs2.</b> <br>"
+"-<u>Prediction</u> <b>better</b> than stock keyboard, but <u>slower</u> at loading keys when need to use it. <br>"
+"-<u>Predictions</u> are <b>horrible,</b> though enjoyed the added spaces for commas and periods. <br>"
+"-<u>Predictive</u> <u>text</u> doesn't <b>work</b> <b>in</b> <b>browser.</b> <br>"
+"-I don't find the keyboard layout all that unique (and the number pad takes some getting used to), but the <u>predictive</u> <u>text</u> is <b>second</b> <b>to</b> <b>none.</b> <br>"
+"-The <u>predictive</u> <u>texting</u> for rapid texters is <b>close</b> <b>to</b> <b>perfection.</b> <br>"
+"</p>","volumn":190,"sentiment":.23,"value":5.47},
{"keyword":"themes","name":"<h1>themes</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;I would love to more <u>themes,</u> the <u>current</u> <u>themes</u> are <b>great</b> but I love customising my phone. <br>"
+"&#43;I <b>would</b> <b>love</b> <u>to</u> <u>more</u> <u>themes,</u> the current <u>themes</u> are great but I <b>love</b> customising my phone. <br>"
+"&#43;The <u>theme</u> is <b>awesome</b> <br>"
+"&#43;Plus the endless personalization, <u>themes,</u> and colors <b>put</b> <b>it</b> over the top <b>in</b> my <b>mind.</b> <br>"
+"&#43;Also, <u>themes</u> are <b>really</b> <b>cool,</b> the typos correction is just amazing. <br>"
+"&#43;The <u>themes</u> are <b>great</b> and the usability is <b>great.</b> <br>"
+"&#43;<b>Love</b> the customisation options and <u>themes!</u> <br>"
+"&#43;Plus the endless personalization, <u>themes,</u> and colors <b>put</b> <b>it</b> over the top <b>in</b> my <b>mind.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-My main issue with the app is the <b>ugly</b> <u>themes.</u> <br>"
+"-The <u>themes</u> <b>just</b> seem a bit limited. <br>"
+"-The word prediction is spot on, the <u>different</u> <u>themes</u> <b>look</b> <b>great,</b> but the inability to use swype is annoying, as is the inability to use ALT+backspace to delete an entire line of text. <br>"
+"-But the <u>themes</u> are <b>lame.</b> <br>"
+"-almost all <u>themes</u> <b>are</b> <b>with</b> <b>closely</b> <b>spaced</b> <b>keys.</b> <br>"
+"-Otherwise <b>in</b> <b>regards</b> <b>to</b> <b>function</b> <b>it</b> <b>is</b> <b>same</b> <b>as</b> <b>android</b> <b>sans</b> <u>themes</u> and colours. <br>"
+"-The <u>current</u> <u>set</u> <u>of</u> <u>themes</u> <b>lack</b> the <b>look</b> and feel. <br>"
+"-The only 'complaint' is that the <u>themes</u> are <b>quite</b> <b>awful.</b> <br>"
+"</p>","volumn":21,"sentiment":.19,"value":3.23},
{"keyword":"typing","name":"<h1>typing</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;The <u>rapid</u> <u>typing</u> is <b>impressive.</b> <br>"
+"&#43;I really enjoyed being able to drag and <u>type</u> but this smart keyboard is <b>unbelievable.</b> <br>"
+"&#43;<u>I</u> <u>type</u> in English and Spanish and the app <b>makes</b> <b>accurate</b> <b>predictions</b> <b>on</b> both <b>languages</b> <b>simultaneously.</b> <br>"
+"&#43;<u>Typing</u> is <b>fast</b> and the auto correction is amazing. <br>"
+"&#43;My <u>typing</u> <b>has</b> <b>become</b> <b>a</b> <b>lot</b> <b>quicker</b> and <b>I</b> love the fact that there are so many options to customise this. <br>"
+"&#43;<b>Smooth</b> <u>typing</u> and soooo smart! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-<u>Landscape</u> <u>typing</u> is far <b>more</b> <b>effective</b> <b>on</b> <b>Thumb</b> <b>Keyboard</b> when using the split keyboard over the mashed together keyboard found in Swiftkey and default android keyboards. <br>"
+"-And <u>typing</u> is <b>tediously</b> <b>slow</b> <b>having</b> <b>to</b> <b>correct</b> <b>nearly</b> every <b>word!</b> <br>"
+"-but in addition to that, the interactions are smooth, the <u>typing</u> is much <b>more</b> <b>responsive</b> <b>than</b> <b>stock</b> <br>"
+"-Much more <u>accurate</u> <u>typing</u> and the space bar is a <b>lot</b> <b>bigger</b> so I am not accidentally pressing unneeded buttons when I go to push the space. <br>"
+"-I <b>like</b> the <u>speed</u> <u>it</u> <u>allows</u> <u>me</u> <u>to</u> <u>type</u> but the predictions that automatically insert when I don't notice change my word completely. <br>"
+"-<u>Typing</u> was really <b>fast,</b> predictions were good, way better than the stock keyboard(s). <br>"
+"</p>","volumn":12,"sentiment":.14,"value":2.78},
{"keyword":"symbols","name":"<h1>symbols</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;Its freakishly accurate in predicting my next words and <u>symbols</u> and numbers <b>work</b> <b>like</b> <b>a</b> <b>charm.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-The keyboard layout cannot be modified <b>to</b> suit the user, thus the <u>odd</u> <u>placement</u> <u>of</u> <u>numbers,</u> <u>symbols,</u> and <u>other</u> <u>buttons</u> <b>become</b> <b>frustrating</b> <b>to</b> <b>try</b> <b>to</b> <b>adjust</b> <b>to.</b> <br>"
+"-So many <b>useless</b> <u>symbols</u> but no backtick (`)?! <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"key","name":"<h1>key</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;The interface and <u>special</u> <u>key</u> <u>layout</u> are the <b>best</b> I've seen. <br>"
+"&#43;I <b>like</b> the <u>multi-character</u> <u>key</u> <u>concept,</u> <u>for</u> <u>popular</u> <u>punctuation</u> <u>marks,</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-Smilies as default on the enter <u>key</u> <b>are</b> a deal <b>breaker</b> for me. <br>"
+"-<u>Key</u> <u>press</u> <u>sounds</u> are <b>obnoxious.</b> <br>"
+"-<u>Punctuation</u> <u>key</u> is <b>annoying.</b> <br>"
+"-<u>Arrow</u> <u>keys</u> are <b>unnecessarily</b> <b>large.</b> <br>"
+"-The <u>layout</u> <u>of</u> the <u>number</u> <u>keys</u> is <b>really</b> <b>dumb.</b> <br>"
+"-Please put this letters on a long press for croatian input, <u>keys</u> are <b>too</b> <b>small.</b> <br>"
+"-The layout of the smiley faces and the main <u>punctuation</u> <u>keys</u> just <b>make</b> so <b>much</b> <b>more</b> <b>sense!</b> <br>"
+"-And hate that the question mark and period are the <b>same</b> <u>key.</u> <br>"
+"</p>","volumn":16,"sentiment":-.62,"value":2.15},
{"keyword":"punctuation","name":"<h1>punctuation</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-The space that <u>inserts</u> <u>after</u> a <u>punctuation</u> is <b>fairly</b> <b>annoying.</b> <br>"
+"-Also, the <u>shortcuts</u> <u>for</u> <u>entering</u> <u>punctuation</u> and <u>emoticons</u> <b>are</b> <b>big</b> <b>time-savers.</b> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"button","name":"<h1>button</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;Very good keyboard, i really don't <b>like</b> how there is a <u>default</u> <u>smiley</u> <u>face</u> <u>button</u> instead of an enter key. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-The <u>dot</u> <u>com</u> <u>button</u> is <b>annoying.</b> <br>"
+"-<b>Just</b> <b>needs</b> <u>next/prev</u> <u>buttons</u> <u>on</u> <u>Web</u> <u>form</u> filling like the Samsung keyboard has. <br>"
+"-Why is the <u>smiley</u> <u>face</u> <u>button</u> <b>more</b> <b>important</b> than the enter <u>button?</u> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"dictionary","name":"<h1>dictionary</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-<u>Dictionary</u> <b>remembers</b> <b>singlish</b> as <b>well</b> <b>like</b> <b>leh,</b> <b>lah,</b> <b>lor.</b> <br>"
+"-And the <u>Swedish</u> <u>dictionary</u> <u>is</u> <u>broken,</u> <b>splits</b> <b>composite</b> <b>words</b> <b>up.</b> <br>"
+"</p>","volumn":5,"sentiment":-.40,"value":1.21},
{"keyword":"suggestions","name":"<h1>suggestions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;<u>Suggestions</u> are <b>awesome</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-The <u>suggestions</u> are <b>very</b> <b>helpful</b> <b>whilst</b> <b>typing</b> <b>messages.</b> <br>"
+"-the <u>suggestions</u> for my spelling errors are almost <b>always</b> <b>correct</b> as <b>to</b> what I meant <b>to</b> type too! <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"input","name":"<h1>input</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;Just like the other reviews say, the <u>input</u> is <b>smooth</b> and the predictions are very accurate. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-<u>Google</u> <u>voice</u> <u>input</u> <b>enters</b> <b>al</b> <b>words</b> <b>correctly</b> <b>but</b> <b>hardly</b> <b>inserts</b> any <b>fullstop</b> or <b>comma.</b> <br>"
+"-<u>Google</u> <u>voice</u> <u>input</u> <b>enters</b> <b>al</b> <b>words</b> <b>correctly</b> <b>but</b> <b>hardly</b> <b>inserts</b> any <b>fullstop</b> or <b>comma.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"space","name":"<h1>space</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;<u>Smart</u> <u>space</u> <b>works</b> really <b>well</b> and the <b>auto</b> <b>correct</b> <b>works</b> really <b>well.</b> <br>"
+"&#43;Prediction works <b>very</b> well, the <u>smart</u> <u>space</u> is <b>very</b> <b>interesting</b> and useful. <br>"
+"&#43;This is important, because if <b>I</b> want it to autocorrect the prior word, <b>I</b> need to press <u>space</u> to accept the suggestion, and the <u>space</u> <b>also</b> <b>adds</b> an <b>actual</b> <u>space.</u> <br>"
+"&#43;And the new <u>space</u> <u>feature</u> is <b>great!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-I <b>hate</b> the fact that you can't turn off predictions, and I also <b>hate</b> that you can't turn off the <u>automatic</u> <u>space</u> after punctuation. <br>"
+"-Needs swype, sometimes doubles on letters, <b>hate</b> the fact that a <u>space</u> automatically equals a period but overall very impressive and worth my $ <br>"
+"-I like swype but the <u>space</u> <u>bar</u> is <b>too</b> <b>small.</b> <br>"
+"-Needs swype, sometimes doubles on letters, <b>hate</b> the fact that a <u>space</u> automatically equals a period but overall very impressive and worth my $ <br>"
+"-<b>Empty</b> <u>space</u> on bottom key rows not in use (reduced accuracy). <br>"
+"-Also <b>hate</b> how hard <u>it</u> <u>is</u> <u>to</u> <u>multiple</u> <u>space</u> <u>after</u> <u>punctuation,</u> and <u>other</u> <u>functions</u> <u>after</u> <u>punctuation</u> as well. <br>"
+"-Much more accurate typing and the <u>space</u> <u>bar</u> is a <b>lot</b> <b>bigger</b> so I am not accidentally pressing unneeded buttons when I go to push the <u>space.</u> <br>"
+"-<u>com</u> <u>button</u> <u>which</u> <u>makes</u> the <u>space</u> <u>bar</u> too <u>small</u> and <u>ends</u> <u>up</u> <u>with</u> <b>messed</b> <u>up</u> <b>searches</b> <b>in</b> <b>chrome.</b> <br>"
+"</p>","volumn":12,"sentiment":-.25,"value":2.23},
{"keyword":"phone","name":"<h1>phone</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;I would <b>love</b> to more themes, the current themes are great but I <b>love</b> <u>customising</u> my <u>phone.</u> <br>"
+"&#43;and i <b>love</b> the <u>phone</u> <u>style</u> <u>number</u> <u>pad.</u> <br>"
+"&#43;I <b>love</b> <u>being</u> <u>able</u> <u>to</u> <u>customize</u> my <u>phone.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-When <b>I</b> use the phone's <b>built</b> <b>in</b> <b>resizing</b> <b>ability,</b> the keyboard is too large to see all the keys. <br>"
+"-<b>Uses</b> too <b>much</b> <b>ram</b> and slows down <u>phone</u> <u>drastically</u> <br>"
+"-If <u>phone</u> <u>keypad</u> <b>was</b> <b>included</b> <b>as</b> <b>a</b> <b>layout,</b> it would combine speed with advanced prediction. <br>"
+"-<u>but</u> the <u>screen</u> <u>on</u> my <u>phone</u> <b>is</b> <b>way</b> to sensitive <br>"
+"-In less than <u>a</u> month, my <u>brand</u> <u>new</u> <u>touchscreen-only</u> <u>phone</u> (Samsung <u>galaxy</u> <u>s3)</u> <b>was</b> <b>beginning</b> <b>to</b> <b>turn</b> <b>me</b> <b>into</b> <u>a</u> <b>non-texter</b> <b>with</b> all the <b>constant</b> <b>typos</b> and <b>incorrect</b> <b>word</b> <b>predictions</b> <b>from</b> the <b>built</b> <b>in</b> <b>keyboard.</b> <br>"
+"</p>","volumn":9,"sentiment":-.22,"value":1.98},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;My typing has become a lot quicker and I <b>love</b> the fact that there are so <u>many</u> <u>options</u> to customise this. <br>"
+"&#43;My <u>favorite</u> <u>option</u> <b>is</b> <b>changing</b> the <b>amount</b> <b>of</b> <b>time</b> <b>for</b> <b>long</b> <b>press</b> since I use the secondary keys a lot. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-No <u>option</u> <b>to</b> <b>toggle</b> <b>auto-space</b> <b>after</b> <b>punctuation</b> and selecting predicted/corrected word. <br>"
+"-No <u>option</u> to toggle auto-space after punctuation and <b>selecting</b> <b>predicted/corrected</b> <b>word.</b> <br>"
+"-An <u>option</u> <u>that</u> <u>disables</u> <u>automatic</u> <u>spacing</u> <u>after</u> <u>punctuation</u> is <b>necessary.</b> <br>"
+"</p>","volumn":6,"sentiment":-.17,"value":1.63},
{"keyword":"auto-correct","name":"<h1>auto-correct</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;The <u>auto</u> <u>correct</u> is <b>flawless!</b> <br>"
+"&#43;Very <b>good</b> <u>corrections</u> and suggestions and very clever, well worth getting <br>"
+"&#43;The <u>auto</u> <u>correct</u> is <b>amazing</b> and so accurate! <br>"
+"&#43;It's a fairly good keyboard but the <u>autocorrection</u> isn't <b>very</b> <b>strong.</b> <br>"
+"&#43;Really good keyboard and excellent <b>predictive</b> and <u>autocorrect</u> <u>engine</u> with this app! <br>"
+"&#43;Its prediction engine is amazing, you can type very quickly and sloppily and the <u>autocorrect</u> <b>will</b> <b>work</b> well <b>almost</b> all the time. <br>"
+"&#43;The <u>auto</u> correct and predictive <u>auto</u> <u>fill</u> <b>are</b> the <b>best</b> <b>thing</b> to ever happen to a phone. <br>"
+"&#43;The <u>auto</u> <u>correct</u> and predictive <u>auto</u> fill <b>are</b> the <b>best</b> <b>thing</b> to ever happen to a phone. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-One little thing annoys me tho: the <u>auto</u> <u>correct</u> is <b>really</b> <b>stubborn!</b> <br>"
+"-<u>Auto</u> <u>correct</u> can <b>be</b> a <b>nightmare.</b> <br>"
+"-<u>Auto</u> <u>correct</u> is ALMOST <b>as</b> <b>good</b> <b>as</b> the <b>iphone,</b> much more responsive then the default, haptic vibrations are spot on. <br>"
+"-The <u>auto</u> <u>space</u> <u>after</u> a <u>full-stop</u> is <b>ridiculous.</b> <br>"
+"-<b>Sometimes</b> the <u>auto</u> correct <u>feature</u> doesn't <b>appear</b> and <b>I</b> have to exit the text message and re open it for it to <b>appear.</b> <br>"
+"-<u>Backspace</u> <u>on</u> <u>auto</u> <u>correct</u> doesn't <b>undo</b> <b>correction.</b> <br>"
+"-<u>Backspace</u> <u>on</u> <u>auto</u> <u>correct</u> doesn't <b>undo</b> <b>correction.</b> <br>"
+"-The <u>correction</u> is <b>just</b> <b>awesome!</b> <br>"
+"</p>","volumn":60,"sentiment":-.10,"value":3.99},
{"keyword":"words","name":"<h1>words</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;Great, <b>love</b> how it corrects it but leaves the <u>words</u> <u>you</u> <u>want.</u> <br>"
+"&#43;My <u>local</u> <u>words</u> <b>also</b> <b>appear</b> <b>as</b> <b>predictions.</b> <br>"
+"&#43;I <b>like</b> the fact that it can predict my <u>words</u> but I rarely start a sentence with I. Also some of the <u>words</u> it will allow me to type and won't correct are some of the most mispelled <u>words,</u> although there are only a handful and the keyboard will learn which <u>words</u> you use and don't. Overall very good keyboard. <br>"
+"&#43;The predicted <u>words</u> <u>database</u> can be <b>pretty</b> <b>impressive</b> <b>at</b> <b>times.</b> <br>"
+"&#43;The predictions are great and it correct everything even if what you typed is way off the <b>actual</b> <u>word.</u> <br>"
+"&#43;The predicted <u>words</u> <u>database</u> can be <b>pretty</b> <b>impressive</b> <b>at</b> <b>times.</b> <br>"
+"&#43;Its freakishly <u>accurate</u> in predicting my next <u>words</u> and symbols and numbers <b>work</b> <b>like</b> <b>a</b> <b>charm.</b> <br>"
+"&#43;I <b>love</b> that it can learn <u>words</u> that I use automatically from sms and Gmail. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-Typing email addresses and <u>other</u> <u>long</u> but <u>irregular</u> <u>words</u> can <b>be</b> <u>a</u> <b>pain.</b> <br>"
+"-Predicting he <u>next</u> <u>word</u> <b>is</b> <b>just</b> <b>not</b> <b>needed.</b> <br>"
+"-<b>Bad</b> <u>word</u> correction. <br>"
+"-Bug2 - <u>auto-input</u> <u>of</u> <u>words</u> <b>seems</b> a <b>bit</b> off. <br>"
+"-<u>Words</u> <u>I</u> commonly <u>use</u> <b>are</b> <b>constantly</b> <b>changed</b> <b>to</b> completely <b>different</b> <b>words</b> and it can slow me down <b>a</b> lot. <br>"
+"-Seriously, swear <u>words</u> <b>are</b> <b>not</b> <b>allowed</b> <b>to</b> <b>be</b> <b>added</b> <b>to</b> <b>dictionary.</b> <br>"
+"-Being a person with a good vocabulary, I still find myself back spacing every <b>few</b> <u>words</u> because this keyboard is far too casual in its suggestions and predictions. <br>"
+"-<u>Not</u> <b>a</b> <u>big</u> <u>deal</u> but <b>I</b> <b>press</b> <b>the</b> <b>space</b> <b>bar</b> every <b>time</b> <b>and</b> <b>it</b> <b>auto</b> <b>add</b> <b>the</b> 'and' <b>word.</b> <br>"
+"</p>","volumn":32,"sentiment":-.06,"value":3.40},
{"keyword":"time-saver","name":"<h1>time-saver</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;The predictions are a <b>huge</b> <u>time-saver.</u> <br>"
+"&#43;<b>Saves</b> <b>me</b> so <b>much</b> <u>time</u> and effort <b>with</b> its super smart spell correction and <b>prediction</b> <b>text.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-Love this keyboard, but every <u>time</u> <u>I</u> <u>turn</u> the handset off and on it <b>loses</b> <b>default</b> <b>settings.</b> <br>"
+"-Also, the shortcuts for entering punctuation and emoticons are <b>big</b> <u>time-savers.</u> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"languages","name":"<h1>languages</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43;Its <u>language</u> <u>detection</u> is amazing, and <b>never</b> <b>gets</b> <b>in</b> your <b>way.</b> <br>"
+"&#43;Its <u>language</u> <u>detection</u> is <b>amazing,</b> and never gets in your way. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"-I also <b>like</b> the <u>combination</u> <u>of</u> <u>multiple</u> <u>languages</u> that use the same alphabet. <br>"
+"-Very useful, <b>handy,</b> <b>can</b> <b>add</b> <u>several</u> <u>languages</u> at the same time. <br>"
+"</p>","volumn":5,"sentiment":.00,"value":1.61},
]