var data_map_totalreviews=442
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_espn = [
{"keyword":"like","name":"<h1>like</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>needs</b> more <u>sports</u> <u>like</u> <u>volleyball</u> and the <u>FIVB</u> and <u>ATV.</u> <br>"
+"- <b>There</b> <b>should</b> <b>be</b> a <u>way</u> <u>to</u> <u>supress</u> <u>sports</u> we don't want <u>to</u> see. <br>"
+"- Love da layout and design but I still think <b>you</b> should be able to choose as many teams as you'd <u>like.</u> <br>"
+"- <u>I</u> <b>wish</b> <u>you</u> <u>could</u> <u>remove</u> <u>sports</u> that <u>I</u> don't <u>want</u> <u>to</u> <u>see</u> there. <br>"
+"- <b>Why</b> is <u>it</u> that <u>we</u> can't even <u>see</u> how <u>many</u> <u>3</u> <u>pointers</u> <u>a</u> <u>player</u> <u>made</u> <u>among</u> <u>other</u> <u>missing</u> <u>stats,</u> <u>like</u> <u>blocks.</u> <br>"
+"- It would be great to disable what <u>sports</u> you don't <b>want</b> to see notifications about. <br>"
+"</p>","volumn":6,"sentiment":-1.00,"value":.79},
{"keyword":"score","name":"<h1>score</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I would rate it 5 stars if <b>there</b> <b>was</b> <u>an</u> <u>option</u> <u>to</u> <u>turn</u> <u>off</u> <u>scores</u> <u>for</u> the <u>WNBA</u> <br>"
+"- i <b>just</b> <b>want</b> my <u>score</u> <u>feed</u> to be one sport only. <br>"
+"- It <b>needs</b> <u>updated,</u> the <u>NFL</u> when <u>you</u> <u>click</u> <u>to</u> <u>view</u> the <u>full</u> <u>score</u> it just has the first digit of the number. <br>"
+"- It seems that <b>there</b> <b>is</b> <u>no</u> <u>option</u> <u>to</u> <u>turn</u> <u>off</u> <u>them.</u> <br>"
+"- <b>So</b> if I want easier to read text I can't <b>see</b> the <u>proper</u> <u>score</u> in this app. <br>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>customize</u> the <u>scores</u> <u>tab.</u> <br>"
+"</p>","volumn":6,"sentiment":-1.00,"value":.79},
{"keyword":"go","name":"<h1>go</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It used to be one of my favorite alert Every since it newer version my friends had to silence our phones or <b>we</b> couldn't <u>go</u> back to sleep, Improvement expectation. <br>"
+"- <b>You</b> can't <u>go</u> back and forth <u>between</u> stories, results and <u>stats.</u> <br>"
+"- I <b>wish</b> <u>it</u> <u>would</u> <u>go</u> <u>to</u> the <u>story</u> <u>on</u> my <u>notification</u> when I press <u>it.</u> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"notification","name":"<h1>notification</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- but I <b>see</b> a <u>lot</u> <u>of</u> <u>negative</u> <u>feedback</u> <u>about</u> <u>notification</u> <u>spamming</u> and that would be a problem. <br>"
+"- <u>A</u> <u>notification</u> <u>alert</u> <u>togle</u> <b>would</b> <b>be</b> <b>decent.</b> <br>"
+"- It would be great to disable what sports you don't want to <b>see</b> <u>notifications</u> <b>about.</b> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"tht-stori","name":"<h1>tht-stori</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Would love to see more college news feed and recruiting news, <u>tht</u> <b>would</b> <b>be</b> <b>great.keep</b> updating and implementing new ideas. <br>"
+"- Would love to see more college news feed and recruiting news, <u>tht</u> <b>would</b> <b>be</b> <b>great</b> and i think widgets could <b>be</b> <b>be</b> . <br>"
+"- Would love <b>to</b> see my favorite scores highlighted.tht would be an awesome feature,also when geting an alert about a <u>story,</u> it doesn't take <b>you</b> <b>to</b> <u>tht</u> <u>story,</u> <b>you</b> have <b>to</b> find, please fix. <br>"
+"- Would love <b>to</b> see my favorite scores highlighted.tht would be an awesome feature,also when geting an alert about a <u>story,</u> it doesn't take <b>you</b> <b>to</b> <u>tht</u> <u>story,</u> <b>you</b> have <b>to</b> stroll find it, please fix. <br>"
+"- Would love <b>to</b> see my favorite scores highlighted.tht would be an awesome feature,also when geting an alert about a <u>story,</u> it doesn't take <b>you</b> <b>to</b> <u>tht</u> <u>story,</u> <b>you</b> have <b>to</b> stroll find it, please fix. <br>"
+"</p>","volumn":5,"sentiment":-1.00,"value":.61},
{"keyword":"could-be-taken","name":"<h1>could-be-taken</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>be</u> <u>taken</u> straight to the article, or at least to it's location on the news stream. <br>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>be</u> <u>taken</u> straight to the article, or at least to it's location on the news stream. <br>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>be</u> <u>taken</u> straight to the article, or at least to it's location on the news stream. <br>"
+"- Would love to see my favorite scores highlighted.tht would be an awesome feature,also when geting an alert about a story, it doesn't take you to tht story, you have to <u>find,</u> <b>please</b> <u>fix.</u> <br>"
+"- Would love to see my favorite scores highlighted.tht would be an awesome feature,also when geting an alert about a story, it doesn't take you to tht story, you have to stroll <u>find</u> it, <b>please</b> <u>fix.</u> <br>"
+"- Would love to see my favorite scores highlighted.tht would be an awesome feature,also when geting an alert about a story, it doesn't take you to tht story, you have to stroll <u>find</u> it, <b>please</b> <u>fix.</u> <br>"
+"</p>","volumn":7,"sentiment":-.86,"value":1.09},
{"keyword":"teams","name":"<h1>teams</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Want</b> <u>to</u> <u>see</u> <u>which</u> <u>BPL</u> <u>teams</u> <u>are</u> <u>playing</u> day <u>after</u> <u>tomorow?</u> <br>"
+"- Also hoping for the option of <b>more</b> <u>favorite</u> <u>teams</u> <br>"
+"- Useless if I can't <b>see</b> the <u>teams</u> I care about on my home screen. <br>"
+"- And I don't <b>want</b> <u>to</u> <u>create</u> a <u>login</u> <u>just</u> <u>to</u> <u>set</u> <u>up</u> <u>notifications</u> <u>for</u> my <u>favorite</u> <u>teams.</u> <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"more","name":"<h1>more</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>needs</b> <u>more</u> <u>lebron</u> <u>info.</u> <br>"
+"- Now, unless <u>I</u> <b>want</b> <u>to</u> <u>remove</u> <u>everybody</u> and <u>ad</u> <u>them</u> just <u>so,</u> <u>I</u> can't quickly reorder anymore. <br>"
+"- however, I would to <b>see</b> <u>more</u> news feed and <u>more</u> <u>stories,</u> some <u>stories</u> I <b>see</b> on other aps are not <b>seen</b> on ESPN and they have <u>more</u> <u>stories</u> than ESPN, so please change.thanks <br>"
+"- however, I would to <b>see</b> <u>more</u> news feed and <u>more</u> <u>stories,</u> some <u>stories</u> I <b>see</b> on other aps are not <b>seen</b> on ESPN and they have <u>more</u> <u>stories</u> than ESPN, so please change and still having issues on some <u>stories,</u> when I click on a story from notifications bar the story doesn't apear, it takes me back to the ESPN homepage <br>"
+"</p>","volumn":8,"sentiment":-.50,"value":1.58},
{"keyword":"improvement","name":"<h1>improvement</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>needs</b> <u>some</u> <u>major</u> <u>improvement.</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"stats","name":"<h1>stats</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>needs</b> <u>individual</u> <u>stats.</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"ESPN","name":"<h1>ESPN</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]