var data_map_totalreviews=559
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_templerun2 = [
{"keyword":"characters","name":"<h1>characters</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Anice game everything in the game is <b>nice</b> and <b>also</b> <u>some</u> <u>of</u> the <u>characters</u> are <b>also</b> <b>nice</b> <br>"
+"&#43; I <b>like</b> the game very much.Very good display and <u>characters.</u> <br>"
+"&#43; This is nice app but the <u>characters</u> are <b>very</b> <b>costly.</b> <br>"
+"&#43; <b>Cool</b> <u>new</u> <u>characters</u> and costumes. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.25,"value":2.64},
{"keyword":"fun","name":"<h1>fun</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Nice</b> and really <u>fun</u> game with different challenges, thanks ! <br>"
+"&#43; It's so <b>much</b> <u>fun</u> I play it every day love it <br>"
+"&#43; thats where the <u>fun</u> <b>ends.</b> <br>"
+"&#43; <u>Fun</u> <b>awesome</b> and can be hard <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.25,"value":2.64},
{"keyword":"graphics","name":"<h1>graphics</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is a very nice game and the <u>graphics</u> are <b>wonderful.</b> <br>"
+"&#43; <b>Awesome</b> <u>graphics</u> and very adictive! <br>"
+"&#43; Nice game <b>cool</b> <u>graphics</u> <br>"
+"&#43; I <b>love</b> the <u>graphics</u> <br>"
+"&#43; <b>Good</b> <u>graphics</u> and nice power ups <br>"
+"&#43; THE <u>Graphics</u> are <b>good</b> and the background <br>"
+"&#43; <b>Good</b> <u>graphics</u> <br>"
+"&#43; <b>Cool</b> <u>graphics.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Nice</b> <u>graphics</u> but concept boring <br>"
+"</p>","volumn":13,"sentiment":1.00,"value":3.56},
{"keyword":"game","name":"<h1>game</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>good</b> and <u>nice</u> <u>game.</u> <br>"
+"&#43; It is <b>easy</b> and <u>enjoyable</u> <u>game</u> <br>"
+"&#43; It is very <b>thrilling</b> and <u>interesting</u> <u>game</u> <br>"
+"&#43; It's a very <b>interesting</b> <u>game</u> so <u>adictive</u> , I love it <br>"
+"&#43; It is very very <b>good</b> and <u>nice</u> <u>game.</u> <br>"
+"&#43; It's a very <b>interesting</b> and <u>exciting</u> <u>game.</u> <br>"
+"&#43; It's an <b>amazing</b> <u>game</u> and enjoy full 2 also it's new software is better than before <br>"
+"&#43; It is very <b>good</b> <u>game.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>adicting</b> <u>game,</u> be warned! <br>"
+"- The <u>game</u> is <b>nice</b> but I guess it needs major upgradations. <br>"
+"- It's fun to play but the <u>game</u> is a <b>bit</b> <b>slow.</b> <br>"
+"- The <u>game</u> <b>is</b> <b>not</b> <b>improved</b> <b>since</b> the <b>beginning.</b> <br>"
+"- <b>Good</b> <u>game</u> but WAY too many ads! <br>"
+"- The <u>game</u> is <b>very</b> <b>glitchy</b> and doesn't like to respond when I swipe. <br>"
+"- A <b>good</b> <u>game,</u> but not very stable. <br>"
+"- It is very <b>amazing</b> <u>game</u> but very hard to get many gems <br>"
+"</p>","volumn":122,"sentiment":.93,"value":5.73},
]