var data_map_totalreviews=1891
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_duolingo = [
{"keyword":"Arabic","name":"<h1>Arabic</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; My only critique <b>is</b> that <b>there</b> <b>is</b> no Chinese, Russian, or <u>Arabic</u> <u>lessons;</u> having these options would make it a truly amazing language learning app for the modern traveller. <br>"
+"&#43; My only critique <b>is</b> that <b>there</b> <b>is</b> <u>no</u> <u>Chinese,</u> <u>Russian,</u> or <u>Arabic</u> <u>lessons;</u> having these options would make it a truly amazing language learning app for the modern traveller. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The app is great, but I would like to <b>see</b> more languages for English speakers and <u>overall</u> <u>such</u> <u>as</u> <u>Arabic.</u> <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> chose dutch but then regreted <u>it</u> because <u>I</u> honestly don't <u>feel</u> <u>I</u> will need <u>it,</u> and <b>there</b> <b>is</b> <u>no</u> <u>option</u> <u>to</u> <u>remove</u> <u>it</u> so every time <u>I</u> switch languages <u>I</u> see dutch <b>there</b> and <u>feel</u> <u>bad</u> because it's lazy of me <u>not</u> <u>to</u> learn <u>it</u> and also impractical of my time <u>to</u> learn <u>it.</u> <br>"
+"- <b>Only</b> <b>thing</b> <b>that</b> <b>would</b> <b>make</b> <b>it</b> any better <b>would</b> be an ASL language <u>option.</u> <br>"
+"- Also it should <b>give</b> <u>options</u> for learning chinese and japanese from english. <br>"
+"</p>","volumn":4,"sentiment":-1.00,"value":.39},
{"keyword":"could","name":"<h1>could</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>it</u> <u>could</u> <u>access</u> the <u>beta</u> <u>content.</u> <br>"
+"- but I <b>wish</b> <u>it</u> <u>could</u> <u>be</u> more <u>interactive</u> <br>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>make</u> <u>it.gracias.</u> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"lesson","name":"<h1>lesson</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Cons: <b>There</b> <b>should</b> <b>be</b> some <u>sort</u> of explanation before you start a section , sometimes it asks questions that you haven't learned about without any <u>sort</u> of help provided . <br>"
+"- <u>I</u> would <b>only</b> <b>want</b> some <u>sort</u> <u>of</u> <u>reference</u> or <u>lesson</u> with verb conjugations aded. <br>"
+"- The only thing I can think of to make it better is if <b>you</b> <b>could</b> <u>download</u> <u>the</u> <u>lessons.</u> <br>"
+"</p>","volumn":4,"sentiment":-.75,"value":.64},
{"keyword":"had","name":"<h1>had</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> would have rated <u>it</u> <u>a</u> five <u>I</u> just <b>wish</b> <u>it</u> <u>had</u> <u>more</u> <u>games</u> <u>to</u> <u>play.</u> <br>"
+"- I just <b>wish</b> <u>it</u> <u>had</u> <u>Russian!</u> <br>"
+"- I <b>wish</b> <u>it</u> <u>had</u> <u>better</u> <u>offline</u> <u>suport</u> as I sometimes have no signal in places I work. <br>"
+"- But <u>I</u> <b>wish</b> <u>i</u> <u>had</u> the <u>option</u> <u>for</u> <u>speaking</u> and <u>listening</u> only instead of <u>writing.</u> <br>"
+"- I <b>wish</b> <u>it</u> <u>had</u> <u>Mandarin</u> which I will be learning next. <br>"
+"</p>","volumn":7,"sentiment":-.71,"value":1.23},
{"keyword":"Japanese","name":"<h1>Japanese</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I would love to <b>see</b> a Russian language course or <u>japanese.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- i had wanted to suport my <u>japanese</u> lessons with this ap, but <b>there</b> <b>is</b> <u>no</u> <u>japanese</u> <u>option.</u> <br>"
+"- But I <b>wish</b> <u>you</u> <u>could</u> <u>ad</u> a <u>Japanese</u> <u>course</u> <br>"
+"- <u>I</u> just <b>wish</b> <u>they</u> <u>would</u> <u>offer</u> <u>Chinese</u> or <u>Japanese</u> maybe! <br>"
+"- <b>Why</b> <b>is</b> <b>there</b> <u>no</u> <u>japanese</u> <u>language?</u> <br>"
+"- but <u>I</u> wished <b>it</b> <b>had</b> <u>some</u> <u>more</u> <u>ad</u> on's <u>like</u> <u>Japanese,</u> Korean,Hindi. <br>"
+"- <u>I</u> <b>wish</b> <u>we</u> <u>had</u> more <u>language</u> <u>options</u> <u>like</u> <u>Korean,</u> <u>Japanese</u> <u>etc</u> <u>etc</u> but <u>overall</u> <u>a</u> <u>great</u> <u>ap</u> <br>"
+"- I <b>wish</b> <u>it</u> <u>had</u> <u>Japanese</u> though. <br>"
+"- I like it but it doesn't <b>have</b> <u>a</u> <u>way</u> <u>to</u> <u>learn</u> <u>Japanese</u> you can only do it if you've learned it please fix it I've been learning <u>Japanese</u> for awhile and this would be <u>a</u> great <u>way</u> for me <u>to</u> <u>learn</u> it quickly. <br>"
+"</p>","volumn":15,"sentiment":-.53,"value":2.17},
{"keyword":"give","name":"<h1>give</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>wish</b> <u>i</u> <u>can</u> <u>give</u> <u>it</u> <u>two</u> <u>more</u> <u>stars!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I love this ap, however I <b>wish</b> that <u>you</u> were able to read the lesson notes in the app like <u>you</u> can online, and I <b>wish</b> that when <u>you</u> clicked the links on <u>translations</u> <u>it</u> <u>did</u> <u>not</u> <u>give</u> <u>you</u> the <u>entire</u> <u>translation.</u> <br>"
+"- For now, <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>give</u> <u>you</u> <u>zero</u> <u>stars.</u> <br>"
+"- Only negative is I <b>wish</b> <u>it</u> <u>would</u> <u>give</u> an <u>overview</u> <u>of</u> the <u>translations</u> you'll be learning in each section. <br>"
+"- <u>I</u> also <b>wish</b> <u>it</u> <u>did</u> more <u>verbal</u> <u>speaking</u> <u>to</u> <u>ensure</u> <u>I</u> <u>am</u> <u>saying</u> <u>things</u> corectly. <br>"
+"</p>","volumn":6,"sentiment":-.50,"value":1.29},
{"keyword":"offline","name":"<h1>offline</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> do <b>wish</b> <u>I</u> <u>could</u> <u>have</u> <u>at</u> <u>least</u> <u>a</u> <u>level</u> ahead <u>available</u> <u>offline.</u> <br>"
+"- Just <b>needs</b> more <u>offline</u> <u>content.</u> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"things","name":"<h1>things</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It works very well, however I <b>wish</b> <u>it</u> <u>would</u> <u>explain</u> <u>things</u> a litle more. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>One</u> <u>thing</u> <u>I</u> <u>think</u> <b>would</b> <b>be</b> <b>useful,</b> <b>would</b> <b>be</b> to ad some more in depth grammer explanations that can easily <b>be</b> refered back to without having to go through the whole module again. <br>"
+"- <b>There</b> <b>are</b> <u>a</u> <u>some</u> <u>things</u> <u>I</u> <u>would</u> <u>like</u> <u>to</u> <u>be</u> <u>able</u> <u>to</u> <u>do</u> <u>like</u> <u>ask</u> <u>it</u> <u>a</u> <u>question</u> or <u>make</u> <u>a</u> <u>note</u> <u>about</u> <u>an</u> <u>item</u> <u>to</u> cover again. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"languages","name":"<h1>languages</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; great for wanting to learn a new language but <b>it</b> would be much better if <b>it</b> <b>had</b> midle eastern or <u>south</u> <u>asian</u> <u>languages</u> or <u>east</u> <u>asia</u> <br>"
+"&#43; I <b>wish</b> <u>there</u> <u>was</u> more <u>speaking</u> the <u>language</u> but overall a <u>great</u> <u>ap</u> <br>"
+"&#43; Fun and easy, but <u>I</u> <b>wish</b> <u>it</u> <u>would</u> <u>tell</u> <u>you</u> the <u>language</u> <u>rules</u> <u>before</u> the <u>lesson.</u> <br>"
+"&#43; But please ad <u>to</u> <u>Russian</u> <u>too</u> because <u>I</u> <b>want</b> <u>to</u> <u>learn</u> <u>Russian</u> because <u>I</u> <u>love</u> <u>Russian</u> <br>"
+"&#43; <u>More</u> <u>languages</u> <b>would</b> <b>be</b> <b>fantastic,</b> but its so good right now. <br>"
+"&#43; <b>More</b> <u>languages</u> please! <br>"
+"&#43; I <b>wish</b> <u>it</u> <u>had</u> the <u>option</u> <u>to</u> <u>learn</u> <u>Hebrew</u> but it's still excellent! <br>"
+"&#43; but please ad <b>more</b> <u>languages</u> please. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>There</b> <b>could</b> <b>be</b> more <u>languages.</u> <br>"
+"- Cons: There should be some <u>sort</u> <u>of</u> explanation before <b>you</b> start a section , sometimes it asks questions that <b>you</b> haven't <u>learned</u> about <u>without</u> <u>any</u> <u>sort</u> <u>of</u> <u>help</u> provided . <br>"
+"- I just wished I could contribute for some <b>more</b> <u>language</u> there. <br>"
+"- I do <b>wish</b> that <u>there</u> <u>were</u> <u>more</u> <u>languages</u> though. <br>"
+"- It <b>needs</b> an update and <u>MORE</u> <u>languages!</u> <br>"
+"- This <b>is</b> app <b>is</b> very useful but <b>there</b> <b>is</b> <u>a</u> <u>minimum</u> <u>of</u> <u>languages</u> if they had more i would give them five stars (RUSSIAN ) <br>"
+"- It would be really great if <b>it</b> <b>had</b> <u>some</u> <u>more</u> <u>languages</u> <u>like</u> Russian,polish,Croatian,Korean,etc. <br>"
+"- Buy <u>I</u> wishes <b>there</b> <b>were</b> <u>more</u> <u>language</u> <u>courses</u> <u>which</u> <u>I</u> <u>was</u> <u>interested</u> <u>in.</u> <br>"
+"</p>","volumn":42,"sentiment":-.26,"value":3.48},
{"keyword":"more","name":"<h1>more</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Really good, <u>more</u> <u>bonus</u> <u>sections</u> <b>would</b> <b>be</b> <b>nice.</b> <br>"
+"&#43; This is a very good ap, but it would be <u>more</u> helpful if <b>there</b> <b>were</b> <u>more</u> <u>explanations,</u> rather than just <u>questions/examples.</u> <br>"
+"&#43; the game aspect (which makes it fun) <b>needs</b> <u>more</u> <u>love.</u> <br>"
+"&#43; Amazing, but <b>need</b> <u>more</u> <u>optimization.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Some of this is, no doubt, my ignorance, so I <b>wish</b> <u>there</u> <u>were</u> <u>more</u> <u>explanation.</u> <br>"
+"- It <b>needs</b> <u>more</u> <u>depth.</u> <br>"
+"- I like the courses and everything but it <b>needs</b> <u>a</u> <u>litle</u> <u>more</u> <u>practises.</u> <br>"
+"- And <b>you</b> <b>could</b> <u>get</u> <u>more</u> <u>stuff</u> to create <b>your</b> avatar with in the shop useing <b>your</b> lingots? <br>"
+"</p>","volumn":11,"sentiment":-.09,"value":2.31},
{"keyword":"Russian","name":"<h1>Russian</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This is an amazing ap, I <b>wish</b> <u>they</u> <u>would</u> <u>ad</u> <u>Russian</u> though <br>"
+"&#43; My only critique <b>is</b> that <b>there</b> <b>is</b> no Chinese, <u>Russian,</u> or Arabic lessons; having these options would make it a truly amazing language learning app for the modern traveller. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- For starters, it doesn't <b>have</b> <u>Russian</u> <u>for</u> <u>beginners</u> as I'd like to start with that instead of the other languages. <br>"
+"- <b>Also</b> <b>there</b> <b>is</b> <u>no</u> <u>RUSSIAN.</u> <br>"
+"</p>","volumn":7,"sentiment":.00,"value":1.95},
{"keyword":"they","name":"<h1>they</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I just <b>hope</b> <u>they</u> <u>can</u> <u>ad</u> more languages. <br>"
+"&#43; I <b>wish</b> they'd improve the Norwegian section but overall its <u>good</u> <br>"
+"&#43; <u>I</u> <b>wish</b> they'd <u>improve</u> the <u>Norwegian</u> <u>section</u> but overall its <u>good</u> <br>"
+"&#43; I can't wait to <b>see</b> how <u>they</u> <u>grow</u> <u>over</u> the <u>years-</u> it would be great to <b>see</b> Finnish offered. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Also I <b>wish</b> <u>they</u> <u>would</u> <u>break</u> <u>it</u> <u>down</u> a bit more. <br>"
+"- I <b>wish</b> <u>they</u> <u>could</u> <u>have</u> <u>included</u> <u>Polish.</u> <br>"
+"- I <b>wish</b> <u>they</u> <u>would</u> <u>ad</u> <u>Tagalog</u> as well! <br>"
+"- I do <b>wish</b> <u>that</u> <u>they</u> <u>would</u> <u>extinguish</u> the <u>pronoun</u> <u>that</u> <u>is</u> <u>implied</u> <u>in</u> <u>Portuguese.</u> <br>"
+"</p>","volumn":11,"sentiment":.00,"value":2.40},
]