var data_map_totalreviews=1006
var data_map_fromdate=20150802
var data_map_todate=20151102
var data_map_yahooweather = [
{"keyword":"graphics","name":"<h1>graphics</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Really <u>wonderful</u> <u>graphics,</u> visually gorgeous, just <b>a</b> pity you can't look forward <b>in</b> more detail, and <b>check</b> the <b>weather</b> <b>in</b> an <b>unsaved</b> <b>location</b> <b>quickly.</b> <br>"
+"&#43; Really <u>wonderful</u> <u>graphics,</u> visually gorgeous, just <b>a</b> pity you can't <b>look</b> <b>forward</b> <b>in</b> <b>more</b> <b>detail,</b> and check the weather <b>in</b> an unsaved location quickly. <br>"
+"&#43; Cool features and <b>excellent</b> <u>graphics</u> <br>"
+"&#43; I <b>love</b> the <u>graphics.</u> <br>"
+"&#43; <b>Good</b> <u>graphics.</u> <br>"
+"&#43; <b>Great</b> <u>graphics.</u> <br>"
+"&#43; <b>Nice</b> <u>graphics</u> giving a grid view of daily detail, daily summary and up to 10 days in advance if you are after long term forecast. <br>"
+"&#43; <b>Brilliant</b> <u>graphics!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":12,"sentiment":1.25,"value":3.73},
{"keyword":"info","name":"<h1>info</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very nice pictures and the <u>info</u> is <b>quite</b> <b>accurate</b> <br>"
+"&#43; It has very <b>accurate</b> <u>info</u> <br>"
+"&#43; <b>Accurate</b> <u>info</u> with beautiful photos <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.00,"value":2.39},
{"keyword":"service","name":"<h1>service</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>service</u> <br>"
+"&#43; <b>Excellent</b> <u>service</u> <br>"
+"&#43; <b>Excellent</b> <u>service</u> <br>"
+"&#43; <b>Great</b> <u>service.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.00,"value":2.39},
{"keyword":"details","name":"<h1>details</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>like</b> the app and I <b>like</b> the description and <u>detail</u> of the app is very well done for a visually impaired person it's very up to date and prety accurate great job keep it up ! <br>"
+"&#43; Nice pictures and I <b>like</b> <u>scrolling</u> <u>down</u> <u>to</u> <u>see</u> <u>more</u> <u>details.</u> <br>"
+"&#43; Nice pictures and I <b>like</b> <u>scrolling</u> <u>down</u> <u>to</u> <u>see</u> <u>more</u> <u>details.</u> <br>"
+"&#43; <u>Detail</u> <u>Info</u> is <b>backwards!</b> <br>"
+"&#43; <b>Picky</b> <u>details</u> and nice accuracy <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":6,"sentiment":1.00,"value":2.79},
{"keyword":"presentation","name":"<h1>presentation</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Nice</b> <u>presentation.</u> <br>"
+"&#43; <b>Good</b> <u>presentation</u> and clearly guide to plan daily life. <br>"
+"&#43; <b>Superb</b> <u>presentation</u> and widgets <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"features","name":"<h1>features</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Cool</b> <u>features</u> and excellent graphics <br>"
+"&#43; So <b>many</b> <u>features,</u> beautiful to look at. <br>"
+"&#43; <b>Best</b> <u>Features</u> ever, easy to use and great maping! <br>"
+"&#43; It is very <b>good,</b> <b>accurate</b> and <u>multiple</u> <u>features</u> <br>"
+"&#43; I <b>love</b> the <u>new</u> <u>features.</u> <br>"
+"&#43; The <u>amazing</u> <u>feature</u> <u>of</u> this <u>widget</u> <b>is</b> that it constantly <b>updates</b> the location and weather during travel. <br>"
+"&#43; <b>Nice</b> <u>features</u> <br>"
+"&#43; <b>Excellent</b> <u>features.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's not as accurate as the iPhone app but it has <b>more</b> and <u>better</u> <u>features</u> <br>"
+"- I <b>like</b> the <u>radar</u> <u>feature</u> so I can see where rain is coming from, the rain forecast is not always corect. <br>"
+"</p>","volumn":12,"sentiment":.92,"value":3.40},
{"keyword":"animations","name":"<h1>animations</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>useful</b> and <u>good</u> <u>animations</u> <br>"
+"&#43; <b>Beautiful</b> <u>animations</u> and fast updates. <br>"
+"&#43; The <u>animations,</u> the design, the corect informations and all of those <b>make</b> this <b>app</b> <b>awesome!</b> <br>"
+"&#43; I <b>love</b> the <u>animations</u> when there are thunderstorms. <br>"
+"&#43; <b>Love</b> <u>animated</u> <u>effects</u> <br>"
+"&#43; The <u>animation</u> <u>effects</u> <b>are</b> <b>simple</b> but prety <b>cool.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Good</u> <u>design</u> but it <b>can</b> <b>miss</b> the <b>weather</b> <b>sometimes.</b> <br>"
+"</p>","volumn":7,"sentiment":.86,"value":2.80},
{"keyword":"background","name":"<h1>background</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>backgrounds</u> also. <br>"
+"&#43; And <b>now</b> the <u>location-specific</u> <u>background</u> <b>includes</b> <b>active</b> <b>weather.</b> <br>"
+"&#43; I <b>love</b> the <u>background</u> <u>pics.</u> <br>"
+"&#43; The <u>light</u> <u>on</u> <u>dark</u> <u>background</u> is <b>very</b> <b>easy</b> <u>on</u> the <u>dark</u> <b>to</b> <b>early</b> <b>morning</b> <b>eyes.</b> <br>"
+"&#43; I <b>like</b> the large app and <u>great</u> <u>background</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":6,"sentiment":.83,"value":2.63},
{"keyword":"pictures","name":"<h1>pictures</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Weather Bug works fine for me, The <u>pictures</u> are <b>beautiful.</b> <br>"
+"&#43; Well at first I had 2nd thought on downloading this app because all the bad reviews, but till now I haven't seen anything wrong with it,I like it,it has <b>nice</b> <u>pictures</u> and is prety accurate, so for now I give 5 starts I hope stays like that. <br>"
+"&#43; I <b>love</b> the <u>pictures</u> and enjoy the very accurate outside temperatures and 10 day predictions. <br>"
+"&#43; It is very nice <u>pictures</u> and the info is <b>quite</b> <b>accurate</b> <br>"
+"&#43; <b>Great</b> <u>pictures.</u> <br>"
+"&#43; <u>Area</u> <u>pictures</u> and forcasts are <b>awesome.</b> <br>"
+"&#43; <b>Awesome</b> <u>pictures</u> and accurate reports. <br>"
+"&#43; I love the interface, and the <u>multi</u> <u>city</u> <u>option</u> is <b>fab</b> to swipe <b>through.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Pictures</u> <b>rarely</b> change and most of the time they <b>are</b> <b>repeated</b> and juxtaposed <b>for</b> <b>different</b> <b>cities</b> <b>.</b> <br>"
+"- Please if you could put weather conditions wallpapers instead of <u>pictures</u> of that city, because those <u>pictures</u> <b>affects</b> the <b>widget,</b> can't see the time clearly. <br>"
+"- I <b>like</b> how <u>it</u> <u>is</u> <u>laid</u> <u>out</u> and <u>with</u> <u>other</u> <u>cities</u> a swipe away if I want. <br>"
+"- I think that it is not to bad really, mostly the information on here is accurate and I <b>like</b> the <u>background</u> <u>pictures</u> that are used to depict the different locations. <br>"
+"</p>","volumn":33,"sentiment":.76,"value":4.25},
{"keyword":"information","name":"<h1>information</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is easy to use app and I <b>love</b> all <u>the</u> <u>other</u> <u>information</u> on wind and sunrise/ sunset etc! <br>"
+"&#43; It is very useful and efficient, all <b>needed</b> <u>information</u> <u>available.</u> <br>"
+"&#43; <b>Great</b> <u>information!</u> <br>"
+"&#43; Great local pictures and <b>useful</b> <u>information</u> including incoming train. <br>"
+"&#43; The animations, the design, the <u>corect</u> <u>informations</u> and all of those <b>make</b> this <b>app</b> <b>awesome!</b> <br>"
+"&#43; Beautiful images, rain effect and <b>useful</b> <u>information</u> all in the same page <br>"
+"&#43; <u>Wind</u> <u>direction</u> <u>information</u> is most <b>helpful</b> <b>too.</b> <br>"
+"&#43; <u>Information</u> <b>is</b> <b>shown</b> clearly, <b>beautifully</b> and in the midle of the screen you have an ad to another Yahoo app. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Information</u> is <b>not</b> <b>accurate</b> <b>lately.</b> <br>"
+"- <b>Inaccurate</b> <u>information.</u> <br>"
+"</p>","volumn":12,"sentiment":.75,"value":3.23},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>user</u> <u>interface,</u> all the info I need. <br>"
+"&#43; I <b>love</b> the <u>interface,</u> and the multi city option is fab to swipe through. <br>"
+"&#43; <u>User</u> <u>interface</u> is <b>crisp!</b> <br>"
+"&#43; <b>Nice</b> <u>interface.</u> <br>"
+"&#43; <b>nice</b> <u>interface.</u> <br>"
+"&#43; <b>Beautiful</b> <u>interface,</u> very <u>reliable</u> <br>"
+"&#43; The <u>interface</u> is clean, <b>intuitive,</b> and fun to use. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I initially <b>liked</b> the <u>user</u> <u>interface</u> but this app apears to either be limited with what you view or just doesn't allow you to change things! <br>"
+"</p>","volumn":9,"sentiment":.67,"value":2.86},
{"keyword":"design","name":"<h1>design</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Nice</b> <u>design</u> and fairly accurate <br>"
+"&#43; The animations, the <u>design,</u> the corect informations and all of those <b>make</b> this <b>app</b> <b>awesome!</b> <br>"
+"&#43; Surprisingly useful and sports a refreshingly <b>unique,</b> <b>simple</b> and <u>elegant</u> <u>design.</u> <br>"
+"&#43; Simply <b>elegant</b> <u>design.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":7,"sentiment":.57,"value":2.52},
{"keyword":"display","name":"<h1>display</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> it the weather is very precise and I <b>love</b> <u>wallpaper</u> <u>displays*</u> <br>"
+"&#43; The pictures and <u>display</u> are <b>great</b> as you can get weather just about anywhere it is all about the <u>display</u> <br>"
+"&#43; It's thoughtful and <u>atractive</u> <u>display</u> invites curiosity and <b>holds</b> <b>interest</b> besides <b>informing.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Nothing</u> <u>displays</u> <u>once</u> <u>gps</u> is <b>turned</b> <b>off,</b> Really <b>stupid,</b> <b>not</b> <b>having</b> my <b>location</b> <b>on</b> <b>constantly.</b> <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Updates</u> <b>working</b> and great ui. <br>"
+"&#43; Beautiful animations and <b>fast</b> <u>updates.</u> <br>"
+"&#43; Extremely informative, <u>updates</u> <b>have</b> <b>brought</b> nice improvements and <b>better</b> <b>functionality.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>like</b> the animated weather and <u>updates,</u> they're spot on and able to choose multiple regions/ countries. <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"UI","name":"<h1>UI</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>ui,</u> and quite precise <br>"
+"&#43; Updates working and <b>great</b> <u>ui.</u> <br>"
+"&#43; It is very <b>nice</b> <u>UI.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Sleek</b> <u>UI</u> and accurate weather info from weather underground. <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"layout","name":"<h1>layout</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>like</b> the background and <u>layout</u> as well. <br>"
+"&#43; <b>Great</b> <u>layout.</u> <br>"
+"&#43; <b>Nice</b> <u>layout.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>like</b> the graphics and the <u>overall</u> <u>layout</u> but it needs to ad weather alerts and text for the forecast. <br>"
+"</p>","volumn":5,"sentiment":.40,"value":2.01},
{"keyword":"use","name":"<h1>use</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>aplication</u> <b>itself</b> <b>provides</b> prety <b>detailed</b> <b>forecast</b> <b>including</b> <b>sunrise/sunset</b> <b>times.</b> <br>"
+"&#43; <b>Love</b> <u>it</u> <u>easy</u> <u>to</u> <u>use</u> and <u>read.</u> <br>"
+"&#43; <b>Beautiful</b> and <u>useful</u> <u>aplication</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very nice, <b>low</b> <u>power</u> <u>use.</u> <br>"
+"</p>","volumn":5,"sentiment":.40,"value":2.01},
{"keyword":"photos","name":"<h1>photos</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Beautiful</b> <u>places</u> every change! <br>"
+"&#43; And <b>enjoy</b> the <u>photos!</u> <br>"
+"&#43; Good system,fair <u>photos</u> <br>"
+"&#43; I <b>love</b> the <u>photos!</u> <br>"
+"&#43; I <b>love</b> the <u>photos</u> and have locations selected purely to see the area depicted. <br>"
+"&#43; <b>Great</b> <u>photos</u> <u>of</u> the curent weather <u>conditions,</u> accurate and informative. <br>"
+"&#43; <b>Wonderful</b> <u>photos.</u> <br>"
+"&#43; <b>Great</b> <u>photos</u> and prety good data. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But I wish the <u>photos</u> <u>of</u> <u>different</u> <u>places</u> <b>were</b> <b>video</b> <u>photos.</u> <br>"
+"- But I wish the <u>photos</u> of different places were <b>video</b> <u>photos.</u> <br>"
+"- The <u>flicker</u> <u>photos</u> don't <b>remain</b> <b>displayed</b> <b>on</b> widget <b>on</b> <b>wallpaper</b> pertaining to city's location. <br>"
+"- It is not only that, but the <u>photos</u> <b>are</b> <b>constantly</b> <b>changed</b> and new images <b>are</b> provided, which is fine mainly for those who have never been to those places before. <br>"
+"- Hapy but improvement needed with location and d is <b>respective</b> <u>photos</u> <br>"
+"</p>","volumn":15,"sentiment":.33,"value":3.04},
{"keyword":"widget","name":"<h1>widget</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Widget</u> is <b>excellent</b> <br>"
+"&#43; the <u>widget</u> is <b>nice</b> and clean but it would be great if it also showed the times at the different locations also. <br>"
+"&#43; <u>Widgets</u> are <b>great!</b> <br>"
+"&#43; I <b>love</b> the <u>widget,</u> too! <br>"
+"&#43; Was the <b>best</b> <u>widget</u> <u>options</u> thus far. <br>"
+"&#43; It is clear and easy to navigate, and the <u>widget</u> is really <b>nice</b> <b>too.</b> <br>"
+"&#43; I <b>love</b> the <u>simple</u> <u>hourly</u> <u>widget.</u> <br>"
+"&#43; GOOD: <b>Excellent</b> <u>widget</u> <u>options</u> with just a the right data and information design in both <u>widget</u> and app form. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Just upgraded android phone and now if GPS is off and I flip past saved cities <b>to</b> the curent <b>location</b> the <u>widget</u> <b>freezes</b> <b>there</b> <b>on</b> a <b>screen</b> <b>that</b> <b>tells</b> <b>me</b> <b>to</b> <b>turn</b> <b>on</b> <b>location</b> <b>service</b> it will not display weather at any <b>location</b> if GPS is off. <br>"
+"- <u>Widget</u> is <b>poor.</b> <br>"
+"- <u>I</u> <b>like</b> <u>to</u> <u>be</u> <u>able</u> <u>to</u> <u>monitor</u> any <u>other</u> <u>locations</u> <u>than</u> my <u>curent</u> <u>through</u> the <u>widget.</u> <br>"
+"- <u>Homescreen</u> <u>widget</u> <b>sometimes</b> don't <b>update,</b> says info unavailable, but when clicked to show the ap, it displays the weather info. <br>"
+"- <u>Widget</u> <b>freezes</b> <b>when</b> GPS off. <br>"
+"- With the ability to make the <u>widget</u> mostly transparent, I could reduce the visual <b>cluter</b> on my home screen, but now the <u>widget</u> <b>is</b> just <b>cluter.</b> <br>"
+"- The <u>home</u> <u>screen</u> <u>widget</u> <b>used</b> <b>to</b> <b>be</b> almost <b>clear</b> when not using the photo background. <br>"
+"</p>","volumn":27,"sentiment":.33,"value":3.63},
{"keyword":"accurate","name":"<h1>accurate</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Beautiful</b> <u>photos,</u> <b>detailed</b> and <u>accurate</u> weather <br>"
+"&#43; Great photos and prety <b>good</b> <u>data.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Weather alerts, <u>accurate,</u> <u>low</u> <u>data</u> <b>use</b> <b>options.</b> <br>"
+"</p>","volumn":4,"sentiment":.25,"value":1.64},
{"keyword":"accuracy","name":"<h1>accuracy</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the different pictures and <u>accuracy.</u> <br>"
+"&#43; Picky details and <b>nice</b> <u>accuracy</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Low</b> <u>accuracy</u> thou. <br>"
+"</p>","volumn":4,"sentiment":.25,"value":1.64},
{"keyword":"rain","name":"<h1>rain</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>looks.</u> <br>"
+"&#43; I <b>love</b> the <u>look</u> though. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>I</b> like the radar feature so <b>I</b> can see where <u>rain</u> <b>is</b> <b>coming</b> <b>from,</b> the <u>rain</u> forecast <b>is</b> not always corect. <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"Radar","name":"<h1>Radar</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Nice</b> <u>radar</u> feature. <br>"
+"&#43; <u>Radar</u> <b>has</b> timestamp and <b>marks</b> your location on map. <br>"
+"&#43; <u>Radar</u> is <b>very</b> <b>accurate.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Radar</u> is <b>so</b> <b>helpful</b> <b>for</b> <b>boating</b> <b>safety.</b> <br>"
+"- It is not sure where the <u>radar</u> <u>map</u> is from but <b>definitely</b> <b>need</b> <b>a</b> <b>different</b> <b>source.</b> <br>"
+"</p>","volumn":6,"sentiment":.17,"value":1.96},
{"keyword":"day","name":"<h1>day</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Beautiful</u> <u>day</u> and it's <b>nice</b> <b>app.</b> <br>"
+"&#43; <b>excellent</b> <u>picture</u> <u>description</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Day</u> and <u>evening</u> <u>descriptions</u> <u>are</u> always <u>reversed,</u> <b>needs</b> <b>to</b> <b>be</b> <b>fixed</b> <br>"
+"- Curently it displays e.g. Tuesday but I want to display Tuesday 12 (when Tuesday is the <b>12th</b> <u>day</u> <u>of</u> the month). <br>"
+"- The <u>day</u> <u>forecast</u> is for night and vice <b>versa.</b> <br>"
+"</p>","volumn":7,"sentiment":.14,"value":2.09},
{"keyword":"images","name":"<h1>images</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>images,</u> <b>reliable,</b> and mostly <u>accurate.</u> <br>"
+"&#43; <b>Great</b> <u>local</u> <u>pictures</u> and useful information including incoming train. <br>"
+"&#43; <b>Great</b> <u>images</u> like to weather conditions. <br>"
+"&#43; <b>Beautiful</b> <u>images,</u> rain effect and useful information all in the same page <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Local</u> <u>images</u> from Flickr in the widget <b>is</b> the <b>feature</b> which makes Yahoo Weather stand out. <br>"
+"- <u>Local</u> <u>conditions</u> <b>updated</b> succinctly and <b>factually</b> <b>!</b> <br>"
+"- But the <u>satellite</u> <u>images</u> don't <b>load</b> the <b>layers</b> <b>it</b> <b>says</b> it's <b>capable</b> <b>of.</b> <br>"
+"</p>","volumn":8,"sentiment":.12,"value":2.20},
{"keyword":"weather","name":"<h1>weather</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>nice</b> and <u>good</u> <u>ap</u> <br>"
+"&#43; <u>Weather</u> <u>Bug</u> <b>works</b> <b>fine</b> <b>for</b> <b>me,</b> The pictures are beautiful. <br>"
+"&#43; Super <b>accurate</b> and very <u>beautiful</u> <u>ap!</u> <br>"
+"&#43; <u>Weather</u> is <b>very</b> <b>good.</b> <br>"
+"&#43; <u>I</u> <b>liked</b> the <u>photos</u> <u>which</u> <u>matched</u> the <u>locations</u> and the <u>fun</u> <u>of</u> <u>tracking</u> <u>weather</u> <u>in</u> <u>various</u> <u>locales.</u> <br>"
+"&#43; <u>Yahoo</u> <u>weather</u> is <b>fantastic.</b> <br>"
+"&#43; <u>Weather</u> <b>offers</b> beautiful sugestive imagery from Flickr? and <b>clean</b> and <b>simple</b> <b>icons</b> <b>with</b> <b>delightful</b> <b>animations</b> <b>to</b> <b>illustrate</b> the <b>weather</b> <b>data.</b> <br>"
+"&#43; The public submited pictures on the widget are a cool idea but maybe the <u>weather</u> picture displayed should reflect <b>what</b> the <u>weather</u> <b>is</b> <b>doing</b> <b>instead</b> <b>of</b> just a <b>random</b> <b>slideshow.I</b> <b>like</b> <b>it</b> doe! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I ve tried <u>almost</u> all free <u>weather</u> <u>aps.Yahoo</u> is the <b>simplest</b> and one of the most accurate with all necessary information,especially radar map is the best of all.Easy to refress and flicker pictures makes it even better.The only fallback is yahoo widgets are not so atractive but not big deal.Beside yahoo i liked 1Weather,WU, AccuW most.But due to simplicity and also accuracy I am using Yahoo. <br>"
+"- The <u>weather</u> by hour is <b>never</b> <b>accurate</b> , not even close . <br>"
+"- <b>Excellent</b> and <u>useful</u> <u>ap</u> <br>"
+"- Sleek UI and <b>accurate</b> <u>weather</u> <u>info</u> from <u>weather</u> underground. <br>"
+"- The curent location is right, but the <u>weather</u> and temperature is <b>completely</b> <b>false.</b> <br>"
+"- Somehow <u>yahoo</u> <u>weather</u> <b>is</b> <b>not</b> <b>working</b> properly, <b>sometimes</b> predictions are wrong. <br>"
+"- Decent enough <u>weather</u> <u>ap,</u> but the ad banner is <b>too</b> <b>large</b> and distracting and it's right in the midle. <br>"
+"- <u>Weather</u> is <b>not</b> <b>accurate</b> I gave a 2 star for that please need an update <br>"
+"</p>","volumn":67,"sentiment":.10,"value":4.31},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Funnily enough, <u>older</u> <u>version</u> <b>worked</b> <b>well.</b> <br>"
+"- Another <b>lazy</b> <u>Android</u> <u>version.</u> <br>"
+"- <u>New</u> <u>version</u> is <b>bad.</b> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"time","name":"<h1>time</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great app accurate weather <b>many</b> <u>times</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The forecast is mediocre and some <u>time</u> is <b>totally</b> <b>wrong</b> <b>with</b> even <b>with</b> <b>present</b> <b>weather</b> <b>conditions</b> <br>"
+"- Pictures <b>rarely</b> <u>change</u> and <u>most</u> <u>of</u> the <u>time</u> <u>they</u> <b>are</b> <b>repeated</b> and juxtaposed <b>for</b> <b>different</b> <b>cities</b> <b>.</b> <br>"
+"- I like the animated weather and updates, they're <b>spot</b> on and able to choose multiple regions/ countries. <br>"
+"- The <u>time</u> is <b>slow</b> <b>to</b> <b>update</b> and the temperature often doesn't <b>update,</b> <b>even</b> <b>after</b> <b>pressing</b> <b>refresh.</b> <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"location","name":"<h1>location</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great app nice design and the <u>GPS</u> <u>locations</u> are <b>prety</b> <b>awesome</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Also,</b> the <u>curent</u> <u>location</u> is <b>not</b> <b>accurate.</b> <br>"
+"- 11/22: Ap is nice on curent location, but 'other' <u>locations</u> <u>DO</u> <u>NOT</u> <b>WORK</b> <b>anymore.</b> <br>"
+"- 'Curent <u>Location'</u> <b>turns</b> <b>itself</b> on and <b>off.</b> <br>"
+"- <u>Locations</u> <b>are</b> <b>deleted</b> <b>intermitently.</b> <br>"
+"- Today, my <u>curent</u> <u>location</u> <b>is</b> Dar Es <b>Salam.</b> <br>"
+"</p>","volumn":8,"sentiment":-.50,"value":1.58},
{"keyword":"forecast","name":"<h1>forecast</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very nice <u>interface</u> <u>but</u> (as in this moment: 0% <u>but</u> it's raining a lot) <u>forecast</u> is <b>unacurated.</b> <br>"
+"&#43; <b>Beautiful</b> <b>but</b> <b>seldom</b> <u>wrong</u> <u>forecast.</u> <br>"
+"&#43; The <u>forecast</u> <u>quality</u> is also <b>very</b> <b>precise.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>forecast</u> is <b>mediocre</b> and some time is totally wrong with even with present weather conditions <br>"
+"- Right now it's bucketing down yet curent weather and <u>forecast</u> is <b>for</b> 'mostly cloudy'. <br>"
+"- Many times the <u>forecast</u> <b>is</b> <b>changed</b> <b>at</b> the <b>last</b> <b>moment.</b> <br>"
+"- <b>Just</b> <u>peachy</u> and <u>accurate</u> <u>forecasting</u> for my sailing <b>needs.</b> <br>"
+"- But the <u>forecast</u> is <b>not</b> <b>very</b> <b>accurate.</b> <br>"
+"- <b>Short</b> and <b>long</b> <u>range</u> <u>forecasts</u> highly inaccurate! <br>"
+"- I like the radar feature so I can see where <u>rain</u> <b>is</b> coming from, the <u>rain</u> <u>forecast</u> <b>is</b> <b>not</b> always <b>corect.</b> <br>"
+"</p>","volumn":10,"sentiment":-.50,"value":1.80},
{"keyword":"temperature","name":"<h1>temperature</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> love the pictures and <b>enjoy</b> the <u>very</u> <u>accurate</u> <u>outside</u> <u>temperatures</u> and <u>10</u> <u>day</u> <u>predictions.</u> <br>"
+"&#43; I <b>enjoy</b> <u>knowing</u> <u>what</u> the <u>weather</u> and <u>temperature</u> <u>is</u> like in the places my friends live especially in the winter. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>daily</u> <u>high</u> <u>temperature</u> <b>is</b> always 2 <b>degrees</b> <b>higher</b> <b>than</b> <b>what</b> <b>is</b> <b>shown</b> <b>on</b> the <b>hourly</b> <u>temperature</u> <b>spread.</b> <br>"
+"- The curent location is right, but the weather and <u>temperature</u> is <b>completely</b> <b>false.</b> <br>"
+"- The time is slow to <b>update</b> and the <u>temperature</u> <b>often</b> doesn't <b>update,</b> even after pressing refresh. <br>"
+"- Why <b>remove</b> <u>Temperature</u> <u>notification</u> <u>color</u> <u>customization?</u> <br>"
+"- <u>Even</u> the <u>curent</u> <u>temperatures</u> <b>are</b> <b>way</b> off. <br>"
+"- <u>Temperature</u> is <b>accurate,</b> sunrise and sunset is too. <br>"
+"- But the <u>curent</u> <u>temperature</u> is <b>wildly</b> <b>different</b> <b>from</b> all my other weather aps and the <b>local</b> <b>radio,</b> <b>which</b> <b>makes</b> this <b>app</b> <b>wrong.</b> <br>"
+"- The <u>temperature</u> shown the Cities <b>are</b> Seoul 62 <b>degrees</b> Singapore 87 <b>degrees</b> and Hong Kong 76 <b>degrees</b> how to fix it? <br>"
+"</p>","volumn":12,"sentiment":-.42,"value":2.07},
{"keyword":"ads","name":"<h1>ads</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Since the last update now <u>great</u> <u>big</u> <u>ads</u> are <b>present</b> <b>in</b> the <b>app.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>giant</u> <u>ads</u> in the midle of the weather info are <b>obtrusive.</b> <br>"
+"- <b>Constantly</b> <b>forgets</b> preferences, and <u>ads</u> <u>random</u> <u>unwanted</u> <u>locations.</u> <br>"
+"- <u>Ad</u> <u>banner</u> is <b>too</b> <b>large.</b> <br>"
+"</p>","volumn":7,"sentiment":-.29,"value":1.66},
]