var data_map_totalreviews=624
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_wechat = [
{"keyword":"something","name":"<h1>something</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>please</b> <u>do</u> <u>something.</u> <br>"
+"&#43; <b>please</b> <u>do</u> <u>something</u> <u>about</u> <u>it.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.67,"value":1.77},
{"keyword":"old","name":"<h1>old</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; can you please <b>make</b> <u>the</u> <u>old</u> <u>backup</u> ? <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"help","name":"<h1>help</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>please</b> <u>help</u> <u>me.</u> <br>"
+"&#43; <b>please</b> <u>help</u> <u>me.</u> <br>"
+"&#43; <b>please</b> <u>help?</u> <br>"
+"&#43; <b>please</b> <u>help</u> <u>me</u> ! <br>"
+"&#43; <b>please</b> <u>help</u> <u>me.</u> <br>"
+"&#43; I forgot my password and email <b>please</b> <u>help</u> <u>me!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>help</u> me, i changes my password to voice pasword.how to log in using voice pasword again. <br>"
+"</p>","volumn":16,"sentiment":.31,"value":3.09},
{"keyword":"bar","name":"<h1>bar</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>need</b> <u>a</u> more <u>convinient</u> <u>sticker</u> <u>scroll</u> <u>bar.</u> <br>"
+"- Please we <b>need</b> more <u>animation</u> <u>stickers.</u> <br>"
+"- There's <u>no</u> <u>notifications</u> <u>bar</u> <u>shown</u> after update. <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"notification","name":"<h1>notification</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Ad feature>notification <u>taskbar</u> for moments. <br>"
+"- It doesn't <b>give</b> <u>notifications</u> either. <br>"
+"- Sometimes cannot use and <b>no</b> <u>notifications.</u> <br>"
+"</p>","volumn":4,"sentiment":-.75,"value":.64},
{"keyword":"more","name":"<h1>more</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- No account permanent delete option, why saving old to old profile, why its worst to show which accounts or contact i dnt have number in my contact list, totally waste of time , if wechat <b>want</b> <u>more</u> <u>user.</u> <br>"
+"- It <b>need</b> <u>t</u> <u>o</u> <u>ad</u> <u>more</u> <u>aditional</u> <u>feature.</u> <br>"
+"- I myself is hapy with this except it still <b>needs</b> <u>more</u> <u>improvement.</u> <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; please <b>give</b> us <u>unlimited</u> <u>botle</u> <u>to</u> <u>collect</u> . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But Am unable to <b>see</b> the <u>near</u> <u>by</u> <u>friends</u> <u>option</u> and <u>botle</u> <u>drift</u> <u>option</u> <u>please</u> <u>sugest</u> <u>me</u> <br>"
+"- This app seriously <b>needs</b> <u>an</u> <u>option</u> <u>where</u> <u>you</u> <u>can</u> <u>edit</u> <u>your</u> <u>text</u> or <u>picture</u> <u>with</u> <u>text</u> <u>moments</u> <u>where</u> if tou misspelled or <u>you</u> forget to type some of the words before posting it. <br>"
+"- cannot <b>see</b> the <u>option</u> <u>of</u> <u>login</u> by SMS when forgot. <br>"
+"- after upgrade, cannot <b>see</b> the <u>option</u> <u>of</u> <u>login</u> <u>by</u> <u>SMS</u> any <b>more.</b> <br>"
+"- I <b>see</b> that there's no <u>option</u> to backup my chat history anymore. <br>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>option</u> <u>to</u> <u>delete</u> the <u>account.</u> <br>"
+"- <u>I</u> <b>want</b> my <u>old</u> <u>acc</u> <u>please.</u> <br>"
+"</p>","volumn":9,"sentiment":-.67,"value":1.53},
{"keyword":"account","name":"<h1>account</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- i <b>want</b> my <u>account</u> <b>back,</b> because i play wechat speed more than one year. <br>"
+"- Please <b>include</b> <u>deactivate</u> <u>account</u> <u>buton</u> too ! <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"versions","name":"<h1>versions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>delete</u> <u>the</u> <u>new</u> <u>version.</u> <br>"
+"- <b>You</b> <b>will</b> <u>introduce</u> <u>deletion</u> <u>option</u> <u>in</u> <u>later</u> <u>versions,</u> but there must be some way to delete it right now? <br>"
+"- <b>You</b> <b>will</b> <u>introduce</u> <u>deletion</u> <u>option</u> <u>in</u> <u>later</u> <u>versions,</u> but there must be some way to delete it right now? <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"improvement","name":"<h1>improvement</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>needs</b> <u>improvement.</u> <br>"
+"- It <b>need</b> <u>improvement</u> immediately. <br>"
+"- <b>No</b> <u>improvement</u> over 3 years. <br>"
+"</p>","volumn":6,"sentiment":-.50,"value":1.29},
{"keyword":"change","name":"<h1>change</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I really <b>want</b> <u>to</u> <u>change</u> my <u>ID.</u> <br>"
+"- If <u>i</u> <b>want</b> <u>to</u> <u>change</u> my <u>cover</u> and <u>picture</u> it will be not responding and <u>i</u> can't <u>to</u> <u>change</u> my <u>picture</u> or <u>cover</u> it make me dislike it <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"delete","name":"<h1>delete</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Cant <b>see</b> <u>moment.</u> <br>"
+"&#43; Cant <b>see</b> <u>moment.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <b>wish</b> <u>I</u> <u>can</u> <u>delete</u> all <u>my</u> <u>moment</u> easily <br>"
+"- I really <b>need</b> <u>your</u> <u>team</u> <u>to</u> <u>delete</u> my <u>account</u> permenantly. <br>"
+"- You will introduce deletion option in later versions, but <b>there</b> <b>must</b> <b>be</b> some <u>way</u> <u>to</u> <u>delete</u> <u>it</u> right <u>now?</u> <br>"
+"- You will introduce deletion option in later versions, but <b>there</b> <b>must</b> <b>be</b> some <u>way</u> <u>to</u> <u>delete</u> <u>it</u> right <u>now?</u> <br>"
+"- Please <b>give</b> me <u>my</u> <u>old</u> <u>acc.</u> <br>"
+"</p>","volumn":7,"sentiment":-.43,"value":1.52},
{"keyword":"update","name":"<h1>update</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; please , <b>need</b> <u>the</u> <u>latest</u> <u>update</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>update</u> the versions.It doesnot tell us whos online and offline. <br>"
+"</p>","volumn":5,"sentiment":.00,"value":1.61},
]