var data_map_totalreviews=1054
var data_map_fromdate=20150228
var data_map_todate=20151102
var data_map_kakaotalk = [
{"keyword":"an","name":"<h1>an</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; There should be seen if the message has been read already <u>and</u> <b>please</b> <u>put</u> <u>an</u> <u>online</u> <u>sign</u> if the person is <u>online.</u> <br>"
+"&#43; There should be seen if the message has been read already <u>and</u> <b>please</b> <u>put</u> <u>an</u> <u>online</u> <u>sign</u> if the person is <u>online.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":6,"sentiment":.33,"value":2.13},
{"keyword":"control-audio-progress","name":"<h1>control-audio-progress</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Other sugestions: video calls; <u>audio</u> player is definitely beter, but <b>we</b> still can't <u>control</u> <u>the</u> <u>audio</u> <u>progress.</u> <br>"
+"- Other sugestions: video calls; <u>audio</u> player is definitely beter, but <b>we</b> still can't <u>control</u> <u>the</u> <u>audio</u> <u>progress.</u> <br>"
+"- Other sugestions: video calls; <u>audio</u> player is definitely better, but <b>we</b> still can't <u>control</u> <u>the</u> <u>audio</u> <u>progress.</u> <br>"
+"- Other sugestions: video calls; <u>audio</u> player is definitely better, but <b>we</b> still can't <u>control</u> <u>the</u> <u>audio</u> <u>progress.</u> <br>"
+"</p>","volumn":4,"sentiment":-1.00,"value":.39},
{"keyword":"fresh-ui","name":"<h1>fresh-ui</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- where's the material design , line have that and whatsap have that you are too late , the <u>UI</u> is too old we <b>need</b> <u>fresh</u> <u>UI</u> <br>"
+"- where's the material design , line have that and whatsap have that you are too late , the <u>UI</u> is too old we <b>need</b> <u>fresh</u> <u>UI</u> ! <br>"
+"- where's the material design , line have that and whatsap have that you are too late , the <u>UI</u> is too old we <b>need</b> <u>fresh</u> <u>UI</u> ! <br>"
+"- where's the material design , line have that and whatsap have that you are too late , the <u>UI</u> is too old we <b>need</b> <u>fresh</u> <u>UI</u> ! <br>"
+"- where's the material design , line have that and whatsap have that you are too late , the <u>UI</u> is too old we <b>need</b> <u>fresh</u> <u>UI</u> ! <br>"
+"- where's the material design , line have that and whatsap have that you are too late , the <u>UI</u> is too old we <b>need</b> <u>fresh</u> <u>UI</u> ? <br>"
+"</p>","volumn":6,"sentiment":-1.00,"value":.79},
{"keyword":"contacts","name":"<h1>contacts</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It would be awesome if <b>you</b> <b>could</b> <u>delete</u> <u>contacts.</u> <br>"
+"- I actually like that <u>you</u> can't see when <u>you</u> or <u>your</u> <u>contacts</u> were <b>online.</b> <br>"
+"- I actually like that you can't see when you or <u>your</u> <u>contacts</u> were <b>online.</b> <br>"
+"- I think <b>there</b> <b>should</b> <b>be</b> a <u>way</u> <u>to</u> <u>delete</u> <u>people</u> from your friends list <u>please.</u> <br>"
+"- I don't wanna hide and block , i <b>want</b> <u>to</u> <u>delete</u> <u>them</u> and don't see my profile <br>"
+"</p>","volumn":6,"sentiment":-.83,"value":.96},
{"keyword":"this","name":"<h1>this</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I'm really love it bcs its more easy to video call with my bf in korea^^ thank you and please <b>improve</b> <u>this</u> ap^^ <br>"
+"- The delete friends <u>option</u> is advertised for the new update, however <u>this</u> <u>option</u> does <b>not</b> seem to be available on the Galaxy. <br>"
+"- I can text my friend and its geting more awesome also I can free call and video call but the thing that I kind of do not like Is it needs wifi and sometime it can not change my profile but rest of them is awesome <b>you</b> <b>should</b> <u>install</u> <u>this</u> or update <br>"
+"- I <b>need</b> someone <u>to</u> email <u>me</u> or call <u>me</u> personally <u>to</u> <u>resolve</u> my <u>issue.</u> <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"improvement","name":"<h1>improvement</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I found that calling feature <b>needs</b> <u>immediate</u> <u>improvement.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Good but <b>needs</b> <u>some</u> <u>improvements.</u> <br>"
+"- Good but <b>needs</b> <u>some</u> <u>improvements.</u> <br>"
+"- Good but <b>needs</b> <u>some</u> <u>improvements.</u> <br>"
+"- This is awesome but video call and vioce call <b>need</b> <u>improvement</u> its <u>stuck</u> sometimes. <br>"
+"- Calls and video chats <b>need</b> <u>improvement,</u> though! <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"update","name":"<h1>update</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>update</u> very well this app.i wish even no internet connection can use this please. <br>"
+"- well <u>its</u> better but I just <b>want</b> <u>them</u> <u>to</u> <u>update</u> <u>it</u> <u>to</u> where <u>we</u> <u>can</u> <u>like</u> video or voice calling with more than 1 person or even 5 I <b>want</b> <u>it</u> <u>like</u> Skype but better and you <u>can</u> see multiple people on you phone or computer <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"ad","name":"<h1>ad</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Everything is great the <b>only</b> <b>thing</b> <b>I</b> <b>would</b> <b>do</b> is <u>ad</u> an update that allows you to videos chat with more than one person <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Much <b>better</b> if you could <u>ad</u> feature where you could see if someone is online. <br>"
+"- <b>Please</b> <u>change</u> the format.like viber or <u>facebook</u> <u>much</u> <u>better.please</u> <u>ad</u> more free emoticons too. <br>"
+"- <b>Please</b> <u>change</u> the format.like viber or <u>facebook</u> <u>much</u> <u>better.please</u> <u>ad</u> more free emoticons too.please indicate if the person is typing a message. <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"notification","name":"<h1>notification</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; it will be great if <b>we</b> <b>can</b> <u>set</u> up <u>a</u> <u>password</u> <u>for</u> the <u>notification</u> <u>cover</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>secondly</b> I cannot <b>see</b> the <u>message</u> <u>notification</u> in the status bar although I have enabled all the option. <br>"
+"- It'd be nice if <b>there</b> <b>was</b> <u>an</u> <u>option</u> <u>to</u> <u>set</u> a <u>short/medium/strong</u> <u>vibration</u> <u>for</u> <u>incoming</u> <u>messages.</u> <br>"
+"- Please don't <b>give</b> me <u>notifications</u> <u>for</u> <u>new</u> <u>emoticons.</u> <br>"
+"</p>","volumn":5,"sentiment":-.40,"value":1.21},
{"keyword":"would-be","name":"<h1>would-be</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; One more thing please <b>make</b> <u>the</u> <u>other</u> <u>features</u> <u>like</u> <u>Kakao</u> <u>Home</u> <u>available</u> and <u>compatible</u> with <u>other</u> devices and country. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>they</u> <u>would</u> also <u>merge</u> <u>KakaoStory</u> <u>into</u> <u>Kakao</u> so it's a one stop destination for all things <u>Kakao.</u> <br>"
+"- <b>Please</b> <u>look</u> <u>into</u> <u>this</u> <u>problem</u> <u>sir.</u> <br>"
+"- But <u>I</u> <b>wish</b> <u>I</u> <u>could</u> <u>send</u> <u>gifs</u> plus it <u>would</u> <u>be</u> <u>nice</u> if the secret chat had a password or something similar to make it more secret <br>"
+"</p>","volumn":5,"sentiment":-.40,"value":1.21},
{"keyword":"number","name":"<h1>number</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Hello , could you please make an update so <b>we</b> <b>can</b> <u>change</u> <u>our</u> <u>number</u> ( the verification one ) . <br>"
+"&#43; Hello , could you please make an update so <b>we</b> <b>can</b> <u>change</u> <u>our</u> <u>number</u> ( the verification one ) . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Harder to <b>see</b> <u>unread</u> <u>number,</u> notification I'd hard to <b>see,</b> (bring <u>back</u> the <u>yellow</u> logo!) <br>"
+"- <b>There</b> <b>is</b> <b>no</b> <b>more</b> <u>back</u> <u>buton.</u> <br>"
+"- If you <b>want</b> <u>to</u> <u>back</u> <u>up</u> <u>photos</u> that your contacts send you, you have <u>to</u> manually select each photo you <b>want</b> <u>to</u> share (this requires at least one tap per photo) and then manually share them <u>to</u> another app. <br>"
+"- I would also like to <b>see</b> <u>internet</u> <u>phone</u> <u>numbers</u> being allowed. <br>"
+"- ( kind of like voxer ) also the notification in app for when somebody has <b>seen</b> or heard your voice note should be changed it can be difficult sometimes to <b>see</b> the <u>number</u> <u>1</u> in yellow. <br>"
+"</p>","volumn":8,"sentiment":-.38,"value":1.70},
{"keyword":"could","name":"<h1>could</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; so i <b>hope</b> <u>new</u> <u>update</u> <u>could</u> <u>fix</u> <u>this,</u> <u>please.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>wish</b> <u>you</u> <u>could</u> <u>see</u> <u>this.</u> <br>"
+"- <u>I</u> just <b>wish</b> <u>we</u> <u>could</u> <u>have</u> <u>a</u> <u>Coin</u> <u>system</u> <u>like</u> <u>Line</u> where <u>we</u> can earn coins instead of buying sticker packs and themes. <br>"
+"- <u>I</u> <b>wish</b> <u>we</u> <u>could</u> <u>look</u> <u>for</u> <u>groups</u> <u>to</u> <u>join</u> any <u>kpop</u> <u>group</u> <u>out</u> <u>there?</u> <br>"
+"</p>","volumn":6,"sentiment":-.33,"value":1.46},
{"keyword":"multiple","name":"<h1>multiple</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- well its better but I just want them to update it to where we can like video or voice calling with more than 1 person or even 5 I want it like Skype but better and you can <b>see</b> <u>multiple</u> <u>people</u> on you phone or computer <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"help","name":"<h1>help</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- My dad doesn't really use kakao so I have taken over <u>it</u> but the ID is set as HIS <u>name</u> but i <b>want</b> <u>it</u> <u>to</u> <u>be</u> <u>MY</u> <u>name</u> so <u>its</u> <u>easier</u> <u>to</u> <u>find</u> <u>me</u> <u>please</u> <u>help!</u> <br>"
+"- My dad doesn't really use kakao so I have taken over <u>it</u> but the ID is set as HIS <u>name</u> but i <b>want</b> <u>it</u> <u>to</u> <u>be</u> <u>MY</u> <u>name</u> so <u>its</u> <u>easier</u> <u>to</u> <u>find</u> <u>me</u> <u>please</u> <u>help!</u> <br>"
+"</p>","volumn":7,"sentiment":-.29,"value":1.66},
{"keyword":"free","name":"<h1>free</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's good over all, but more free <u>stickers</u> <u>to</u> <u>choose</u> <u>from</u> <b>would</b> <b>be</b> <b>nice</b> <br>"
+"&#43; So please, <b>make</b> <u>your</u> <u>stickers</u> free. <br>"
+"&#43; But <u>I</u> <b>hope</b> <u>there</u> <u>are</u> more <u>free</u> <u>emoticons</u> and <u>themes</u> <u>!</u> <br>"
+"&#43; please <b>give</b> more and <u>new</u> <u>sticker.</u> <br>"
+"&#43; nice app but <u>I</u> <b>wish</b> <u>there</u> <u>were</u> more <u>free</u> <u>cute</u> <u>stickers</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>you</b> don't <u>know</u> when someone is online or typing <u>not</u> a <u>bit</u> <u>close</u> <u>to</u> <u>Viber</u> <u>and</u> the <u>stickers</u> <u>are</u> <u>crap</u> <u>ye</u> <u>should</u> <u>do</u> <u>more</u> <u>for</u> <u>free</u> <br>"
+"- I use this app to talk to fiancee and as much as we LOVE the cat/dog voice we <b>wish</b> <u>there</u> <u>were</u> <u>more</u> <u>selections.</u> <br>"
+"- It <b>need</b> more <u>free</u> <u>stickers.</u> <br>"
+"- The <u>stickers</u> are great but when I went <u>to</u> the item store <b>there</b> <b>was</b> <u>no</u> <u>free</u> <u>stickers</u> <u>to</u> <u>be</u> <u>downloaded</u> which kind of suck but the <u>stickers</u> provided are enough. <br>"
+"- Stop Being Slack with the Moving Emoticons, Please <b>Give</b> us <u>some</u> <u>more</u> <u>FREE</u> <u>emoticons</u> Don't <u>be</u> <u>Stoy!</u> <br>"
+"- At now <u>I</u> can't <b>see</b> the <u>friends</u> <u>are</u> <u>in</u> <u>online</u> or <u>not.</u> <br>"
+"- Says unable to connect to Internet, also there are no <u>free</u> stickers, I <b>need</b> <u>some</u> <u>free</u> <u>ones</u> <u>except</u> <u>default.</u> <br>"
+"- Says unable to connect to Internet, <b>also</b> <b>there</b> <b>are</b> <u>no</u> <u>free</u> <u>stickers,</u> I need some <u>free</u> ones except default. <br>"
+"</p>","volumn":26,"sentiment":-.27,"value":2.99},
{"keyword":"is","name":"<h1>is</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Please ad a feature that let's you <b>see</b> <u>which</u> <u>friend</u> <u>is</u> <u>online</u> <u>kind</u> <u>of</u> like <u>Facebook</u> <u>please.</u> <br>"
+"&#43; I don't have CC and i really <b>hope</b> that <u>feature</u> <u>is</u> back. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Please <b>make</b> a android tablet ap, or <u>else</u> <u>hangouts</u> <u>is</u> <u>beter</u> <br>"
+"- however wished <b>there</b> <b>was</b> <u>the</u> <u>option</u> <u>to</u> <u>choose</u> <u>to</u> <u>see</u> <u>who</u> <u>is</u> <u>visable</u> <u>online.</u> <br>"
+"- I just <b>wish</b> <u>there</u> <u>is</u> a different <u>ringback</u> <u>tone</u> between active / nonactive user. <br>"
+"</p>","volumn":5,"sentiment":-.20,"value":1.41},
{"keyword":"call","name":"<h1>call</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The lag needs to be fixed and <u>the</u> <u>call</u> should be <b>more</b> <b>clear</b> and smooth. <br>"
+"</p>","volumn":6,"sentiment":-.17,"value":1.63},
]