var data_map_totalreviews=377
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_camera360 = [
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Good</b> <u>aplications</u> <br>"
+"&#43; It is <b>easy</b> <u>aplication</u> for great image editing <br>"
+"&#43; The <b>new</b> <b>update</b> is totally awesome <b>i</b> love it, its <u>fast</u> <u>powerful</u> <u>easy</u> interface,lot of nice changes <b>are</b> <b>done</b> <b>in</b> <b>new</b> <b>update</b> <br>"
+"&#43; <b>Great</b> <u>colors,</u> <u>easy</u> to use <br>"
+"&#43; This <u>aplication</u> is <b>so</b> <b>easy</b> and better then others <br>"
+"&#43; This <u>aplication</u> <b>always</b> <b>stop.</b> <br>"
+"&#43; It is very <b>cool</b> and <u>easy</u> <u>aplication</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":7,"sentiment":1.00,"value":2.95},
{"keyword":"features","name":"<h1>features</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>features</u> but. <br>"
+"&#43; Your <u>features</u> are <b>so</b> <b>awesome.</b> <br>"
+"&#43; <b>Nice</b> <u>features</u> <br>"
+"&#43; <b>Good</b> <u>features,</u> effects :) <br>"
+"&#43; <b>nice</b> <u>features</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Please return the previous <u>focus</u> <u>feature</u> and the shuter speed is also <b>very</b> <b>slow.</b> <br>"
+"</p>","volumn":7,"sentiment":.57,"value":2.52},
{"keyword":"selfie","name":"<h1>selfie</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is <b>easy</b> <u>selfies</u> and everything. <br>"
+"&#43; The <u>selfie</u> <u>mode</u> is <b>awesome!</b> <br>"
+"&#43; <b>Great</b> <u>selfies.</u> <br>"
+"&#43; The <u>selfie</u> <b>takes</b> <b>picture</b> as it is with amazing quality and modifications <br>"
+"&#43; The <u>selfies</u> <b>look</b> <b>great</b> too. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>selfie</u> <u>camera</u> is <b>inverted</b> and I couldn't access any of the effects on the main <u>camera</u> as well. <br>"
+"- I don't <b>like</b> the <u>selfie</u> <u>part.</u> <br>"
+"</p>","volumn":8,"sentiment":.38,"value":2.45},
{"keyword":"editing","name":"<h1>editing</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Amazing</b> <u>edit</u> picture. <br>"
+"&#43; <b>Amazing</b> <u>editing</u> features. <br>"
+"&#43; Lovely <u>editing</u> <u>options</u> and more filters <b>wud</b> <b>be</b> <b>5</b> <b>stars</b> <br>"
+"&#43; It's nice and simple liked <b>de</b> <u>editing</u> <br>"
+"&#43; I <b>love</b> this app and it has an <u>excellent</u> <u>editing</u> <u>options</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- where d hell <u>auto</u> <u>focus</u> <u>option</u> <b>gone?</b> <br>"
+"- The new interface (and the creators response) showed me <b>where</b> the <u>manual</u> <u>options</u> are for the camera and returned this app back to a 5 star app. <br>"
+"- No <b>full</b> <u>screen</u> <u>option</u> available like the previous version. <br>"
+"</p>","volumn":8,"sentiment":.25,"value":2.33},
{"keyword":"picture","name":"<h1>picture</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Sometimes</b> the <u>pictures</u> <b>pixelate</b> <b>for</b> some <b>effects,</b> otherwise <b>nice.</b> <br>"
+"&#43; <b>Great</b> <u>picture</u> taking and editing tools <br>"
+"&#43; S4 user- <b>I</b> use it wit my selfie stick and it's awesome, <u>pictures</u> <b>come</b> <b>out</b> really <b>clean.</b> <br>"
+"&#43; my <u>pictures</u> taking are <b>so</b> <b>beautifull</b> <br>"
+"&#43; The <b>new</b> <b>update</b> is totally awesome <b>i</b> love it, its fast powerful easy interface,lot <u>of</u> <u>nice</u> <u>changes</u> <b>are</b> <b>done</b> <b>in</b> <b>new</b> <b>update</b> <br>"
+"&#43; <b>Great</b> <u>pictures</u> quality. <br>"
+"&#43; His <u>picture</u> was clearly and <b>beautiful.</b> <br>"
+"&#43; So easy to makeover my <u>pictures</u> be <b>great.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <b>effects</b> are pointless as the <u>final</u> <u>picture</u> <b>does</b> <b>not</b> <b>have</b> the <b>chosen</b> <b>effect.</b> <br>"
+"- I hate the latest update,, the <u>picture</u> <b>not</b> <b>take</b> <b>full</b> screen,, the oldest one was better, i loved it,, but this new one is so bad i hate it. <br>"
+"- All the <u>pictures</u> <b>looks</b> <b>blired</b> and <b>low</b> <b>quality.</b> <br>"
+"- Amazing app nit only lets you edit <u>picture</u> also <b>have</b> <b>live</b> <b>filters.</b> <br>"
+"- I <b>like</b> this <u>aps</u> so <u>useful</u> <u>for</u> <u>taking</u> <u>pictures</u> <br>"
+"- The <u>pictures</u> don't <b>show</b> up <b>in</b> the <b>app</b> album,the camera often crashes and <b>above</b> <b>all</b> <b>it</b> doesn't <b>open</b> <b>at</b> <b>times!</b> <br>"
+"</p>","volumn":18,"sentiment":.17,"value":3.06},
{"keyword":"filters","name":"<h1>filters</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>loved</b> <u>all</u> <u>of</u> the <u>filters!</u> <br>"
+"&#43; <b>Well</b> , exactly it's better than last update , <u>HDR</u> <u>filter</u> Is the <b>best</b> <b>in</b> <b>all</b> <b>of</b> <b>them</b> , also another <u>filters</u> , and the bluring is so perfect <br>"
+"&#43; <b>Beautiful</b> <u>Filters.</u> . .. <br>"
+"&#43; <u>Filters</u> are <b>awesome!</b> <br>"
+"&#43; I just <b>love</b> all <u>the</u> <u>filters</u> and it's a very functional ap <br>"
+"&#43; <b>Good</b> <u>filters.</u> <br>"
+"&#43; Lovely editing options and <u>more</u> <u>filters</u> <b>wud</b> <b>be</b> <b>5</b> <b>stars</b> <br>"
+"&#43; My all time favourite Camera.Most beautiful and <b>Creative</b> <u>filters.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The new <u>filter</u> <u>oil</u> <u>painting</u> is <b>not</b> <b>there</b> I got a samsung galaxy s5 <br>"
+"- <b>Great</b> <u>Filter</u> but bad Resolution <br>"
+"- <u>More</u> <u>filters</u> and this would <b>be</b> five <b>stars.</b> <br>"
+"- Can't use the <u>new</u> <u>filters</u> <b>aded</b> <b>on</b> my <b>snapchat</b> <br>"
+"- The <u>filters</u> in this app is just <b>so</b> <b>awesome,</b> it works very fine in my phone(moto g 2 ), but didn't see the same affects in other phone. <br>"
+"- No <b>live</b> <u>preview</u> <u>of</u> <u>filters</u> when shooting photo <br>"
+"- <u>Filters</u> are <b>awesome</b> but the quality of image is not that good. <br>"
+"- No <b>live</b> <u>preview</u> <u>of</u> <u>filters</u> when shooting photo <br>"
+"</p>","volumn":25,"sentiment":.16,"value":3.38},
{"keyword":"effects","name":"<h1>effects</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Nice</b> <u>effects!</u> <br>"
+"&#43; I love the <u>effects</u> and app is <b>so</b> <b>easy</b> <b>to</b> <b>use.</b> <br>"
+"&#43; <b>Awesome</b> <u>effects</u> <br>"
+"&#43; Awesome lovely app and <b>nice</b> <u>effects</u> <br>"
+"&#43; I <b>love</b> the <u>effect</u> <br>"
+"&#43; <u>I</u> <b>love</b> the <u>effects</u> <u>part</u> that <u>you</u> <u>save</u> <u>a</u> <u>photo</u> the <u>way</u> <u>you</u> <u>like</u> <u>it.</u> <br>"
+"&#43; It is very nice <u>effects</u> <u>simple</u> <u>to</u> <u>use</u> the <u>glossy</u> <u>effect</u> is <b>awesome</b> <br>"
+"&#43; <b>Awesome</b> <u>cool</u> <u>effect</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The photo quality is a litle poor but the <u>effects</u> are <b>awesome.</b> <br>"
+"- For some reason <u>filter</u> <u>effects</u> doesn't <b>work</b> <b>on</b> <b>photos.</b> <br>"
+"- The <u>effects</u> are <b>pointless</b> as the final picture does not have the chosen effect. <br>"
+"- Plus <u>effects</u> doesn't <b>work</b> <b>at</b> <b>all!</b> <br>"
+"- How about <u>ading</u> <u>effects</u> like the way snapchat <b>just</b> <b>aded</b> the <b>facial</b> <u>effects</u> <b>updated</b> in there's <b>?</b> <br>"
+"- The <u>effects</u> <b>does</b> <b>not</b> <b>change</b> <b>at</b> <b>all.</b> <br>"
+"</p>","volumn":26,"sentiment":.12,"value":3.37},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>new</u> <u>interface</u> (and the <u>creators</u> <u>response)</u> <b>showed</b> <b>me</b> where the manual options are for the camera <u>and</u> returned this app back to a 5 star app. <br>"
+"- The <u>new</u> <u>interface</u> (and the <u>creators</u> <u>response)</u> showed me where the manual options are for the camera <u>and</u> <b>returned</b> this <b>app</b> <b>back</b> <b>to</b> <b>a</b> <b>5</b> <b>star</b> <b>app.</b> <br>"
+"- now, after the latest update, the app <b>has</b> <b>become</b> almost useless because it became too slow reacting, cannot focus quickly, and the <u>interface</u> <b>has</b> <b>become</b> <b>incomfortable.</b> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"photos","name":"<h1>photos</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's really <b>great</b> and <u>capture</u> <u>photos</u> really well <br>"
+"&#43; <b>Best</b> <u>Photo</u> <u>quality</u> effects blockbuster camera <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>photo</u> <u>quality</u> is a litle <b>poor</b> but the effects are awesome. <br>"
+"- The <u>photos</u> <b>are</b> no longer <b>wide</b> <b>angle</b> and full screen - just unatractive boxy <u>photos.</u> <br>"
+"- The <u>photos</u> are no longer wide angle and full screen - just <b>unatractive</b> <u>boxy</u> <u>photos.</u> <br>"
+"- I love it, but the <u>video</u> <u>quality</u> is <b>lower</b> <b>than</b> my <b>default</b> <b>camera,</b> make it HD. <br>"
+"- I love it, but the <u>video</u> <u>quality</u> is <b>lower</b> <b>than</b> my <b>default</b> <b>camera,</b> make it HD. <br>"
+"- Filters are awesome but the <u>quality</u> <u>of</u> <u>image</u> is <b>not</b> that <b>good.</b> <br>"
+"</p>","volumn":8,"sentiment":-.38,"value":1.70},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Wonderful the <b>new</b> <u>version.</u> <br>"
+"&#43; the <u>new</u> <u>version</u> is <b>better</b> and easy., <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I really <b>hate</b> the <u>new</u> <u>version</u> <br>"
+"- <u>New</u> <u>version</u> <b>lost</b> <b>Capture</b> <b>by</b> <b>touchscreen</b> <b>function.</b> <br>"
+"- <u>latest</u> <u>version</u> <b>is</b> <b>d</b> worst. <br>"
+"- The update <u>version</u> is <b>so</b> <b>poor.</b> <br>"
+"</p>","volumn":9,"sentiment":-.22,"value":1.98},
]