var data_map_totalreviews=1054
var data_map_fromdate=20150228
var data_map_todate=20151102
var data_map_kakaotalk = [
{"keyword":"emojis","name":"<h1>emojis</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I really love this app because I am from Korea and the <u>emojis</u> are <b>super</b> <b>cute!</b> <br>"
+"&#43; The <u>emojis</u> are <b>so</b> <b>cute</b> and funny and it's a much better communications system than Snapchat! <br>"
+"&#43; But not only is the app itself great, the animations and <u>emojis</u> are <b>entertaining!</b> <br>"
+"&#43; I <b>love</b> how i can chat and free call my freinds and relatives and i <b>love</b> their <u>cute</u> <u>emojies.</u> <br>"
+"&#43; Plus their <u>exclusive</u> <u>emojis</u> <b>make</b> <b>it</b> <b>super</b> <b>fun.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":5,"sentiment":1.40,"value":3.01},
{"keyword":"themes","name":"<h1>themes</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The characters as well as the <u>themes</u> are <b>cute</b> and original. <br>"
+"&#43; I really <b>liked</b> the app as well as its <u>cute</u> <u>themes</u> <br>"
+"&#43; Hope you can creat more new cute free stickers and emotion and <u>theme</u> <b>too</b> <b>thank!</b> <br>"
+"&#43; Stickers and <u>theme</u> are <b>prety</b> <b>good.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.25,"value":2.64},
{"keyword":"fun","name":"<h1>fun</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> <b>like</b> this app because it's easy and <u>fun</u> <u>way</u> <u>of</u> <u>communicating</u> <u>in</u> <u>a</u> <u>group</u> <u>with</u> my <u>family</u> and <u>friends.</u> <br>"
+"&#43; It is <b>easy</b> <u>Fast</u> <u>Fun.</u> <br>"
+"&#43; Abd the sticker so <b>much</b> <u>fun</u> . <br>"
+"&#43; It is SO <b>much</b> <u>fun</u> <br>"
+"&#43; So <b>much</b> <u>fun</u> to stay connected. <br>"
+"&#43; As <u>of</u> that, kakaotalk messenger is the <b>most</b> <u>fun</u> and fantastic app out in the market. <br>"
+"&#43; Hardly <b>use</b> the stickers but they seem <u>fun</u> and the chat is <b>really</b> <b>easy</b> <b>to</b> <b>use.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":7,"sentiment":1.14,"value":3.09},
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Wonderful</b> <u>aplication.</u> <br>"
+"&#43; <b>Wonderful</b> <u>aplication.</u> <br>"
+"&#43; The <u>aplication</u> is <b>nice</b> but I hope we can still use the same account on different devices and contacts won't dissapear. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"features","name":"<h1>features</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Voice filter is really <b>funny</b> <u>feature</u> to love it. <br>"
+"&#43; <b>I</b> hope that the <u>saving</u> <u>features</u> are similar <b>to</b> Facebook which can save the messages forever and can <b>be</b> <b>opened</b> <b>to</b> <b>different</b> <b>devices.</b> <br>"
+"&#43; <b>I</b> hope that the <u>saving</u> <u>features</u> are similar <b>to</b> Facebook which can save the messages forever and can <b>be</b> <b>opened</b> <b>to</b> <b>different</b> <b>devices.</b> <br>"
+"&#43; I hope that the <u>saving</u> <u>features</u> are <b>similar</b> <b>to</b> <b>Facebook</b> <b>which</b> <b>can</b> <b>save</b> the <b>messages</b> forever and <b>can</b> be opened <b>to</b> different devices. <br>"
+"&#43; nobody <b>likes</b> that <u>feature,</u> you going to allow people to choose. <br>"
+"&#43; I <b>love</b> the <u>new</u> <u>feature</u> <br>"
+"&#43; Free calls and messaging with the cute stickers are very <b>nice</b> <u>features.</u> <br>"
+"&#43; Free calls and messaging with the cute stickers are very <b>nice</b> <u>features.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- That <u>feature</u> was <b>probably</b> my <b>favorite</b> because as someone who is indecisive, it gave me the option to alternate between different lock screens. <br>"
+"- <b>I</b> liked new stickers but <u>other</u> <u>features</u> <b>look</b> like wastes <b>to</b> <b>me.</b> <br>"
+"</p>","volumn":13,"sentiment":.77,"value":3.33},
{"keyword":"video","name":"<h1>video</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The sound and <u>video</u> <b>is</b> <b>first</b> <b>rate.</b> <br>"
+"&#43; <b>I</b> am always talk with friends with this app and clear voice talk and <u>video</u> <b>call</b> <b>even</b> <b>international</b> <b>too.</b> <br>"
+"&#43; <b>I</b> love the <b>app</b> really <b>I</b> use it to text my <b>friends</b> and everything but is there anyway you could <u>ad</u> <u>video</u> <b>calls</b> as <b>well</b> <b>that</b> <b>would</b> <b>make</b> the <b>app</b> <b>great</b> and very <b>helpful</b> <b>for</b> <b>me</b> and my <b>friend</b> to be able to <u>video</u> call each other. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":.75,"value":2.14},
{"keyword":"Line","name":"<h1>Line</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Line</u> <b>has</b> better stickers which are so cute and funny, and <b>most</b> <b>of</b> all <b>Free!</b> <br>"
+"&#43; <u>Line</u> is way <b>better</b> <b>by</b> <b>far</b> in all these regard. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":.75,"value":2.14},
{"keyword":"quality","name":"<h1>quality</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's free and the <u>call</u> <u>quality</u> is <b>great</b> <b>even</b> <b>on</b> <b>4G</b> <br>"
+"&#43; Really <b>good</b> <u>sound</u> <u>quality.</u> <br>"
+"&#43; Best <b>video</b> <u>quality</u> ever <br>"
+"&#43; I love the free calling, but I think the <u>quality</u> could <b>be</b> <b>increased</b> a <b>litle.</b> <br>"
+"&#43; The <u>call</u> <u>quality</u> was <b>good</b> <b>quite</b> satisfy <br>"
+"&#43; Call <u>quality</u> is <b>consistently</b> <b>good</b> <b>among</b> all <b>other</b> <b>similar</b> <b>aps.</b> <br>"
+"&#43; The <u>call</u> <u>quality</u> for me is <b>great,</b> and the filters are hilarious. <br>"
+"&#43; The <u>talking</u> <u>quality</u> is <b>aweful.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Seems like they're just copying and pasting their responses, and those low <u>quality</u> <u>answers</u> <b>even</b> <b>take</b> <b>a</b> few weeks. <br>"
+"- In early days of kakao the <u>picture</u> <u>quality</u> <b>was</b> <b>Orignal</b> mega <b>pixel</b> . <br>"
+"</p>","volumn":11,"sentiment":.55,"value":2.94},
{"keyword":"item-store","name":"<h1>item-store</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Beyond that <b>major</b> <b>issue,</b> the new <u>item</u> <u>store</u> <b>looks</b> <b>clean.</b> <br>"
+"&#43; <b>Cute</b> <u>items</u> also. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"free","name":"<h1>free</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Great</u> <u>free</u> <u>ap,</u> <u>sometimes</u> <u>difficult</u> <u>to</u> <u>answer</u> <u>voice</u> <u>calls</u> <u>but</u> the <u>call</u> <u>quality</u> is <b>excellent.</b> <br>"
+"&#43; Hope you can creat more new cute free stickers and <u>emotion</u> and theme <b>too</b> <b>thank!</b> <br>"
+"&#43; <b>Love</b> it, cute emojis and <u>free.</u> <br>"
+"&#43; I <b>love</b> the <u>free</u> <u>calling,</u> but I think the quality could be increased a litle. <br>"
+"&#43; thoughtful gifts <u>free</u> <b>calls</b> and <u>free</u> <u>texts</u> it's <u>good</u> <u>to</u> <u>talk</u> <u>to</u> <u>people</u> <u>rookery</u> don't <b>know</b> <b>just</b> <b>out</b> <b>boots</b> <u>top</u> <b>gear</b> <u>free</u> <b>calls</b> <u>free</u> <b>text</b> <b>images</b> <u>free</u> quotation without any drugs <br>"
+"&#43; <u>thoughtful</u> <u>gifts</u> <u>free</u> <u>calls</u> and <u>free</u> <b>texts</b> it's good to talk to people rookery don't <b>know</b> <b>just</b> <b>out</b> <b>boots</b> <b>top</b> <b>gear</b> <u>free</u> <u>calls</u> <u>free</u> <b>text</b> <b>images</b> <u>free</u> quotation without any drugs <br>"
+"&#43; <u>easy,</u> <u>easy</u> <u>free</u> <u>call,</u> emoticon were <b>cute.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Too</u> <u>few</u> <u>free</u> <u>emotics,</u> <b>check</b> the <b>FB</b> <b>messanger.</b> <br>"
+"- <u>F.</u> <u>Prety</u> <u>cool</u> <u>free</u> <u>texting</u> and all but it <b>takes</b> so <b>long</b> <b>to</b> <b>download</b> <br>"
+"- The <u>free</u> <u>call</u> is kind <b>of</b> <b>annoying.</b> <br>"
+"</p>","volumn":11,"sentiment":.45,"value":2.85},
{"keyword":"emoticons","name":"<h1>emoticons</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>emoticons</u> are <b>really</b> <b>cute</b> and the app works smoothly overall. <br>"
+"&#43; My daughter and <b>i</b> love it, <u>especially</u> the <u>emoticons</u> <b>always</b> <b>put</b> <b>a</b> <b>smile</b> <b>on</b> our <b>faces.</b> <br>"
+"&#43; Chats and calls work smoothly, mobile ver and PC ver are well synced, and the <u>basic</u> <u>emoticons</u> are <b>lovely,</b> <b>too.</b> <br>"
+"&#43; I <b>love</b> the <u>emoticons</u> and it's easy to use! <br>"
+"&#43; I really <b>love</b> the <u>emoticons</u> ??? <br>"
+"&#43; I <b>love</b> the <u>emoticons</u> and it's easy to use! <br>"
+"&#43; The <u>best</u> <u>emoticons</u> <u>ever,</u> <u>great</u> <u>design</u> and <u>great</u> <u>for</u> <b>keeping</b> <b>track</b> <b>of</b> <b>who</b> texted and <b>who</b> didn't:) <br>"
+"&#43; <u>Emoticons</u> are <b>very</b> <b>important</b> along <b>with</b> voice messages. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Before I updated to newest version I can buy the <u>emoticons</u> <b>using</b> <b>IDR</b> (Indonesian curency). <br>"
+"- <u>I</u> <b>love</b> <u>using</u> <u>kakaotalk</u> its <u>fun</u> <u>because</u> <u>of</u> the <u>emoticons</u> or <u>stickers,</u> but <u>i</u> have issues such as <u>i</u> can't use it for calls, we can't seem to understand each other in calls <u>using</u> <u>kakaotalk</u> and <u>i</u> hate it when <u>i</u> miss type the words and <u>i</u> can't cancel the text. <br>"
+"- But your <u>emoticon</u> are <b>too</b> <b>expensive.</b> <br>"
+"- The notification toons are adorable and the <u>emoticons</u> are <b>cool</b> <b>as</b> <b>hell</b> <br>"
+"</p>","volumn":17,"sentiment":.41,"value":3.24},
{"keyword":"Korean","name":"<h1>Korean</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> this <u>ap,</u> its the <u>best</u> <u>one</u> I have ever used but now that i got a new phone I'm not able to download the stickers and I really <b>love</b> those stickers :( it would also be nice if new <u>ones</u> were aded as well. <br>"
+"&#43; It's <b>super</b> <u>beautiful</u> <u>ap</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":5,"sentiment":.40,"value":2.01},
{"keyword":"stickers","name":"<h1>stickers</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I love the cute and bright design, and the <u>hilarious</u> <u>stickers</u> just <b>capture</b> <b>expressions</b> so <b>perfectly.</b> <br>"
+"&#43; The texting and <u>stickers</u> are really <b>good</b> <b>too,</b> <b>good</b> for couples :-). <br>"
+"&#43; The <u>stickers</u> are <b>so</b> <b>cute,</b> its nice to voice or video call, and when you are oit of the country you can still text and call. <br>"
+"&#43; the <u>stickers</u> are <b>cute</b> <b>too!</b> <br>"
+"&#43; <u>Stickers</u> and theme are <b>prety</b> <b>good.</b> <br>"
+"&#43; The <u>stickers</u> are really nice and there better <b>then</b> <b>Skype</b> <br>"
+"&#43; The <u>stickers</u> are <b>really</b> <b>nice</b> and there better then Skype <br>"
+"&#43; I <b>love</b> this ap, its the best one I have ever used but now that i got a new phone I'm not able to download the <u>stickers</u> and I really <b>love</b> those <u>stickers</u> :( it would also be nice if new ones were aded as well. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Cute</b> <u>stickers,</u> fast messaging. <br>"
+"- The <u>stickers</u> are <b>not</b> <b>as</b> <b>much</b> <b>as</b> <b>line.</b> <br>"
+"- <b>atractive</b> <u>sticker</u> and emo. <br>"
+"- I <b>liked</b> <u>new</u> <u>stickers</u> but other features look like wastes to me. <br>"
+"- After the update I can't longer use voice note, <u>stickers</u> <b>log</b> <b>several</b> <b>times.</b> <br>"
+"</p>","volumn":18,"sentiment":.39,"value":3.28},
{"keyword":"call","name":"<h1>call</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's <b>so</b> cool, easy and fun i really love the animation and the <u>International</u> free <u>call</u> is <b>so</b> <b>clear</b> and you can really talk as long as you want and text the person you are talking to at the same time., it's really ideal for do some classes with someone overseas. <br>"
+"&#43; <u>Call</u> is so <b>much</b> <b>nice</b> <b>than</b> the <b>other</b> <b>app</b> . <br>"
+"&#43; The stickers kakao friends are exceptionally cute, the calls between the U.s and Morocco work perfectly fine , but <u>video</u> <u>calling</u> is still <b>impossible</b> <b>even</b> <b>with</b> the <b>updates.</b> <br>"
+"&#43; The stickers kakao friends are exceptionally cute, the <u>calls</u> between the U.s and Morocco <b>work</b> perfectly <b>fine</b> <b>,</b> but video calling is still impossible even with the updates. <br>"
+"&#43; And the <u>calls</u> <b>absolutely</b> <b>do</b> <b>not</b> <b>work</b> <b>with</b> <b>Bluetooth.</b> <br>"
+"&#43; <b>Clear</b> audio <u>call</u> and <u>good</u> for chating. <br>"
+"&#43; I love how i can chat and <b>free</b> <u>call</u> my freinds and relatives and i love their cute emojies. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>call</u> <b>apears</b> <b>to</b> <b>be</b> <b>connected</b> but it is not. <br>"
+"- It needs much better call quality- <u>80%</u> <u>of</u> the <u>calls</u> <b>are</b> <b>garbage!</b> <br>"
+"- Both <u>ends</u> <u>of</u> the <u>call</u> <u>atempt</u> <b>have</b> <b>downloaded</b> the <b>latest</b> <b>version,</b> <b>yet</b> the <b>same</b> <b>error</b> <b>message</b> as before the update apears to both users (error number is 6-1007, saying the person you're trying to reach does not <b>have</b> the <b>latest</b> <b>version</b> and must update in order to call). <br>"
+"- Voice <u>calls</u> are good but <u>video</u> <u>call</u> <b>is</b> the <b>worst</b> no <b>voice</b> no <u>video</u> on using it. <br>"
+"</p>","volumn":11,"sentiment":.36,"value":2.76},
{"keyword":"voice","name":"<h1>voice</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Wonderful ap, very fun to use and I <b>love</b> the <u>voice</u> <u>filters,</u> haha! <br>"
+"&#43; This is a great Ap and the <u>voice</u> <u>quality</u> is <b>superb.</b> <br>"
+"&#43; <u>Voice</u> <u>filter</u> <b>is</b> really <b>funny</b> <b>feature</b> to love it. <br>"
+"&#43; It is very useful chating to friends and family even let's you do <u>voice</u> calls??but how can you do video <b>calls?</b> <br>"
+"&#43; <b>Excellent</b> <u>voice</u> call clarity. <br>"
+"&#43; <u>Voice</u> <b>calls</b> <b>between</b> <b>Korea</b> and U.S. are excellent. <br>"
+"&#43; <b>I</b> am always <u>talk</u> with friends with this app and clear <u>voice</u> <u>talk</u> and video <b>call</b> <b>even</b> <b>international</b> <b>too.</b> <br>"
+"&#43; <u>Voice</u> <b>calls</b> <b>between</b> <b>Korea</b> and U.S. are excellent. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Don't <b>like</b> the cat and dog's <u>voices</u> now. <br>"
+"- <u>Voice</u> <u>calls</u> are <b>good</b> but video call is the worst no voice no video on using it. <br>"
+"- Voice calls are good but video call is the <b>worst</b> no <u>voice</u> no video on using it. <br>"
+"- she hear my <u>voice</u> is <b>too</b> <b>late.</b> <br>"
+"- <u>Voice</u> is <b>not</b> <b>clear</b> <b>on</b> <b>2g</b> <b>edge</b> <b>data</b> <b>network</b> <b>can</b> <b>update</b> <b>for</b> <b>suport</b> <b>2g</b> <b>Edge</b> <br>"
+"- My favorite future is probably <u>voice</u> <b>recording</b> <u>cause</u> on most days I'm just way too lazy to type. <br>"
+"- After new update <u>voice</u> <u>call</u> is <b>not</b> <b>clear</b> <b>on</b> 2G Edge and very <b>noise</b> <u>call</u> please improve <u>call</u> quality <b>on</b> 2G Edge <br>"
+"- The <u>voice</u> is <b>so</b> <b>low</b> i can't barely listen ?? to what people say <br>"
+"</p>","volumn":22,"sentiment":.27,"value":3.36},
{"keyword":"chat-bubl","name":"<h1>chat-bubl</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The new <u>video</u> <u>chat</u> <u>option</u> has amazing <u>video</u> and <b>call</b> <b>quality.</b> <br>"
+"&#43; The new <u>video</u> <u>chat</u> <u>option</u> <b>has</b> <b>amazing</b> <u>video</u> and call quality. <br>"
+"&#43; Hardly <b>use</b> the stickers but they seem fun and the <u>chat</u> is <b>really</b> <b>easy</b> <b>to</b> <b>use.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The new <u>chat</u> <u>buble</u> is <b>not</b> <b>acceptable.</b> <br>"
+"- I don't <b>like</b> the <u>new</u> <u>chat</u> <u>bubles.</u> <br>"
+"- The <u>administrator</u> <u>of</u> the <u>group</u> <u>chat</u> can't <b>kick</b> out the <b>member</b> <b>who</b> <b>make</b> an <b>annoying</b> <u>chat</u> that <b>can</b> <b>make</b> the other people uncomfortable. <br>"
+"</p>","volumn":9,"sentiment":.22,"value":2.42},
{"keyword":"messenger","name":"<h1>messenger</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Kakao is a very <b>reliable</b> <u>messenger.</u> <br>"
+"&#43; This is very good way better than kik and <u>some</u> <u>of</u> <b>the</b> <u>other</u> <u>messengers</u> <b>has</b> all <b>the</b> <b>media</b> <b>options</b> you could want. <br>"
+"&#43; <b>Great</b> <u>messenger.</u> <br>"
+"&#43; <b>Fantastic</b> <u>Messenger.</u> <br>"
+"&#43; <b>Nice</b> <u>messenger.</u> <br>"
+"&#43; I <b>love</b> <u>using</u> this <u>messenger</u> <u>but</u> <u>i</u> purchased one of the emoticons (Ben - You answer!) <br>"
+"&#43; Kakao is a very <b>reliable</b> <u>messenger.</u> <br>"
+"&#43; Nice and <b>fast</b> <u>messenger.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Wechat,</u> <u>whatsap</u> or even <u>fb</u> <u>messenger</u> <b>gave</b> their user <b>cute</b> <b>free</b> <b>stickers</b> all year round.why couldn't kakaotalk? <br>"
+"- Wechat, <u>whatsap</u> or even fb messenger <b>gave</b> their user <b>cute</b> <b>free</b> <b>stickers</b> all year round.why couldn't kakaotalk? <br>"
+"- Wechat, whatsap or <u>even</u> <u>fb</u> <u>messenger</u> <b>gave</b> their user <b>cute</b> <b>free</b> <b>stickers</b> all year round.why couldn't kakaotalk? <br>"
+"- But as is, it's still my <b>favorite</b> <u>messenger.</u> <br>"
+"- Yes I know it's an old <u>messenger</u> but I think this is the <b>coolest</b> <u>messenger</u> ever thanks for this ap <br>"
+"- Yes I know it's an <b>old</b> <u>messenger</u> but I think this is the coolest <u>messenger</u> ever thanks for this ap <br>"
+"</p>","volumn":16,"sentiment":.19,"value":2.96},
{"keyword":"dl","name":"<h1>dl</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>pressin</u> <u>yellow</u> <u>dl</u> <u>buton</u> <u>nothin</u> <u>hapens</u> and <u>dl</u> butn just <b>pops</b> up <b>again.</b> <br>"
+"- pressin yellow <u>dl</u> buton nothin hapens and <u>dl</u> <u>butn</u> just <b>pops</b> up <b>again.</b> <br>"
+"- Where's the <b>seting</b> <u>buton,</u> it's gone. <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"doe-lag","name":"<h1>doe-lag</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> will download this app <u>,</u> because <u>i</u> see this on Love Sick the Series and <u>I</u> <b>love</b> <u>August</u> so <u>much</u> <u>:D</u> <u><3</u> <u><3</u> <u>xoxo</u> <u>Pete</u> <u>=)</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>like</b> <u>much</u> <u>kakao</u> <u>but</u> <u>i</u> <b>like</b> most beautiful emotion angry depressed hated emotion <b>like</b> that and stop send game purhases cause I'm poor . <br>"
+"- I <b>like</b> <u>much</u> <u>kakao</u> but i <b>like</b> most beautiful emotion angry depressed hated emotion <b>like</b> that and stop send me game with Porsches. <br>"
+"- <u>I</u> <u>like</u> the <u>new</u> <u>look</u> <u>of</u> <u>it</u> and <u>it</u> doesn't <u>take</u> <u>up</u> <u>to</u> <u>much</u> <u>space</u> <u>on</u> my <u>phone</u> <u>like</u> <u>other</u> <u>chat</u> <u>aps</u> and <u>it</u> doesn't <u>lag</u> also works and opens fast <br>"
+"- <u>I</u> <u>like</u> the <u>new</u> <u>look</u> <u>of</u> <u>it</u> and <u>it</u> doesn't <u>take</u> <u>up</u> <u>to</u> <u>much</u> <u>space</u> <u>on</u> my <u>phone</u> <u>like</u> <u>other</u> <u>chat</u> <u>aps</u> and <u>it</u> doesn't <u>lag</u> also works and opens fast <br>"
+"- <u>love</u> <u>kakao,</u> <u>but</u> <u>lately</u> <u>they</u> <b>have</b> <b>goten</b> a <b>lot</b> <b>of</b> <b>ugly</b> <b>stickers.</b> <br>"
+"- It's fast app for messages and I <b>likes</b> <u>sticker</u> <u>on</u> <u>kakao.</u> <br>"
+"- <u>One</u> <u>of</u> the <u>features</u> <u>in</u> the <u>Kakao</u> <u>Lab</u> <b>was</b> the lock screen notification <b>cover.</b> <br>"
+"</p>","volumn":8,"sentiment":-.88,"value":1.20},
{"keyword":"custom-servic","name":"<h1>custom-servic</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Fast,</b> <b>easy</b> <b>to</b> <b>access,</b> <u>wonderful</u> <u>service</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Their <u>customer</u> <u>services</u> is <b>extremely</b> <b>poor.</b> <br>"
+"- <u>Customer</u> <u>Service</u> is <b>terible.</b> <br>"
+"- <u>Customer</u> <u>Service</u> is <b>terible.</b> <br>"
+"- <u>Customer</u> <u>Service</u> is <b>terible.</b> <br>"
+"- <u>Customer</u> <u>Service</u> is <b>terible.</b> <br>"
+"- <u>Customer</u> <u>Service</u> is <b>terible.</b> <br>"
+"- Stupid and <b>bad</b> <u>service.</u> <br>"
+"</p>","volumn":8,"sentiment":-.75,"value":1.33},
{"keyword":"phone","name":"<h1>phone</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The voice <b>call</b> feature is exceptional: the audio is much more clear than <u>regular</u> <u>phone</u> and Kakao doesn't <b>keep</b> <b>droping</b> the <b>call</b> (problem <b>I</b> <b>had</b> <b>with</b> Viber). <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The app is great but cannot be moved to the sd card and my <u>phone</u> <b>has</b> a <b>low</b> <b>memory</b> <b>space.</b> <br>"
+"- My <u>texting</u> <u>on</u> my <u>phone</u> is <b>unbelievably</b> <b>slow.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>new</u> <u>version.</u> <br>"
+"&#43; Chats and calls work smoothly, mobile <u>ver</u> and <u>PC</u> <u>ver</u> are <b>well</b> <b>synced,</b> and the basic emoticons are lovely, too. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>new</u> <u>version</u> <b>looks</b> <b>bad</b> <b>,</b> <b>I</b> really cannot get the concept of that <u>new</u> look <b>!</b> <br>"
+"- It's galaxy note 3 and i hv the <b>newest</b> <u>version</u> <br>"
+"- and <b>l</b> <b>am</b> <b>receiving</b> <b>message</b> <b>box</b> <b>on</b> the <b>screen</b> saying this aplication is affecting the speed of your mobile, etc <b>l</b> need solution or better kakao <u>version</u> from Galaxy Aps. <br>"
+"</p>","volumn":6,"sentiment":-.33,"value":1.46},
{"keyword":"messaging","name":"<h1>messaging</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I like to xperience and <b>enjoy</b> <u>it</u> <u>message</u> <u>with</u> <u>stickers</u> <u>great!</u> <br>"
+"&#43; <u>Messages</u> <b>delivers</b> <b>quickly.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Message</u> <b>sends</b> <b>out</b> too <b>slow!</b> <br>"
+"- <u>Hearing</u> <u>voice</u> or <u>messaging</u> <u>them</u> <b>is</b> <b>not</b> <b>enough</b> <b>tho.</b> <br>"
+"- Slow sending <u>message</u> when <u>use</u> mobile <u>data</u> it's <u>take</u> more than <u>20s</u> if <u>continue</u> <u>chat</u> <u>message</u> sending <u>is</u> <u>normal</u> but if <u>you</u> <u>swap</u> <u>it'</u> <b>start</b> <b>to</b> <b>slow</b> again <br>"
+"- <u>Hearing</u> <u>voice</u> or <u>messaging</u> <u>them</u> <b>is</b> <b>not</b> <b>enough</b> <b>tho.</b> <br>"
+"</p>","volumn":7,"sentiment":-.14,"value":1.80},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Update</u> too <b>no</b> <b>at</b> <b>manage</b> <b>friend</b> another <b>ok!</b> <br>"
+"&#43; The <b>new</b> <u>updated</u> <b>just</b> <b>has</b> <b>improved</b> <b>everything.I</b> <b>like</b> the <b>new</b> <b>KakaoTalk</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>updates</u> are quite <b>annoying</b> <b>though.</b> <br>"
+"- But the <u>updates</u> are <b>not</b> <b>so</b> <b>good</b> <b>during</b> this <b>time.</b> <br>"
+"- mine is <b>a</b> Small ART [interpreter mode] <b>device</b> and the <u>post</u> <u>5.1.0</u> <u>updates</u> <b>are</b> <b>not</b> <b>working</b> <b>in</b> my <b>device.</b> <br>"
+"</p>","volumn":7,"sentiment":-.14,"value":1.80},
{"keyword":"design","name":"<h1>design</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> <b>love</b> the <u>cute</u> and <u>bright</u> <u>design,</u> and the hilarious stickers just capture expressions so perfectly. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>hate</b> the <u>new</u> <u>design!</u> <br>"
+"- <u>Some</u> <u>of</u> your <u>aplication</u> <u>design</u> is <b>almost</b> <b>similar</b> <b>to</b> <b>LINE.</b> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"notification","name":"<h1>notification</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>Notification</u> <u>Cover</u> is <b>great!</b> <br>"
+"&#43; I <b>love</b> the <u>notification</u> <u>cover</u> very much <br>"
+"&#43; The <u>notification</u> <u>screen</u> is <b>nice.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>like</b> the <u>notification</u> <u>cover</u> but the camera shortcut is stoped working for me after the update. <br>"
+"- <b>annoying</b> <u>notification</u> from developer. <br>"
+"- The <u>notification</u> <u>toons</u> are <b>adorable</b> and the emoticons are cool as hell <br>"
+"- I am an Android user and I <b>love</b> the <u>notification</u> <u>panel</u> by Kakao Lab. <br>"
+"</p>","volumn":9,"sentiment":.00,"value":2.20},
]