var data_map_totalreviews=1189
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_imdb = [
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>aplication</u> is <b>really</b> <b>nice</b> and good. <br>"
+"&#43; I <b>have</b> always <b>liked</b> the <u>aplication,</u> however the video player is not at all smooth, maximum resolution 720p is more than sufficient. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Aplication</u> is <b>slow</b> and lagy <b>as</b> <b>slowpoke</b> even when phone is connected via hi-speed wi-fi connection. <br>"
+"</p>","volumn":3,"sentiment":.67,"value":1.77},
{"keyword":"great-wai","name":"<h1>great-wai</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; A <u>great</u> <u>way</u> <b>to</b> <b>relive</b> the <b>older</b> <b>movies.</b> <br>"
+"&#43; An <u>easy</u> and <u>fun</u> <u>way</u> <b>to</b> <b>look</b> up any <b>media</b> that <b>interests</b> <b>you.</b> <br>"
+"&#43; <u>Great</u> <u>way</u> to watch movie trailers and <b>look</b> up <b>actors.</b> <br>"
+"&#43; <u>Great</u> <u>way</u> <b>to</b> <b>watch</b> <b>movie</b> <b>trailers</b> and look up actors. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":6,"sentiment":.67,"value":2.46},
{"keyword":"resource","name":"<h1>resource</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Excellent</b> <u>resource.</u> <br>"
+"&#43; An <b>invaluable</b> <u>resource.</u> <br>"
+"&#43; <b>Good</b> <u>resource</u> for parents. <br>"
+"&#43; <b>Great</b> <u>resources</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Invaluable</b> <u>resource;</u> I use it multiple times a week. <br>"
+"</p>","volumn":5,"sentiment":.60,"value":2.21},
{"keyword":"movies","name":"<h1>movies</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <b>best</b> <u>movies</u> and etc source <br>"
+"&#43; <u>Foreign</u> <u>movies</u> <b>are</b> <b>listed</b> as <b>well.</b> <br>"
+"&#43; I am a <b>big</b> <b>big</b> <u>movie</u> <u>fan</u> and tv <u>fan</u> I love being able to get updates about the actors that I follow. <br>"
+"&#43; <b>Great</b> <u>movie</u> and television app. <br>"
+"&#43; I <b>love</b> <u>watching</u> <u>old</u> <u>movies</u> and I use this app to look up information regarding the film as well-known as the actors. <br>"
+"&#43; It's a very <b>great</b> <u>movies</u> <u>archive,</u> but the UI is just so discouraging to even use the ap <br>"
+"&#43; The <b>best</b> <u>movies</u> and etc source <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Basic</u> <u>movie</u> <u>infos</u> <b>are</b> now <b>better</b> <b>served</b> <b>through</b> <b>a</b> <b>simple</b> <b>Google</b> Search. <br>"
+"- <b>I</b> wishlist items <b>should</b> save the date when the <u>movie</u> was aded and <b>should</b> <b>allow</b> <b>to</b> <b>enter</b> the <b>discovered</b> <b>way</b> (sugested <b>by,</b> <b>saw</b> <b>trailer,</b> <b>etc)</b> <br>"
+"</p>","volumn":9,"sentiment":.56,"value":2.75},
{"keyword":"android-develop-crew","name":"<h1>android-develop-crew</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>I</b> sugest the <u>android</u> <u>development</u> <u>crew</u> take <b>a</b> look at the iOS <u>crews</u> work and <b>ask</b> <b>for</b> some <b>help.</b> <br>"
+"&#43; <b>I</b> sugest the <u>android</u> <u>development</u> <u>crew</u> take <b>a</b> look at the iOS <u>crews</u> work and <b>ask</b> <b>for</b> some <b>help.</b> <br>"
+"&#43; I sugest the <u>android</u> <u>development</u> <u>crew</u> <b>take</b> a <b>look</b> <b>at</b> the <b>iOS</b> <u>crews</u> <b>work</b> and ask for some help. <br>"
+"&#43; <b>I</b> sugest the <u>android</u> <u>development</u> <u>crew</u> take <b>a</b> look at the iOS <u>crews</u> work and <b>ask</b> <b>for</b> some <b>help.</b> <br>"
+"&#43; <b>I</b> sugest the <u>android</u> <u>development</u> <u>crew</u> take <b>a</b> look at the iOS <u>crews</u> work and <b>ask</b> <b>for</b> some <b>help.</b> <br>"
+"&#43; I sugest the <u>android</u> <u>development</u> <u>crew</u> <b>take</b> a <b>look</b> <b>at</b> the <b>iOS</b> <u>crews</u> <b>work</b> and ask for some help. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Outdated / bad UI, no Chromecast suport, barely any <b>useful</b> <u>development</u> recently. <br>"
+"</p>","volumn":8,"sentiment":.50,"value":2.58},
{"keyword":"DATA","name":"<h1>DATA</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Really <b>handy</b> <u>good</u> <u>work</u> <br>"
+"&#43; <u>Good</u> <u>movie</u> <b>reviews</b> <b>database</b> <br>"
+"&#43; Available <u>data</u> <u>connections</u> <b>can</b> <b>run</b> <b>360</b> <b>resolution</b> <b>videos</b> <b>easily.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> also <b>like</b> <u>to</u> <u>click</u> <u>FORCE</u> <u>STOP</u> and <u>CLEAR</u> <u>CACHE</u> and <u>DATA</u> <u>for</u> <u>good</u> <u>measure.</u> <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"Google","name":"<h1>Google</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Horible</b> <u>google</u> <u>movie</u> tube search up first one better and free and new <u>movies</u> <br>"
+"&#43; Besides the <b>streaming,</b> its convenient, but <u>google</u> <b>can</b> <b>help</b> just as <b>well,</b> and it is actually faster than this app. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> prefer the Full <u>Web</u> <u>Site,</u> because <u>one</u> can't <u>use</u> <u>Find</u> On This <u>Page,</u> <u>nor</u> <u>can</u> <u>one</u> <u>HighLight</u> and <u>Copy</u> <u>a</u> <u>Name,</u> <u>Word</u> <u>nor</u> <u>a</u> <u>Phrase,</u> <u>nor</u> <u>have</u> <u>Google</u> <b>Search</b> <b>for</b> the <b>HighLighted</b> <b>Section.</b> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"tool","name":"<h1>tool</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The most <b>important</b> <u>tool</u> for the trade. <br>"
+"&#43; It's a <b>wonderful</b> <u>tool</u> with so many useful parts. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Indispensable</b> <u>tool</u> for Movie/TV buffs! <br>"
+"</p>","volumn":4,"sentiment":.25,"value":1.64},
{"keyword":"information","name":"<h1>information</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Excellent</b> <u>information</u> and pictures <u>of</u> actor and <u>actresses.</u> <br>"
+"&#43; Absolutely the <b>best</b> <u>source</u> <u>of</u> movie and/or TV <u>information.</u> <br>"
+"&#43; <b>Great</b> <u>source</u> <u>of</u> <u>information!</u> <br>"
+"&#43; <u>Fantastic</u> <u>source</u> <u>of</u> <u>movie</u> <u>information</u> and the <u>trivia</u> is <b>aways</b> <b>interesting.</b> <br>"
+"&#43; Always <b>good</b> and <u>reliable</u> <u>information!</u> <br>"
+"&#43; <b>Great</b> <u>information</u> Ap. <br>"
+"&#43; Always <b>good</b> and <u>reliable</u> <u>information.</u> <br>"
+"&#43; <b>Great</b> <u>information</u> Ap. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Great</b> but <u>less</u> <u>information</u> than the iOS version. <br>"
+"- The <u>information</u> is <b>good</b> but in the end it is a shoping site so the inclusion of advertising on a site that in its self is an advert for Films TV and Cinema times is ading adverts on adverts. <br>"
+"- Otherwise, the app is prety similar to the web version, but a <u>litle</u> <u>less</u> <b>easier</b> to navigate. <br>"
+"- <b>Great</b> but <u>less</u> <u>information</u> than the iOS version. <br>"
+"- <b>Great</b> but <u>less</u> <u>information</u> than the iOS version. <br>"
+"- <b>Great</b> but <u>less</u> <u>information</u> than the iOS version. <br>"
+"- <b>Have</b> a <b>lots</b> <u>information</u> but its very heavy when playing trailer, i can play HQ clip from youtube but it always buffering in here, don't know because the ads or what <br>"
+"- <b>Great</b> but <u>less</u> <u>information</u> than the iOS version. <br>"
+"</p>","volumn":26,"sentiment":.23,"value":3.49},
{"keyword":"messag-board","name":"<h1>messag-board</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Also,</b> <u>re:</u> the <u>message</u> <u>boards,</u> if <u>you</u> <u>dare</u> <u>to</u> <u>share</u> <u>a</u> thought about <u>a</u> film on <u>you</u> will <b>be</b> <b>agravated</b> contradicted and insulted. <br>"
+"&#43; <u>Message</u> <u>Boards</u> <b>are</b> <b>finally</b> <b>fixed!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The trailers eat too much data, the <u>message</u> <u>boards</u> are <b>abusive,</b> trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The trailers eat too much data, the <u>message</u> <u>boards</u> are <b>abusive,</b> trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The trailers eat too much data, the <u>message</u> <u>boards</u> are <b>abusive,</b> trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The trailers eat too much data, the <u>message</u> <u>boards</u> are <b>abusive,</b> trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The <u>Message</u> <u>Boards</u> are <b>too</b> <b>small.</b> <br>"
+"- Following the latest update, the app now display larger thumbnail images but the <u>message</u> <u>boards</u> <b>refuse</b> <b>to</b> <b>load.</b> <br>"
+"- The <u>message</u> <u>boards</u> <u>section</u> <b>is</b> just a <b>crapy</b> web <b>view.</b> <br>"
+"- The trailers eat too much data, the <u>message</u> <u>boards</u> are <b>abusive,</b> trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is very good. <br>"
+"</p>","volumn":10,"sentiment":-1.00,"value":1.30},
{"keyword":"photo-viewer","name":"<h1>photo-viewer</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>New</u> <u>photo</u> <u>viewer</u> <b>looks</b> <b>better</b> but doesn't work <b>better.</b> <br>"
+"- <u>New</u> <u>photo</u> <u>viewer</u> looks <b>better</b> but doesn't <b>work</b> <b>better.</b> <br>"
+"- <u>New</u> <u>photo</u> <u>viewer</u> <b>looks</b> <b>better</b> but doesn't work <b>better.</b> <br>"
+"- <u>New</u> <u>photo</u> <u>viewer</u> looks <b>better</b> but doesn't <b>work</b> <b>better.</b> <br>"
+"</p>","volumn":4,"sentiment":-1.00,"value":.39},
{"keyword":"contributions","name":"<h1>contributions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's ok for identifying most films and actors, but the users' <u>contributions</u> <b>are</b> <b>childish</b> <b>giberish.</b> <br>"
+"- It's ok for identifying most films and actors, but the users' <u>contributions</u> <b>are</b> <b>childish</b> <b>giberish.</b> <br>"
+"- It's ok for identifying most films and actors, but the users' <u>contributions</u> <b>are</b> <b>childish</b> <b>giberish.</b> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"giberish","name":"<h1>giberish</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's ok for identifying most films and actors, but the users' contributions are <b>childish</b> <u>giberish.</u> <br>"
+"- It's ok for identifying most films and actors, but the users' contributions are <b>childish</b> <u>giberish.</u> <br>"
+"- It's ok for identifying most films and actors, but the users' contributions are <b>childish</b> <u>giberish.</u> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>user</u> <u>interface</u> is <b>absolutely</b> <b>obsolete</b> hence takes away the experience from the actual functionality of the service/aplication, it seems quite clear a redesign is needed on here. <br>"
+"- <b>Bad</b> <u>interface.</u> <br>"
+"- <u>Interface</u> is <b>decent</b> <b>enough</b> but where is Imdb Top 250. <br>"
+"- I <b>like</b> the <u>new</u> <u>interface</u> <u>for</u> <u>viewing</u> <u>photos,</u> but the app slows to a crawl (super lagy) when scrolling through thumbnails and especially when swiping through full <u>photos.</u> <br>"
+"- But, <u>user</u> <u>reviews</u> <b>are</b> <b>really</b> <b>biased.</b> <br>"
+"- <u>User</u> <u>interface</u> and functionality <b>is</b> <b>falling</b> <b>behind.</b> <br>"
+"- <u>User</u> <u>interface</u> and functionality <b>is</b> <b>falling</b> <b>behind.</b> <br>"
+"- It is <b>not</b> <u>user</u> <b>friendly</b> <br>"
+"</p>","volumn":9,"sentiment":-.89,"value":1.31},
{"keyword":"layout","name":"<h1>layout</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Layout</u> is <b>too</b> <b>messy.</b> <br>"
+"- The <u>layout</u> is <b>nice</b> but I wish the app had that feature <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"speed","name":"<h1>speed</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- My <u>network</u> <u>speed</u> <b>is</b> a <b>measly</b> ~2mbit/s, but other aps from Google, etc, show that there are ways around it. <br>"
+"- The UI is really clutered, while the <u>speed</u> is <b>incredibly</b> <b>slow.</b> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>ios</u> <u>version.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Web</u> <u>version</u> as an app but the message board area is <b>awful.</b> <br>"
+"- <u>:@</u> The <u>previous</u> <u>version</u> was <b>much</b> <b>better!</b> <br>"
+"- Less <b>infomation</b> <b>than</b> <b>what</b> the <u>iOS</u> <u>version</u> <b>offers.</b> <br>"
+"- <u>:@</u> The <u>previous</u> <u>version</u> was <b>much</b> <b>better!</b> <br>"
+"- Less <b>infomation</b> <b>than</b> <b>what</b> the <u>iOS</u> <u>version</u> <b>offers.</b> <br>"
+"</p>","volumn":8,"sentiment":-.62,"value":1.45},
{"keyword":"trailers","name":"<h1>trailers</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Trailers</u> <b>use</b> <b>to</b> <b>play</b> smoothly, now <b>they</b> constantly <b>buffer!</b> <br>"
+"&#43; The <u>trailers</u> don't always run smoothly, and <b>devour</b> a <b>TON</b> <b>of</b> <b>data,</b> <b>regardless</b> <b>of</b> <b>seting.</b> <br>"
+"&#43; The <u>trailers</u> don't always <b>run</b> <b>smoothly,</b> and devour <b>a</b> TON of data, regardless of seting. <br>"
+"&#43; It was really great but since the new update the <u>trailers</u> and videos won't <b>play</b> <b>anymore.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>trailers</u> <b>eat</b> too <b>much</b> <b>data,</b> the message boards are abusive, trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The <u>trailers</u> <b>eat</b> too <b>much</b> <b>data,</b> the message boards are abusive, trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The <u>trailers</u> <b>eat</b> too <b>much</b> <b>data,</b> the message boards are abusive, trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The <u>trailers</u> <b>eat</b> too <b>much</b> <b>data,</b> the message boards are abusive, trivia is more like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- <u>Trailers</u> play and <b>then</b> <b>pause</b> <b>to</b> <b>buffer</b> and <b>then</b> play and <b>pause</b> <b>to</b> <b>buffer</b> again. <br>"
+"- <u>Trailers</u> are only <b>720p.</b> <br>"
+"- <u>Trailers</u> don't <b>play</b> <b>properly</b> or are slow <br>"
+"- The <u>movie</u> <u>trailers</u> doesn't <b>work</b> <b>at</b> <b>all</b> <b>?</b> <br>"
+"</p>","volumn":26,"sentiment":-.62,"value":2.64},
{"keyword":"loading","name":"<h1>loading</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- and now the <u>loading</u> is <b>too</b> <b>slow</b> until it won't work. <br>"
+"- It was <b>slow</b> <u>loading,</u> then a update. <br>"
+"- <u>Load</u> too <b>slow</b> <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"UI","name":"<h1>UI</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's <b>a</b> very great movies archive, but the <u>UI</u> <b>is</b> just <b>so</b> <b>discouraging</b> <b>to</b> even <b>use</b> the <b>ap</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Outdated / <b>bad</b> <u>UI,</u> no Chromecast suport, barely any useful development recently. <br>"
+"- <b>Awful</b> <u>UI.</u> <br>"
+"- <u>Curent</u> <u>UI</u> is <b>ancient.</b> <br>"
+"- The <u>UI</u> <b>is</b> <b>really</b> <b>clutered,</b> while the speed <b>is</b> incredibly slow. <br>"
+"</p>","volumn":7,"sentiment":-.57,"value":1.37},
{"keyword":"trivia","name":"<h1>trivia</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> find at least <u>99</u> <u>percent</u> <u>of</u> the <u>trivia</u> and <u>other</u> <u>things</u> are <b>very</b> <b>interesting</b> <br>"
+"&#43; I particularly <b>love</b> the <u>trivia</u> <u>associated</u> <u>with</u> each <u>movie.</u> <br>"
+"&#43; Really <b>enjoy</b> the <u>trivia</u> <u>section.</u> <br>"
+"&#43; The <u>trivia</u> is <b>interesting</b> and fun to read. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The trailers eat too much data, the message boards are abusive, <u>trivia</u> is <b>more</b> like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The trailers eat too much data, the message boards are abusive, <u>trivia</u> is <b>more</b> like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The trailers eat too much data, the message boards are abusive, <u>trivia</u> is <b>more</b> like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The trailers eat too much data, the message boards are abusive, <u>trivia</u> is <b>more</b> like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is satisfactory. <br>"
+"- The trailers eat too much data, the message boards are abusive, <u>trivia</u> is <b>more</b> like rumour, and the parental guidance descriptions tend to be somewhat exagerated, but for basics such as cast and pictures it is very good. <br>"
+"- For any film lover, release dates, trailers and <u>trivia</u> are <b>all</b> <b>here.</b> <br>"
+"</p>","volumn":11,"sentiment":-.55,"value":1.85},
{"keyword":"ads","name":"<h1>ads</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I love the ap, keep up the good work, the <u>ads</u> are a litle <b>iritating</b> <b>though.</b> <br>"
+"&#43; And the <u>ads</u> along the botom <b>are</b> <b>always</b> <b>covering</b> up <b>content</b> <b>causing</b> <b>a</b> <b>lot</b> <b>accidental</b> <b>clicks.</b> <br>"
+"&#43; <u>Ads</u> <b>suck</b> as <b>well.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Also <b>disable</b> <u>ads.</u> <br>"
+"- and all the <b>stupid</b> <u>ads</u> that are increasing in number every day. <br>"
+"- It is very useful but the <u>ads</u> <b>make</b> the <b>app</b> <b>look</b> <b>second</b> <b>grade.</b> <br>"
+"- Too <b>many</b> <u>Ads</u> :(. <br>"
+"- But the <u>ads</u> <b>are</b> <b>geting</b> <b>longer</b> when watching <b>a</b> trailer. <br>"
+"- Too <b>many</b> <u>Ads</u> :(. <br>"
+"- It is not very responsive, the <u>ads</u> are <b>obtrusive,</b> and hadn't had a material update <br>"
+"- Sloow and too <b>many</b> <u>ads.</u> <br>"
+"</p>","volumn":14,"sentiment":-.50,"value":2.14},
{"keyword":"screen","name":"<h1>screen</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Enjoyed it <b>a</b> lot but after this last update the <u>screen</u> <b>is</b> no <b>longer</b> <b>forced</b> <b>to</b> <b>stay</b> <b>on</b> and will time out while watching trailers. <br>"
+"- Enjoyed it <b>a</b> lot but after this last update the <u>screen</u> is no longer forced to stay on and <b>will</b> <b>time</b> out <b>while</b> <b>watching</b> <b>trailers.</b> <br>"
+"- Enjoyed it <b>a</b> lot but after this last update the <u>screen</u> is no longer forced to stay on and <b>will</b> <b>time</b> out <b>while</b> <b>watching</b> <b>trailers.</b> <br>"
+"- <u>Screen</u> doesn't <b>stay</b> <b>on</b> when <b>playing</b> <b>trailers.</b> <br>"
+"- <u>Screen</u> <b>goes</b> <b>to</b> <b>sleep.</b> <br>"
+"- <u>Screen</u> <b>goes</b> <b>to</b> <b>sleep</b> <b>in</b> the <b>midle</b> <b>of</b> <b>playing</b> <b>trailers</b> <b>on</b> <b>5.5</b> <br>"
+"</p>","volumn":13,"sentiment":-.46,"value":2.10},
{"keyword":"cinema-time","name":"<h1>cinema-time</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; We also <b>enjoy</b> <u>learning</u> <u>more</u> <u>about</u> <u>filming</u> <u>locations,</u> <u>trivia</u> and <u>goofs.</u> <br>"
+"&#43; <b>Even</b> my <u>minor</u> <u>role</u> <u>in</u> <u>making</u> <u>films</u> <b>is</b> <b>included,</b> it's brilliant. <br>"
+"&#43; <b>Best</b> <u>TV</u> <u>show/movie</u> companion app ever! <br>"
+"&#43; I <b>love</b> your <u>site</u> and with the app it was so easier to watch the videos. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>mobile</u> <u>site</u> <b>sucks,</b> <b>too,</b> but not as bad. <br>"
+"- The information <u>is</u> good but <u>in</u> the end it <u>is</u> <u>a</u> shoping <u>site</u> so the <u>inclusion</u> <u>of</u> <u>advertising</u> <u>on</u> <u>a</u> <u>site</u> <u>that</u> <u>in</u> its <u>self</u> <u>is</u> an <u>advert</u> <u>for</u> <u>Films</u> <u>TV</u> and <u>Cinema</u> <u>times</u> <u>is</u> <b>ading</b> <u>adverts</u> <u>on</u> <b>adverts.</b> <br>"
+"- The information is good but in the end it is a shoping site so the inclusion of advertising on a site that in its self is an advert for Films TV and Cinema times is <b>ading</b> <u>adverts</u> on <u>adverts.</u> <br>"
+"- Good movie ap, but <u>design</u> <u>is</u> very out <u>dated,</u> <u>please</u> <b>update</b> <b>to</b> <b>match</b> <b>lollipop.</b> <br>"
+"- It need <u>material</u> <u>design.Make</u> every <u>topicture</u> (in theatre section) <u>scrollable</u> like your iOS version.This app <u>is</u> way <u>below</u> <u>in</u> <u>terms</u> <u>of</u> <u>functionality,</u> compared <u>to</u> it's iOS <b>version.</b> <br>"
+"- The <u>banner</u> <u>adverts</u> <b>are</b> <b>annoying</b> <b>as</b> <b>hell.</b> <br>"
+"- I <b>love</b> the <u>site</u> but I can't just search for genres of movies on the app. <br>"
+"- Maybe the <u>mobile</u> <u>site</u> is <b>good</b> <b>enough</b> (never seen it though) and I could free up some storage. <br>"
+"</p>","volumn":18,"sentiment":-.44,"value":2.45},
{"keyword":"video","name":"<h1>video</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Still <b>Cant</b> <u>load</u> <u>videos.</u> <br>"
+"&#43; I have always liked the aplication, however the <u>video</u> <u>player</u> is <b>not</b> <b>at</b> all <b>smooth,</b> maximum resolution 720p is more than sufficient. <br>"
+"&#43; Used to be great, but <u>video</u> <b>lags</b> <b>now.</b> <br>"
+"&#43; It was really great but since the new update the trailers and <u>videos</u> won't <b>play</b> <b>anymore.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Videos</u> <b>are</b> <b>not</b> <b>playing</b> <b>anymore.</b> <br>"
+"- After last update, <u>video</u> <u>player</u> <b>is</b> <b>not</b> <b>showing</b> <u>video.</u> <br>"
+"- Since update 5.5, the <u>video</u> <u>playback</u> <u>feature</u> doesn't <b>work</b> <b>properly.</b> <br>"
+"- The <u>streaming</u> <u>on</u> <u>trailers</u> are <b>unwatchable.</b> <br>"
+"- <u>Videos</u> <b>now</b> <b>begin</b> <b>to</b> <b>play</b> but then freezes despite still buffering the entire video. <br>"
+"- <u>Videos</u> now begin to play but <b>then</b> <b>freezes</b> <b>despite</b> still <b>buffering</b> the <b>entire</b> <b>video.</b> <br>"
+"- <u>Video</u> <u>quality</u> is <b>poor.</b> <br>"
+"- I have like the aplication, however the <u>video</u> <u>player</u> is <b>not</b> <b>at</b> all <b>smooth,</b> maximum resolution 720p is more than sufficient. <br>"
+"</p>","volumn":26,"sentiment":-.38,"value":2.87},
{"keyword":"search","name":"<h1>search</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Many nice features and <u>search</u> <b>is</b> <b>working</b> better <b>now.</b> <br>"
+"&#43; <b>Great</b> <u>search</u> <u>engine</u> <br>"
+"&#43; <u>Checkin</u> <u>function</u> <b>is</b> <b>great</b> <b>BUT.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This app is great if you can find what you're looking for, but the <u>search</u> <u>function</u> is <b>awful.</b> <br>"
+"- <b>I</b> understand that <u>checkin</u> <u>function</u> <b>is</b> <b>serving</b> <b>to</b> <b>people</b> <b>who</b> <b>need</b> <b>to</b> <b>track</b> <b>what</b> they've <b>watched</b> <b>along</b> the <b>way</b> but when <b>navigating</b> the <b>films</b> <b>you</b> don't <b>see</b> the <b>ones</b> <b>you</b> <b>checked</b> <b>in</b> <b>are</b> quite <b>clear</b> <b>like</b> the <b>ones</b> <b>you</b> <b>ad</b> <b>into</b> the <b>list</b> <b>of</b> <b>your</b> <b>watchlist.</b> <br>"
+"- It is very <b>limited</b> <u>search</u> <u>capabilities.</u> <br>"
+"- Ap is slow to load pages and photos and the <u>dynamic</u> <u>search</u> is <b>horible.</b> <br>"
+"- The <u>search</u> also is <b>more</b> <b>swift.</b> <br>"
+"- User interface and <u>functionality</u> <b>is</b> <b>falling</b> <b>behind.</b> <br>"
+"- User interface and <u>functionality</u> <b>is</b> <b>falling</b> <b>behind.</b> <br>"
+"</p>","volumn":11,"sentiment":-.36,"value":2.03},
{"keyword":"notifications","name":"<h1>notifications</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- RECOMENDATIONS: <b>more</b> <u>notification</u> <u>options/setings,</u> better trailer streaming for slower devices/connections. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"IMDb","name":"<h1>IMDb</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It <b>is</b> simple to use and <u>IMDb</u> <b>is</b> THE <b>place</b> to go for movie and TV information at your fingertips! <br>"
+"&#43; <u>Imdb</u> is <b>great</b> <b>for</b> movie info, trivia and <b>discussions.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>IMDb</u> undoubtedly <b>is</b> the <b>best</b> <b>database</b> but why the app <b>is</b> so worst than web version? <br>"
+"- Interface is decent enough but where is <u>Imdb</u> Top <b>250.</b> <br>"
+"- The <u>onscreen</u> <u>message</u> <u>you</u> <u>get</u> <u>from</u> <u>IMDB</u> when pages won't load is <b>childish</b> and stupid. <br>"
+"- <u>IMDb</u> aparently is <b>too</b> <b>busy</b> <b>trying</b> <b>to</b> <b>make</b> <b>me</b> <b>spend</b> <b>money</b> <b>on</b> <b>recent</b> <b>films.like</b> I can afford that. <br>"
+"</p>","volumn":6,"sentiment":-.33,"value":1.46},
{"keyword":"page","name":"<h1>page</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- For <b>one,</b> <u>character</u> <u>pages</u> aren't <b>available.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"view","name":"<h1>view</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>new</u> <u>discussion</u> <u>view.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Besides, the <u>desktop</u> <u>view</u> <b>is</b> <b>bugy</b> as hell! <br>"
+"- The message boards section is just a <b>crapy</b> <u>web</u> <u>view.</u> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"playback","name":"<h1>playback</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Y is the <u>playback</u> so <b>pathetic?</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"reference","name":"<h1>reference</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>reference</u> point. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is <b>easy</b> <u>reference</u> for downloadable movies <br>"
+"- <b>Good</b> <u>reference</u> for movie plot and rating. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"s","name":"<h1>s</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>All</u> is <b>well.</b> <br>"
+"&#43; works every time and I <b>like</b> the <u>new</u> update especially the voting feature <br>"
+"&#43; Checkin function is <b>great</b> <u>BUT.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>New</u> <u>DVD/BluRay</u> <b>releases</b> severely <b>outdated.</b> <br>"
+"- <b>Slow</b> <u>n.</u> Poor. <br>"
+"- <u>Trailers/video</u> <b>could</b> <b>play</b> <b>better.</b> <br>"
+"- My network speed is a <b>measly</b> ~2mbit/s, but other aps from Google, etc, show that there are ways around it. <br>"
+"- so <b>slow</b> <u>now.Oh</u> dear,it needs fixing <br>"
+"- Ie almost useless (like the <b>mobile</b> <u>friendly</u> s(h)ite. <br>"
+"</p>","volumn":10,"sentiment":-.30,"value":2.00},
{"keyword":"design","name":"<h1>design</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; You going to ad some features to your app like favorite list for artists and another one for films,,, and make sure your <u>design</u> is <b>creative</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Design</u> is <b>very</b> <b>outdated.</b> <br>"
+"- Old and <b>boring</b> <u>design.</u> <br>"
+"- Just like the website, the app feels clutered, the readability is dimished by bad typography and the navigation and <u>visual</u> <u>design</u> is just <b>plain</b> <b>old</b> fashioned. <br>"
+"</p>","volumn":7,"sentiment":-.29,"value":1.66},
{"keyword":"database","name":"<h1>database</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Mobile <b>friendly</b> <u>version</u> <u>of</u> THE movie <u>database.</u> <br>"
+"&#43; <b>Great</b> <u>database,</u> old fashioned design. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>great</b> <u>database</u> but poor aplication. <br>"
+"- <u>Database</u> is <b>gigantic,</b> but nobody really needs it. <br>"
+"- IMDb undoubtedly is the <b>best</b> <u>database</u> but why the app is so worst than web version? <br>"
+"- Wonderfully <b>complete</b> <u>database!</u> <br>"
+"</p>","volumn":8,"sentiment":-.25,"value":1.83},
{"keyword":"watchlist","name":"<h1>watchlist</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Loads of information and <b>love</b> the <u>watchlist.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Watchlist</u> <b>is</b> <b>also</b> <b>not</b> <b>working.</b> <br>"
+"- The <u>watchlist</u> is <b>available</b> <b>but</b> <b>not</b> your <b>own</b> <b>created</b> <b>lists.</b> <br>"
+"</p>","volumn":5,"sentiment":-.20,"value":1.41},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Update</u> to Material Design so the app can <b>be</b> <b>fun</b> again. <br>"
+"&#43; It is better than the website sometimes, <u>I</u> <b>love</b> the features and <u>regular</u> <u>updates</u> <u>for</u> <u>stability</u> and <u>such.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Just <u>updated</u> <u>today</u> and now it is <b>super</b> <b>slow.</b> <br>"
+"- <b>Terible</b> <u>updates.</u> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
]