var data_map_totalreviews=1548
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_googlemap = [
{"keyword":"information","name":"<h1>information</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>More</u> <u>information</u> is needed like road speed limits and actual rate of speed, but by far the best navigation app and extremely <b>accurate.</b> <br>"
+"&#43; And the <u>new</u> <u>visual</u> <u>information</u> displaying all the ETA's is <b>great.</b> <br>"
+"&#43; Also the <u>lane</u> <u>information</u> is <b>super</b> <b>helpful.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>useful</b> <u>information</u> about the world which brings us to close. <br>"
+"</p>","volumn":4,"sentiment":.75,"value":2.14},
{"keyword":"traffic","name":"<h1>traffic</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>live</u> <u>traffic</u> <u>funtion.</u> <br>"
+"&#43; I <b>love</b> the lane change warnings and the <u>traffic</u> <u>condition</u> <u>overlay!</u> <br>"
+"&#43; I <b>like</b> the <u>new</u> <u>traffic</u> update and rerouting feature only you forgot about the hands-free part. <br>"
+"&#43; Otherwise the app <b>is</b> prety excellent, and the <u>traffic</u> <u>layer</u> <b>is</b> a <b>lifesaver!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Used to be great but now the <u>traffic</u> <u>colors</u> are <b>barely</b> <b>visible.</b> <br>"
+"</p>","volumn":8,"sentiment":.38,"value":2.45},
{"keyword":"tool","name":"<h1>tool</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Hopefully it will stay an <b>enjoyable</b> <u>tool.</u> <br>"
+"&#43; Accurate, trust worthy and just an all <b>round</b> <u>great</u> <u>tool</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's a very <b>useful</b> <u>tool.</u> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"Functionality","name":"<h1>Functionality</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>Functionality</u> , Small Issues. <br>"
+"&#43; <b>Great</b> <u>Functionality</u> , Small Issues. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's a useless waste of real estate, and the <u>functionality</u> is <b>available</b> <b>via</b> the <b>menu.</b> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"home","name":"<h1>home</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Nar <b>sweet</b> <u>home.</u> <br>"
+"&#43; My <u>home</u> <u>adress</u> <b>is</b> <b>saved</b> <b>as</b> <u>home.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I can no longer <b>select</b> <u>home</u> as my starting location with 1 click. <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"street","name":"<h1>street</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very easy to use and <u>true</u> <u>street</u> <b>aps</b> <b>view.</b> <br>"
+"&#43; the <u>street</u> <u>view</u> is <b>great,</b> a must get. <br>"
+"&#43; I like it because the <u>street</u> <u>view</u> <b>has</b> an <b>awesome</b> <b>feature!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Track</u> <u>up</u> <u>view</u> <u>is</u> <u>a</u> <u>poor</u> <u>substitute</u> <u>because</u> <u>1)</u> it's <u>too</u> <u>hard</u> <u>to</u> <u>read</u> <u>while</u> <u>driving</u> and 2)I've <u>NEVER</u> <b>had</b> <u>a</u> <b>phone</b> <b>compass</b> that accurately worked in <u>a</u> car, so <u>its</u> really random direction <u>view.</u> <br>"
+"</p>","volumn":6,"sentiment":.33,"value":2.13},
{"keyword":"life","name":"<h1>life</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Accurate</b> and <u>a</u> <u>life</u> saver sometimes! <br>"
+"&#43; It is an <b>indispensable</b> <u>part</u> <u>of</u> my <u>life.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is <b>embarassing</b> and potentially <u>life</u> threatening to get lost and worse to get made fun of by one's friends when Android's core GPS navigation app is broken. <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>useful</b> <u>aplication</u> I love it ! <br>"
+"&#43; <b>Wonderful</b> <u>aplication.</u> <br>"
+"&#43; <b>Great</b> <u>aplication,</u> very <b>useful</b> and <u>precise.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>useful</b> <u>aplication.</u> <br>"
+"- <b>Also,</b> the text-to-speech <u>suport</u> <u>aplication</u> <b>dlted</b> when <b>I</b> cleaned my sd card and <b>I</b> can't find another one compatible with the Navigation <u>aplication</u> in the Play Store. <br>"
+"- This <u>aplication</u> is <b>most</b> <b>useful</b> <b>to</b> all <b>people.</b> <br>"
+"</p>","volumn":8,"sentiment":.12,"value":2.20},
{"keyword":"features","name":"<h1>features</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Great</u> <u>features</u> <b>to</b> <b>show</b> <b>traffic</b> <b>while</b> <b>navigating</b> rather <b>than</b> just when <b>showing</b> the <b>overall</b> <b>route.</b> <br>"
+"&#43; But some <u>features</u> are <b>fantastic.</b> <br>"
+"&#43; Good , but some <b>new</b> <u>feature</u> is must <br>"
+"&#43; <b>Cool</b> <b>new</b> <u>features</u> and a lot more <u>accurate.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Some <u>new</u> <u>features</u> are <b>good</b> but removal of useful <u>features</u> has caused me to reduce rating <br>"
+"- Also, <b>I</b> don't know how long this <u>feature</u> <b>has</b> <b>been</b> <b>around,</b> but <b>I</b> LOVE how it picks up on traffic problems and atempts to find faster routes. <br>"
+"- <u>Many</u> <u>features</u> are <b>only</b> <b>useful</b> <b>in</b> <b>USA.</b> <br>"
+"</p>","volumn":8,"sentiment":.12,"value":2.20},
{"keyword":"search","name":"<h1>search</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Voice</u> <u>search</u> <b>fails</b> very <b>often.</b> <br>"
+"- Also, <u>search</u> <u>history</u> is no <b>longer</b> <b>available</b> when <u>search</u> mode is accessed. <br>"
+"- Also, <u>search</u> history <b>is</b> no longer available when <u>search</u> <u>mode</u> <b>is</b> <b>accessed.</b> <br>"
+"- This used to be the best gps now it's slow, <u>voice</u> doesn't <b>always</b> <b>work,</b> doesn't keep up with your movement on the map, freezes. <br>"
+"- My maps keeps shuting down on me, gives me wrong directions and the <u>search</u> <u>buton</u> is <b>horible.</b> <br>"
+"</p>","volumn":5,"sentiment":-1.20,"value":.41},
{"keyword":"user","name":"<h1>user</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Slightly <b>less</b> <u>user</u> friendly than desktop version <br>"
+"- This was an unneeded change and drastically effects how <u>several</u> <u>users</u> <b>use</b> the <b>app.</b> <br>"
+"- It is <b>not</b> <u>user</u> friendly.long <b>winded</b> <br>"
+"- It is <b>not</b> <u>user</u> <b>friendly.</b> <br>"
+"- It is <b>not</b> <u>user</u> <b>friendly</b> <br>"
+"</p>","volumn":5,"sentiment":-1.00,"value":.61},
{"keyword":"Nokia","name":"<h1>Nokia</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- My <u>7</u> <u>years</u> <u>old</u> <u>Nokia</u> <b>has</b> <b>navigation</b> <b>with</b> <b>built</b> <b>in</b> <b>gps</b> <b>in</b> <b>it.</b> <br>"
+"- <u>Nokia</u> <b>here</b> <b>maps</b> and <b>here</b> drive are the best navigation aps available. <br>"
+"- <u>Idk</u> why <u>it</u> <u>worked</u> better <u>on</u> my <u>old</u> <u>Galaxy</u> <u>S3</u> <u>but</u> this <u>curent</u> <u>upgrade</u> is <b>unreliable</b> when driving <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"arow","name":"<h1>arow</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Motion is not detected, voice <b>does</b> not work, <u>arow</u> doesn't <b>move</b> or face the <b>proper</b> <b>direction.</b> <br>"
+"- After the update the <u>arow</u> showing your direction is <b>wrong,</b> compass is <b>wrong</b> and NO RECALIBRATING COMPASS DOES NOT WORK. <br>"
+"- Would puting a blue ribon on Mona Lisa's nose and a fat Her <u>smile</u> <u>text</u> <u>arow</u> pointing to her cheeks <b>enhance</b> <b>user</b> <b>experience?</b> <br>"
+"</p>","volumn":5,"sentiment":-1.00,"value":.61},
{"keyword":"places","name":"<h1>places</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The 'places' and 'navigation' butons are <b>not</b> <b>necessary</b> as they just open 'maps' <br>"
+"- This is dangerous when driving, and the <u>place</u> is <b>unknown.</b> <br>"
+"- Some <u>places</u> are <b>not</b> <b>as</b> <b>accurate</b> <b>as</b> waze's, <b>especially</b> <u>places</u> with ramps and flyovers. <br>"
+"- Google play store is a <b>full</b> boring <u>download</u> <u>place</u> <br>"
+"</p>","volumn":4,"sentiment":-1.00,"value":.39},
{"keyword":"routes","name":"<h1>routes</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>I</b> reroute and says the <u>other</u> <u>route</u> is <b>10</b> <b>min</b> <b>faster.</b> <br>"
+"- It <b>is</b> not separating the <u>routes</u> isn't <b>saving</b> <b>time,</b> it's making it unreliable. <br>"
+"- Everything but my selected route, and <u>alternative</u> <u>routes,</u> is <b>not</b> <b>visible.</b> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"name-bu-stop","name":"<h1>name-bu-stop</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>even</b> <u>names</u> <u>of</u> <u>bus</u> <u>stops</u> <b>are</b> <b>given</b> very <b>easy</b> <b>to</b> <b>find</b> <b>a</b> <b>place</b> <b>map</b> <b>loading</b> and navigation is coming within seconds really <b>a</b> great service giving <b>5</b> star because there is no <b>6</b> <br>"
+"- even <u>names</u> <u>of</u> <u>bus</u> <u>stops</u> <b>are</b> <b>given</b> very <b>easy</b> <b>to</b> <b>find</b> <b>a</b> <b>place</b> <b>map</b> <b>loading</b> and navigation is coming within seconds really <b>a</b> great service giving <b>5</b> star because there is no 6. <br>"
+"- <b>kindly</b> <u>request</u> <u>ad</u> <u>d</u> <u>bus</u> <u>routes.so</u> s <b>easy</b> <b>for</b> <b>other</b> . <br>"
+"- even <u>names</u> <u>of</u> <u>bus</u> <u>stops</u> <b>are</b> <b>given</b> very <b>easy</b> <b>to</b> <b>find</b> <b>a</b> <b>place</b> <b>l</b> <b>wonder</b> <b>what</b> <b>is</b> the <b>wrong</b> <b>with</b> <b>this</b> <b>map</b> <b>please</b> <b>read</b> <b>help</b> <b>in</b> <b>map</b> <b>menu</b> <b>setings.</b> <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"destination","name":"<h1>destination</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It will often have me driving in circles and <u>destination</u> <u>points</u> are <b>not</b> <b>accurate.</b> <br>"
+"- <b>Gives</b> me the wrong time and <b>location</b> <u>it</u> use to be good <u>now</u> <u>it</u> <u>sucks</u> <br>"
+"- My location is way off my <b>whole</b> <u>destination</u> is blocks away. <br>"
+"</p>","volumn":4,"sentiment":-.75,"value":.64},
{"keyword":"numbers","name":"<h1>numbers</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- When taking public transportation the <u>bus</u> <u>numbers</u> <b>are</b> <b>highlighted</b> <b>in</b> <b>a</b> <b>dark</b> <b>color</b> <b>with</b> <b>a</b> <b>dark</b> <b>font;</b> virtually <b>unreadable.</b> <br>"
+"- Motorway <u>junction</u> <u>numbers</u> <b>missing.</b> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"directions","name":"<h1>directions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; An <b>accurate</b> <u>sense</u> <u>of</u> <u>direction,</u> lol ! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>directions</u> <b>are</b> <b>not</b> as accurate the <b>way</b> it used to be. <br>"
+"- <b>Wrong</b> <u>directions</u> and ETA on curent version. <br>"
+"- <u>Rerouting</u> <u>directions</u> are <b>painful</b> - keeps trying to route in large circles when a u-turn will do. <br>"
+"- <u>Walking</u> <u>directions</u> remain <b>inaccurate</b> and glitchy. <br>"
+"- <u>Wonderful</u> <u>ap,</u> <u>but</u> <u>useless</u> <u>in</u> <u>direction</u> <u>up</u> <u>mode</u> <u>as</u> the <u>direction</u> <u>of</u> the <u>icon</u> <b>never</b> <b>matches</b> the <b>actual</b> <u>direction</u> <u>of</u> <b>travel.</b> <br>"
+"- <u>Walking</u> <u>directions</u> are <b>terible</b> and the rest of the app isn't much better. <br>"
+"- <u>Directions</u> <b>lag,</b> frequently <b>unreliable.</b> <br>"
+"- <u>Directions</u> <b>frequently</b> <b>lag,</b> the app can't find location even in areas with lots of wi-fi signals and open skies and turn-by-turn directions is often silent, except to say, GPS signal lost. <br>"
+"</p>","volumn":12,"sentiment":-.67,"value":1.82},
{"keyword":"time","name":"<h1>time</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Ap is very very <b>useful</b> <u>lot</u> <u>of</u> <u>times</u> its has help me thanks a <u>lot</u> <br>"
+"&#43; The <u>locations</u> <u>are</u> <b>lets</b> <b>face</b> <b>it</b> <b>not</b> <b>accurate.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>fact</u> that <u>opening</u> <u>times</u> <u>are</u> <u>incorect</u> is fairly <b>annoying</b> <b>too,</b> but <u>I</u> guess that's not Google's fault. <br>"
+"- <u>Time</u> is <b>off.</b> <br>"
+"- <u>Travel</u> <u>time</u> is <b>easier</b> and maps are more up to date. <br>"
+"- Now the <u>departure/arival</u> <u>time</u> has <b>been</b> <b>removed</b> <b>too,</b> <b>rendering</b> <b>it</b> <b>useless!</b> <br>"
+"- What used to be a great app has now become a beautiful gadget of limited use, <u>time</u> to look for a maps app that doesn't assume its user is <b>totally</b> <b>dumb.</b> <br>"
+"- After last update show <u>incorect</u> <u>position</u> <u>and</u> doesn't <b>want</b> <b>to</b> <b>navigate</b> <b>me.</b> <br>"
+"- Those <u>time</u> <u>blurbs</u> every <u>inch</u> <u>you</u> <u>scroll</u> are super <b>annoying</b> and blocking the map. <br>"
+"- Those <u>time</u> <u>blurbs</u> every <u>inch</u> <u>you</u> <u>scroll</u> are super annoying and <b>blocking</b> the <b>map.</b> <br>"
+"</p>","volumn":14,"sentiment":-.64,"value":2.00},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>new</u> <u>updates.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Most</u> <u>recent</u> <u>update</u> <b>is</b> <b>crap!</b> <br>"
+"- The <u>updates</u> <b>have</b> <b>not</b> <b>improved</b> <b>functionality</b> <b>in</b> the <b>slightest.</b> <br>"
+"- <u>Rerouting</u> <u>updates</u> are <b>so</b> <b>awesome!</b> <br>"
+"- Didn't <b>like</b> <u>a</u> <u>few</u> <u>updates,</u> <u>but</u> <u>geting</u> <u>better</u> and <u>better!</u> <br>"
+"- <u>Ur</u> <u>last</u> <u>update</u> is <b>bad.</b> <br>"
+"</p>","volumn":8,"sentiment":-.62,"value":1.45},
{"keyword":"Google","name":"<h1>Google</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>I</b> hate to dump my carefully created caustic comments about ui iritations but <u>Google</u> <b>made</b> the <b>changes</b> <b>in</b> <b>a</b> <b>thoughtful</b> and <b>elegant</b> <b>way.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Google</u> <b>has</b> <b>really</b> <b>goten</b> <b>slow.</b> <br>"
+"- <u>Google</u> is <b>evil</b> <b>to</b> <b>developers!</b> <br>"
+"- <u>Google</u> is <b>evil</b> <b>to</b> <b>developers!</b> <br>"
+"- Here's an <b>idea</b> <u>Google,</u> stop relying on the phones compass and just calculate direction of travel by positional differences of the GPS like all other GPS devices. <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"sugestions","name":"<h1>sugestions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- [Hope my <u>sugestion</u> is <b>clear]</b> <br>"
+"- [Hope my <u>sugestion</u> is <b>clear]</b> <br>"
+"- I <b>hate</b> <u>seeing</u> <u>slower</u> <u>sugestions.</u> <br>"
+"</p>","volumn":6,"sentiment":-.50,"value":1.29},
{"keyword":"being","name":"<h1>being</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> <u>being</u> <u>able</u> <u>to</u> <u>see</u> where traffic congestion is on the map so I know <u>to</u> avoid those areas. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Why</b> <u>is</u> My <u>review</u> <u>is</u> <u>being</u> <u>removed?</u> <br>"
+"- Should have <u>route</u> data navigation like WAZE which <b>stores</b> the <u>route</u> even when temporarily <u>there</u> <u>is</u> <b>lose</b> <b>of</b> <b>gps.</b> <br>"
+"- <u>Lol</u> another <u>review</u> <b>complained</b> <b>about</b> <b>wasting</b> <b>time</b> offering public transportation routes because they are longer. <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"turn","name":"<h1>turn</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>turn</u> by <u>turn</u> navigation is <b>so</b> <b>accurate.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's much less functional now and it's a lot <b>slower</b> <u>turn</u> by <u>turn,</u> you'll miss <u>turns</u> now.It doesn't keep up! <br>"
+"- It's much less functional now and it's a lot <b>slower</b> <u>turn</u> by <u>turn,</u> you'll miss <u>turns</u> now.It doesn't keep up! <br>"
+"- It's much less functional now and it's <b>a</b> lot slower turn by turn, you'll miss <u>turns</u> <b>now.It</b> doesn't <b>keep</b> up! <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"butons","name":"<h1>butons</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Maps 9: still no <u>zoom</u> <u>butons,</u> offline maps <b>unsearchable,</b> they expire. <br>"
+"- However, when navigating, I often don't <b>like</b> their <u>zoom</u> <u>level,</u> and when I flick <u>zoom</u> out, the map will just reset my <u>zoom.</u> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"options","name":"<h1>options</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> <b>liked</b> <u>seeing</u> the <u>1</u> <u>minute</u> <u>slower/faster</u> <u>options</u> <u>while</u> <u>driving.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Terible but there's no <b>other</b> <u>option</u> <br>"
+"- The highway is <b>not</b> always the <b>fastest</b> <u>option.</u> <br>"
+"- Freezes, weaker update, new <u>route</u> <u>options</u> <b>are</b> the <b>worst</b> <b>way</b> ever to select your <u>route.</u> <br>"
+"</p>","volumn":5,"sentiment":-.40,"value":1.21},
{"keyword":"change","name":"<h1>change</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Lastly, <b>would</b> <b>love</b> <u>to</u> <u>be</u> <u>able</u> <u>to</u> <u>ad</u> <u>intermediate</u> <u>stops</u> <u>by</u> <u>touching</u> <u>screen</u> and <u>change</u> <u>route</u> <u>by</u> <u>draging</u> <u>path</u> <u>to</u> <u>alternate</u> <u>route.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This was an <b>unneeded</b> <u>change</u> and drastically effects how several users use the app. <br>"
+"- The <u>new</u> <u>changes</u> to the interface are <b>unnecessary</b> <b>too.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"Accuracy","name":"<h1>Accuracy</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Accuracy</u> <b>is</b> <b>spot</b> on! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Accuracy</u> <b>is</b> 95%. <br>"
+"- <u>Accuracy</u> is <b>not</b> <b>well</b> and it <b>not</b> working properly means when I select specific route then it shows mi to oposite direction from my destination <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"setings","name":"<h1>setings</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>simple</b> <u>setings,</u> user friendly . <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Map is user <b>friendly.very</b> <u>simple</u> <u>setings.</u> <br>"
+"- try in <u>setings</u> <b>2g</b> <b>only.disable</b> <b>auto</b> <b>update.simple</b> <u>setings,</u> <b>5*</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I truly <b>love</b> the <u>old</u> <u>version</u> because it was super fast and reliable. <br>"
+"&#43; better <b>old</b> <u>version</u> with full screen maps. <br>"
+"&#43; <u>Version</u> <u>6</u> was the <b>best.</b> <br>"
+"&#43; <u>Version</u> <u>6</u> is <b>better</b> <br>"
+"&#43; This <u>new</u> <u>version</u> is <b>great.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>is</b> <b>not</b> <b>like</b> <u>old</u> <u>version.</u> <br>"
+"- The <u>previous</u> <u>version</u> <b>had</b> <b>traffic</b> <b>lines</b> that were easy to see without taking atention off of the road. <br>"
+"- This <u>version</u> <b>has</b> too <b>many</b> <b>complications</b> <br>"
+"- Navigation used to show streets as you were passing them, the <u>new</u> <u>version</u> <b>just</b> <b>shows</b> <b>a</b> <b>blue</b> <b>line.</b> <br>"
+"- <u>Older</u> <u>version</u> was <b>more</b> <b>accurate</b> <b>to</b> my <b>location</b> <br>"
+"- <u>Previous</u> <u>version</u> was <b>much</b> <b>better</b> <b>to</b> <b>use.</b> <br>"
+"- Good but wish the <u>new</u> <u>version</u> <b>had</b> <b>dimming.</b> <br>"
+"- This <u>new</u> <u>version</u> <b>takes</b> <b>lot</b> <b>of</b> <b>time</b> and names <b>of</b> streets are missing. <br>"
+"</p>","volumn":16,"sentiment":-.31,"value":2.46},
{"keyword":"location","name":"<h1>location</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Gives me accurate directions and shows me <b>where</b> the <u>location</u> <u>I</u> <u>need</u> is. <br>"
+"&#43; My <u>location</u> <b>is</b> always <b>jumping</b> <b>around.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Location</u> has been <b>very</b> <b>inconsistent,</b> often placing me a 1/4 to 1/2 mile east of where I actually am. <br>"
+"- 'Location <u>accuracy'</u> <u>dialog</u> <b>will</b> <b>always</b> <b>pop</b> up. <br>"
+"- <u>Location</u> extremely <b>slow</b> to respond on nexus 6. <br>"
+"- My <u>location</u> is so <b>frustrating</b> <b>now!</b> <br>"
+"- <u>Location</u> <b>is</b> <b>WAAAYYYY</b> off! <br>"
+"- My <u>location</u> <b>is</b> way off my <b>whole</b> <b>destination</b> <b>is</b> blocks away. <br>"
+"- <u>Location</u> is <b>very</b> <b>poor</b> <br>"
+"</p>","volumn":16,"sentiment":-.31,"value":2.46},
{"keyword":"maps","name":"<h1>maps</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Google</u> <u>Maps</u> is <b>obviously</b> <b>great,</b> but I'd love to see heavier Waze integration. <br>"
+"&#43; The <u>map</u> is <b>very</b> <b>nice</b> <b>very</b> short <br>"
+"&#43; Align to North is good, but <u>tilt</u> <u>map</u> as <u>per</u> <u>direction</u> is <b>very</b> <b>important</b> <br>"
+"&#43; I simply <b>love</b> the <u>new</u> <u>maps</u> <u>interface.</u> <br>"
+"&#43; <u>Google</u> <u>Maps</u> <b>makes</b> the <b>phone</b> <b>a</b> <b>wonderful</b> and <b>easy</b> <b>to</b> <b>use</b> <b>resouce.</b> <br>"
+"&#43; Always <b>reliable</b> <u>map</u> <br>"
+"&#43; <u>Maps</u> <u>needs</u> to be <b>accurate</b> of up to ten feet <b>from</b> the <b>actual</b> <b>location.</b> <br>"
+"&#43; I've purchased GPS systems in the past but <u>Google</u> <u>Maps</u> are by far the <b>best</b> and <b>right</b> there on my phone at no aditional cost. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Offline</u> <u>map</u> <u>saving</u> is <b>very</b> <b>useful</b> <b>in</b> no <b>network</b> <b>areas</b> <br>"
+"- <u>Nokia</u> <u>map</u> is always too <b>fast.</b> <br>"
+"- For <b>weeks</b> now, <u>maps</u> has <b>not</b> <b>been</b> <b>functioning</b> <b>properly.</b> <br>"
+"- Since the merge of Places, <u>Google</u> <u>Maps</u> is <b>not</b> the <b>same.</b> <br>"
+"- The 'places' and 'navigation' butons are not necessary as they just <b>open</b> 'maps' <br>"
+"- It is very <b>helpful</b> <u>maps</u> , I am amazed <br>"
+"- <u>Map</u> <b>refuses</b> <b>to</b> <b>navigate</b> <b>without</b> <b>restart</b> and no <b>way</b> <b>to</b> turn off annoying and useless route voice notifications. <br>"
+"- <u>Maps</u> is <b>not</b> <b>latestly.</b> <br>"
+"</p>","volumn":58,"sentiment":-.21,"value":3.85},
{"keyword":"navigation","name":"<h1>navigation</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>navigation</u> <u>feature</u> is <b>simply</b> <b>amazing!</b> <br>"
+"&#43; <b>Serious</b> <u>navigation</u> bug. <br>"
+"&#43; It is not only is it a <b>superb</b> <u>navigation</u> <u>program,</u> it's also fantastic at finding local places to eat or play. <br>"
+"&#43; The <u>navigation</u> <b>is</b> <b>overall</b> <b>fine.</b> <br>"
+"&#43; <u>navigation</u> no <b>longer</b> <b>works</b> since last update! <br>"
+"&#43; <b>Good</b> <u>Navigation</u> <u>system</u> even in Myanmar! <br>"
+"&#43; <b>Great</b> <u>navigation</u> <u>tool</u> <br>"
+"&#43; <u>Navigation</u> is <b>superb</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>New</u> <u>navigation</u> <u>version</u> <u>crashes,</u> stuters, <b>loses</b> <b>GPS</b> <b>position,</b> <b>goes</b> haywire, next to <b>useless</b> <b>with</b> <b>latest</b> <b>upset.</b> <br>"
+"- In <b>Turkey</b> <u>navigation</u> <b>still</b> <b>does</b> <b>not</b> <b>work.</b> <br>"
+"- even names of bus stops are given very easy to find <b>a</b> place map loading and <u>navigation</u> <b>is</b> <b>coming</b> <b>within</b> <b>seconds</b> really <b>a</b> <b>great</b> <b>service</b> giving <b>5</b> star because there <b>is</b> no <b>6</b> <br>"
+"- The 'places' and 'navigation' <u>butons</u> are <b>not</b> <b>necessary</b> as they just open 'maps' <br>"
+"- It is very good in general, but every time <b>you</b> use <u>navigation</u> <b>requires</b> <b>you</b> <b>to</b> <b>re-select</b> <b>routing</b> <b>options,</b> <b>to</b> <b>avoid</b> highways, <b>avoid</b> tolls and <b>avoid</b> <b>feries.</b> <br>"
+"- <u>Navigation</u> freezes and <b>will</b> <b>not</b> <b>give</b> <b>turn</b> <b>by</b> <b>turn</b> <b>directions</b> <br>"
+"- even names of bus stops are given very easy to find <b>a</b> place map loading and <u>navigation</u> <b>is</b> <b>coming</b> <b>within</b> <b>seconds</b> really <b>a</b> <b>great</b> <b>service</b> giving <b>5</b> star because there <b>is</b> no 6. <br>"
+"- It is <b>not</b> the <b>smartest</b> <u>navigation</u> by any means. <br>"
+"</p>","volumn":51,"sentiment":-.20,"value":3.74},
{"keyword":"GPS","name":"<h1>GPS</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Best</u> <u>gps</u> ever used and <b>helps</b> <b>to</b> <b>avoid</b> <b>traffic</b> <br>"
+"&#43; <u>Best</u> <u>gps</u> <b>ever</b> <b>used</b> and helps to avoid traffic <br>"
+"&#43; It's a <b>great</b> <u>gps</u> and the best part is FREE un like other <u>gps</u> aps and it's very accurate. <br>"
+"&#43; A <u>real</u> <u>GPS</u> is much <b>more</b> <b>functional.</b> <br>"
+"&#43; <b>HORRIBLE</b> <u>GPS!</u> <br>"
+"&#43; <u>GPS</u> <u>signal</u> <b>locked</b> and set <b>to</b> <b>high</b> <b>accuracy.</b> <br>"
+"&#43; <u>GPS</u> no longer acquires and <b>consistently</b> <b>displays</b> <b>incorect</b> <b>location.</b> <br>"
+"&#43; <u>GPS</u> no <b>longer</b> <b>acquires</b> and consistently displays incorect location. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>GPS</u> didn't <b>used</b> <b>to</b> <b>be</b> <b>reliable,</b> but the last update seems <b>to</b> have aded all the new sections <b>to</b> the city. <br>"
+"- But The <u>GPS</u> <b>is</b> my <b>lenovo</b> <b>is</b> not so accurate. <br>"
+"- Other than my OnStar <u>GPS</u> in my vehicle this is the <b>best</b> <u>GPS</u> <u>available.</u> <br>"
+"- provider or the ap, but I've only been able to view directions and a map, but no <b>guided</b> <u>GPS</u> on new phone for the past 3. <br>"
+"- <u>GPS</u> <b>IS</b> WAY <b>OFF.</b> <br>"
+"- <u>Gps</u> not <b>accurate</b> but <u>helpful.</u> <br>"
+"- It needs faster <u>gps</u> location with samsung device, <b>especially</b> if <u>gps</u> <b>is</b> <b>turned</b> on after app has been opened <b>(</b> often have to re-start app to get Gmaps to find curent location and not last used location). <br>"
+"- The <b>only</b> <u>gps</u> base app that reliable <br>"
+"</p>","volumn":18,"sentiment":-.06,"value":2.83},
{"keyword":"useful","name":"<h1>useful</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>good</b> and <u>useful</u> <u>aplication</u> <br>"
+"&#43; <u>I</u> <b>love</b> <u>saving</u> <u>a</u> <u>map</u> <u>for</u> <u>offline</u> <u>use</u> <u>because</u> even <u>offline,</u> GPS works and <u>I</u> can navigate with the maps. <br>"
+"&#43; I <b>loved</b> how <u>it</u> <u>used</u> <u>to</u> <u>switch</u> automatically, but now <u>it</u> doesn't even exist! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Some new <u>features</u> are good but <u>removal</u> <u>of</u> <u>useful</u> <u>features</u> <b>has</b> <b>caused</b> <b>me</b> <b>to</b> <b>reduce</b> <b>rating</b> <br>"
+"- <u>always</u> <u>useful</u> <u>2</u> <u>view</u> <u>all</u> <u>streets</u> and <u>roads</u> <u>more</u> <u>useful</u> <u>2</u> <b>go</b> <b>anywher</b> <br>"
+"- What <u>used</u> to be a great app has now become a <b>beautiful</b> <u>gadget</u> <u>of</u> limited <u>use,</u> time to look for a maps app that doesn't assume its <u>user</u> is totally dumb. <br>"
+"</p>","volumn":7,"sentiment":.00,"value":1.95},
{"keyword":"service","name":"<h1>service</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <b>best</b> <u>maping</u> <u>service</u> available. <br>"
+"&#43; <b>Excellent</b> <u>service</u> better than garmin. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But <u>I</u> <b>dislike</b> the <u>play</u> <u>services</u> <u>batery</u> <u>drain</u> <br>"
+"- It is very <b>poor</b> <u>service</u> <br>"
+"</p>","volumn":5,"sentiment":.00,"value":1.61},
]