var data_map_totalreviews=1548
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_googlemap = [
{"keyword":"features","name":"<h1>features</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is a absolutely wonderful aplication ,but it absolutely <b>needs</b> <u>the</u> <u>toll</u> <u>avoiding</u> <u>feature.</u> <br>"
+"&#43; <b>More</b> <u>features</u> please. <br>"
+"&#43; <u>Hapier</u> that the My <u>Maps</u> <u>feature</u> is <b>back!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":5,"sentiment":.60,"value":2.21},
{"keyword":"sygic-gps-navig","name":"<h1>sygic-gps-navig</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Can't search for <b>a</b> places while I'm offline even after downloading the map to use offline, another problem is downloading the offline maps could be way <u>better</u> if we can download countries or even cities not <b>a</b> 50km areas as of now, please solve these issues because google deserve to be the best or at least like HERE from Nokia. <br>"
+"- Can't search for <b>a</b> places while I'm offline even after downloading the map to use offline, another problem is downloading the offline maps could be way <u>better</u> if we can download countries or even cities not <b>a</b> 50km areas as of now, please solve these issues because google deserve to be the best or at least like HERE from NOKIA, Thanks. <br>"
+"- It <b>needs</b> <u>better</u> <u>offline</u> <u>maps</u> <u>suport.</u> <br>"
+"- Ading speed limit, <u>better</u> <u>POI</u> <b>would</b> <b>be</b> also <b>awesome.</b> <br>"
+"- <u>I</u> <b>wish</b> <u>Google</u> <u>maps</u> <u>will</u> <u>fix</u> <u>it</u> and <u>be</u> <u>better</u> <u>like</u> <u>Garmin,</u> <u>TomTom</u> and <u>sygic</u> <u>GPS</u> <u>navigation</u> <br>"
+"- <u>I</u> <b>wish</b> <u>Google</u> <u>maps</u> will fix it and <u>be</u> <u>better</u> <u>like</u> <u>Garmin,</u> <u>TomTom</u> and <u>sygic</u> <u>GPS</u> <u>navigation</u> <br>"
+"</p>","volumn":6,"sentiment":-1.33,"value":.46},
{"keyword":"speed","name":"<h1>speed</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>would</b> like to know how fast I'm going when driving, <u>speed</u> <b>would</b> <b>be</b> <b>nice</b> to know <br>"
+"- <u>I</u> would like to <b>see</b> the <u>speed</u> <u>limit</u> <u>of</u> the <u>area</u> I'm <u>in.</u> <br>"
+"- It <b>needs</b> <u>speedometer</u> and <u>speed</u> <u>warnings</u> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"this","name":"<h1>this</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>revert</u> <u>this</u> <u>change</u> back so the navigating arow is back at the botom of the screen. <br>"
+"- Odly though, if I pull the list of directions up it's still able <u>to</u> route <u>me</u> EXACTLY <u>to</u> where I am and where I <b>want</b> <u>to</u> <u>go</u> so <u>this</u> <u>tells</u> <u>me</u> that the the GPS can track <u>me.</u> <br>"
+"- It's not fear, turn by turn navigation is still not <u>enabled</u> in Morocco :( <b>please</b> <u>enable</u> <u>this</u> <u>feature</u> <br>"
+"- I have been a google suporter for quite awhile but <u>this</u> <u>gps</u> <u>maps</u> <b>needs</b> <b>to</b> <b>be</b> <b>fixed!</b> <br>"
+"- Sometimes I think I might not need to <b>make</b> so <u>many</u> <u>changes,</u> <u>talking</u> the <u>tricky</u> <u>route,</u> if the program could take into account that I would be in the carpool lane. <br>"
+"</p>","volumn":6,"sentiment":-.83,"value":.96},
{"keyword":"time","name":"<h1>time</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Thick</u> <u>Traffic</u> <u>color</u> <u>lines</u> are <b>back</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The widgets were suposed <u>to</u> be one-tap solution <u>to</u> get directions <u>to</u> places frequented, but if there is a possible <u>toll</u> on the route, and I <b>want</b> <u>to</u> <u>avoid</u> <u>toll</u> every <u>time,</u> I have <u>to</u> cancel out of navigation, check Avoid Tolls options and get fresh directions. <br>"
+"- Please ad a toll road option it would make <u>the</u> <u>traffic</u> <u>time</u> <b>more</b> <b>accurate.</b> <br>"
+"- I just <b>wish</b> <u>it</u> <u>would</u> <u>shut</u> <u>up</u> <u>from</u> <u>time</u> <u>to</u> <u>time.</u> <br>"
+"</p>","volumn":4,"sentiment":-.75,"value":.64},
{"keyword":"search","name":"<h1>search</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- You have public transit, car, and bicycle ad commercial truck driving route options to <b>your</b> maps and you'd easily <u>cornet</u> <u>another</u> <u>market</u> <u>of</u> the <u>search</u> <u>business.</u> <br>"
+"- But needs <u>a</u> <u>way</u> <u>to</u> ad another stop <u>on</u> your route, like say you <b>want</b> <u>to</u> <u>search</u> <u>for</u> <u>food</u> <u>on</u> the <u>way</u> <u>to</u> your <u>destination</u> and have navigation take you there first <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"offline","name":"<h1>offline</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> <b>wish</b> <u>offline</u> <u>was</u> <u>a</u> <u>litle</u> <u>more</u> <u>robust</u> <br>"
+"- Instead <u>of</u> <u>expiring</u> <u>of</u> <u>offline</u> <u>maps</u> <u>in</u> <u>30</u> <u>days,</u> <b>you</b> <b>should</b> incrementally <u>update</u> <u>it</u> <br>"
+"- It <b>need</b> <u>offline</u> <u>mode</u> <u>Available</u> <u>for</u> all <u>regions!</u> <br>"
+"- It <b>needs</b> <u>offline</u> <u>maps</u> with proper details. <br>"
+"- It <b>need</b> <u>offline</u> <u>navigation,</u> because sometimes it won't work in bad signal area <br>"
+"- Also, <u>offline</u> <u>maps</u> shouldn't <b>need</b> <b>updating,</b> <b>especially</b> when <b>it</b> doesn't <b>notify</b> <b>you</b> and <b>you</b> <b>end</b> <b>up</b> <b>with</b> no <u>maps</u> when <b>you</b> <b>need</b> them. <br>"
+"- It <b>need</b> <u>offline</u> <u>download.</u> <br>"
+"- If you can't <b>provide</b> the most <u>needed</u> <u>offline</u> <u>maps</u> features,your junk cosmetic updates that we receive quite often must be a piece of junk. <br>"
+"</p>","volumn":15,"sentiment":-.67,"value":2.04},
{"keyword":"location","name":"<h1>location</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Graphic</u> <b>needs</b> <b>to</b> <b>change</b> <b>in</b> <b>singapore</b> <b>cos</b> <b>i</b> already <b>update</b> the <b>app</b> but the <b>picture</b> <b>shows</b> <b>were</b> <b>like</b> <b>3-4</b> <b>years</b> <b>back</b> <br>"
+"- Something seriously wrong with the fact that you need to <b>make</b> <u>your</u> <u>location</u> tracked to use a simple Home shortcut. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Excellent maping but Not <u>updated</u> 3d building In My phone <b>Please</b> <u>update</u> <br>"
+"- This app continually crashes on any highway, all states from Texas to Ohio, Does not function without network connectivity, it <b>needs</b> <u>road</u> <u>updates.</u> <br>"
+"- <b>Please</b> <u>considere</u> <u>it</u> <u>in</u> <u>the</u> <u>future</u> <u>updates.</u> <br>"
+"- Ya done screwed up with <u>the</u> <u>updates</u> <u>someone</u> <b>needs</b> <b>to</b> <b>fix</b> <b>that.</b> <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"Maps","name":"<h1>Maps</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It <b>needs</b> <u>higher</u> <u>map</u> <u>of</u> <u>density!</u> <br>"
+"- <u>Love</u> <u>Google</u> <u>Maps</u> <u>Ap,</u> however it <b>would</b> <b>be</b> <b>nice</b> to <b>be</b> able to habe it where you could ad unlimited numbers of stopeds or POI along you route. <br>"
+"- I like the new interface, but those two features would make <u>Maps</u> so much <b>better.</b> <br>"
+"- <u>Offline</u> <u>maps</u> <b>need</b> <b>to</b> <b>update</b> <b>like</b> <b>everyday.</b> <br>"
+"</p>","volumn":6,"sentiment":-.67,"value":1.13},
{"keyword":"bring","name":"<h1>bring</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Please</b> <u>bring</u> back <u>road</u> <u>names</u> <u>in</u> the <u>verbal</u> <u>instructions,</u> or I will have to switch to something else. <br>"
+"- It need to be able to <b>see</b> every <u>road</u> at any level as country <u>roads</u> don't apear until you zoom right in, which then makes navigation almost impossible! <br>"
+"- <u>Nobody</u> <u>wants</u> <u>to</u> <u>see</u> the <u>droped</u> <u>pin</u> <u>name,</u> they <b>want</b> <u>to</u> <u>see</u> what they called their stared place! <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"route","name":"<h1>route</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I am an avid ADV rider and <b>need</b> <u>routes</u> through National Forests and such. <br>"
+"- <b>Alternative</b> <u>route</u> if <b>there</b> <b>is</b> <u>an</u> <u>accident</u> or <u>delay</u> <u>on</u> your <u>chosen</u> <u>route</u> would be another good edition. <br>"
+"- I love the app but would be great if you could <b>include</b> <u>truck</u> <u>routes</u> in citys (sydney australia ) like weight restrictions on streets. <br>"
+"- <u>I</u> <b>wish</b> <u>they</u> <u>would</u> <u>ad</u> <u>ability</u> <u>to</u> <u>plan</u> <u>route</u> <u>by</u> <u>drawing</u> <u>on</u> <u>screen</u> <u>with</u> <u>miliage</u> <u>counter.</u> <br>"
+"- Can't select specific roads you <b>want</b> <u>to</u> <u>take</u> unless it's a <u>sugested</u> <u>route.</u> <br>"
+"- Problem with <b>no</b> <u>routes.</u> <br>"
+"- _Really_ <b>needs</b> <u>a</u> <u>feature</u> <u>to</u> <u>allow</u> <u>ading</u> <u>multiple</u> <u>stops</u> <u>to</u> your <u>route</u> <u>like</u> <u>mapquest.</u> <br>"
+"- I really <b>need</b> <u>bicycling</u> <u>routes</u> <u>in</u> <u>Costa</u> <u>Rica,</u> and all I get is car <u>routes.</u> <br>"
+"</p>","volumn":14,"sentiment":-.57,"value":2.07},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I'd like to still be able to <b>see</b> all <u>my</u> <u>options.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- [4) <u>need</u> <u>real</u> <u>time</u> (present) <u>speed</u> <u>display</u> like speedometer, towards destination] [5) <u>need</u> <u>tracking</u> <u>options</u> <u>for</u> <u>realizing</u> <u>from</u> which <u>root</u> <u>we</u> just <u>passed</u> through]. <br>"
+"- I <b>wish</b> to ad a <u>rename</u> <u>option</u> <u>for</u> <u>saved</u> <u>locations</u> <br>"
+"- [4) <u>need</u> <u>real</u> <u>time</u> (present) <u>speed</u> <u>display</u> like speedometer, towards destination] [5) <u>need</u> <u>tracking</u> <u>options</u> <u>for</u> <u>realizing</u> <u>from</u> which <u>root</u> <u>we</u> just <u>passed</u> through]. <br>"
+"- Where's <u>the</u> <u>option</u> <u>to</u> <u>ad</u> <u>the</u> <u>number</u> and <u>adress</u> <u>info</u> <u>to</u> contacts all at once? <br>"
+"- <u>An</u> <u>option</u> <u>to</u> <u>save</u> <u>the</u> no <u>toll</u> <u>roads</u> seting <b>would</b> <b>be</b> <b>great.</b> <br>"
+"- One, it doesn't <b>give</b> you <u>the</u> <u>option</u> <u>to</u> <u>customize</u> your <u>travel</u> <u>method</u> (fastest <u>route</u> <u>v</u> <u>shortest</u> <u>distance</u> etc). <br>"
+"- <u>A</u> <u>simple</u> <u>option</u> <u>in</u> <u>setings</u> <u>instead</u> <u>of</u> <u>waiting</u> <u>for</u> the <u>prompt</u> <u>to</u> <u>show</u> <u>up</u> <b>would</b> <b>be</b> <b>great</b> <br>"
+"- Also, <u>a</u> <u>sites</u> <u>to</u> <u>see</u> <u>option</u> when traveling through the different cities <b>would</b> <b>be</b> <b>cool</b> too. <br>"
+"</p>","volumn":30,"sentiment":-.53,"value":2.87},
{"keyword":"star","name":"<h1>star</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- If street view option is aded i would <b>give</b> it <u>a</u> <u>5</u> <u>star</u> <u>rating.</u> <br>"
+"- <u>One</u> <u>star</u> <u>because</u> <u>Google</u> <b>needs</b> <b>to</b> <b>adress</b> this <b>problem.</b> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"need","name":"<h1>need</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>need</u> <u>for</u> <u>it!</u> <br>"
+"- Plus the street maps in some areas are old and apear like <b>there</b> <b>is</b> <u>no</u> <u>road</u> <b>anymore.</b> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"them","name":"<h1>them</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Hard <u>to</u> <b>see,</b> <u>please</u> <u>make</u> <u>them</u> <u>thicker</u> like <u>they</u> <u>used</u> <u>to</u> <u>be</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- And <u>I</u> <b>wish</b> <u>we</u> <u>could</u> <u>have</u> <u>a</u> <u>Favorite</u> <u>places</u> <u>list,</u> so <u>I</u> don't <u>have</u> <u>to</u> <u>GPS</u> <u>certain</u> <u>locations</u> all the time, or <u>remember</u> or <u>hunt</u> <u>them</u> down. <br>"
+"- And I <b>wish</b> <u>we</u> could have a Favorite places list, so I don't have to GPS certain locations all the time, or <u>remember</u> or <u>hunt</u> <u>them</u> down. <br>"
+"- Also, offline maps shouldn't <b>need</b> updating, especially when it doesn't notify you and you end up with no maps when you <b>need</b> <u>them.</u> <br>"
+"</p>","volumn":5,"sentiment":-.40,"value":1.21},
{"keyword":"they","name":"<h1>they</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Good for people that don't <b>want</b> <u>to</u> <u>be</u> <u>tracked.</u> <br>"
+"&#43; Still, there is much more <u>they</u> could do, and I <b>hope</b> <u>they</u> <u>will.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Even</u> <u>a</u> <u>vague</u> <u>mention</u> that <u>they</u> <u>are</u> <u>being</u> <u>aded</u> <b>would</b> <b>be</b> <b>awesome,</b> instead of me just wondering what my devices <u>are</u> doing in the background. <br>"
+"- <u>I</u> love Google Maps but this update, when <u>I</u> get directions, the <u>bus</u> numbers do not show; there's <b>just</b> <u>gray</u> <u>boxes</u> where the <u>bus</u> <u>#</u> <u>should</u> <u>be.</u> <br>"
+"- Nobody wants to <b>see</b> the droped pin name, <u>they</u> want to <b>see</b> <u>what</u> <u>they</u> <u>called</u> their <u>stared</u> <u>place!</u> <br>"
+"- I <b>wish</b> <u>they</u> <u>had</u> <u>dinning</u> <u>between</u> <u>turns</u> still. <br>"
+"</p>","volumn":7,"sentiment":-.29,"value":1.66},
{"keyword":"navigation","name":"<h1>navigation</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Maps are most <b>developed,</b> but <u>navigation</u> <u>system</u> <b>need</b> <b>to</b> <b>be</b> <b>more</b> <b>developed!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Good</u> <u>except</u> <u>navigation</u> <b>needs</b> <b>to</b> <b>have</b> <b>a</b> <b>sticky</b> <b>default</b> <b>on</b> <b>routing</b> <b>OPTIONS.</b> <br>"
+"- <b>There</b> <b>is</b> <u>no</u> <u>other</u> <u>maping</u> <u>service</u> <u>as</u> <u>good</u> <u>as</u> <u>GMaps</u> <u>period</u> <br>"
+"</p>","volumn":4,"sentiment":-.25,"value":1.14},
]