var data_map_totalreviews=756
var data_map_fromdate=20150702
var data_map_todate=20151102
var data_map_chasemobile = [
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>smooth</b> <u>interface,</u> great options and very easy to use! <br>"
+"&#43; <u>New</u> <u>interface</u> is <b>great.</b> <br>"
+"&#43; <b>Clean</b> <u>interface,</u> easy to check curent balances and recent transactions. <br>"
+"&#43; <b>Great</b> <u>interface.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This app functions the way I need it to in that I can view my statement and pay my credit card but the <u>interface</u> is <b>so</b> <b>archaic.</b> <br>"
+"</p>","volumn":5,"sentiment":.80,"value":2.41},
{"keyword":"money","name":"<h1>money</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> how easily I can manage my <u>money</u> and transfer all from my phone without having to run to the bank. <br>"
+"&#43; It is <b>easy</b> <u>Money</u> <u>managment.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.67,"value":1.77},
{"keyword":"ability","name":"<h1>ability</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great advice <b>love</b> the <u>ability</u> to check balances anywhere and <u>transfer</u> <u>funds</u> <br>"
+"&#43; I <b>love</b> the <u>ability</u> to deposit checks with it too. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.67,"value":1.77},
{"keyword":"access","name":"<h1>access</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; awesome <b>love</b> the <u>easy</u> <u>access</u> <br>"
+"&#43; It is <b>easy</b> <u>Access.</u> <br>"
+"&#43; It is <b>easy</b> <u>Access.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is <b>easy</b> <u>access</u> I can pay all my bills thanks exelent ap <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"balance","name":"<h1>balance</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This is <u>a</u> great ap, <u>i</u> really <b>enjoy</b> <u>being</u> <u>able</u> <u>to</u> <u>see</u> my <u>curent</u> <u>balance</u> <u>without</u> <u>having</u> <u>to</u> <u>log</u> <u>in</u> every <u>time.so</u> <u>convenient!</u> <br>"
+"&#43; <b>Love</b> it for the ease in making payments, <u>seeing</u> <u>charges</u> and <u>balance.</u> <br>"
+"&#43; I used <u>to</u> have problems and since the upgrade, it's been great and I <b>love</b> <u>not</u> <u>having</u> <u>to</u> <u>log</u> <u>in</u> <u>to</u> <u>see</u> my <u>balance.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Available <u>balance</u> <u>info</u> <b>sometimes</b> <b>does</b> <b>not</b> <b>include</b> <b>curent</b> <b>pending</b> <b>activity.</b> <br>"
+"- <u>Balance</u> is <b>not</b> <b>accurate.</b> <br>"
+"</p>","volumn":6,"sentiment":.33,"value":2.13},
{"keyword":"preview","name":"<h1>preview</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the <u>preview</u> <u>of</u> your <u>balance.</u> <br>"
+"&#43; Love <b>love</b> <b>love</b> the <u>preview</u> <u>action</u> too. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Also like the new <u>preview</u> <u>swipe</u> <u>option</u> <b>to</b> <b>see</b> <b>account</b> <b>overview</b> <b>without</b> <b>having</b> <b>to</b> <b>sign</b> <b>in.</b> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"service","name":"<h1>service</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very <b>good</b> <u>service.</u> <br>"
+"&#43; It is very <b>professional</b> <u>services</u> <br>"
+"&#43; The <b>best</b> <u>Customer</u> <u>service</u> ever- Patrice <br>"
+"&#43; <b>Good</b> <u>services</u> and take care customers <br>"
+"&#43; So <b>is</b> <b>customer</b> <u>service</u> <br>"
+"&#43; <u>Customer</u> <u>service</u> was <b>really</b> <b>helpful</b> hence 2 stars. <br>"
+"&#43; <b>Excellent</b> <u>service</u> <br>"
+"&#43; <b>Excellent</b> <u>customer</u> <u>service</u> for a full size international bank. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Mediocre</b> <b>pointless</b> <u>stupid</u> <u>service.</u> <br>"
+"- My deposits are limited to a laugh with this ap, seriously; what a pointless <b>stupid</b> <u>service</u> by Chase. <br>"
+"- The app is worthless, <b>seems</b> <b>designed</b> <b>to</b> <b>confuse</b> <b>not</b> <b>help</b> the <u>customer.</u> <br>"
+"- <u>Poor</u> <u>service</u> <u>and</u> <b>do</b> <b>not</b> <b>get</b> the <b>credit</b> <b>card</b> the cash back reward is horible it only pays 1% per 30+ days the worst reward <b>card</b> out there. <br>"
+"</p>","volumn":14,"sentiment":.29,"value":2.92},
{"keyword":"banking","name":"<h1>banking</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is <b>easy</b> <u>banking.</u> <br>"
+"&#43; I <b>love</b> the <u>ease</u> <u>of</u> <u>banking</u> <u>thru</u> my <u>phone.</u> <br>"
+"&#43; It is <b>easy</b> <u>banking.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Great</u> <u>bank</u> and terific people, but the app is the <b>worst!</b> <br>"
+"</p>","volumn":7,"sentiment":.29,"value":2.23},
{"keyword":"phone","name":"<h1>phone</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> how easily I can manage my money and transfer <u>all</u> <u>from</u> my <u>phone</u> without having to run to the bank. <br>"
+"&#43; <b>Love</b> it and easy <u>to</u> <u>use.</u> <br>"
+"&#43; Always accurate, <u>easy</u> <u>to</u> <u>use</u> and <u>never</u> <b>had</b> <u>a</u> <b>problem.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Each <u>phone</u> <u>call</u> <u>I</u> <u>made</u> <b>resulted</b> <b>in</b> <b>a</b> <b>new</b> completely <b>ridiculous</b> <b>excuse</b> <b>as</b> <b>to</b> why <b>mu</b> <b>funds</b> aren't <b>available.</b> <br>"
+"- <u>New</u> <u>phone,</u> <b>unable</b> to acess! <br>"
+"</p>","volumn":6,"sentiment":.17,"value":1.96},
{"keyword":"Chase","name":"<h1>Chase</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Love</u> <u>chase</u> <b>gives</b> you a lot oportunities,to love the banking so much,very <b>good</b> <b>bank</b> ,I really recommend. <br>"
+"&#43; Awesome ap, usability is on point, it's stable and fast, and <u>Chase</u> <b>has</b> <b>fixed</b> the <b>issues</b> <b>that</b> <b>lead</b> <b>to</b> my <b>previous</b> <b>two</b> <b>star</b> <b>rating.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Chase</u> <u>customer</u> <u>service</u> <u>representatives</u> are <b>awesome.</b> <br>"
+"- <u>Chase</u> and Security are <b>mutually</b> <b>exclusive.</b> <br>"
+"</p>","volumn":8,"sentiment":.12,"value":2.20},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Updates</u> are <b>awful!</b> <br>"
+"- <u>Updates</u> are <b>awful!</b> <br>"
+"- <u>To?</u> many <u>updates</u> and the <u>updates</u> should be <b>better</b> and end up been worst. <br>"
+"- To? many <u>updates</u> and the <u>updates</u> should be <b>better</b> and end up been worst. <br>"
+"- <u>To?</u> many <u>updates</u> and the <u>updates</u> should be better and <b>end</b> <b>up</b> been worst. <br>"
+"- <u>Fewer</u> <u>updates</u> and a swipe sign in would be <b>nice.</b> <br>"
+"- <u>Recent</u> <u>updates</u> <b>make</b> <b>interface</b> more user <b>friendly.</b> <br>"
+"- too <b>many</b> <u>updates.</u> <br>"
+"</p>","volumn":11,"sentiment":-1.27,"value":1.13},
{"keyword":"pin-login","name":"<h1>pin-login</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- No <u>pin</u> <u>login,</u> <b>useless.</b> <br>"
+"- No <u>pin</u> <u>login,</u> <b>useless.</b> <br>"
+"- No <u>pin</u> <u>login,</u> <b>useless.</b> <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>></b> <u>last</u> <u>version</u> much better. <br>"
+"- <u>Latest</u> <u>version</u> <b>is</b> <b>bugy.</b> <br>"
+"- <u>Latest</u> <u>version</u> <b>is</b> <b>bugy</b> as hell! <br>"
+"- <u>Latest</u> <u>version</u> <b>resolved</b> <b>keyboard</b> and check deposit problems. <br>"
+"- <u>Latest</u> <u>version</u> resolved keyboard and <b>check</b> <b>deposit</b> <b>problems.</b> <br>"
+"- I am so upset that the <u>old</u> <u>version</u> is <b>not</b> <b>usable</b> any <b>more.</b> <br>"
+"</p>","volumn":9,"sentiment":-.67,"value":1.53},
{"keyword":"picture","name":"<h1>picture</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Picture</u> is <b>not</b> <b>clear</b> message preventing deposit. <br>"
+"- now I constantly get <u>picture</u> <b>is</b> <b>unclear</b> <b>try</b> again or we are experiencing difficulties <b>try</b> again later. <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"people","name":"<h1>people</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> <b>love</b> <u>being</u> <u>able</u> <u>to</u> <u>pay</u> <u>bills</u> or <u>people</u> <u>on</u> the <u>go.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Also, the <u>images</u> <u>that</u> <u>are</u> <u>suposed</u> <u>to</u> <u>be</u> <u>related</u> <u>to</u> your <u>location</u> <b>never</b> <b>show</b> up <b>anymore.</b> <br>"
+"- Can no longer deposit, <u>images</u> are <b>so</b> <b>full</b> <b>of</b> <b>artifacts</b> that it can't read the check <br>"
+"- <u>Background</u> <u>image</u> is <b>still</b> <b>not</b> <b>updated,</b> has old version. <br>"
+"- The <u>people</u> <u>who</u> <u>are</u> <u>giving</u> <u>bad</u> <u>reviews</u> <u>are</u> <b>obviously</b> <b>inept</b> <b>at</b> <b>working</b> <b>with</b> <b>aps.</b> <br>"
+"</p>","volumn":5,"sentiment":-.60,"value":1.01},
{"keyword":"icon","name":"<h1>icon</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I love the app - I <b>hate</b> the <u>new</u> <u>icon!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>new</u> <u>Icon</u> for the ap, the Android Man, is <b>ugly</b> and confusing. <br>"
+"- <u>Icon</u> <u>issue</u> is <b>just</b> <b>cosmetic</b> but unsetling. <br>"
+"- I updated to the most recent version of this app and the chase <u>icon</u> <b>is</b> not anymore there, the <u>icon</u> shown <b>is</b> an <b>android.</b> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>quickpay</u> <u>option</u> is <b>very</b> <b>convenient.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>money</u> <u>transfer</u> <u>option</u> is no <b>longer</b> <b>available</b> after the last update. <br>"
+"- -- in fact the app freezes <b>so</b> that the <u>only</u> <u>option</u> is to Force Stop. <br>"
+"- -- in fact the app freezes <b>so</b> that the <u>only</u> <u>option</u> is to Force Stop. <br>"
+"</p>","volumn":5,"sentiment":-.40,"value":1.21},
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's a <b>simple</b> to use <u>aplication.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- When I deposit a check the <u>auto</u> <u>focus</u> <u>on</u> the <u>aplication</u> is <b>terible</b> my checks are out of <u>focus.</u> <br>"
+"- <b>Clean</b> <u>aplication</u> all the time and easy to use. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"Functionality","name":"<h1>Functionality</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; that was a <b>great</b> <u>function.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Functionality</u> is <b>most</b> <b>important,</b> I don't care about all the new features if I can't use them. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
]