var data_map_totalreviews=973
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_spotifymusic = [
{"keyword":"UI","name":"<h1>UI</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>new</u> <u>ui</u> is <b>inconvenient.</b> <br>"
+"&#43; <u>I</u> <b>like</b> the <u>new</u> <u>UI</u> very <u>clean.</u> <br>"
+"&#43; <b>Nice</b> <u>UI</u> and ample music selection. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.00,"value":2.10},
{"keyword":"selection","name":"<h1>selection</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great app no problems and a <b>great</b> <u>selection</u> of music! <br>"
+"&#43; Always the <b>best</b> <u>selection.</u> <br>"
+"&#43; <b>Huge</b> <u>selection,</u> reliable just about anywhere, excellent features. <br>"
+"&#43; I <b>love</b> the <u>selections.</u> <br>"
+"&#43; I <b>love</b> the <u>selections.</u> <br>"
+"&#43; <b>Great</b> <u>selection.</u> <br>"
+"&#43; <b>Great</b> <u>selection.</u> <br>"
+"&#43; <b>Great</b> <u>selection</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":11,"sentiment":1.00,"value":3.40},
{"keyword":"playlists","name":"<h1>playlists</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I enjoy the <u>playlists</u> <b>featuring</b> new music and a <b>variety</b> <b>of</b> <b>artists.</b> <br>"
+"&#43; I <b>love</b> that you can have <u>playlists</u> <u>with</u> your <u>favorite</u> <u>musik!</u> <br>"
+"&#43; <u>Playlists</u> are <b>great,</b> like that it recommends music, will show lyrics, info about bands, and also has audio books <br>"
+"&#43; I <b>love</b> the <u>option</u> <u>of</u> <u>listening</u> <u>to</u> a <u>playlist.</u> <br>"
+"&#43; I like the artist selection better than Amazon Prime, and the <u>playlists</u> <b>are</b> <b>fun</b> to do with friends. <br>"
+"&#43; It is <b>easy</b> <u>playlist.</u> <br>"
+"&#43; I <b>love</b> the <u>playlists</u> and you have more control over you can listen to depending on your condition or mood unlike Pandora. <br>"
+"&#43; I <b>like</b> the fact that their <u>new</u> <u>weekly</u> <u>discovery</u> <u>playlist</u> is made with your musical taste. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":12,"sentiment":.92,"value":3.40},
{"keyword":"radio","name":"<h1>radio</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> Spotify for the connect feature, it's very useful, and I also <b>love</b> their <u>radio</u> <u>function</u> as well ^_^ <br>"
+"&#43; <b>Seamless</b> <u>ease</u> <u>of</u> <u>use.</u> <br>"
+"&#43; It is not interested in playing a fee, but overall is good <u>radio</u> <b>has</b> a <b>variety</b> and I use it more than Pandora. <br>"
+"&#43; All in all I love spotify, I think it's better than Pandora, the <u>radio</u> is usually really great and <b>has</b> a <b>big</b> <b>variety.</b> <br>"
+"&#43; All in all I love spotify, I think it's better than Pandora, the <u>radio</u> is usually <b>really</b> <b>great</b> and has a big variety. <br>"
+"&#43; <b>Great</b> <u>radio.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":8,"sentiment":.88,"value":2.95},
{"keyword":"choice","name":"<h1>choice</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>choice</u> for music! <br>"
+"&#43; <u>I</u> <b>love</b> the <u>choice</u> <u>of</u> <u>playlists</u> and <u>radio</u> <u>offerings!</u> <br>"
+"&#43; <b>Great</b> <u>music</u> <u>choices</u> <br>"
+"&#43; <b>Good</b> <u>music</u> <u>choice</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":6,"sentiment":.83,"value":2.63},
{"keyword":"options","name":"<h1>options</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>offline</u> <u>option</u> is <b>amazing</b> and music selection can't be beat for the price. <br>"
+"&#43; The <u>offline</u> <u>optin</u> is <b>cool</b> <b>too!</b> <br>"
+"&#43; <b>Beter</b> <u>display</u> and variety <u>of</u> <u>options.</u> <br>"
+"&#43; Prety much all music <b>great</b> <u>options</u> <br>"
+"&#43; <b>Also</b> the <u>offline</u> <u>option</u> is <b>awesome.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- What is lacking is an <b>improved</b> <u>options</u> <u>area,</u> as there isn't much to it now. <br>"
+"</p>","volumn":6,"sentiment":.67,"value":2.46},
{"keyword":"service","name":"<h1>service</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>music</u> <u>service!</u> <br>"
+"&#43; This is a <b>great</b> <u>service.</u> <br>"
+"&#43; i <b>love</b> this <u>service,</u> point blank period. <br>"
+"&#43; <b>Great</b> <u>service.</u> <br>"
+"&#43; <b>Great</b> <u>service</u> <br>"
+"&#43; In adition <u>to</u> that, the <u>concept</u> and implementation <u>of</u> the <u>service</u> as well as the <u>way</u> <u>it</u> <u>talks</u> <u>to</u> <u>other</u> <u>services/aps</u> <b>are</b> very <b>high</b> <b>quality.</b> <br>"
+"&#43; <b>Great</b> <u>service.</u> <br>"
+"&#43; <u>Amazing</u> <u>service</u> but ?10 a month <b>is</b> a bit <b>pricy.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>free</u> <u>service</u> <b>is</b> <b>crap.</b> <br>"
+"- I <b>love</b> <u>Spotify</u> <u>as</u> a <u>service</u> but one of the latest app updates reduced the volume significantly. <br>"
+"- Every <u>free</u> <u>service</u> <b>has</b> a <b>limit.</b> <br>"
+"- <u>Nice</u> <u>service</u> but playlists at the start <b>are</b> <b>annoying</b> <b>in</b> <b>most</b> <b>xases</b> <br>"
+"</p>","volumn":36,"sentiment":.64,"value":4.22},
{"keyword":"variety","name":"<h1>variety</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is easy to navigate and has a <b>great</b> <u>variety.</u> <br>"
+"&#43; <b>Great</b> <u>variety</u> in playlist. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's Uped My Game Tremendously And the <u>Variety</u> Of choices <b>Is</b> <b>Awesome</b> Great <b>Work</b> On that Keep it up Y'all <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"Spotify","name":"<h1>Spotify</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Spotify</u> <u>Premium</u> is <b>great!</b> <br>"
+"&#43; The <u>premium</u> <u>version</u> <u>of</u> <u>spotify</u> <b>is</b> absolutely <b>amazing</b> and worth the <b>money.</b> <br>"
+"&#43; <u>Spotify</u> <u>premium</u> is <b>great.</b> <br>"
+"&#43; <u>Spotify</u> is a great ap, but <b>please,</b> <b>please</b> ad a sleep timer and <b>alarm</b> <b>feature!</b> <br>"
+"&#43; <u>Spotify</u> <b>is</b> a <b>great</b> <b>ap,</b> but please, please ad a sleep timer and alarm feature! <br>"
+"&#43; I love <b>music,</b> <u>spotify</u> <b>has</b> <b>music!</b> <br>"
+"&#43; <u>Spotify</u> <b>has</b> a <b>huge</b> <b>selection</b> <b>of</b> <b>music</b> and it keeps geting better! <br>"
+"&#43; I <b>love</b> <u>spotify</u> <u>premium!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Love</u> <u>spotify</u> <u>but</u> from the drop down it <b>never</b> <b>says</b> the <b>right</b> <b>song.</b> <br>"
+"- I have used prety much all other popular streaming services like rdio, google all access, Pandora, milk, and more but <u>Spotify</u> <b>wins</b> <b>hands</b> <b>down</b> <b>for</b> <b>me.</b> <br>"
+"- <u>Spotify</u> for android was <b>great,</b> but now there is no search function. <br>"
+"- <b>Since</b> <b>few</b> <b>months</b> <b>ago,</b> <u>spotify</u> <b>is</b> <b>running</b> increasingly <b>slower</b> navigating between menus. <br>"
+"- <u>Spotify</u> is <b>better</b> <b>than</b> iHeart Radio and <b>Pandora.</b> <br>"
+"</p>","volumn":17,"sentiment":.41,"value":3.24},
{"keyword":"music","name":"<h1>music</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Music</u> <u>selection</u> is <b>excellent.</b> <br>"
+"&#43; The <u>music</u> <u>variety</u> is <b>fantastic.</b> <br>"
+"&#43; So far the <b>best</b> <u>music</u> <u>streaming</u> service! <br>"
+"&#43; <b>Great</b> <u>music</u> <u>library,</u> tremendous updates the last year to the Playlist and <u>music</u> discovery. <br>"
+"&#43; <b>Great</b> <u>music.</u> <br>"
+"&#43; The offline option is amazing and <u>music</u> <u>selection</u> can't <b>be</b> <b>beat</b> <b>for</b> the <b>price.</b> <br>"
+"&#43; <b>Great</b> <u>music.</u> <br>"
+"&#43; A <b>great</b> <u>varity</u> <u>of</u> <u>music</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>BC</u> <u>I</u> <u>LOVE</u> <u>MUSIC</u> AND <u>I</u> <b>LISTEN</b> <u>IN</u> THIS APP OVER <u>A</u> YEAR AND <u>I</u> USED THE FREE TRIALS THO BUT WHEN <u>I</u> D.L <u>IT</u> ALREADY <u>I</u> CNT USE THE 7DAYS FREE TRIAL. <br>"
+"- <u>Music</u> <u>selection</u> is <b>great,</b> problem is that everytime it goes to ads it stops streaming completely and won't allow me to go on to the next song, change Playlists, etc. <br>"
+"- And the <u>shuffle</u> <b>needs</b> <b>to</b> actually <u>shuffle</u> my <b>list</b> <b>thank</b> <b>you</b> very much. <br>"
+"- And <b>like</b> <b>Eric</b> <b>Haskin</b> said, the <u>shuffle</u> is <b>always</b> <b>predictable.</b> <br>"
+"- <b>Huge</b> <u>selection</u> and variety <u>of</u> <u>music.</u> <br>"
+"- It's <b>a</b> good player, <b>however</b> <b>lost</b> the <u>concept</u> <u>of</u> <u>online</u> <u>music.</u> <br>"
+"- The <u>shuffle</u> <u>function</u> usually <b>plays</b> <b>some</b> <b>of</b> the <b>same</b> <b>songs</b> <b>over</b> and <b>over.</b> <br>"
+"- In <u>a</u> future update, I'd <b>love</b> <u>to</u> <u>see</u> the <u>ability</u> <u>for</u> <u>users</u> <u>to</u> <u>aply</u> <u>tags</u> <u>to</u> <u>music</u> (ie <u>slow,</u> <u>EDM,</u> etc) and <u>tags</u> can be grouped together in search <u>to</u> produce <u>a</u> variety of similar <u>music,</u> organized by the most relevant. <br>"
+"</p>","volumn":66,"sentiment":.39,"value":4.58},
{"keyword":"artists","name":"<h1>artists</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; So <b>many</b> <u>new</u> <u>artists</u> I love now versus what the masses choose to enjoy. <br>"
+"&#43; I <b>love</b> that you choose the <u>artists</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The songs lag and slow then it sounds like the <u>artist</u> <b>is</b> <b>singing</b> <b>through</b> <b>static.</b> <br>"
+"</p>","volumn":3,"sentiment":.33,"value":1.43},
{"keyword":"quality","name":"<h1>quality</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great search engine and <b>excellent</b> <u>sound</u> <u>quality</u> <br>"
+"&#43; Great app super fast loading songs and <u>sound</u> <u>quality</u> is <b>really</b> <b>good.</b> <br>"
+"&#43; <u>Sound</u> <u>quality</u> is <b>great.</b> <br>"
+"&#43; In adition to that, the concept and implementation of the service as well as the way it talks to other services/aps are very <b>high</b> <u>quality.</u> <br>"
+"&#43; Ap otherwise is <u>great</u> and music offerings are <b>varied</b> and <u>great</u> <u>quality</u> compared to other radio aps. <br>"
+"&#43; It is better than <u>sound</u> <u>cloud</u> <b>works</b> <b>great</b> <br>"
+"&#43; <b>Awesome</b> <u>quality.</u> <br>"
+"&#43; After <b>updating</b> (5/10) the <u>sound</u> is <b>really</b> <b>quiet.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Sound</u> <u>quality</u> <u>is</u> <u>horible,</u> volume lowers then back up, <b>keeps</b> <b>doing</b> that for every song played. <br>"
+"- The resulting output is much <b>lower</b> <u>sound</u> than the original. <br>"
+"- <u>User</u> <b>friendly,</b> lots of choice, unlimited downloads, good <u>quality,</u> you'll strugle to find a better music ap! <br>"
+"- <u>Horible</u> <u>limited</u> <u>amount</u> <u>of</u> <u>songs</u> <u>you</u> <u>can</u> <u>listen</u> <u>to</u> <u>without</u> <u>premium</u> only <b>shuffles</b> <u>songs</u> <b>poor</b> <b>music</b> <b>selection</b> better <u>off</u> using Pandora or soundcloud <br>"
+"- It's ok because it's <b>great</b> <u>quality</u> but I hate the ads and the fact it won't work on my computer. <br>"
+"</p>","volumn":15,"sentiment":.33,"value":3.04},
{"keyword":"better","name":"<h1>better</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>I</u> <b>like</b> the <u>artist</u> <u>selection</u> <u>better</u> than Amazon Prime, and the playlists are fun to do with friends. <br>"
+"&#43; I <b>like</b> <u>Spotify</u> <u>better</u> than Soundcloud for the aesthetics and style but I'm guessing iOS devices gets more features than androids. <br>"
+"&#43; The new interface is beautiful and I <b>hate</b> <u>to</u> <u>see</u> <u>it</u> <u>brought</u> <u>down</u> <u>by</u> <u>decreased</u> <u>functionality.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I <b>like</b> <u>it</u> <u>better</u> than Pandora. <br>"
+"</p>","volumn":7,"sentiment":.29,"value":2.23},
{"keyword":"price","name":"<h1>price</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Good electronics, but the <u>price</u> for the service <b>is</b> double the <b>competition.</b> <br>"
+"&#43; <b>Great</b> <u>price.</u> <br>"
+"&#43; Great selection and <b>decent</b> <u>price.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Price</u> <b>went</b> <b>up</b> but oh well. <br>"
+"- This <u>price</u> <b>is</b> a <b>litle</b> expensive for <b>premium</b> if someone isn't a student like myself. <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"premium","name":"<h1>premium</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Premium</u> is even <b>more</b> <b>amazing!</b> <br>"
+"&#43; Having <u>premium</u> is <b>amazing</b> <br>"
+"&#43; I love this aplication and I'm a <b>paid</b> <u>premium</u> <u>user.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Premium</u> is <b>annoying</b> <br>"
+"- <u>Premium</u> <u>subscriber</u> <b>fed</b> <b>up</b> <b>slow</b> <b>slow</b> <b>slow</b> <br>"
+"- This price is a <b>litle</b> <u>expensive</u> for <u>premium</u> if someone isn't a student like myself. <br>"
+"</p>","volumn":7,"sentiment":.14,"value":2.09},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>A</b> robust feature set and <b>a</b> <u>large</u> <u>amount</u> <u>of</u> <u>content</u> <u>with</u> <b>a</b> <u>beautiful</u> <u>interface</u> <b>makes</b> <b>a</b> <b>great</b> <b>music</b> <b>ap</b> <br>"
+"&#43; <u>Interface</u> <b>has</b> <b>improved</b> a ton over time and the <b>selection</b> <b>of</b> <b>music</b> they have is great especially if you like indie <b>music.</b> <br>"
+"&#43; The <u>new</u> <u>interface</u> is <b>beautiful</b> and I hate to see it brought down by decreased functionality. <br>"
+"&#43; <b>Nice</b> <u>interface.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Bad</b> <u>interface,</u> good music. <br>"
+"- This <u>interface</u> <b>looked</b> <b>cool</b> when everyone was using winamp but <b>now</b> it sucks. <br>"
+"- <u>Interface</u> is <b>awesome</b> however I really would prefer if you guys could make the status bar transparent in all views! <br>"
+"- The <u>user</u> <u>interface</u> <b>make</b> no <b>honest</b> <b>sense</b> unless you're utilizing an iphone which I don't apreciate <br>"
+"</p>","volumn":8,"sentiment":.12,"value":2.20},
{"keyword":"subscription","name":"<h1>subscription</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>disapointed</b> <u>thinking</u> <u>of</u> cancelling <u>subscription</u> <br>"
+"- <b>Uninstalled</b> and <u>downgrading</u> <u>subscription</u> because <u>of</u> mobile app <u>problems</u> at end <u>of</u> month if no fix is available! <br>"
+"- The <u>subscription</u> <b>is</b> <b>nothing</b> compared to the cost of purchasing individually all the music I love. <br>"
+"</p>","volumn":3,"sentiment":-1.00,"value":.10},
{"keyword":"free","name":"<h1>free</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I ended up upgrading to premiem to avoid commercials l, but the <u>free</u> <u>version</u> is great and <b>offers</b> <b>similar</b> <b>features.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- BC I LOVE MUSIC AND I LISTEN IN THIS APP OVER A YEAR AND I USED THE <u>FREE</u> <b>TRIALS</b> <b>THO</b> <b>BUT</b> WHEN I D.L IT ALREADY I CNT USE THE 7DAYS <u>FREE</u> TRIAL. <br>"
+"- <u>Free</u> <b>acess</b> <b>aint</b> <b>what</b> <b>I</b> <b>expected</b> <b>but</b> <b>total</b> <b>acess</b> <b>is</b> <b>great!</b> <br>"
+"- <u>Free</u> <u>version</u> is <b>not</b> <b>very</b> <b>useful.</b> <br>"
+"- While the premium version is very good, the <u>free</u> <u>one</u> is <b>prety</b> <b>bad:</b> too many commercials, it plays random songs not from the album you selected. <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"chromecast-suport","name":"<h1>chromecast-suport</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I want to use Spotify because I can't stand Play Music's interface, but the <u>lack</u> <u>of</u> <u>Chromecast</u> <u>suport</u> <b>is</b> a <b>big</b> <b>turn</b> off. <br>"
+"- It is very <b>bad</b> <u>suport.</u> <br>"
+"- No <u>Chromecast</u> <u>suport,</u> the exclusion of this is <b>really</b> <b>hard</b> <b>to</b> <b>overlook.</b> <br>"
+"- <u>Chromecast</u> <u>suport</u> is <b>poor.</b> <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"functions","name":"<h1>functions</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Discover</u> <u>function</u> is <b>useful</b> and search is quick and effective. <br>"
+"- <u>Other</u> <u>functions</u> can be <b>equally</b> <b>slow.</b> <br>"
+"- The Ap's geting better, the library of music is growing, but the connect <u>functionality</u> is <b>rather</b> <b>lagy;</b> took 5 mins to find itself (nexus 5) and my PS3. <br>"
+"- EDIT: immediately <b>after</b> <b>writing</b> this <b>review,</b> the <u>search</u> <u>function</u> <b>magically</b> <b>apears.</b> <br>"
+"</p>","volumn":5,"sentiment":-.80,"value":.81},
{"keyword":"search","name":"<h1>search</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>search</u> <u>engine</u> and excellent sound quality <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- That said, the <u>search</u> is <b>so</b> <b>slow</b> that it often times out. <br>"
+"- The <u>search</u> <u>buton</u> <u>on</u> the <u>side</u> <b>keeps</b> <b>disapearing.</b> <br>"
+"- i pulled the <u>option</u> bar out from the left side and the <u>search</u> <u>option</u> is no longer <b>there.</b> <br>"
+"- <b>Occasionally</b> the <u>search</u> <u>buton</u> <b>will</b> <b>be</b> where it is suposed to but It has been very rare. <br>"
+"- The <u>search</u> <u>buton</u> <b>keeps</b> <b>disapearing.</b> <br>"
+"</p>","volumn":6,"sentiment":-.50,"value":1.29},
{"keyword":"color","name":"<h1>color</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>like</b> the <u>new</u> <u>color!</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>new</u> <u>color</u> is <b>awful!</b> <br>"
+"- Prety <b>ugly</b> <u>color.</u> <br>"
+"- I really don't <b>like</b> the <u>new</u> <u>color.</u> <br>"
+"- The <u>new</u> <u>color</u> is <b>horible,</b> but I don't care I use themed icons <br>"
+"</p>","volumn":8,"sentiment":-.50,"value":1.58},
{"keyword":"songs","name":"<h1>songs</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; New and <b>old</b> <u>songs</u> always available. <br>"
+"&#43; The <u>variety</u> <u>of</u> <u>songs</u> are <b>nice</b> <b>especially</b> the <b>combination</b> <u>of</u> <u>songs.</u> <br>"
+"&#43; <b>Great</b> <u>songs</u> and easy to do long it. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Every <u>song</u> <b>Sounds</b> <b>Muffled</b> <br>"
+"- The app becomes unresponsive very often: when I <b>dislike</b> a <u>song,</u> lose connectivity for a few seconds,. <br>"
+"- Each <u>song</u> <u>that</u> <u>plays</u> <u>skips</u> <u>like</u> <u>it</u> <b>needs</b> <b>buffering,</b> so I'd pause <u>it</u> for bit, let <u>it</u> play and <u>its</u> still ends up skiping! <br>"
+"- I love this app but some <u>song</u> and album <u>of</u> <u>Taylor</u> <u>swift</u> are <b>not</b> <b>here.</b> <br>"
+"- I <b>love</b> that there are a <u>lot</u> <u>of</u> <u>songs</u> to choose from but you can't skip <u>songs</u> more than like 5 times then you have to wait like an hour to skip again. <br>"
+"- I just don't <b>like</b> that if you don't buy the premium version, you can't skip an <u>unlimited</u> <u>amount</u> <u>of</u> <u>songs.</u> <br>"
+"- The <u>songs</u> <u>lag</u> and slow <b>then</b> it <b>sounds</b> like the artist is singing through static. <br>"
+"- The <u>sugested</u> <u>songs</u> are <b>stupid.</b> <br>"
+"</p>","volumn":14,"sentiment":-.36,"value":2.28},
{"keyword":"volume","name":"<h1>volume</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Volume</u> is <b>constantly</b> <b>diping</b> and rising. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Sound quality is horible, <u>volume</u> <b>lowers</b> then back <b>up,</b> keeps doing that for every song played. <br>"
+"- In adition it has a very <b>low</b> <u>max</u> <u>volume</u> in comparison. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"connection","name":"<h1>connection</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Now however, the app is insistent that it's offline even if offline mode is turned off and the <u>Internet</u> <u>connection</u> is <b>good.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"updates","name":"<h1>updates</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> all the music and <u>updates</u> on artists. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>two</u> <u>latest</u> <u>updates</u> are <b>horible.</b> <br>"
+"- <u>Latest</u> <u>updates</u> <b>are</b> <b>breaking</b> the <b>app.</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"ads","name":"<h1>ads</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The music is almost <b>limitless</b> <u>ad</u> Bluetooth and enjoy endlessly <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Most annoying <u>audio</u> <u>ads</u> <b>to</b> <b>ever</b> <b>exist.</b> <br>"
+"- more the <u>ads</u> are <b>very</b> <b>frequent.</b> <br>"
+"</p>","volumn":6,"sentiment":-.17,"value":1.63},
{"keyword":"premium-version","name":"<h1>premium-version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Curent</u> <u>version</u> is <b>excellent!</b> <br>"
+"&#43; The <u>premium</u> <u>version</u> <b>is</b> possibly the <b>best</b> music <b>app</b> ever. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Love</u> this <u>ap,</u> just wish it <b>had</b> more <b>music</b> <b>from</b> <b>smaller</b> <b>artists.</b> <br>"
+"- <u>Premium</u> <u>version</u> is <b>expensive.</b> <br>"
+"- While the <u>premium</u> <u>version</u> is <b>very</b> <b>good,</b> the free one is prety bad: too many commercials, it plays random songs not from the album you selected. <br>"
+"</p>","volumn":7,"sentiment":.00,"value":1.95},
]