var data_map_totalreviews=1891
var data_map_fromdate=20150501
var data_map_todate=20151102
var data_map_duolingo = [
{"keyword":"format","name":"<h1>format</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This <u>format</u> is simple, FREE, and <b>makes</b> <b>it</b> <b>fun</b> to learn! <br>"
+"&#43; This <u>format</u> is <b>simple,</b> FREE, and makes it fun to learn! <br>"
+"&#43; Have tried several different languages on it, the <u>format</u> is <b>great,</b> the lessons are small enough <b>to</b> <b>fit</b> <b>in</b> my <b>busy</b> <b>schedule</b> so its easy <b>to</b> just, do a lesson when ever <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.67,"value":2.77},
{"keyword":"resource","name":"<h1>resource</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This is a <b>great</b> <u>resource</u> for anyone wanting to begin learning a new language! <br>"
+"&#43; This has been the <b>absolute</b> <u>best</u> <u>resource</u> I've found in learning French and Spanish. <br>"
+"&#43; <b>Fantastic</b> <u>resource!</u> <br>"
+"&#43; <b>Fantastic</b> <u>resource!</u> <br>"
+"&#43; But it's a <b>good</b> <u>resource.</u> <br>"
+"&#43; <b>Great</b> <u>resource.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":6,"sentiment":1.33,"value":3.13},
{"keyword":"litle","name":"<h1>litle</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This app is so helpful and I <b>love</b> that I can set a <u>goal</u> <u>for</u> each <u>day!</u> <br>"
+"&#43; It <b>is</b> not only <b>is</b> it educational and challenging, it's fun as all get out, and for some reason the <u>litle</u> <u>bell</u> <u>that</u> <u>sounds</u> when you're corect <b>is</b> like crack lol <b>I</b> wanna hear it, but even the <b>incorect</b> <u>bell</u> <b>sound</b> <b>is</b> <b>nice.</b> <br>"
+"&#43; I <b>love</b> the <u>concept</u> <u>of</u> <u>doing</u> a <u>litle</u> every <u>day.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.33,"value":2.43},
{"keyword":"steps","name":"<h1>steps</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is <b>easy</b> <u>steps</u> I enjoy the app. <br>"
+"&#43; The practice session and the methodology , <u>sequence</u> <u>of</u> <u>practicing</u> <u>steps</u> is <b>awesome</b> and quite good <br>"
+"&#43; It doesnt lag and the <u>steps</u> are <b>easy</b> <b>to</b> <b>follow</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.33,"value":2.43},
{"keyword":"variety","name":"<h1>variety</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>variety</u> <b>really</b> <b>helps</b> keep it interesting too. <br>"
+"&#43; The <u>variety</u> <u>of</u> <u>activities</u> <b>keeps</b> <b>it</b> <b>interesting.</b> <br>"
+"&#43; <b>Great</b> <u>variety</u> <u>of</u> <u>activities</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":1.33,"value":2.43},
{"keyword":"fun","name":"<h1>fun</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It's <u>fun,</u> <b>simple</b> and <u>efficient!</u> <br>"
+"&#43; DuoLingo is <u>fun</u> yet <b>challenging!</b> <br>"
+"&#43; Learning and <u>fun</u> <b>combined</b> <b>together</b> <b>in</b> <b>a</b> very <b>creative</b> <b>way.</b> <br>"
+"&#43; It is very easy and <u>fun</u> to use, fairly <b>advanced,</b> and definitely <u>adictive</u> - in a good way. <br>"
+"&#43; It is so <b>much</b> <u>fun!</u> <br>"
+"&#43; It is <b>easy</b> <u>fun</u> learning! <br>"
+"&#43; It's so <b>much</b> <u>fun</u> and it's simple too. <br>"
+"&#43; Well we are doing competion in my school and we are learning french and it is so <b>much</b> <u>fun</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's easy to learn, <u>fun-I</u> <b>spend</b> <b>hours</b> <b>on</b> <b>it!</b> <br>"
+"</p>","volumn":18,"sentiment":1.22,"value":4.11},
{"keyword":"introduction","name":"<h1>introduction</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; A <b>brilliant</b> <u>introduction</u> to language. <br>"
+"&#43; <b>Great</b> <u>introduction</u> to Spanish. <br>"
+"&#43; They make learning way easier and it is a <b>nice</b> <u>introduction</u> to the chapter. <br>"
+"&#43; <b>Excellent</b> <u>introduction</u> to the language. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":4,"sentiment":1.00,"value":2.39},
{"keyword":"reminders","name":"<h1>reminders</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is very user friendly and I <b>like</b> the <u>reminders</u> <u>to</u> <u>return</u> <u>to</u> <u>class</u> <br>"
+"&#43; It is very user friendly and I <b>like</b> the <u>reminders</u> <u>to</u> <u>return</u> <u>to</u> <u>class</u> <br>"
+"&#43; You learn great languages and I <b>like</b> the <u>reminders</u> <br>"
+"&#43; I <b>love</b> the <u>simplicity,</u> the <u>daily</u> <u>reminders,</u> and how you can decide whether you do speaking or just listening exercises in case you're in a public place and can't speak too loud. <br>"
+"&#43; I am learning so much, and I <b>love</b> the <u>reminders.</u> <br>"
+"&#43; The <u>reminders</u> are <b>great</b> and I am really learning! <br>"
+"&#43; The <u>reminders</u> to practice are <b>great</b> <b>too.</b> <br>"
+"&#43; I <b>love</b> how I get a <u>reminder</u> on my phone to practice. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>reminders</u> <b>are</b> a <b>litle</b> <b>annoying.</b> <br>"
+"</p>","volumn":13,"sentiment":.92,"value":3.49},
{"keyword":"interface","name":"<h1>interface</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This app is absolutely amazing in terms of what it can do, the <u>interface</u> is <b>brilliant.</b> <br>"
+"&#43; Useful lessons and <b>lovely</b> <u>interface</u> with good intuitive design. <br>"
+"&#43; It is <b>easy</b> <u>interface.</u> <br>"
+"&#43; <u>Interface</u> is <b>good</b> <b>too</b> <br>"
+"&#43; It is <b>easy</b> <u>interface,</u> great way to learn and refresh your languages :) <br>"
+"&#43; It is easy to use, <b>intuitive</b> <u>interface.</u> <br>"
+"&#43; Smooth and <b>clean</b> <u>interface.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Great</b> <u>interface</u> that breaks down the languages into bite-size chunks <br>"
+"</p>","volumn":8,"sentiment":.88,"value":2.95},
{"keyword":"program","name":"<h1>program</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; A <b>wonderful</b> <u>program.</u> <br>"
+"&#43; <u>Program</u> is easy to use and <b>has</b> <b>a</b> <b>good</b> <b>mix</b> <b>of</b> <b>visual,</b> and <b>speech</b> <b>examples</b> which all help to reinforce the language! <br>"
+"&#43; <u>Program</u> is <b>easy</b> <b>to</b> <b>use</b> and has a good mix of visual, and speech examples which all help <b>to</b> reinforce the language! <br>"
+"&#43; I really <b>enjoyed</b> the <u>German</u> <u>program,</u> It's fun and easy to use. <br>"
+"&#43; Great app and very <b>effective</b> <u>program.</u> <br>"
+"&#43; The <u>full</u> <u>version</u> <u>on</u> my <u>main</u> <u>computer</u> <b>offers</b> a <b>greater</b> <b>range</b> <b>of</b> <b>possibilities.</b> <br>"
+"&#43; <b>Good</b> <u>program</u> <b>easy</b> but <u>thorough</u> <br>"
+"&#43; I <b>like</b> how well <u>it</u> works nice refiners to tell you to keep at <u>it</u> so you don't forget it's there eat to use and <u>flows</u> well <u>with</u> <u>computer</u> <u>version</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It's a <b>great</b> <u>program</u> to keep up your language skills, but it's maybe not the best for beginners, because the beginning of a language doesn't show you the alphabet so you can learn how to read the language, and corect pronunciations. <br>"
+"- <b>Helpful</b> <u>program,</u> but not thorough enough. <br>"
+"- It is very <b>useful</b> <u>program</u> <br>"
+"</p>","volumn":15,"sentiment":.87,"value":3.57},
{"keyword":"owl","name":"<h1>owl</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great way to learn, totally free, and the mascot is a <b>green</b> <u>owl.</u> <br>"
+"&#43; The <u>owl</u> is <b>cute.</b> <br>"
+"&#43; I found it to be challenging enough, but not so impossible you feel lost, the unlockable levels are a cool feature, and the <u>litle</u> <u>owl</u> <b>is</b> a <b>hoot!</b> <br>"
+"&#43; Plus the <u>owl</u> is <b>adorable</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":5,"sentiment":.80,"value":2.41},
{"keyword":"content","name":"<h1>content</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>content,</u> presentation and effectiveness <u>of</u> this <u>visual</u> and <u>aural</u> <u>programme</u> is <b>both</b> <b>impressive</b> and effective. <br>"
+"&#43; Great design and <b>excellent</b> <u>content.</u> <br>"
+"&#43; The <u>way</u> the <u>courses</u> <u>are</u> <u>offered</u> is <b>effective.</b> <br>"
+"&#43; Can't speak for the other <u>courses</u> but the <u>course</u> <u>content</u> is great and <b>works</b> <b>well</b> <b>on</b> my <b>device.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I would have given 5 stars but my problem with it is that <b>in</b> some <b>categories,</b> the <u>content</u> is <b>very</b> <b>repetitive.</b> <br>"
+"</p>","volumn":5,"sentiment":.80,"value":2.41},
{"keyword":"tool","name":"<h1>tool</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Great</b> <u>tool,</u> designed in a fun and exciting game set-up! <br>"
+"&#43; this is a <b>wonderful</b> <u>tool</u> that will teach a lot. <br>"
+"&#43; A <b>wonderful</b> <u>tool</u> and adition to learning a language <br>"
+"&#43; It's a <b>great</b> <u>tool</u> for the beginner parts in a language. <br>"
+"&#43; has been a <b>wonderful</b> <u>tool.</u> <br>"
+"&#43; Duolingo is a <b>wonderful</b> <u>tool</u> for brushing up <br>"
+"&#43; I love learning new things and this <u>tool</u> is the <b>easiest</b> <b>by</b> <b>far!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Brilliant</b> <u>educational</u> <u>tool</u> 5 stars. <br>"
+"- It is very <b>useful</b> <u>tool.</u> <br>"
+"</p>","volumn":9,"sentiment":.78,"value":2.98},
{"keyword":"use","name":"<h1>use</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> the reminders, the flow and <u>ease</u> <u>of</u> <u>use.</u> <br>"
+"&#43; I <b>like</b> the <u>activites</u> <u>which</u> <u>use</u> the <u>microphone,</u> they are good fun and there aren't too many or too few. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"</p>","volumn":3,"sentiment":.67,"value":1.77},
{"keyword":"free","name":"<h1>free</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This is <u>fun,</u> <b>easy,</b> <u>free</u> (!) <br>"
+"&#43; Great way to learn, <u>totally</u> <u>free,</u> and the mascot <b>is</b> a <b>green</b> <b>owl.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Free,</u> easy to use, extensive, lessons broken down to reasonable time increments so I <b>can</b> <b>fit</b> <b>them</b> <b>in</b> my <b>day.</b> <br>"
+"</p>","volumn":3,"sentiment":.67,"value":1.77},
{"keyword":"learning","name":"<h1>learning</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I'd <b>love</b> <u>to</u> <u>learn,</u> thank you for a brilliant ap! <br>"
+"&#43; I <b>love</b> how easy and handy <u>it</u> <u>is</u> <u>to</u> <u>learn</u> <u>new</u> <u>languages,</u> and seting your own goals really helps the intensity of <u>it</u> <br>"
+"&#43; <u>Learning</u> and fun <b>combined</b> <b>together</b> <b>in</b> <b>a</b> very <b>creative</b> <b>way.</b> <br>"
+"&#43; It is <b>easy</b> and <u>fun</u> <u>learning.</u> <br>"
+"&#43; I always rate things price/quality, and by far this is the <b>best</b> free <u>learning</u> <u>tool</u> ever, no ads! <br>"
+"&#43; <u>Learning</u> is <b>so</b> <b>easy</b> and fun. <br>"
+"&#43; Great and <b>portable</b> <u>learning</u> <u>experience.</u> <br>"
+"&#43; I <b>love</b> the aplication and the <u>learning</u> <u>style,</u> however I'm trying to learn Portuguese for Portugal not Brazil. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This app lacks a lot of different languages that I <b>would</b> <b>love</b> <u>to</u> <u>try</u> <u>to</u> <u>learn,</u> however, it is simple <u>to</u> use and understand, interactive, and I find the comment section that comes up when you press the flag after you check your answer <u>to</u> be very helpful. <br>"
+"- <b>Wonderful</b> <u>learning</u> tool. <br>"
+"- Extremely adictive and fun YES YES YES till the <u>degree</u> <u>that</u> <u>i</u> <u>want</u> <u>to</u> <u>learn</u> <u>ALL</u> <u>available</u> <u>languages</u> <b>lol.great</b> <b>ap</b> <br>"
+"- <u>Learning</u> <u>languages</u> becomes <b>adictive.</b> <br>"
+"- I am <u>Learning</u> <b>italian</b> with this ap, the best part is how it teaches grammar and constructing scentances so you can aply them to words that you learn over time. <br>"
+"- I'm combining it with <u>learning</u> from another book, so it might be less effective on its own, but <u>I</u> feel I'm <u>learning</u> quickly and the <u>content</u> I'm <u>learning</u> is <b>useful.</b> <br>"
+"- <u>Learning</u> another <u>language</u> has <b>never</b> been <b>so</b> <b>easy.</b> <br>"
+"- Extremely <b>useful</b> <u>learning</u> <u>tool</u> <br>"
+"</p>","volumn":47,"sentiment":.57,"value":4.42},
{"keyword":"aplication","name":"<h1>aplication</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This <u>aplication</u> is <b>terifically</b> <b>excellent!</b> <br>"
+"&#43; <b>Wonderful</b> <u>Aplication.</u> <br>"
+"&#43; The <u>aplication</u> is <b>perfect</b> <b>to</b> <b>practice</b> <b>English</b> <b>everyday.</b> <br>"
+"&#43; The <u>aplication</u> <b>is</b> <b>nicely</b> <b>designed.</b> <br>"
+"&#43; It is very <b>comfortable</b> <u>aplication.</u> <br>"
+"&#43; It is very <b>effective</b> <u>aplication</u> <br>"
+"&#43; It is very <b>interesting</b> <u>aplication.</u> <br>"
+"&#43; I <b>love</b> this <u>aplication</u> because it tracks my strength and weaknesses and reminds me to practice <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- An efficient, <b>sunning</b> <u>aplication</u> . <br>"
+"- The <u>aplication</u> <b>occasionally</b> <b>gets</b> <b>stuck,</b> and fails to update progress even though the phone is connected. <br>"
+"- The <u>aplication</u> occasionally gets stuck, and <b>fails</b> <b>to</b> <b>update</b> <b>progress</b> even though the phone is connected. <br>"
+"</p>","volumn":15,"sentiment":.53,"value":3.24},
{"keyword":"system","name":"<h1>system</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>score</u> and <u>streak</u> <u>system</u> <b>makes</b> <b>it</b> <b>fun</b> too. <br>"
+"&#43; I <b>love</b> the <u>curent</u> <u>grading</u> <u>system</u> and I <b>love</b> there are several different ways to learn - type what you hear, type what you see, match English and French words, speak what you hear. <br>"
+"&#43; And the <u>voice</u> <u>pronunciation</u> <u>system</u> <b>is</b> <b>ok.</b> <br>"
+"&#43; <b>Excellent</b> <u>system</u> and unbeatable value. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- But it doesn't explain how anything is <b>pronounced</b> <b>not</b> the <b>rules</b> <b>of</b> the <b>languages</b> <u>native</u> <u>system.</u> <br>"
+"</p>","volumn":6,"sentiment":.50,"value":2.29},
{"keyword":"user","name":"<h1>user</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>User</u> <u>friendly</u> and we'll <b>constructed</b> <b>app</b> <b>to</b> <b>ensure</b> <b>max</b> <b>language</b> <b>development.</b> <br>"
+"&#43; It's simple and very <u>user</u> <b>friendly.</b> <br>"
+"&#43; <b>Awesome</b> and very <u>user</u> <u>friendly</u> ! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The mobile app is <u>user</u> <b>friendly</b> and <u>functional</u> but lacks some of the desktop capabilities, including the very important lesson background and on page butons for accents and characters not found on the keyboard of the <u>users</u> language. <br>"
+"</p>","volumn":4,"sentiment":.50,"value":1.89},
{"keyword":"Duolingo","name":"<h1>Duolingo</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>DuoLingo</u> <b>is</b> <b>fun</b> yet <b>challenging!</b> <br>"
+"&#43; I've always <b>loved</b> <u>Duolingo</u> and I'm so glad that the mobile app is so nice-looking and easy to use. <br>"
+"&#43; <u>Duolingo</u> <b>is</b> a <b>wonderful</b> <b>tool</b> for brushing up <br>"
+"&#43; Since ading more languages, <u>Duolingo</u> <b>is</b> easily the <b>best</b> <b>way</b> to learn a new language on your Android device. <br>"
+"&#43; <u>Duolingo</u> <b>provides</b> an <b>easy</b> <b>to</b> <b>understand</b> <b>perspective</b> <b>of</b> <b>learning</b> <b>a</b> <b>foreign</b> <b>language</b> that can otherwise be quite perplexing <br>"
+"&#43; I never did computer games as the <b>skills</b> aren't transferable; but <u>Duolingo</u> <b>is</b> <b>giving</b> me a <b>real,</b> <b>tradable</b> <b>skill.</b> <br>"
+"&#43; <u>Duolingo</u> is <b>such</b> a <b>great</b> <b>program.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>Duolingo</u> is <b>great,</b> easy <b>to</b> <b>use</b> <b>on</b> the <b>go,</b> only <b>thing</b> I wish was that it would let me do practice offline for when I'm <b>on</b> the underground. <br>"
+"- In my opinion I think that <u>Duolingo</u> is <b>better</b> <b>than</b> <b>Roseta</b> <b>stone</b> because of the interaction and learning system I'm only for teen and this app make it easy to learn any language. <br>"
+"- <u>Duolingo</u> is <b>extremely</b> <b>useful</b> <b>for</b> learning a new language entirely or <b>for</b> <b>anyone</b> more <b>advanced.</b> <br>"
+"</p>","volumn":11,"sentiment":.45,"value":2.85},
{"keyword":"practice","name":"<h1>practice</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <u>Figure</u> 6 months <u>of</u> <u>daily</u> <u>practice</u> <b>will</b> <b>do</b> <b>wonders</b> <br>"
+"&#43; <b>good</b> <u>practice.</u> <br>"
+"&#43; <b>Awesome</b> <u>practice.</u> <br>"
+"&#43; The <u>practice</u> <u>session</u> and the methodology , sequence of practicing steps is <b>awesome</b> and quite good <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This app is really useful for language learners but I miss one thing: I would use that option to choose the learning method that I <b>like</b> <u>during</u> the <u>practice.</u> <br>"
+"- <u>Practice</u> <b>is</b> a <b>combo</b> of vocabular and grammar. <br>"
+"</p>","volumn":6,"sentiment":.33,"value":2.13},
{"keyword":"exercises","name":"<h1>exercises</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It has <b>unlimited</b> <u>exercises</u> and learning bar to keep us updated about our progress. <br>"
+"&#43; <b>Great</b> <u>exercises</u> and plenty info. <br>"
+"&#43; I <b>love</b> how it changes up my <u>strength</u> <u>exercises</u> every time I practice. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- It is very <b>useful</b> <u>exercise</u> that keep on reminding what you have learnt! <br>"
+"- It has <u>pronunciation</u> and <u>spelling</u> <u>exercises</u> <b>to</b> <b>practice</b> <b>with.</b> <br>"
+"</p>","volumn":5,"sentiment":.20,"value":1.81},
{"keyword":"pronunciation","name":"<h1>pronunciation</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>However,</b> the French, German, and <u>Irish</u> <u>pronunciation</u> is <b>abysmal,</b> I'm not familiar enough with any other languages to judge their quality. <br>"
+"- The <u>Dutch</u> <u>pronunciation</u> is <b>not</b> so <b>great</b> <b>though.</b> <br>"
+"</p>","volumn":3,"sentiment":-.67,"value":.43},
{"keyword":"is","name":"<h1>is</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I <b>love</b> how easy <u>it</u> <u>is</u> <u>to</u> <u>interface</u> <u>with.</u> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <u>I</u> do, however, apreciate that alternative <u>translations</u> are <u>accepted</u> 99% of the time and the <u>1%</u> that <u>a</u> <u>corect</u> <u>translation</u> <u>is</u> <u>not</u> <u>accepted</u> can <b>easily</b> <b>be</b> <b>reported.</b> <br>"
+"- <u>Interactive</u> <u>training</u> is <b>awesome.</b> <br>"
+"</p>","volumn":4,"sentiment":-.50,"value":.89},
{"keyword":"version","name":"<h1>version</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; But i <b>love</b> the <u>last</u> <u>version.</u> <br>"
+"&#43; I feel like the <u>mobile</u> <u>version</u> is <b>less</b> <b>serious</b> (you get words to choose from on many questions, for example), but the convenience is incredible, and honestly you get out what you put in whether you're <u>mobile</u> or desktop. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The <u>previous</u> <u>version</u> <b>was</b> a <b>great</b> <b>app</b> , but this one 3.8.0 sometimes does not load the pictures/audio parts. <br>"
+"- The <u>Android</u> <u>version</u> <b>should</b> <b>have</b> the <b>same</b> <b>store</b> where you buy extra lessons, it just has boring streak protector and change the owl's look. <br>"
+"- The <u>Android</u> <u>version</u> should have the same store where you buy extra lessons, it just has boring streak protector and <b>change</b> the owl's <b>look.</b> <br>"
+"- On <b>top</b> <b>of</b> <b>that,</b> the <u>Ipad</u> <u>version</u> <b>explains</b> how the sentences in other languages work, making it easier to learn how to construct sentences corectly. <br>"
+"- <u>I</u> like that the <u>pc,</u> <u>tablet</u> and <u>smartphone</u> <u>versions</u> are <b>slightly</b> <b>different.</b> <br>"
+"</p>","volumn":7,"sentiment":-.43,"value":1.52},
{"keyword":"voice","name":"<h1>voice</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; The <u>voice</u> <u>recognition</u> <u>I</u> <u>feel</u> <b>is</b> <b>sketchy</b> but great <b>ap</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- The only thing i'm not too fond of is how <b>fast</b> the <u>voice</u> <b>says</b> certain words, some of them sound like blghgdgb. <br>"
+"- The <u>voice</u> <b>is</b> <b>not</b> <b>hd</b> <b>like</b> <b>iphone!</b> <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"skills","name":"<h1>skills</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; I never did computer games as the <u>skills</u> aren't <b>transferable;</b> but Duolingo is giving me a real, tradable skill. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- If not, I am not sure that people can learn and memorize, since is <b>game-like</b> and <b>personal</b> <u>intuition</u> <u>skill</u> plays a big role- everyone could read on some website the basic of the language though. <br>"
+"- <b>More</b> <u>bonus</u> <u>skills,</u> store options, friend challenges, etc. <br>"
+"</p>","volumn":3,"sentiment":-.33,"value":.77},
{"keyword":"language","name":"<h1>language</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; Great and <b>easy</b> to learn <u>languages.</u> <br>"
+"&#43; But I AM a <u>language</u> <u>teacher</u> and this app is <b>wonderful</b> <b>for</b> <b>giving</b> <b>students</b> <b>interactive</b> <b>practice</b> <b>outside</b> <b>of</b> the <b>classroom.</b> <br>"
+"&#43; Really helpful and user <b>friendly</b> <u>language</u> <u>tutor</u> <br>"
+"&#43; <u>Best</u> <u>language</u> <b>learning</b> <b>app</b> <b>ever,</b> plus it's all for free and plus you are suporting to translate the web. <br>"
+"&#43; <u>Range</u> <u>of</u> <u>languages,</u> is <b>free</b> and easy and fun to use daily! <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Well, when i try to learn some asian language(which is my <b>prime</b> <u>language)</u> i found that some of the grammar and vocab are totally over-ruled and rigid, i can't even use more variation <u>language,</u> so please fix some of the grammar etc at some of the <u>language,</u> thanks! <br>"
+"- It's <b>useful</b> <u>language</u> to know more and more. <br>"
+"- If not, I am not sure that people can learn and memorize, since is game-like and personal intuition skill <b>plays</b> a <b>big</b> <b>role-</b> <b>everyone</b> <b>could</b> <b>read</b> <b>on</b> some <b>website</b> the <u>basic</u> <u>of</u> the <u>language</u> though. <br>"
+"- The <u>range</u> <u>of</u> <u>languages</u> <b>is</b> <b>somewhat</b> <b>limited</b> <b>at</b> this <b>point</b> but <b>covers</b> the <b>popular</b> <b>European</b> <u>languages</u> and <b>includes</b> <b>a</b> <b>few</b> <b>surprises</b> (Norwegian and Irish to name <b>a</b> couple). <br>"
+"- It's a great program to keep up your <u>language</u> skills, but it's maybe not the best for beginners, because the <u>beginning</u> <u>of</u> a <u>language</u> doesn't <b>show</b> you the alphabet so you can learn how to read the <u>language,</u> and <b>corect</b> <b>pronunciations.</b> <br>"
+"- However, the French, German, and Irish pronunciation is abysmal, I'm <b>not</b> <b>familiar</b> enough <u>with</u> any <u>other</u> <u>languages</u> to judge their quality. <br>"
+"</p>","volumn":13,"sentiment":-.08,"value":2.49},
{"keyword":"lessons","name":"<h1>lessons</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Useful</b> <u>lessons</u> and lovely interface with good intuitive design. <br>"
+"&#43; <u>Lessons</u> are so <b>well</b> <b>organised</b> and systematic. <br>"
+"&#43; I love that it's free and the <u>lessons</u> are <b>endless!</b> <br>"
+"&#43; I like that the <u>lessons</u> are <b>easy</b> <b>to</b> <b>navigate</b> and there is some variety <b>to</b> make them fun. <br>"
+"&#43; <u>Lessons</u> are <b>short</b> and sweet. <br>"
+"&#43; I <b>love</b> the <u>short</u> <u>litle</u> <u>lessons</u> that allow me to increase my Spanish skills in the <u>litle</u> pieces of spare time I have. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- Free, easy to use, extensive, <u>lessons</u> broken down to reasonable time increments so I <b>can</b> <b>fit</b> <b>them</b> <b>in</b> my <b>day.</b> <br>"
+"- it would be perfect if <u>lessons</u> <b>are</b> <b>shown</b> <b>before</b> every <b>level</b> like on the desktop version, It is really good, though. <br>"
+"- <u>Resumes</u> <u>lessons</u> from the home screen with litle to no issues, interface isn't clutered and is <b>reasonably</b> <b>responsive.</b> <br>"
+"- <b>Simple</b> <u>lessons,</u> <u>easy</u> to follow <br>"
+"- <b>Also,</b> the <u>number</u> <u>of</u> <u>lessons</u> are <b>extensive</b> and it's very easy to learn! <br>"
+"- The Spanish <u>lesson</u> <u>background</u> <b>is</b> a <b>Mayan</b> <b>temple,</b> which <b>is</b> culturally insensitive on so many levels. <br>"
+"</p>","volumn":13,"sentiment":.00,"value":2.56},
{"keyword":"alternative","name":"<h1>alternative</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; <b>Good</b> <u>alternative</u> to courses. <br>"
+"&#43; Vocab well set out and <u>translations</u> <b>make</b> <b>sense.</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- I do, however, apreciate that <u>alternative</u> <u>translations</u> <b>are</b> <b>accepted</b> <b>99%</b> <b>of</b> the <b>time</b> and the 1% that a corect translation is not <b>accepted</b> can easily be reported. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
{"keyword":"option","name":"<h1>option</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; It is a really <b>good</b> <u>option</u> to learn and improve your English skills. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This app is really useful for language learners but I miss one thing: I would use that <u>option</u> <b>to</b> <b>choose</b> the <b>learning</b> <b>method</b> that I like during the practice. <br>"
+"- Finding friends and challengers is not priority to the creators but is a <b>tiny</b> <u>option.</u> <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"website","name":"<h1>website</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; A <b>great</b> <u>adaptation</u> <u>of</u> the <u>website.</u> <br>"
+"&#43; The <u>website</u> is <b>even</b> <b>better!</b> <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- This <u>website,</u> and their app <b>are</b> <b>revolutionizing</b> the <b>availability</b> <b>of</b> a <b>language</b> learning outlet. <br>"
+"- The <u>website</u> is still <b>more</b> <b>complete,</b> but I can't think of a mobil app that is both this comprehensive and this easy to navigate and use. <br>"
+"</p>","volumn":4,"sentiment":.00,"value":1.39},
{"keyword":"suplement","name":"<h1>suplement</h1>"
+"<strong>top positive:</strong><br><p align=left>"
+"&#43; This app is an <b>excellent</b> <u>suplement</u> to learning a language. <br>"
+"</p>"+"<strong>top negative:</strong><br><p align=left>"
+"- <b>Wonderful</b> <u>suplement</u> if your also using an audio course, and you want to start learning to read French as well. <br>"
+"</p>","volumn":3,"sentiment":.00,"value":1.10},
]